export const USER_PROFILE_CONTENT = {
  pageAriaLabel: "Perfil do usuário",
  backFallback: "Portal Suprimentos",
  loading: "Carregando perfil…",
  error: "Não foi possível carregar o perfil.",
  retry: "Tentar novamente",
  forbidden: "Você não tem permissão para ver este perfil.",
  identityTitle: "Identidade",
  identitySubtitle: "Dados do diretório Minha DELPI (somente leitura neste Portal).",
  shortcutsTitle: "Atalhos",
  shortcutsSubtitle: "Caminhos liberados no Portal Suprimentos.",
  shortcutsAriaLabel: "Atalhos do Portal Suprimentos",
  preferencesTitle: "Preferências",
  preferencesSubtitle: "Valem só neste Portal — distinta do perfil global Minha DELPI.",
  accessTitle: "Acesso na plataforma",
  accessSubtitle: "Permissões e capacidades do Portal Suprimentos nesta sessão.",
  accessSelfOnly: "A lista completa de permissões RBAC aparece no seu próprio perfil.",
  accessLoading: "Carregando acessos…",
  accessContextHeading: "Contexto admin",
  accessCapabilitiesHeading: "Capacidades da sessão",
  accessPermissionsHeading: "Permissões RBAC",
  superadmin: "Superadmin",
  capabilityAccess: "Acesso ao Portal",
  capabilityManage: "Administração do Portal",
  permissionAccess: "Acessar Portal Suprimentos",
  permissionManage: "Administrar Portal Suprimentos",
  permissionAccessCode: "supplies.access",
  permissionManageCode: "supplies.manage",
  emailLabel: "E-mail",
  nameLabel: "Nome",
  jobTitleLabel: "Cargo",
  phoneLabel: "Telefone",
  mobileLabel: "Celular",
  whatsappLabel: "WhatsApp",
  defaultBranchLabel: "Filial padrão",
  defaultBranchEmpty: "Nenhuma (usar a primeira liberada)",
  tableDensityLabel: "Densidade de tabelas",
  densityComfortable: "Confortável",
  densityCompact: "Compacta",
  save: "Salvar preferências",
  saving: "Salvando…",
  saveOk: "Preferências atualizadas.",
  saveError: "Não foi possível salvar as preferências.",
  unitsLabel: "Filiais",
  helpAriaLabel: "Ajuda: perfil do Portal Suprimentos",
  shortcutHome: "Início",
  shortcutOverview: "Visão geral",
  shortcutSc: "Solicitações",
  shortcutHelp: "Ajuda",
} as const;
