export const USER_PROFILE_CONTENT = {
  pageAriaLabel: "Perfil do usuário",
  backFallback: "Portal Suprimentos",
  loading: "Carregando perfil…",
  error: "Não foi possível carregar o perfil.",
  retry: "Tentar novamente",
  forbidden: "Você não tem permissão para ver este perfil.",
  identityTitle: "Identidade",
  identitySubtitle: "Dados do diretório Minha DELPI (somente leitura neste Portal).",
  shortcutsTitle: "Atalhos",
  shortcutsSubtitle: "Caminhos liberados no Portal Suprimentos.",
  preferencesTitle: "Preferências",
  preferencesSubtitle: "Valem só neste Portal — distinta do perfil global Minha DELPI.",
  preferencesOther:
    "Preferências só podem ser alteradas no próprio perfil.",
  accessTitle: "Acesso",
  accessSubtitle: "Capabilities e filiais efetivas neste Portal.",
  accessOther: "O bloco de acesso aparece apenas no seu próprio perfil.",
  emailLabel: "E-mail",
  nameLabel: "Nome",
  jobTitleLabel: "Cargo",
  phoneLabel: "Telefone",
  mobileLabel: "Celular",
  whatsappLabel: "WhatsApp",
  defaultBranchLabel: "Filial padrão",
  defaultBranchEmpty: "Nenhuma (usar a primeira liberada)",
  tableDensityLabel: "Densidade de tabelas",
  densityComfortable: "Confortável",
  densityCompact: "Compacta",
  save: "Salvar preferências",
  saving: "Salvando…",
  saveOk: "Preferências atualizadas.",
  saveError: "Não foi possível salvar as preferências.",
  unitsLabel: "Filiais",
  hostProfileNote:
    "Foto, cargo e contatos vêm do Meu Perfil da Minha DELPI (/profile). Aqui só dá para editar preferências deste Portal.",
  helpAriaLabel: "Ajuda: perfil do Portal Suprimentos",
  shortcutHome: "Início",
  shortcutOverview: "Visão geral",
  shortcutSc: "Solicitações",
  shortcutHelp: "Ajuda",
  badgeSelf: "Você",
  badgeAdminView: "Leitura admin",
} as const;
