import type { FlowchartEditorLabels } from "@delpi/plugin-ui";

import { TM_HELP_TOOLTIPS } from "./helpTooltips";

const D = TM_HELP_TOOLTIPS.diagramEditor;

export const TRANSFORMOMETRO_FLOWCHART_EDITOR_LABELS: FlowchartEditorLabels = {
  usoGeral: D.usoGeral,
  canvasTab: D.canvasTab,
  mermaidTab: D.mermaidTab,
  addLane: D.addLane,
  autoLayout: D.autoLayout,
  templateLinear: D.templateLinear,
  templateDecision: D.templateDecision,
  templateSwimlanes: D.templateSwimlanes,
  laneSelect: D.laneSelect,
  laneRename: D.laneRename,
  laneRemove: D.laneRemove,
  selectionDelete: D.selectionDelete,
  selectionMove: D.selectionMove,
  selectionCopy: D.selectionCopy,
  selectionPaste: D.selectionPaste,
  selectionDuplicate: D.selectionDuplicate,
  selectionEdgeKind: D.selectionEdgeKind,
  nodeHints: D.nodes,
  elementGroupTabs: [
    { id: "events", label: "Eventos" },
    { id: "gateways", label: "Desvios" },
    { id: "tasks", label: "Tarefas" },
    { id: "activities", label: "Atividades" },
    { id: "artifacts", label: "Artefatos" },
    { id: "boundary", label: "Borda" },
    { id: "lanes", label: "Faixas" },
  ],
  eventSubTabs: [
    { id: "events_start", label: "Início" },
    { id: "events_intermediate", label: "Intermediários" },
    { id: "events_end", label: "Fim" },
  ],
  editorActions: [
    { id: "addLane", label: "Faixa", hint: D.addLane },
    { id: "autoLayout", label: "Layout automático", hint: D.autoLayout },
    { id: "templateLinear", label: "Modelo linear", hint: D.templateLinear },
    { id: "templateDecision", label: "Modelo decisão", hint: D.templateDecision },
    { id: "templateSwimlanes", label: "Modelo BPMN com faixas", hint: D.templateSwimlanes },
  ],
  selectionActions: [
    { id: "delete", label: "Excluir", hint: D.selectionDelete },
    { id: "copy", label: "Copiar", hint: D.selectionCopy },
    { id: "paste", label: "Colar", hint: D.selectionPaste },
    { id: "duplicate", label: "Duplicar", hint: D.selectionDuplicate },
    { id: "cycleEdgeKind", label: "Tipo de conexão", hint: D.selectionEdgeKind },
  ],
  confirmDeleteLane: {
    title: "Excluir faixa",
    message: "Excluir a faixa ativa e realocar os nós?",
    confirmLabel: "Excluir",
  },
  emptyLaneFallback: "Faixa",
  laneInlineLabel: "Nome da faixa",
  exportEmptyDiagram: "Diagrama vazio.",
  exportCanvasMissing: "Canvas do diagrama não encontrado.",
  exportViewportMissing: "Viewport do diagrama não encontrado.",
  exportOpenCanvasTab: "Abra a aba Desenho antes de exportar o PNG.",
  mermaidApply: "Aplicar ao desenho",
  mermaidSyncFromDrawing: "Atualizar do desenho",
  mermaidPlaceholder: "Cole ou edite o código Mermaid…",
  canvasTabLabel: "Desenho",
  mermaidTabLabel: "Mermaid",
  toolbarElementsTab: "Elementos",
  toolbarModelsTab: "Modelos",
  toolbarHowToUse: "Como usar",
  toolbarAriaLabel: "Ferramentas do diagrama",
  toolbarGroupsAriaLabel: "Grupos de ferramentas",
  toolbarHowToUseAriaLabel: "Como usar o editor de diagrama",
  paletteCategoriesAriaLabel: "Categorias de elementos BPMN",
  paletteEventsAriaLabel: "Tipos de evento",
  selectionDockAriaLabel: "Ações de seleção do diagrama",
  laneToolbarAriaLabel: "Faixas do diagrama",
  mermaidRefreshFromDrawing: "Atualizar do desenho",
  mermaidStarterTemplate: "Modelo inicial",
  mermaidApplyToDrawing: "Aplicar ao desenho",
  mermaidApplying: "Aplicando…",
  mermaidReadonlyEmpty: "Sem preview.",
  mermaidCodeAriaLabel: "Código Mermaid",
  mermaidRendering: "Gerando preview…",
  mermaidRenderError: "Erro ao renderizar Mermaid.",
};
