"""C5-GOVERNED-WRITE-FOUNDATION-01 governed-write semantic contracts."""

from app.domain.governed_write.model import (
    ConfirmationDecision,
    ConfirmationReason,
    ConfirmationRecord,
    ConfirmationState,
    GovernedWriteBinding,
    ProposalReadiness,
    StructuredConfirmation,
    WriteAuditStage,
    WriteDecisionAuditRecord,
    WriteGateDecision,
    WriteGateReason,
    WriteGateStatus,
    WriteOutcomeProjection,
    WriteOutcomeStatus,
    WriteProposalPreview,
)
from app.domain.governed_write.rules import (
    GOVERNED_WRITE_BINDINGS,
    bind_confirmation,
    evaluate_write_continuation,
    preview_fingerprint,
    project_proposal_preview,
    project_write_outcome,
    proposal_digest,
    write_binding_for,
)

__all__ = [
    "ConfirmationDecision",
    "ConfirmationReason",
    "ConfirmationRecord",
    "ConfirmationState",
    "GOVERNED_WRITE_BINDINGS",
    "GovernedWriteBinding",
    "ProposalReadiness",
    "StructuredConfirmation",
    "WriteAuditStage",
    "WriteDecisionAuditRecord",
    "WriteGateDecision",
    "WriteGateReason",
    "WriteGateStatus",
    "WriteOutcomeProjection",
    "WriteOutcomeStatus",
    "WriteProposalPreview",
    "bind_confirmation",
    "evaluate_write_continuation",
    "preview_fingerprint",
    "project_proposal_preview",
    "project_write_outcome",
    "proposal_digest",
    "write_binding_for",
]
