BEGIN;

-- V014 — Trilha append-only de mudanças de contagem do Production Run.
--
-- production_runs.pieces_total continua sendo o estado atual; esta
-- registra os fatos observados a partir da implantação (sem backfill):
-- delta > 0 = production, delta < 0 = correction, delta 0 nunca é gravado.
-- Cada evento é persistido na MESMA transação da atualização do run.

CREATE TABLE IF NOT EXISTS production_control.production_run_count_events (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          UUID        NOT NULL
        REFERENCES production_control.production_runs(id) ON DELETE CASCADE,
    pieces_total    BIGINT      NOT NULL,
    delta_pieces    BIGINT      NOT NULL,
    event_type      VARCHAR(30) NOT NULL
        CHECK (event_type IN ('production', 'correction')),
    occurred_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_pc_count_events_pieces_total_nonneg CHECK (pieces_total >= 0),
    CONSTRAINT ck_pc_count_events_delta_nonzero CHECK (delta_pieces <> 0)
);

-- Leitura principal: eventos de um run em ordem cronológica.
CREATE INDEX IF NOT EXISTS ix_pc_run_count_events_run_chrono
    ON production_control.production_run_count_events (run_id, occurred_at, id);

COMMENT ON TABLE production_control.production_run_count_events IS
    'Fatos append-only de mudança de pieces_total por run (production/correction). Sem heartbeat/poll sem mudança; salto observado vira um único evento agregado.';

COMMENT ON COLUMN production_control.production_run_count_events.pieces_total IS
    'Total físico de peças do run logo após a mudança observada.';

COMMENT ON COLUMN production_control.production_run_count_events.delta_pieces IS
    'Variação em peças físicas entre a observação anterior e a atual (nunca 0).';

COMMENT ON COLUMN production_control.production_run_count_events.event_type IS
    'production (delta positivo) ou correction (delta negativo).';

COMMENT ON COLUMN production_control.production_run_count_events.occurred_at IS
    'Instante em que o Production Control observou e confirmou a mudança — não é o instante físico da borda do sensor.';

COMMIT;
