"""Seleção auto tier C — rotas geradas do OpenAPI."""

from __future__ import annotations

from typing import Callable

from app.domain.services.operational_route_registry_service import (
    OperationalRouteRegistryService,
)


class OperationalRouteAutoTierCSelectionService:
    def __init__(self, resolver) -> None:
        self._resolver = resolver

    def select_auto_tier_c(
        self,
        message: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        rank_candidates: Callable[..., list[dict]] | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        previous_messages: list | None = None,
    ) -> dict | None:
        if not allowed_action_ids or not candidates_loader or not rank_candidates:
            return None

        candidates = candidates_loader(
            message,
            allowed_action_ids=allowed_action_ids,
            limit=120,
        )

        if not candidates:
            return None

        ranked = rank_candidates(
            message,
            candidates,
            allowed_action_ids=allowed_action_ids,
        )

        if not ranked:
            return None

        top = ranked[0]
        operation_id = str(top.get("operationId") or "").strip()

        if top.get("selectionScore") is None or not operation_id:
            return None

        route = OperationalRouteRegistryService.route_by_operation_id(operation_id)

        if not route or not route.get("autoGenerated"):
            return None

        return self._resolver.resolve_route_action(
            route,
            message,
            allowed_action_ids,
            candidates=[top],
            candidates_loader=candidates_loader,
            previous_messages=previous_messages,
            build_date_branch_parameters=build_date_branch_parameters,
        )
