export const PAC_HELP_TOOLTIPS = {
  filters: {
    scope:
      "Escopo da não conformidade: interna (detectada na planta) ou externa (cliente/fornecedor). Vazio = todos.",
    status: "Estágio do plano no fluxo PAC (triagem, contenção, análise, validação, concluído, etc.).",
    severity: "Prioridade do plano: baixa, média, alta ou crítica.",
    branch: "Filial TOTVS (01 ou 02). Vazio = todas as filiais.",
    customer: "Filtra planos pelo nome do cliente informado na identificação.",
    product: "Código do produto vinculado à NC.",
    failureMode: "Texto do modo de falha registrado no plano (busca parcial).",
    owner: "Responsável pelo plano (usuário ou identificador cadastrado).",
    department: "Área ou departamento associado ao problema.",
    rootCause: "Texto ou categoria da causa raiz registrada no plano.",
    overdueOnly:
      "Mostra apenas planos com ações ou prazos em atraso conforme regras de SLA do PAC.",
    includeCompleted:
      "Inclui na listagem ações já marcadas como concluídas (planos ainda em andamento).",
    refresh: "Recarrega a listagem com os filtros atuais.",
    clear: "Remove todos os filtros aplicados.",
  },
  kpis: {
    openPlans: "Planos em andamento (não concluídos nem cancelados) no recorte atual.",
    criticalOpen: "Planos abertos classificados com severidade crítica.",
    overduePlans: "Planos com prazo ou estágio em atraso segundo o SLA configurado.",
    overdueActions: "Ações corretivas/contenção com prazo vencido e ainda não concluídas.",
    waitingValidation: "Planos aguardando validação de eficácia ou encerramento formal.",
    completedThisMonth: "Planos concluídos no mês calendário corrente.",
    avgClosure:
      "Média de dias entre abertura e encerramento dos planos concluídos na janela analítica.",
    avgEffectiveness:
      "Média de dias até o registro de eficácia nos planos revisados na janela analítica.",
    recurrence:
      "Grupos com mesmo produto e modo de falha abertos duas ou mais vezes na janela.",
  },
  charts: {
    overview: "Visão consolidada: abertos, críticos, aguardando validação e concluídos no mês.",
    byBranch: "Comparativo de planos abertos e críticos por filial.",
    byScope: "Distribuição entre NC interna e externa.",
    byStatus: "Quantidade de planos em cada estágio do fluxo.",
    bySeverity: "Distribuição por nível de severidade nos planos carregados.",
    topCategories: "Categorias de problema mais frequentes na janela selecionada.",
    topFailureModes: "Modos de falha que mais se repetem nos planos analisados.",
    actionsMix: "Volume de ações criadas por tipo (contenção, corretiva, preventiva, etc.).",
    topCustomers: "Clientes com maior número de planos de ação na janela.",
    topProducts: "Produtos com mais ocorrências de NC na janela.",
    topOwners: "Responsáveis com maior volume de planos abertos ou tratados.",
    effectivenessByAction:
      "Percentual de eficácia entre planos revisados, agrupado por tipo de ação predominante.",
  },
  sections: {
    problem: "Resumo do relato, severidade, escopo e identificação principal da NC.",
    planStatus: "Fluxo operacional do plano, estágio atual e alteração de status.",
    audit: "Histórico de eventos do plano (criação, alterações, eficácia, reabertura).",
    template: "Relatório estruturado do cliente (ex.: 8D) quando o plano usa template dedicado.",
    ishikawa:
      "Diagrama espinha de peixe (6M): hipóteses de causa por Máquina, Método, Material, Mão de obra, Medição e Meio ambiente.",
    fiveWhys:
      "Trilhas de porquês de ocorrência e detecção. Quantidade flexível; deslize horizontalmente para ver todos os passos.",
    actions:
      "Plano de ações corretivas, preventivas e de contenção com responsável, prazo, evidência e status.",
    effectiveness:
      "Registro da verificação de eficácia após implementação das ações (eficaz, parcial ou ineficaz).",
    evidences: "Anexos que comprovam contenção, correção ou verificação (arquivos, fotos, laudos).",
    similarCases:
      "Planos anteriores com produto, sintoma ou causa semelhantes para reutilizar aprendizado.",
    timeline: "Linha do tempo das mudanças de status e marcos do plano.",
    disciplineProgress:
      "Checklist das disciplinas D0–D8 do método 8D e percentual de preenchimento.",
    recurrencePanel:
      "Agrupamentos com reabertura recorrente do mesmo produto e modo de falha.",
    myQueue: "Fila pessoal de planos e ações sob sua responsabilidade.",
    solutionPatterns: "Padrões de solução reutilizáveis promovidos a partir de planos eficazes.",
  },
  form: {
    identification: "Dados cadastrais do plano: título, cliente, produto, lote e filial.",
    source: "Canal de origem do relato (e-mail, PDF, texto manual) e referência externa.",
    context: "Cliente, produto, lote, área e modo de falha para contextualizar a NC.",
    description: "Narrativa do problema relatado e tags de sintoma para busca futura.",
    actionType: "Classificação da ação: contenção, corretiva, preventiva, verificação, padronização ou treinamento.",
    actionTrack: "Em 8D, indica se a ação trata a causa de ocorrência ou de detecção.",
    actionEvidence:
      "Quando marcado, exige anexo de evidência antes de concluir a ação.",
    actionResponsible: "Pessoa ou equipe responsável pela execução da ação.",
    actionResponsibleUserLink:
      "Busque um usuário Delpi com acesso ao PAC (nome ou e-mail). Opcional — habilita a Minha fila e notificações para essa pessoa.",
    actionResponsibleLinked:
      "Usuário vinculado por ID — a ação entra na Minha fila dele enquanto estiver aberta.",
    actionResponsibleTeamUnlinked:
      "Este membro ainda não tem usuário Delpi vinculado na seção 2. Vincule na equipe de análise para habilitar a Minha fila.",
    actionResponsibles:
      "Selecione um ou mais membros da equipe 8D. Cada um com usuário Delpi vinculado recebe a ação na Minha fila e alertas de prazo.",
    actionDueDate: "Prazo acordado para conclusão da ação.",
    actionStatus: "Situação atual da ação (pendente, em andamento, concluída, etc.).",
    actionDescription: "O que será feito — descrição objetiva da ação corretiva ou de contenção.",
    rootCause: "Síntese da causa raiz validada após Ishikawa e porquês.",
    confidence: "Grau de confiança da equipe na causa raiz identificada.",
  },
  detail: {
    title: "Nome curto do plano para listagens, buscas e relatórios.",
    customer: "Cliente ou demandante associado à não conformidade.",
    productCode: "Código do material ou produto no cadastro Delpi (TOTVS).",
    customerProductReference:
      "Referência do cliente no cadastro do produto (SB1010.B1_REFEREN). Também serve para localizar o PA Delpi.",
    productDescription: "Descrição técnica do material ou item afetado.",
    supplierBatch: "Lote do fornecedor ou lote interno vinculado à ocorrência.",
    department: "Área ou departamento onde o problema foi detectado ou tratado.",
    failureMode: "Como a falha se manifestou (ex.: trinca, oxidação, dimensional).",
    problemCategory: "Classificação do tipo de problema para análises e recorrência.",
    symptomTags: "Palavras-chave separadas por vírgula — alimentam busca e casos similares.",
    sourceReference: "ID do e-mail, ticket, arquivo ou outra referência do canal de origem.",
    clientNcRegistry: "Número formal da reclamação registrada pelo cliente.",
    statusPipeline: "Estágio atual do plano no fluxo operacional do PAC.",
    updateStatus: "Avança ou retrocede o plano no fluxo (triagem, contenção, análise, etc.).",
    reopenReason: "Justificativa obrigatória (mín. 5 caracteres) para reabrir plano encerrado.",
    reopenTargetStatus: "Estágio em que o plano deve retomar após a reabertura.",
    effectivenessResult: "Veredito da verificação: eficaz, parcial, ineficaz ou pendente.",
    effectivenessNotes: "Evidências e conclusão da verificação de eficácia das ações.",
    effectivenessRejection: "Motivo da rejeição quando a coordenação não aprova a submissão.",
    promotePattern: "Registra este plano como padrão de solução reutilizável (eficácia comprovada).",
    fiveWhysOccurrence: "Cadeia de porquês sobre por que o problema ocorreu.",
    fiveWhysDetection: "Cadeia de porquês sobre por que o problema não foi detectado antes.",
    fiveWhysQuestion: "Formule a pergunta deste passo (ex.: Por que o defeito ocorreu?).",
    fiveWhysAnswer: "Responda à pergunta acima; o próximo passo parte desta resposta.",
    fiveWhysStep: "Responda ao porquê anterior nesta trilha até chegar à causa provável.",
    timelineFilter: "Filtra eventos da linha do tempo por categoria.",
  },
  evidence: {
    type: "Formato do anexo: imagem, PDF, planilha, e-mail, etc.",
    section: "Disciplina 8D ou área do plano à qual o anexo se refere.",
    linkedAction: "Associa a evidência a uma ação corretiva ou de contenção específica.",
    description: "Texto livre que descreve o conteúdo ou contexto do anexo.",
    upload: "Selecione um arquivo do computador (imagem, PDF, planilha, etc.) para anexar.",
  },
  ishikawa: {
    notes: "Comentários gerais sobre a análise 6M e hipóteses descartadas.",
    machine: "Causas relacionadas a equipamentos, ferramental e manutenção.",
    method: "Causas ligadas a método, processo e procedimento.",
    material: "Causas ligadas a matéria-prima, insumos e especificação.",
    manpower: "Causas ligadas a pessoas, treinamento e competência.",
    measurement: "Causas ligadas a medição, calibração e critérios de aceite.",
    environment: "Causas ligadas a ambiente, layout e condições externas.",
  },
  rnc8d: {
    identification: "Dados do relatório formal 8D para materiais adquiridos.",
    ncDescription: "Descrição técnica da não conformidade conforme planilha do cliente.",
    contact: "Nome da pessoa de contato no cliente para o relatório 8D.",
    purchaseOrder: "Ordem de compra e posição do material reclamado.",
    invoice: "Número da nota fiscal de entrada do material.",
    invoiceDate: "Data em que a NF foi digitada no sistema.",
    defectiveQty: "Quantidade de peças com defeito identificado.",
    phone: "Telefone de contato do cliente.",
    clientBatch: "Lote informado pelo cliente na reclamação.",
    batchQty: "Quantidade total do lote reclamado.",
    disposition: "Decisão sobre o material (devolver, segregar, retrabalhar, etc.).",
    rejectedQty: "Quantidade efetivamente rejeitada.",
    characteristic: "Tipo de requisito avaliado (dimensional, especificação, componente).",
    specified: "O que estava especificado ou aceito como conforme.",
    observations: "Observações adicionais da descrição técnica da NC.",
    returnBy: "Prazo acordado com o cliente para devolver o relatório 8D.",
    attentionTo: "Destinatário formal do relatório no cliente.",
    attentionEmail: "E-mail para envio do relatório ao cliente.",
    team: "Equipe multidisciplinar responsável pela análise 8D (D1).",
    teamLeader: "Indica o membro líder da equipe de análise.",
    teamMemberArea:
      "Área ou departamento em que o membro atua na análise (ex.: Qualidade, Engenharia, Produção).",
    teamMemberSelect: "Membros cadastrados na seção 2. O vínculo Delpi é feito nesta seção.",
    teamMemberUserLink:
      "Pesquise na Delpi usuários com acesso ao PAC (mesmo fluxo da busca de cliente).",
    teamMemberLinked: "Usuário Delpi vinculado a este membro da equipe.",
    teamMemberUnlinked:
      "Sem vínculo — ações com este membro não entram na Minha fila até vincular um usuário Delpi.",
    containment: "Ações imediatas por área (cliente final, planta, fornecedor) — D3.",
    containmentArea: "Onde a contenção se aplica: cliente final, planta do cliente ou fornecedor.",
    containmentQty: "Quantidade de material ou lotes afetados na contenção.",
    containmentActionPlan: "Descrição da ação imediata para isolar o problema.",
    containmentResponsible: "Responsável pela execução da contenção.",
    containmentDate: "Prazo ou data de conclusão da ação de contenção.",
    effectivenessSection: "Verificação se a correção eliminou o problema — D6.",
    resolvedHow: "Narrativa de como foi comprovado que o problema foi resolvido.",
    okMaterialDate: "Data a partir da qual o material voltou a ser aceito (ponto de corte).",
    newPartsId: "Como identificar visualmente lotes/peças produzidos após a correção.",
    verificationResponsible: "Quem realizou a verificação de eficácia.",
    verificationDate: "Data em que a verificação de eficácia foi concluída.",
    preventiveSection: "Ações para evitar recorrência e atualizar documentos — D7.",
    howAvoidFuture: "Medidas sistêmicas para evitar repetição do problema.",
    otherProcesses: "Outros produtos ou processos que podem ser afetados pela mesma causa.",
    evalResponsible: "Responsável pela avaliação de risco e prevenção.",
    evalDate: "Data de conclusão da avaliação preventiva.",
    documentation: "Documentos (FMEA, instrução, PPAP) que precisam ser revisados.",
    docAffected: "Nome ou código do documento afetado (instrução, FMEA, desenho, etc.).",
    docResponsible: "Responsável pela revisão ou atualização do documento.",
    docDate: "Prazo ou data prevista para conclusão da atualização documental.",
    clientClosure: "Campo de encerramento formal para uso do cliente no relatório 8D.",
  },
  alerts: {
    stalled:
      "Planos sem movimentação recente no estágio atual — podem precisar de follow-up.",
    effectivenessPending:
      "Planos com eficácia submetida aguardando aprovação do coordenador.",
    recurrence:
      "Padrões com múltiplas aberturas do mesmo produto e falha nos últimos meses.",
  },
  tables: {
    code: "Identificador legível do plano (ex.: PAC-2026-0029), gerado automaticamente na abertura.",
    title: "Nome curto do plano para listagens, buscas e relatórios.",
    customer: "Cliente ou demandante associado à não conformidade.",
    branch: "Filial TOTVS onde o plano foi aberto ou onde o problema ocorreu.",
    scope: "NC interna (detectada na planta) ou externa (cliente/fornecedor).",
    product: "Código do material ou produto no cadastro (TOTVS).",
    severity: "Prioridade do plano: baixa, média, alta ou crítica.",
    status: "Estágio atual do plano no fluxo PAC (triagem, contenção, análise, etc.).",
    sla: "Situação do prazo conforme regras de SLA (em dia, em risco ou vencido).",
    updatedAt: "Data e hora da última alteração registrada no plano.",
    rowActions: "Atalho para abrir o detalhe do plano ou executar ações na linha.",
    plan: "Código e título do plano de ação vinculado à tarefa.",
    action: "Descrição da ação corretiva, de contenção ou preventiva atribuída a você.",
    actionType: "Classificação da ação: contenção, corretiva, preventiva, verificação, etc.",
    dueDate: "Prazo acordado para conclusão da ação; destaca atrasos e vencimentos próximos.",
    actionStatus: "Situação atual da ação (pendente, em andamento, concluída, etc.).",
    failureMode: "Como a falha se manifestou (ex.: trinca, oxidação, dimensional).",
    totalPlans: "Quantidade total de planos no grupo de recorrência.",
    openPlans: "Planos ainda em andamento neste grupo.",
    criticalOpen: "Planos abertos com severidade crítica neste grupo.",
    lastPlan: "Código do plano mais recente neste agrupamento.",
    lastOpened: "Data da abertura do plano mais recente do grupo.",
    category: "Categoria de problema associada ao padrão de solução.",
    effectiveness: "Taxa histórica de eficácia quando o padrão foi reutilizado.",
    usageCount: "Quantas vezes o padrão foi aplicado em planos posteriores.",
    recommendedActions: "Ações sugeridas pelo padrão para resolver problemas semelhantes.",
    file: "Nome do arquivo anexado como evidência.",
    planRef: "Plano de ação ao qual a evidência está vinculada.",
    sectionRef: "Disciplina 8D ou área do plano à qual o anexo se refere.",
    description: "Texto que descreve o conteúdo ou contexto do registro.",
    uploadedAt: "Data e hora em que o arquivo foi enviado ao sistema.",
    evidenceType: "Formato do anexo: imagem, PDF, planilha, e-mail, etc.",
    linkedAction: "Ação corretiva ou de contenção associada à evidência.",
    fileSize: "Tamanho do arquivo em bytes, exibido de forma legível.",
    evidenceActions: "Pré-visualizar, baixar ou remover o anexo.",
    similarityScore: "Grau de semelhança com o plano atual (produto, sintoma e contexto).",
    summary: "Resumo do problema tratado no plano histórico.",
    effectivenessStatus: "Resultado da verificação de eficácia e data de encerramento.",
    proposedEffectiveness: "Veredito de eficácia proposto pelo responsável (eficaz, parcial ou ineficaz).",
    submittedAt: "Data em que a eficácia foi submetida para aprovação.",
    submittedBy: "Usuário que registrou a submissão de eficácia.",
    causeTrack: "Em 8D, indica se a ação trata a causa de ocorrência ou de detecção.",
    evidenceRequired: "Se a ação exige anexo de evidência antes de ser concluída.",
    customerCode: "Código do cliente no cadastro TOTVS (SA1).",
    customerStore: "Loja do cliente no cadastro TOTVS, quando aplicável.",
    customerName: "Razão social ou nome fantasia do cliente.",
    selectCustomer: "Selecionar este cliente para preencher o plano.",
    directoryUserName: "Nome do usuário na plataforma Delpi.",
    directoryUserEmail: "E-mail do usuário na plataforma Delpi.",
    selectDirectoryUser: "Vincular este usuário Delpi ao membro ou responsável.",
    reorder: "Arraste para reordenar as linhas da tabela.",
  },
} as const;
