export {
  ChartTypeCatalogPanel,
  DELPI_CHART_CATALOG_CATEGORIES,
  DELPI_CHART_TYPE_CATALOG,
  DELPI_CHART_CATALOG_ICON_MAP,
  resolveChartCatalogIcon,
  type ChartTypeCatalogPanelProps,
  type DelpiChartCatalogEntry,
  type DelpiChartType,
} from "./ChartTypeCatalogPanel";
export {
  TableInsertCatalogPanel,
  DELPI_TABLE_GRID_MAX_COLS,
  DELPI_TABLE_GRID_MAX_ROWS,
  DELPI_TABLE_INSERT_PRESETS,
  type DelpiTableInsertPreset,
  type DelpiTableInsertSelection,
  type TableInsertCatalogPanelProps,
} from "./TableInsertCatalogPanel";
export {
  ImpactEffortMatrix,
  ImpactEffortMatrixLegend,
  type ImpactEffortMatrixLegendProps,
  type ImpactEffortMatrixProps,
} from "./ImpactEffortMatrix";
export {
  impactEffortMatrixBemClasses,
  impactEffortMatrixTransformometroClasses,
  quadrantClassName,
  type ImpactEffortMatrixClassNames,
} from "./impactEffortMatrixClasses";
export {
  DEFAULT_IMPACT_EFFORT_AXIS_LABELS,
  DEFAULT_IMPACT_EFFORT_QUADRANT_DESCRIPTIONS,
  DEFAULT_IMPACT_EFFORT_QUADRANT_LABELS,
  clampImpactEffortScore,
  resolveImpactEffortQuadrant,
  type ImpactEffortAxisLabels,
  type ImpactEffortConfidence,
  type ImpactEffortMatrixMode,
  type ImpactEffortPoint,
  type ImpactEffortQuadrant,
  type ImpactEffortQuadrantDescriptions,
  type ImpactEffortQuadrantLabels,
} from "./impactEffortTypes";
export { ConfigurableSeriesChart, type ConfigurableSeriesChartProps } from "./ConfigurableSeriesChart";
export { SeriesChartPrimitive, type SeriesChartPrimitiveProps, type SeriesPlotRenderProps } from "./SeriesChartPrimitive";
export { LineSeriesChart, type LineSeriesChartProps } from "./LineSeriesChart";
export { BarSeriesChart, type BarSeriesChartProps } from "./BarSeriesChart";
export {
  ComparativeAreaChart,
  comparativeAreaChartBemClasses,
  type ComparativeAreaChartPoint,
  type ComparativeAreaChartProps,
  type ComparativeAreaChartSeries,
} from "./ComparativeAreaChart";
export {
  SpeedometerGauge,
  SPEEDOMETER_TONE_COLORS,
  resolveSpeedometerZoneThresholds,
  speedometerGaugeBemClasses,
  type SpeedometerGaugeClassNames,
  type SpeedometerGaugeProps,
  type SpeedometerGaugeTone,
} from "./SpeedometerGauge";
export {
  HorizontalValueBars,
  horizontalValueBarsBemClasses,
  type HorizontalValueBarItem,
  type HorizontalValueBarsClassNames,
  type HorizontalValueBarsProps,
} from "./HorizontalValueBars";
export {
  ChartSeriesViewport,
  chartSeriesViewportBemClasses,
  type ChartSeriesViewportClassNames,
  type ChartSeriesViewportLabels,
  type ChartSeriesViewportProps,
} from "./ChartSeriesViewport";
export {
  seriesChartBemClasses,
  seriesChartTvClasses,
  SeriesChartClassesProvider,
  useSeriesChartClasses,
  type SeriesChartClassNames,
  type SeriesChartClassesProviderProps,
} from "./seriesChartClasses";
export {
  DEFAULT_CATEGORY_PADDING_PERCENT,
  DEFAULT_SERIES_CHART_OPTIONS,
  OFFICE_CHART_AREA_FILL,
  OFFICE_CHART_AREA_STROKE,
  OFFICE_CHART_PLOT_FILL,
  OFFICE_CHART_PLOT_STROKE,
  OFFICE_CHART_SERIES_COLOR,
  SERIES_CHART_CATEGORY_PALETTE,
  SERIES_CHART_CHROME_VERSION,
  SERIES_CHART_LEGEND_POSITION_OPTIONS,
  SERIES_CHART_LEGEND_LAYOUT_OPTIONS,
  SERIES_CHART_LEGEND_SORT_OPTIONS,
  SERIES_CHART_VALUE_FORMAT_OPTIONS,
  SERIES_CHART_CATEGORY_LABEL_ROTATION_OPTIONS,
  SERIES_CHART_CATEGORY_LABEL_OVERFLOW_OPTIONS,
  SERIES_CHART_CATEGORY_LABEL_FORMAT_OPTIONS,
  formatSeriesChartValue,
  formatSeriesChartCategoryLabel,
  resolveSeriesChartValueDisplaySpec,
  resolveSeriesChartCategoryDisplaySpec,
  localizeEnglishMonthTokensInLabel,
  parseSeriesChartCategoryDate,
  truncateSeriesChartCategoryLabel,
  mergeSeriesChartOptions,
  migrateSeriesChartOptionsOnLoad,
  resolveSeriesChartDisplayOptions,
  resolveSeriesChartLegendLayout,
  resolveSeriesChartLegendSort,
  resolveSeriesChartTicks,
  resolveSeriesChartValueDomain,
  resolveSeriesCategoryColor,
  resolveValueScaleColor,
  resolveGoalThresholdColor,
  GOAL_SCALE_BAND_RATIO,
  GOAL_SCALE_COLORS,
  seriesValueExtent,
  seriesChartThemeStyle,
  usableSeriesChartPoints,
  type SeriesChartCategoryLabelFormat,
  type SeriesChartCategoryLabelOverflow,
  type SeriesChartCategoryLabelRotation,
  type SeriesChartColorScale,
  type SeriesChartKind,
  type SeriesChartLegendLayout,
  type SeriesChartLegendLayoutResolved,
  type SeriesChartLegendPosition,
  type SeriesChartLegendSort,
  type SeriesChartLegendSortResolved,
  type SeriesChartOptions,
  type SeriesChartPoint,
  type SeriesChartSeriesSpec,
  type SeriesChartResolvedMeta,
  type SeriesChartTheme,
  type SeriesChartValueFormat,
} from "./seriesChartOptions";
export {
  applySeriesChartLegendSort,
  buildSeriesChartLegendItems,
  seriesChartUsesCategoryLegend,
  sortSeriesChartPoints,
  sortSeriesChartSeriesList,
  type SeriesChartLegendItem,
} from "./seriesChartLegendItems";
export {
  orderSeriesIndicesForOverlappingPaint,
  seriesPaintMagnitude,
  type SeriesPaintMagnitudeSource,
} from "./seriesChartPaintOrder";
export {
  DEFAULT_SERIES_CHART_DATA_LABELS,
  dataLabelOutsideGutterPx,
  dataLabelsConfigFromPreset,
  formatSeriesChartDataLabelText,
  matchDataLabelsPreset,
  mergeSeriesChartDataLabels,
  resolveDataLabelPosition,
  resolveSeriesChartDataLabels,
  shouldHideDataLabel,
  type SeriesChartDataLabelPosition,
  type SeriesChartDataLabelSeparator,
  type SeriesChartDataLabelsConfig,
  type SeriesChartDataLabelsPresetId,
  type SeriesChartDataLabelsResolved,
} from "./seriesChartDataLabels";
export {
  SERIES_CHART_ELEMENT_CATALOG,
  CHART_ELEMENT_CATALOG,
  isSeriesChartElementApplicable,
  isChartElementApplicable,
  isSeriesChartElementEnabled,
  isChartElementEnabled,
  setSeriesChartElementEnabled,
  setChartElementEnabled,
  applyChartElementVisibility,
  chartElementPartRefs,
  chartElementPrimaryPartRef,
  chartElementIdForPartRef,
  isChartElementOpenForPart,
  type SeriesChartElementDefinition,
  type ChartElementDefinition,
  type SeriesChartElementId,
  type ChartElementId,
} from "./seriesChartElementCatalog";
export {
  applyChartAddElementChoice,
  applyChartAddElementChoiceWithParts,
  chartAddElementChoiceRootId,
  chartAddElementMoreOptionsPartRef,
  isChartAddElementChoiceActive,
  type ChartAddElementChoiceId,
} from "./seriesChartAddElementChoices";
export {
  CHART_MARKER_RADIUS,
  CHART_PART_DATA_ATTR,
  CHART_LINE_STROKE_WIDTH_SEMANTIC,
  CHART_SERIES_LINE_STROKE_WIDTH,
  applyMarkerStyleToAll,
  bindChartPartPointer,
  chartOptionsToParts,
  chartPartAllowsDelete,
  chartPartAllowsEdit,
  chartPartAllowsFrame,
  chartPartAllowsMove,
  chartPartAllowsResize,
  chartPartCapabilities,
  chartPartDomProps,
  chartPartVisualPrimitive,
  chartPrimitiveSupportsFill,
  chartPrimitiveSupportsStroke,
  clampChartPartFrame,
  defaultChartPartFrame,
  defaultStrokeWidthForChartPrimitive,
  deleteChartPart,
  filterVisibleSeriesPoints,
  findChartPartFromTarget,
  getChartPartState,
  chartPartTypographyStyle,
  isChartPartRefEqual,
  isChartPartInteractionSelected,
  isFullBleedChartAreaFrame,
  mergeChartPartsWithOptions,
  mergeSeriesChartOptionsWithParts,
  normalizeChartPartsForLoad,
  nudgeChartPartFrame,
  parseChartPartRef,
  partsToChartOptions,
  resizeChartPartFrame,
  resolveChartAreaStyle,
  resolveChartPartFontSize,
  resolveChartPartFrameRoot,
  CHART_PART_FONT_SIZE_DEFAULTS,
  isChartTextPartKind,
  resolveMarkerStyle,
  resolvePlotAreaStyle,
  resolveSeriesLineStyle,
  resolveChartLinePartStroke,
  resolveCategorySlicePaintColor,
  resolveSeriesPaintColor,
  resolveSeriesStrokeColor,
  resolveSeriesStrokeWidth,
  applyChartTextStyleToSiblingParts,
  serializeChartPartRef,
  upsertChartPartState,
  CHART_PART_RESIZE_HANDLES,
  type ChartPartCapabilities,
  type ChartPartFrame,
  type ChartPartRef,
  type ChartPartResizeHandle,
  type ChartPartState,
  type ChartPartStyle,
  type ChartPartsMap,
  type ChartTextPartKind,
  type ChartVisualPrimitive,
  type SeriesChartInteraction,
} from "./seriesChartParts";
export {
  buildSeriesChartLayout,
  resolveSeriesName,
  resolveVisibleXLabelIndices,
  resolveXLabelStep,
  resolveXLabelTextAnchor,
  shouldRotateXLabels,
  SERIES_CHART_PLOT_INSET,
  SERIES_CHART_VIEW_H,
  SERIES_CHART_VIEW_W,
  type SeriesChartLayout,
} from "./seriesChart";
export * from "./seriesChart";

export {
  densifySeriesChartCurve,
  resolveSeriesChartStrokePoints,
  seriesChartPointsAttr,
  type SeriesChartCurvePoint,
} from "./seriesChartCurve";

export {
  TIME_MULTI_SERIES_TYPES,
  PERIOD_COMPARE_TYPES,
  RANKING_TYPES,
  COMPOSITION_TYPES,
  CATEGORICAL_TYPES,
  CHART_TYPE_LABELS_PT,
  chartTypesForFamily,
  defaultChartTypeForFamily,
  familySupportsChartTypeSwitch,
  type ChartDataFamily,
} from "./chartDataFamilies";

export {
  ChartTypeSegmentToggle,
  type ChartTypeSegmentToggleProps,
} from "./ChartTypeSegmentToggle";

export {
  delpiChartTypeToPersisted,
  persistedChartTypeToDelpi,
  persistedChartTypesToDelpi,
} from "./chartTypeBridge";

export {
  MultiTypeSeriesChart,
  type MultiTypeSeriesChartProps,
  type MultiTypeSeriesSpec,
} from "./MultiTypeSeriesChart";

export {
  ChartViewShell,
  chartViewShellBemClasses,
  type ChartViewShellClassNames,
  type ChartViewShellProps,
} from "./ChartViewShell";
