# -----------------
# gateway - DOCKERFILE DEV
# -----------------

FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/*

COPY nginx.conf /etc/nginx/nginx.conf
COPY snippets/ /etc/nginx/snippets/
COPY healthcheck.sh /usr/local/bin/gateway-healthcheck.sh
RUN chmod 0755 /usr/local/bin/gateway-healthcheck.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]