# -----------------
# gateway - DOCKERFILE DEV
# -----------------

FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/*

COPY nginx.conf /etc/nginx/nginx.conf
COPY snippets/ /etc/nginx/snippets/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]