events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://portal:5173;
    }

    location /core-api/ {
      proxy_pass http://core-api:8000/;
    }

    location /auth/ {
      proxy_pass http://keycloak:8080/;
    }
  }
}
