import type { FlowchartNodeType } from "./bpmnNodeCatalog";

export type FlowchartEditorLabels = {
  usoGeral: string;
  canvasTab: string;
  mermaidTab: string;
  addLane: string;
  autoLayout: string;
  templateLinear: string;
  templateDecision: string;
  templateSwimlanes: string;
  laneSelect: string;
  laneRename: string;
  laneRemove: string;
  selectionDelete: string;
  selectionMove: string;
  selectionCopy: string;
  selectionPaste: string;
  selectionDuplicate: string;
  selectionEdgeKind: string;
  nodeHints: Partial<Record<FlowchartNodeType, string>>;
  elementGroupTabs: Array<{ id: string; label: string }>;
  eventSubTabs: Array<{ id: string; label: string }>;
  editorActions: Array<{ id: string; label: string; hint: string }>;
  selectionActions: Array<{ id: string; label: string; hint: string }>;
  confirmDeleteLane: { title: string; message: string; confirmLabel: string };
  emptyLaneFallback: string;
  laneInlineLabel: string;
  exportEmptyDiagram: string;
  exportCanvasMissing: string;
  exportViewportMissing: string;
  exportOpenCanvasTab: string;
  mermaidApply: string;
  mermaidSyncFromDrawing: string;
  mermaidPlaceholder: string;
  canvasTabLabel: string;
  mermaidTabLabel: string;
  toolbarElementsTab: string;
  toolbarModelsTab: string;
  toolbarHowToUse: string;
  toolbarAriaLabel: string;
  toolbarGroupsAriaLabel: string;
  toolbarHowToUseAriaLabel: string;
  paletteCategoriesAriaLabel: string;
  paletteEventsAriaLabel: string;
  selectionDockAriaLabel: string;
  laneToolbarAriaLabel: string;
  mermaidRefreshFromDrawing: string;
  mermaidStarterTemplate: string;
  mermaidApplyToDrawing: string;
  mermaidApplying: string;
  mermaidReadonlyEmpty: string;
  mermaidCodeAriaLabel: string;
  mermaidRendering: string;
  mermaidRenderError: string;
};
