/** Microcopy do catálogo de fontes de dados (TV). */
export const DATA_BUILDER_CHAT_CONTENT = {
  title: "Fontes de dados",
  titleReplace: "Trocar fonte de dados",
  useOnSlide: "Usar no slide",
  discard: "Descartar",
  draftTitle: "Rascunho",
  draftEmpty: "Adicione fontes pelo catálogo.",
  draftCount: "{count} fonte(s)",
  configSourceTitle: "Filtros da fonte âncora",
  adjustFilters: "Ajustar filtros",
  hideFilters: "Ocultar filtros",
  catalogHint: "Busque no catálogo e configure os filtros ao selecionar a rota.",
  addSuggestion: "Adicionar",
  removeSource: "Remover",
  preview: "Prévia",
  previewTitle: "Prévia tabular",
  previewEmpty: "Prévia sem linhas com os filtros atuais.",
  hidePreview: "Ocultar prévia",
  catalogEmpty: "Nenhuma rota encontrada para essa busca.",
  catalogLoading: "Carregando catálogo…",
  loading: "Carregando…",
  sessionError: "Não foi possível iniciar o catálogo de fontes.",
  materializeError: "Não foi possível aplicar o modelo no slide.",
  previewError: "Não foi possível gerar a prévia.",
  primaryMark: "âncora",
} as const;
