/** Microcopy do assistente de dados (TV). */
export const DATA_BUILDER_CHAT_CONTENT = {
  title: "Assistente de dados",
  titleReplace: "Trocar fonte com o assistente",
  placeholderAi: "Descreva o dado, filtre, junte fontes…",
  placeholderSearch: "Buscar fonte por nome, path ou operação…",
  send: "Enviar",
  search: "Buscar",
  useOnSlide: "Usar no slide",
  discard: "Descartar",
  draftTitle: "Rascunho",
  draftEmpty: "Nenhuma fonte no rascunho ainda.",
  configTitle: "Configuração",
  configHint: "Filial e período aplicados às fontes que você adicionar.",
  configSourceTitle: "Filtros da fonte âncora",
  modeSearch: "Pesquisa",
  modeAi: "Assistente IA",
  modeSearchHint: "Busca no catálogo por nome (sem IA).",
  modeAiHint: "Descreva o dado em linguagem natural.",
  addSuggestion: "Adicionar",
  removeSource: "Remover",
  preview: "Prévia",
  previewTitle: "Prévia tabular",
  previewEmpty: "Prévia sem linhas com os filtros atuais.",
  catalogEmpty: "Nenhuma rota encontrada para essa busca.",
  catalogLoading: "Carregando catálogo…",
  loading: "Pensando…",
  sessionError: "Não foi possível iniciar o assistente de dados.",
  materializeError: "Não foi possível aplicar o modelo no slide.",
  previewError: "Não foi possível gerar a prévia.",
  primaryMark: "âncora",
  branchLabel: "Filial",
  periodDaysLabel: "Período (dias)",
} as const;
