/**
 * Fonte única de rótulos e enums de fallback para parâmetros de dados no MFE TV Dashboard.
 * Labels/hints/ENUM_OPTION_LABELS gerados de api-delpi/app/content/openapi_param_locale.json —
 * rode: python3 scripts/sync_tv_data_param_catalog.py --write
 * Preferir meta/OpenAPI da API quando disponível; estes mapas cobrem UI estável entre rotas.
 * enumLabels no JSON são bilíngues (en + pt-BR); o MFE consome pt-BR.
 */

export const PARAM_FIELD_LABELS: Record<string, string> = {
  "active": "Ativo",
  "actual_end_end": "Fim do fim real",
  "actual_end_start": "Início do fim real",
  "adjustment_percent": "Ajuste (%)",
  "area_id": "Área",
  "audit_date": "audit_date",
  "audit_status": "Status da auditoria",
  "branch": "Filial",
  "branch_code": "Código da filial",
  "branches": "Filiais",
  "catalog_version": "Versão do catálogo",
  "centroCusto": "Centro de custo",
  "centroTrabalho": "Centro de trabalho",
  "code": "Código",
  "code_exact": "Código exato",
  "codigo": "Código",
  "codigoOperador": "Código do operador",
  "codigo_peca": "Código da peça",
  "codigo_produto": "Código do produto",
  "competence": "Competência",
  "competencia_fim": "Competência final",
  "competencia_inicio": "Competência inicial",
  "cost_center": "Centro de custo",
  "customer": "Cliente",
  "customer_code": "Código do cliente",
  "customer_name": "Nome do cliente",
  "customer_reference": "Referência do cliente",
  "customer_segment": "Segmento",
  "customers": "Clientes",
  "data": "Data",
  "dataFim": "Data fim",
  "dataInicio": "Data início",
  "data_fim": "Data fim",
  "data_final": "Data final",
  "data_inicial": "Data inicial",
  "data_inicio": "Data início",
  "date": "Data",
  "dateRangePreset": "Período",
  "date_end": "Data fim",
  "date_from": "Data início",
  "date_start": "Data início",
  "date_to": "Data fim",
  "delay_range": "Faixa de atraso",
  "delayed_only": "Somente atrasadas",
  "delivery_end": "Fim da entrega",
  "delivery_start": "Início da entrega",
  "department": "Departamento",
  "department_id": "Departamento",
  "descricao": "Descrição",
  "descricao_peca": "Descrição da peça",
  "description": "Descrição",
  "details_limit": "Limite de detalhes",
  "dimension": "Dimensão",
  "direction": "Direção",
  "dry_run": "Simulação",
  "due_date": "due_date",
  "efficiency_bands": "Faixas de eficiência",
  "employee": "Colaborador",
  "end_date": "Data fim",
  "eventTypes": "Tipos de evento",
  "evidence_type": "Tipo de evidência",
  "expected_revision_number": "Revisão esperada",
  "failure_mode": "Modo de falha",
  "file_kind": "Tipo de arquivo",
  "filename": "Nome do arquivo",
  "filial": "Filial",
  "filial_id": "Filial",
  "finished_product_code": "Código do produto acabado",
  "format": "Formato",
  "from": "De",
  "granularity": "Granularidade",
  "group_by": "Agrupar por",
  "group_code": "Código do grupo",
  "has_revision": "Com revisão",
  "has_variant": "Com variante",
  "history_limit": "Limite do histórico",
  "id": "ID",
  "includeBlocked": "Incluir bloqueados",
  "includeWithoutSafetyStock": "Incluir sem estoque de segurança",
  "include_bom": "Incluir estrutura (BOM)",
  "include_completed": "Incluir concluídos",
  "include_others": "Incluir Demais",
  "include_qtd_pi": "Incluir quantidade PI",
  "include_test_products": "Incluir produtos de teste",
  "incluir_bloqueados": "Incluir bloqueados",
  "inspecao_status": "Status da inspeção",
  "inspection_id": "Inspeção",
  "inspector": "Inspetor",
  "invoice_number": "Número da nota",
  "issue_date_end": "Data de emissão (fim)",
  "issue_date_start": "Data de emissão (início)",
  "item_code": "Código do item",
  "legacy": "Modo legado",
  "limit": "Limite",
  "linked_sort_by": "Ordenar vínculos por",
  "linked_sort_dir": "Direção da ordenação dos vínculos",
  "listing_type": "Tipo de listagem",
  "location": "Localização",
  "loss_type": "Tipo de perda",
  "lot": "Lote",
  "max_depth": "Profundidade máxima",
  "max_size_bytes": "Tamanho máximo (bytes)",
  "metric": "Métrica",
  "min_plans": "Mínimo de planos",
  "min_size_bytes": "Tamanho mínimo (bytes)",
  "mine": "Somente meus",
  "modified_from": "Modificado a partir de",
  "modified_to": "Modificado até",
  "months": "Meses",
  "mother_only": "Somente OP mãe",
  "mother_op": "Somente OP mãe",
  "motivo": "Motivo",
  "mp": "Matéria-prima",
  "name": "Nome",
  "name_process": "Nome do processo",
  "nonconformity_scope": "Escopo de NC",
  "notify": "Notificar",
  "novos_negocios": "Novos negócios",
  "offset": "Deslocamento",
  "only_positive": "Somente saldo positivo",
  "only_with_delays": "Somente com atraso",
  "op": "Ordem de produção",
  "op_key": "Chave da OP",
  "open_only": "Somente em aberto",
  "operation_id": "Operação",
  "operator_code": "Código do operador",
  "ordem_producao": "Ordem de produção",
  "orderBy": "Ordenar por",
  "orderDir": "Direção da ordenação",
  "overdue_only": "Somente atrasados",
  "owner_user_id": "Responsável",
  "pa": "Produto acabado",
  "page": "Página",
  "pageSize": "Tamanho da página",
  "page_size": "Tamanho da página",
  "pending_only": "Somente pendentes",
  "periodDays": "Período (dias)",
  "periodEnd": "periodEnd",
  "periodStart": "periodStart",
  "period_end": "period_end",
  "period_start": "period_start",
  "plan_id": "Plano",
  "price_source": "Fonte de preço",
  "priority": "Prioridade",
  "problem_category": "Categoria do problema",
  "product": "Produto",
  "productGroup": "Grupo de produto",
  "product_code": "Código do produto",
  "product_group": "Grupo de produto",
  "product_prefix": "Prefixo do produto",
  "product_type": "Tipo de produto",
  "production_order": "Ordem de produção",
  "q": "Busca",
  "rank_by": "Agrupar ranking por",
  "raw_material_code": "Código da matéria-prima",
  "recurso": "Recurso",
  "reference_date": "Data de referência",
  "resource": "Recurso",
  "resource_id": "Recurso",
  "responsible": "Responsável",
  "responsible_user_id": "Usuário responsável",
  "result": "Resultado",
  "resultado": "Resultado",
  "revision": "Revisão",
  "root_cause_category": "Categoria da causa raiz",
  "savings_type": "Tipo de economia",
  "scope": "Escopo",
  "search": "Busca",
  "section": "Seção",
  "sector_name": "Setor",
  "senso_order": "Ordem do senso",
  "setor_id": "ID do setor",
  "severity": "Severidade",
  "shift": "Turno",
  "sort": "Ordenação",
  "sortBy": "Ordenar por",
  "sortDirection": "Direção",
  "sort_by": "Ordenar por",
  "sort_dir": "Direção da ordenação",
  "start_date": "Data início",
  "status": "Status",
  "status_ok_only": "Somente status OK",
  "stock_method": "Método de estoque",
  "stop_reason": "Motivo de parada",
  "store": "Loja",
  "store_code": "Código da loja",
  "strict_idd_period": "Período IDD estrito",
  "summary_mode": "Modo do summary",
  "summary_only": "Somente resumo",
  "supplier": "Fornecedor",
  "supplierStore": "Loja do fornecedor",
  "supplier_code": "Código do fornecedor",
  "supplier_part_number": "Part number do fornecedor",
  "supplier_store": "Loja do fornecedor",
  "template_key": "Chave do template",
  "title": "Título",
  "tm": "TM",
  "to": "Até",
  "top_limit": "Limite do ranking",
  "top_n": "Top N",
  "type": "Tipo",
  "unit": "Unidade",
  "view": "Visão",
  "warehouse": "Armazém",
  "work_center": "Centro de trabalho",
};

export const PARAM_FIELD_HINTS: Record<string, string> = {
  "active": "Filtra apenas registros ativos (sim) ou inativos (não).",
  "actual_end_end": "Fim do intervalo da data de fim real (AAAA-MM-DD).",
  "actual_end_start": "Início do intervalo da data de fim real (AAAA-MM-DD).",
  "adjustment_percent": "Percentual de ajuste aplicado no cálculo.",
  "area_id": "Identificador da área (ex.: auditoria 5S).",
  "audit_date": "Data (AAAA-MM-DD).",
  "audit_status": "Status da auditoria no fluxo (aberta, concluída etc.).",
  "branch": "Escopo: all (sem filtro de filial), 01 ou 02. Vazio equivale a all, quando permitido.",
  "branch_code": "Código da filial no Protheus (ex.: 01 ou 02).",
  "branches": "Lista de filiais (CSV). Vazio = todas as filiais permitidas.",
  "catalog_version": "Versão do catálogo a consultar.",
  "centroCusto": "Código do centro de custo no Protheus.",
  "centroTrabalho": "Filtro por centro de trabalho.",
  "code": "Código do registro a filtrar.",
  "code_exact": "Busca pelo código exato (sem correspondência parcial).",
  "codigo": "Código do registro a filtrar.",
  "codigoOperador": "Código do operador no Protheus.",
  "codigo_peca": "Código da peça no cadastro de ferramentas.",
  "codigo_produto": "Filtro por código do produto.",
  "competence": "Competência no formato AAAA-MM (mês de referência).",
  "competencia_fim": "Fim da janela de competência (AAAA-MM-DD ou AAAA-MM).",
  "competencia_inicio": "Início da janela de competência (AAAA-MM-DD ou AAAA-MM).",
  "cost_center": "Código do centro de custo no Protheus.",
  "customer": "Código ou identificador do cliente.",
  "customer_code": "Código do cliente (CLIENTE).",
  "customer_name": "Nome (ou parte do nome) do cliente.",
  "customer_reference": "Referência do cliente no pedido ou cadastro.",
  "customer_segment": "Filtra clientes: weg (WEG) ou new_business (novos negócios). Vazio = todos os segmentos.",
  "customers": "Lista CSV de clientes CODIGO/LOJA.",
  "data": "Data de referência (AAAA-MM-DD).",
  "dataFim": "Data final do período (AAAA-MM-DD).",
  "dataInicio": "Data inicial do período (AAAA-MM-DD).",
  "data_fim": "Fim do período (AAAA-MM-DD).",
  "data_final": "Data final do período consultado (AAAA-MM-DD).",
  "data_inicial": "Data inicial do período consultado (AAAA-MM-DD).",
  "data_inicio": "Início do período (AAAA-MM-DD).",
  "date": "Data de referência (AAAA-MM-DD).",
  "dateRangePreset": "Atalho de período (este mês, últimos 30 dias etc.).",
  "date_end": "Data final do período consultado (AAAA-MM-DD).",
  "date_from": "Data inicial do período consultado (AAAA-MM-DD).",
  "date_start": "Data inicial do período consultado (AAAA-MM-DD).",
  "date_to": "Data final do período consultado (AAAA-MM-DD).",
  "delay_range": "Código oficial de FAIXA_ATRASO.",
  "delayed_only": "Quando verdadeiro, retorna apenas OPs atrasadas.",
  "delivery_end": "Fim do intervalo da data de entrega prevista (AAAA-MM-DD).",
  "delivery_start": "Início do intervalo da data de entrega prevista (AAAA-MM-DD).",
  "department": "Identificador ou nome do departamento.",
  "department_id": "Identificador do departamento no painel IDD.",
  "descricao": "Descrição (ou parte dela) para filtrar.",
  "descricao_peca": "Descrição da peça no cadastro.",
  "description": "Descrição (ou parte dela) para filtrar.",
  "details_limit": "Máximo de linhas de detalhe retornadas.",
  "dimension": "Dimensão do ranking.",
  "direction": "Direção da ordenação: asc (crescente) ou desc (decrescente).",
  "dry_run": "Valida sem persistir quando verdadeiro.",
  "due_date": "Data (AAAA-MM-DD).",
  "efficiency_bands": "Faixas de eficiência em CSV (ex.: ok, low, verify).",
  "employee": "Código ou matrícula do colaborador.",
  "end_date": "Fim do período (AAAA-MM-DD).",
  "eventTypes": "Tipos de evento a incluir (CSV).",
  "evidence_type": "Tipo de evidência anexa ao registro.",
  "expected_revision_number": "Número de revisão para concorrência otimista.",
  "failure_mode": "Modo de falha associado à NC ou PAC.",
  "file_kind": "Tipo/categoria do arquivo.",
  "filename": "Filtro parcial pelo nome do arquivo.",
  "filial": "Código da filial no Protheus (ex.: 01 ou 02).",
  "filial_id": "Escopo: all (sem filtro de filial), 01 ou 02. Vazio equivale a all, quando permitido.",
  "finished_product_code": "Código do produto acabado (PA).",
  "format": "Formato de saída ou apresentação do dado.",
  "from": "Início do intervalo (data ou valor).",
  "granularity": "Como agrupar os pontos da série: day (dia), week (semana), month (mês) ou year (ano).",
  "group_by": "Como agregar o resultado (geral, filial, produto etc.).",
  "group_code": "Código do grupo de produto/material.",
  "has_revision": "Filtra arquivos que possuem sufixo de revisão.",
  "has_variant": "Filtra arquivos que possuem sufixo de variante.",
  "history_limit": "Máximo de pontos no histórico retornado.",
  "id": "Identificador único do registro.",
  "includeBlocked": "Inclui materiais bloqueados quando verdadeiro.",
  "includeWithoutSafetyStock": "Inclui matérias-primas sem estoque de segurança cadastrado.",
  "include_bom": "Quando verdadeiro, expande a estrutura do produto ao carregar o plano de inspeção de processo.",
  "include_completed": "Inclui itens já concluídos no resultado.",
  "include_others": "Quando verdadeiro, agrega clientes fora do Top N na linha Demais.",
  "include_qtd_pi": "Inclui quantidade de produto intermediário (PI) no resultado.",
  "include_test_products": "Inclui produtos de teste no resultado.",
  "incluir_bloqueados": "Inclui registros bloqueados na listagem.",
  "inspecao_status": "Filtra apontamentos pelo status de inspeção na auditoria de processo.",
  "inspection_id": "Identificador da inspeção.",
  "inspector": "Código ou nome do inspetor.",
  "invoice_number": "Número da nota fiscal.",
  "issue_date_end": "Fim do filtro pela data de emissão do documento (AAAA-MM-DD).",
  "issue_date_start": "Início do filtro pela data de emissão do documento (AAAA-MM-DD).",
  "item_code": "Código do item/material no Protheus.",
  "legacy": "Usa comportamento legado da API (campos/alias antigos).",
  "limit": "Máximo de registros retornados pela API (ranking ou listagem truncada).",
  "linked_sort_by": "Campo de ordenação dos itens vinculados.",
  "linked_sort_dir": "Direção da ordenação dos vínculos: asc ou desc.",
  "listing_type": "Filtro de tipo da listagem (ex.: Todos, LMP, Amostra).",
  "location": "Localização / endereço de estoque no Protheus.",
  "loss_type": "Tipo de perda a considerar: refugo, scrap ou ambos.",
  "lot": "Número do lote.",
  "max_depth": "Profundidade máxima da hierarquia/estrutura retornada.",
  "max_size_bytes": "Tamanho máximo do arquivo em bytes.",
  "metric": "Métrica do ranking: hours (horas) ou cost (custo), em ordem decrescente.",
  "min_plans": "Quantidade mínima de planos para incluir no resultado.",
  "min_size_bytes": "Tamanho mínimo do arquivo em bytes.",
  "mine": "Retorna apenas registros do usuário atual.",
  "modified_from": "Data/hora mínima de modificação (ISO).",
  "modified_to": "Data/hora máxima de modificação (ISO).",
  "months": "Quantidade de meses no intervalo analisado.",
  "mother_only": "Quando verdadeiro, retorna apenas OPs mãe.",
  "mother_op": "Quando verdadeiro, restringe às OPs mãe (sufixo 001 em H6_OP).",
  "motivo": "Filtro por código de motivo (CYO).",
  "mp": "Filtro por código de matéria-prima.",
  "name": "Nome (ou parte do nome) para filtrar.",
  "name_process": "Nome do processo Transforma Mais.",
  "nonconformity_scope": "Escopo das não conformidades consideradas.",
  "notify": "Envia notificações quando verdadeiro.",
  "novos_negocios": "Se verdadeiro, exclui o cliente-chave WEG.",
  "offset": "Quantos registros pular antes de retornar a página (paginação por deslocamento).",
  "only_positive": "Quando verdadeiro, inclui apenas linhas de armazém com quantidade maior que zero.",
  "only_with_delays": "Retorna apenas títulos/clientes com atraso.",
  "op": "Número da ordem de produção (OP).",
  "op_key": "Chave da ordem de produção (OP_CHAVE).",
  "open_only": "Quando verdadeiro, retorna apenas OPs em aberto.",
  "operation_id": "Identificador da operação.",
  "operator_code": "Código(s) do operador (CSV).",
  "ordem_producao": "Código da ordem de produção.",
  "orderBy": "Campo usado para ordenar o ranking (ex.: horas, custo).",
  "orderDir": "Direção da ordenação: asc (crescente) ou desc (decrescente).",
  "overdue_only": "Lista apenas itens atrasados.",
  "owner_user_id": "Usuário responsável pelo registro.",
  "pa": "Filtro por código de produto acabado.",
  "page": "Número da página na listagem paginada.",
  "pageSize": "Quantidade de linhas por página.",
  "page_size": "Quantidade de linhas por página.",
  "pending_only": "Retorna apenas itens pendentes quando verdadeiro.",
  "periodDays": "Quantos dias para trás entram no cálculo (ex.: 30 = último mês até hoje).",
  "periodEnd": "Data (AAAA-MM-DD).",
  "periodStart": "Data (AAAA-MM-DD).",
  "period_end": "Data (AAAA-MM-DD).",
  "period_start": "Data (AAAA-MM-DD).",
  "plan_id": "Identificador do plano de ação.",
  "price_source": "Origem do preço usado no cálculo.",
  "priority": "Prioridade: high, medium ou low.",
  "problem_category": "Categoria do problema reportado.",
  "product": "Código ou identificador do produto.",
  "productGroup": "Filtro por grupo de produto (B1_GRUPO).",
  "product_code": "Código do produto no Protheus (ex.: 90xxxxxx).",
  "product_group": "Grupo de produto no Protheus.",
  "product_prefix": "Prefixo do código de produto para filtrar famílias.",
  "product_type": "Filtra por tipo: PA (acabado) ou PI (intermediário).",
  "production_order": "Ordem(ns) de produção (CSV).",
  "q": "Texto livre de busca (código, nome ou descrição).",
  "rank_by": "Dimensão do ranking: stop_reason (motivo), resource, cost_center, operator, product ou operation.",
  "raw_material_code": "Código da matéria-prima.",
  "recurso": "Código do recurso de produção.",
  "reference_date": "Data de referência usada no cálculo (AAAA-MM-DD).",
  "resource": "Código do recurso de produção (máquina/recurso do centro de trabalho).",
  "resource_id": "Identificador do recurso de agendamento.",
  "responsible": "Filtro por nome do responsável.",
  "responsible_user_id": "Filtro por id do usuário responsável.",
  "result": "Filtro de resultado da inspeção. Histórico de entrada: APROVADA/REJEITADA; inspeção de processo: A/R/T.",
  "resultado": "Resultado da inspeção: A (aprovado), R (reprovado) ou T (pendente).",
  "revision": "Número ou código da revisão.",
  "root_cause_category": "Categoria da causa raiz.",
  "savings_type": "Tipo de economia (Kaizen).",
  "scope": "Escopo da consulta (ex.: occurrence, future, all).",
  "search": "Texto livre de busca.",
  "section": "Seção ou bloco do formulário/checklist.",
  "sector_name": "Nome do setor.",
  "senso_order": "Ordem do senso na auditoria 5S.",
  "setor_id": "Identificador do setor no Transformômetro.",
  "severity": "Nível de severidade.",
  "shift": "Turno de produção.",
  "sort": "Critério de ordenação da listagem.",
  "sortBy": "Campo de ordenação permitido.",
  "sortDirection": "Direção da ordenação: asc ou desc.",
  "sort_by": "Campo usado para ordenar a listagem.",
  "sort_dir": "Direção da ordenação: asc (crescente) ou desc (decrescente).",
  "start_date": "Início do período (AAAA-MM-DD).",
  "status": "Status do registro no fluxo.",
  "status_ok_only": "Retorna apenas registros com status OK.",
  "stock_method": "Método de valorização/consulta de estoque.",
  "stop_reason": "Código do motivo de parada na view de horas improdutivas (ex.: RT, OT, MT). Vazio = todos os motivos.",
  "store": "Código da loja do cliente.",
  "store_code": "Loja do cliente (LOJA).",
  "strict_idd_period": "Exige período estrito no cálculo do IDD.",
  "summary_mode": "kpi carrega PI só em OVs FINALIZADA; full carrega PI em todas as candidatas (gráficos/itens).",
  "summary_only": "Quando ativo, retorna só o resumo sem a lista detalhada.",
  "supplier": "Código ou nome do fornecedor.",
  "supplierStore": "Loja do fornecedor.",
  "supplier_code": "Código do fornecedor no Protheus.",
  "supplier_part_number": "Código do produto no fornecedor (SA5010.A5_CODPRF).",
  "supplier_store": "Loja do fornecedor.",
  "template_key": "Chave do modelo/template usado.",
  "title": "Título (ou parte dele) para filtrar.",
  "tm": "Código TM (Transforma Mais).",
  "to": "Fim do intervalo (data ou valor).",
  "top_limit": "Quantidade máxima de itens no ranking.",
  "top_n": "Quantidade de itens no Top N.",
  "type": "Tipo do registro a filtrar.",
  "unit": "Filtro por unidade de medida (B1_UM).",
  "view": "Modo de visualização (ex.: consolidado, filial, departamento; ou por material/produto conforme a rota).",
  "warehouse": "Código do armazém/estoque.",
  "work_center": "Código do centro de trabalho (CT) no Protheus. Vazio = todos os centros.",
};

/** Rótulos PT-BR das opções de enum — gerados de openapi_param_locale.json enumLabels. */
export const ENUM_OPTION_LABELS: Record<string, Record<string, string>> = {
  audit_status: { "closed": "Encerrada", "closed_without_nc_treatment": "Encerrada sem tratamento de NC", "draft": "Rascunho", "evaluation_complete": "Avaliação concluída", "nc_in_progress": "NC em andamento" },
  branch: { "01": "Filial 01", "02": "Filial 02", "ES": "ES", "SC": "SC", "all": "Todas" },
  branch_code: { "01": "Filial 01", "02": "Filial 02" },
  customer_segment: { "new_business": "Novos negócios", "weg": "WEG" },
  department_id: { "commercial": "Comercial", "engineering": "Engenharia", "financial": "Financeiro", "hr": "RH", "production": "Produção", "quality": "Qualidade", "supplies": "Suprimentos" },
  dimension: { "centro_trabalho": "Centro de trabalho", "colaborador": "Colaborador", "materia_prima": "Matéria-prima", "motivo": "Motivo", "produto_acabado": "Produto acabado" },
  direction: { "asc": "Crescente", "desc": "Decrescente" },
  evidence_type: { "email": "E-mail", "image": "Imagem", "manual_text": "Texto manual", "message": "Mensagem", "other": "Outro", "pdf": "PDF", "spreadsheet": "Planilha", "system_reference": "Referência do sistema" },
  filial: { "01": "Filial 01", "02": "Filial 02" },
  filial_id: { "01": "Filial 01", "02": "Filial 02", "all": "Todas" },
  granularity: { "auto": "Automático", "day": "Dia", "month": "Mês", "week": "Semana", "year": "Ano" },
  group_by: { "branch": "Filial", "branch_summary": "Resumo por filial", "day": "Dia", "day_work_center": "Dia × centro de trabalho", "general": "Geral", "product": "Produto", "product_group": "Grupo de produto", "unit": "Unidade" },
  inspecao_status: { "all": "Todos", "inspecionou": "Inspecionou", "nao_inspecionou": "Não inspecionou", "sem_cadastro": "Não possui inspeção cadastrada" },
  linked_sort_dir: { "asc": "Crescente", "desc": "Decrescente" },
  listing_type: { "Amostra": "Amostra", "LMP": "LMP", "Outro": "Outro", "Todos": "Todos" },
  loss_type: { "both": "Ambos", "refugo": "Refugo", "scrap": "Scrap" },
  metric: { "balance": "Saldo", "cost": "Custo", "delay_days": "Dias de atraso", "hours": "Horas", "order_qty": "Qtd. ordem", "reported_qty": "Qtd. apontada" },
  nonconformity_scope: { "external": "Externa", "internal": "Interna" },
  orderBy: { "custo": "Custo", "data": "Data", "horas": "Horas" },
  orderDir: { "asc": "Crescente", "desc": "Decrescente" },
  priority: { "high": "Alta", "low": "Baixa", "medium": "Média" },
  product_type: { "PA": "Produto acabado (PA)", "PI": "Produto intermediário (PI)" },
  rank_by: { "cost_center": "Centro de custo", "op": "OP", "operation": "Operação", "operator": "Operador", "product": "Produto", "resource": "Recurso", "stop_reason": "Motivo de parada", "warehouse": "Armazém" },
  result: { "A": "Aprovado (A)", "APROVADA": "Aprovada", "R": "Reprovado (R)", "REJEITADA": "Rejeitada", "T": "Pendente (T)" },
  resultado: { "A": "Aprovado (A)", "R": "Reprovado (R)", "T": "Pendente (T)" },
  savings_type: { "financeiro": "Financeiro", "material": "Material", "misto": "Misto", "qualitativo": "Qualitativo", "tempo": "Tempo" },
  section: { "attachments": "Anexos", "containment": "Contenção", "corrective": "Corretiva", "documentation": "Documentação", "effectiveness": "Eficácia", "general": "Geral", "nc_description": "Descrição da NC", "preventive": "Preventiva", "root_cause": "Causa raiz" },
  severity: { "critical": "Crítica", "high": "Alta", "low": "Baixa", "medium": "Média" },
  shift: { "ADMINISTRATIVO": "Administrativo", "TURNO_1": "Turno 1", "TURNO_2": "Turno 2", "TURNO_3": "Turno 3" },
  sort: { "cost_asc": "Custo ↑", "cost_desc": "Custo ↓", "created_desc": "Criação ↓", "date_asc": "Data ↑", "date_desc": "Data ↓", "delay_asc": "Atraso ↑", "delay_desc": "Atraso ↓", "delivery_asc": "Entrega ↑", "delivery_desc": "Entrega ↓", "due_date_asc": "Vencimento ↑", "due_date_desc": "Vencimento ↓", "hours_asc": "Horas ↑", "hours_desc": "Horas ↓", "issue_asc": "Emissão ↑", "issue_desc": "Emissão ↓", "op_asc": "OP ↑", "op_desc": "OP ↓", "priority_desc": "Prioridade ↓", "product_code_asc": "Código ↑", "product_code_desc": "Código ↓", "qty_asc": "Quantidade ↑", "qty_desc": "Quantidade ↓", "quantity_asc": "Quantidade ↑", "quantity_desc": "Quantidade ↓", "stock_value_asc": "Valor ↑", "stock_value_desc": "Valor ↓" },
  sortDirection: { "asc": "Crescente", "desc": "Decrescente" },
  sort_by: { "customer_name": "Nome do cliente", "defect_description": "Descrição do defeito", "executed_by": "Executado por", "last_revision_date": "Data da última revisão", "launch_date": "Data de lançamento", "lmp_number": "Número LMP", "occurrence_date": "Data da ocorrência", "problem_tags": "Tags do problema", "products": "Produtos", "registered_at": "Registrado em", "released_by": "Liberado por", "sale_number": "Número da venda", "status": "Status" },
  sort_dir: { "asc": "Crescente", "desc": "Decrescente" },
  status: { "1": "Registrada (1)", "2": "Em análise (2)", "3": "Procede (3)", "4": "Não procede (4)", "5": "Cancelada (5)", "Andamento": "Andamento", "Atrasado": "Atrasado", "Pontual": "Pontual", "Retornada": "Retornada", "Todos": "Todos", "above_safety_stock": "Acima do estoque de segurança", "action_plan_defined": "Plano de ação definido", "all": "Todos", "aprovado": "Aprovado", "archived": "Arquivado", "at_safety_stock": "No estoque de segurança", "below_safety_stock": "Abaixo do estoque de segurança", "cancelado": "Cancelado", "cancelled": "Cancelado", "closed": "Encerrado", "closed_without_nc_treatment": "Encerrada sem tratamento de NC", "completed": "Concluído", "containment": "Contenção", "descontinuado": "Descontinuado", "done": "Concluído", "draft": "Rascunho", "evaluation_complete": "Avaliação concluída", "implantado": "Implantado", "in_progress": "Em andamento", "late": "Atrasado", "nc_in_progress": "NC em andamento", "on_time": "No prazo", "open": "Aberto", "outlier": "Fora da faixa", "published": "Publicado", "recebido": "Recebido", "root_cause_analysis": "Análise de causa raiz", "triage": "Triagem", "valid": "Válido", "waiting_validation": "Aguardando validação", "without_safety_stock": "Sem estoque de segurança", "won": "Ganha" },
  stock_method: { "auto": "Automático", "estimated": "Estimado", "hybrid": "Híbrido", "official_closure": "Fechamento oficial" },
  summary_mode: { "full": "Completo", "kpi": "Somente KPI" },
  type: { "all": "Todos", "customer": "Cliente", "external": "Externo", "internal": "Interno", "supplier": "Fornecedor" },
  view: { "by_finished_product": "Por produto acabado", "by_material": "Por material", "consolidated": "Consolidado", "department": "Departamento", "filial": "Filial", "full": "Completo", "summary": "Resumo" },
};

/** Enums de UI quando o OpenAPI não declara `enum` (valores estáveis entre rotas). */
export const UI_FALLBACK_ENUMS: Record<string, Array<string | number>> = {
  sort_dir: ["asc", "desc"],
  direction: ["asc", "desc"],
  orderDir: ["asc", "desc"],
  linked_sort_dir: ["asc", "desc"],
  product_type: ["PA", "PI"],
  loss_type: ["refugo", "scrap", "both"],
  stock_method: ["auto", "hybrid", "estimated", "official_closure"],
};

/** Rótulo PT canônico; ignora rótulo EN residual do OpenAPI/humanize. */
export function resolveParamFieldLabel(key: string, schemaLabel?: string): string {
  return PARAM_FIELD_LABELS[key] ?? schemaLabel?.trim() ?? key;
}

export function resolveParamFieldHint(key: string, schemaDescription?: string): string | undefined {
  const fromCatalog = PARAM_FIELD_HINTS[key]?.trim();
  if (fromCatalog) return fromCatalog;
  const fromSchema = schemaDescription?.trim();
  return fromSchema || undefined;
}
