export const TV_DASHBOARD_HELP_TOOLTIPS = {
  ribbon: {
    slides:
      "Navegue e gerencie as telas da apresentação. Use as setas para alternar sem sair do editor.",
    newSlide: "Adiciona uma nova tela personalizada vazia ao final da playlist para montar gráficos e indicadores.",
    prevSlide: "Volta para a tela anterior na ordem de exibição.",
    nextSlide: "Avança para a próxima tela na ordem de exibição.",
    currentSlide: "Ações sobre a tela selecionada no filmstrip ou no palco.",
    pause: "Desativa a tela na exibição da TV sem removê-la da playlist.",
    activate: "Reativa uma tela pausada para voltar a aparecer na rotação.",
    duplicate: "Cria uma cópia idêntica da tela atual, logo após ela na lista.",
    delete: "Remove a tela da playlist. Esta ação não pode ser desfeita.",
    insert:
      "Adiciona elementos ao slide personalizado: textos, mídias e formas. Clique no palco para selecionar e editar.",
    background:
      "Define a cor ou imagem de fundo do slide personalizado. A imagem cobre toda a área do palco.",
    font: "Formata o texto selecionado: família, tamanho, estilo, realce e cor.",
    paragraph:
      "Alinhamento horizontal e vertical, justificação, entrelinhas e espaçamento entre caracteres.",
    shape: "Ajusta preenchimento, contorno e espessura da forma selecionada.",
    strokeWidth: "Espessura do contorno da forma, em pixels.",
    organize:
      "Controla camadas e mídia do elemento selecionado: ordem (frente/fundo), troca de arquivo ou remoção.",
    undo: "Desfazer a última alteração na programação ou no slide (Ctrl+Z).",
    redo: "Refazer alteração desfeita na programação ou no slide (Ctrl+Y ou Ctrl+Shift+Z).",
    zoomOut: "Diminuir zoom do palco no editor.",
    zoomIn: "Aumentar zoom do palco no editor.",
    zoomReset: "Restaurar zoom do palco para 100%.",
    zoomFit: "Ajustar o palco para caber na área visível do editor.",
    bold: "Aplica ou remove negrito no trecho selecionado ou no bloco inteiro.",
    italic: "Aplica ou remove itálico no trecho selecionado ou no bloco inteiro.",
    underline: "Sublinha o trecho selecionado ou o bloco inteiro.",
    strikethrough: "Tacha o trecho selecionado ou o bloco inteiro.",
    clearFormatting: "Remove formatação de fonte e volta ao estilo padrão do bloco.",
    textColor: "Cor do texto do bloco ou do trecho selecionado.",
    textHighlight: "Cor de realce (marca-texto) do trecho selecionado.",
    alignLeft: "Alinha o parágrafo à esquerda.",
    alignCenter: "Centraliza o parágrafo horizontalmente.",
    alignRight: "Alinha o parágrafo à direita.",
    alignJustify: "Justifica o parágrafo nas duas margens.",
    bulletList: "Lista com marcadores.",
    orderedList: "Lista numerada.",
    alignTop: "Alinha o texto ao topo da caixa.",
    alignMiddle: "Centraliza o texto verticalmente na caixa.",
    alignBottom: "Alinha o texto à base da caixa.",
    fontFamily: "Família tipográfica do bloco de texto.",
    fontSizeDown: "Diminuir tamanho da fonte.",
    fontSizeUp: "Aumentar tamanho da fonte.",
    fontSize: "Tamanho da fonte em pixels.",
    mediaLibrary: "Escolher arquivo já enviado à playlist.",
    duplicateBlock: "Duplicar elemento selecionado (Ctrl+D).",
    cropImage: "Abrir painel de recorte da imagem no inspetor lateral.",
    opacity: "Transparência do elemento (10% a 100%).",
    objectFit: "Como a mídia preenche o quadro: cortar ou conter.",
    borderWidth: "Espessura da borda em pixels.",
    borderColor: "Cor da borda do elemento.",
    borderRadius: "Arredondamento dos cantos em pixels.",
    boxShadow: "Sombra projetada do elemento.",
    alignSelection: "Alinhar ou distribuir os elementos selecionados no palco.",
    alignSelectionLeft: "Alinhar borda esquerda dos elementos selecionados.",
    alignSelectionCenterH: "Centralizar horizontalmente a seleção.",
    alignSelectionRight: "Alinhar borda direita dos elementos selecionados.",
    alignSelectionTop: "Alinhar topo dos elementos selecionados.",
    alignSelectionCenterV: "Centralizar verticalmente a seleção.",
    alignSelectionBottom: "Alinhar base dos elementos selecionados.",
    distributeH: "Distribuir espaçamento horizontal entre 3 ou mais elementos.",
    distributeV: "Distribuir espaçamento vertical entre 3 ou mais elementos.",
    groupSelection: "Agrupar elementos para mover e redimensionar juntos.",
    ungroupSelection: "Separar elementos de um grupo.",
    insertIndicator: "Inserir bloco de indicador ou gráfico com dados da api-delpi.",
    insertIcon: "Ícones vetoriais prontos para o slide.",
    insertTextGroup: "Caixas de título e texto livre no slide.",
    insertMediaGroup: "Imagens e vídeos da biblioteca da playlist ou upload.",
    insertIllustrationsGroup: "Biblioteca visual de formas editáveis e ícones.",
    insertDataGroup: "Blocos de indicadores, gráficos e tabelas com dados da api-delpi.",
    insertHeading: "Caixa de título em destaque para comunicados e chamadas principais.",
    insertText: "Bloco de texto livre para mensagens e legendas.",
    insertImage: "Imagem posicionável no slide; envie o arquivo após inserir.",
    insertVideo: "Vídeo em loop no slide; envie o arquivo após inserir.",
    insertShape: "Formas geométricas com preenchimento e contorno configuráveis.",
  },
  tabs: {
    element:
      "Propriedades do elemento selecionado no slide personalizado: conteúdo, link, posição, rotação e fundo.",
    slide:
      "Configurações da tela atual: título exibido no filmstrip, tempo na rotação e filtros operacionais (quando aplicável).",
    playlist:
      "Parâmetros globais da apresentação: resolução da TV, transição entre telas, duração padrão e link público.",
  },
  ribbonTabs: {
    home: "Gerencie slides da apresentação: adicionar telas, navegar e pausar ou duplicar a tela atual.",
    insert: "Insira elementos no slide personalizado: títulos, textos, imagens, vídeos e formas.",
    format: "Formate o slide e o elemento selecionado: fundo, fonte, forma, camadas e mídia.",
    view: "Controles de exibição do palco: zoom, réguas, grade, guias centrais e encaixe ao arrastar.",
  },
  view: {
    zoom: "Amplia ou reduz o palco no editor (50% a 200%). Não altera a exibição na TV.",
    grid: "Mostra grade de 5% no palco para alinhar elementos visualmente.",
    guides: "Exibe guias horizontais e verticais no centro do palco.",
    rulers: "Mostra réguas horizontais e verticais ao redor do palco, como no PowerPoint.",
    snap: "Encaixa posição e tamanho na grade e nas guias ao soltar o elemento.",
    showGroup: "Elementos visuais de apoio no palco do editor (não aparecem na TV).",
  },
  header: {
    back: "Voltar à lista de programações.",
    preview: "Abrir pré-visualização em tela cheia.",
    share: "Abrir página de compartilhamento e link público.",
    copyLink: "Copiar link público da apresentação.",
    qr: "Gerar QR code do link público.",
    regenerateToken: "Gerar novo link público (invalida o anterior).",
    toggleLink: "Ativar ou desativar o link público da programação.",
    delete: "Excluir esta programação permanentemente.",
  },
  fields: {
    slideTitle: "Nome curto para identificar a tela no filmstrip e nos relatórios internos.",
    slideDuration:
      "Tempo em segundos que a tela permanece visível antes de passar para a próxima. Mínimo 5 s.",
    slideUrl: "Endereço HTTPS exibido em tela cheia nesta slide (página externa ou dashboard embutido).",
    slideBranch: "Filtra os dados operacionais desta tela para uma filial. Vazio = consolidado.",
    slidePeriod: "Janela de dias usada nas consultas de KPIs e indicadores desta tela.",
    viewport:
      "Resolução de referência para o layout. Escolha o perfil mais próximo do monitor da TV.",
    transition: "Efeito visual ao trocar de tela na exibição (fade, deslizar ou corte direto).",
    slideTransition:
      "Substitui a transição padrão da programação só nesta tela. Deixe em «Herdar» para usar o padrão.",
    defaultDuration:
      "Duração aplicada a novas telas e às que não tiverem tempo individual definido.",
    refreshInterval:
      "Intervalo para atualizar dados ao vivo (KPIs, estoque etc.) sem recarregar a página inteira.",
    publicUrl:
      "Link para abrir a apresentação em tela cheia no navegador da TV ou em um player dedicado.",
  },
  contextMenu: {
    menu: "Menu de contexto do elemento no palco.",
    quickFormat: "Atalhos rápidos de preenchimento e contorno.",
    fill: "Cor de preenchimento",
    outline: "Cor do contorno",
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    editText: "Editar texto",
    bringToFront: "Trazer para frente",
    sendToBack: "Enviar para trás",
    bringForward: "Avançar",
    sendBackward: "Recuar",
    delete: "Excluir",
    format: "Formatar…",
  },
  element: {
    panel:
      "Clique em um elemento no palco ou arraste para reposicionar. Use as alças para redimensionar.",
    content: "Texto exibido no elemento. Títulos usam fonte maior na TV.",
    link: "URL aberta ao toque/clique na TV, quando o player suportar interação.",
    shapeText: "Texto opcional renderizado dentro da forma.",
    strokeWidth: "Espessura da borda da forma, em pixels.",
    position:
      "Posição e tamanho em percentual do palco (0–100). Útil para alinhamento preciso entre elementos.",
    rotation: "Gira o elemento em graus (−180 a 180) em torno do centro do quadro.",
    layerUp: "Move o elemento uma camada acima, sobrepondo os demais.",
    layerDown: "Envia o elemento uma camada abaixo, atrás dos demais.",
    remove: "Remove o elemento selecionado do slide.",
    entranceAnimation:
      "Efeito de entrada na TV quando o slide aparece (fade ou deslizar). Não anima no palco do editor.",
    entranceDelay: "Atraso em milissegundos antes do elemento entrar na tela.",
    entranceDuration: "Duração da animação de entrada em milissegundos.",
    uploadMedia: "Substitui a imagem ou vídeo do elemento pelo arquivo enviado.",
    backgroundColor: "Cor sólida de fundo do slide personalizado.",
    uploadBackground: "Imagem de fundo em tela cheia. Substitui a cor quando definida.",
  },
} as const;
