export const RICH_TEXT_LABELS = {
  toolbar: "Formatação de texto",
  fontSection: "Fonte",
  paragraphSection: "Parágrafo",
  fontFamily: "Fonte",
  fontFamilyHint: "Família tipográfica do trecho selecionado.",
  fontSize: "Tamanho",
  fontSizeHint: "Tamanho da fonte em pixels — digite ou escolha na lista.",
  fontSizeDecrease: "Diminuir tamanho da fonte",
  fontSizeIncrease: "Aumentar tamanho da fonte",
  bold: "Negrito",
  italic: "Itálico",
  underline: "Sublinhado",
  strikethrough: "Tachado",
  textColor: "Cor do texto",
  textColorHint: "Cor do texto selecionado.",
  highlightColor: "Realce",
  highlightColorHint: "Cor de realce (fundo) do texto selecionado.",
  clearFormatting: "Limpar formatação",
  alignLeft: "Alinhar à esquerda",
  alignCenter: "Centralizar",
  alignRight: "Alinhar à direita",
  alignJustify: "Justificar",
  bulletList: "Lista com marcadores",
  orderedList: "Lista numerada",
  indent: "Aumentar recuo",
  outdent: "Diminuir recuo",
  link: "Inserir link",
  table: "Inserir tabela",
  tableCatalog: "Catálogo de tabelas",
  horizontalRule: "Linha horizontal",
  horizontalRuleHint:
    "Insere uma linha divisória — a mesma que <hr> no HTML e --- (ou ***) no Markdown. No visual, Backspace/Delete ao lado da linha remove.",
  heading: "Título (H2)",
  undo: "Desfazer",
  redo: "Refazer",
  insertSection: "Inserir",
  linkDialogTitle: "Inserir link",
  linkDialogEditTitle: "Editar link",
  linkUrlLabel: "URL do link",
  linkUrlPlaceholder: "https://…",
  linkApply: "Aplicar",
  linkCancel: "Cancelar",
  linkOpen: "Abrir link em nova aba",
  linkEditAction: "Editar link",
  linkRemove: "Remover link",
  imageResize: "Redimensionar imagem",
  sourceHtml: "Editar HTML",
  sourceMarkdown: "Editar Markdown",
  sourceVisual: "Voltar ao visual",
  sourceEditor: "Fonte HTML do texto",
  sourceMarkdownEditor: "Fonte Markdown do texto",
  sourceHint:
    "Digite < para tags (inclui hr) e edite style=\"…\" para CSS. Só o allowlist é preservado ao salvar (sem script/CSS global).",
  sourceMarkdownHint:
    "Edite em Markdown (GFM). Use --- ou *** para linha horizontal. Ao voltar ao visual, o conteúdo vira HTML sanitizado. Tabelas/estilos ricos podem simplificar.",
  sourceSuggestList: "Sugestões de HTML e CSS",
  sourceSuggestTag: "tag HTML",
  sourceSuggestCss: "propriedade CSS",
  sourceSuggestCssValue: "valor CSS",
} as const;
