export const RICH_TEXT_LABELS = {
  toolbar: "Formatação de texto",
  fontSection: "Fonte",
  paragraphSection: "Parágrafo",
  fontFamily: "Fonte",
  fontSize: "Tamanho",
  bold: "Negrito",
  italic: "Itálico",
  underline: "Sublinhado",
  strikethrough: "Tachado",
  textColor: "Cor do texto",
  highlightColor: "Realce",
  clearFormatting: "Limpar formatação",
  alignLeft: "Alinhar à esquerda",
  alignCenter: "Centralizar",
  alignRight: "Alinhar à direita",
  alignJustify: "Justificar",
  bulletList: "Lista com marcadores",
  orderedList: "Lista numerada",
  indent: "Aumentar recuo",
  outdent: "Diminuir recuo",
  link: "Inserir link",
  heading: "Título (H2)",
  undo: "Desfazer",
  redo: "Refazer",
  linkPrompt: "URL do link",
} as const;
