export const RICH_TEXT_LABELS = {
  toolbar: "Formatação de texto",
  fontSection: "Fonte",
  paragraphSection: "Parágrafo",
  fontFamily: "Fonte",
  fontSize: "Tamanho",
  fontSizeDecrease: "Diminuir tamanho da fonte",
  fontSizeIncrease: "Aumentar tamanho da fonte",
  bold: "Negrito",
  italic: "Itálico",
  underline: "Sublinhado",
  strikethrough: "Tachado",
  textColor: "Cor do texto",
  highlightColor: "Realce",
  clearFormatting: "Limpar formatação",
  alignLeft: "Alinhar à esquerda",
  alignCenter: "Centralizar",
  alignRight: "Alinhar à direita",
  alignJustify: "Justificar",
  bulletList: "Lista com marcadores",
  orderedList: "Lista numerada",
  indent: "Aumentar recuo",
  outdent: "Diminuir recuo",
  link: "Inserir link",
  table: "Inserir tabela",
  tableCatalog: "Catálogo de tabelas",
  heading: "Título (H2)",
  undo: "Desfazer",
  redo: "Refazer",
  insertSection: "Inserir",
  linkDialogTitle: "Inserir link",
  linkDialogEditTitle: "Editar link",
  linkUrlLabel: "URL do link",
  linkUrlPlaceholder: "https://…",
  linkApply: "Aplicar",
  linkCancel: "Cancelar",
  linkOpen: "Abrir link em nova aba",
  linkEditAction: "Editar link",
  linkRemove: "Remover link",
} as const;
