"""Domínio transversal — convenções TOTVS/Protheus da Delpi."""

from app.domain.totvs.protheus_product_types import (
    PRODUCT_TYPE_FINISHED_GOOD,
    PRODUCT_TYPE_INTERMEDIATE,
    PRODUCT_TYPE_LABELS_PT,
    PRODUCT_TYPE_RAW_MATERIAL,
)
from app.domain.totvs.protheus_warehouses import (
    AVAILABLE_BALANCE_WAREHOUSES,
    COST_UNIT_WAREHOUSE,
    WAREHOUSE_ALMOXARIFADO,
    WAREHOUSE_FABRICA,
    WAREHOUSE_LABELS_PT,
    WORK_IN_PROCESS_WAREHOUSES,
)

__all__ = [
    "AVAILABLE_BALANCE_WAREHOUSES",
    "COST_UNIT_WAREHOUSE",
    "PRODUCT_TYPE_FINISHED_GOOD",
    "PRODUCT_TYPE_INTERMEDIATE",
    "PRODUCT_TYPE_LABELS_PT",
    "PRODUCT_TYPE_RAW_MATERIAL",
    "WAREHOUSE_ALMOXARIFADO",
    "WAREHOUSE_FABRICA",
    "WAREHOUSE_LABELS_PT",
    "WORK_IN_PROCESS_WAREHOUSES",
]
