/**
 * Rótulos e aliases de busca em português para ícones Lucide (kebab-case).
 * Sem entrada → cai no nome kebab; busca também casa aliases.
 */

export const LUCIDE_ICON_PT_LABELS: Readonly<Record<string, string>> = {
  activity: "Atividade",
  "alert-triangle": "Alerta",
  "bar-chart-3": "Gráfico de barras",
  "check-circle-2": "Concluído",
  "dollar-sign": "Financeiro",
  factory: "Fábrica",
  gauge: "Indicador",
  package: "Produto",
  percent: "Percentual",
  shield: "Segurança",
  star: "Estrela",
  target: "Meta",
  "trending-down": "Queda",
  "trending-up": "Tendência",
  users: "Equipe",
  eye: "Olho",
  heart: "Coração",
  smile: "Sorriso",
  "thumbs-up": "Positivo",
  "thumbs-down": "Negativo",
  handshake: "Acordo",
  sparkles: "Destaque",
  lightbulb: "Ideia",
  award: "Prêmio",
  flag: "Bandeira",
  user: "Usuário",
  "user-round": "Pessoa",
  mail: "E-mail",
  phone: "Telefone",
  megaphone: "Megafone",
  "map-pin": "Local",
  globe: "Mundo",
  "building-2": "Empresa",
  home: "Início",
  "clipboard-list": "Lista",
  "clipboard-check": "Checklist",
  "shield-check": "Protegido",
  calendar: "Calendário",
  clock: "Relógio",
  "line-chart": "Gráfico de linha",
  "pie-chart": "Gráfico de pizza",
  truck: "Entrega",
  warehouse: "Armazém",
  settings: "Configurações",
  search: "Busca",
  image: "Imagem",
  camera: "Câmera",
  sun: "Sol",
  moon: "Lua",
  zap: "Energia",
  leaf: "Folha",
  coffee: "Café",
  bookmark: "Marcador",
};

/** Termos PT extras que apontam para o kebab do ícone. */
export const LUCIDE_ICON_PT_ALIASES: Readonly<Record<string, readonly string[]>> = {
  gauge: ["indicador", "medidor", "velocimetro", "velocímetro", "kpi"],
  "trending-up": ["alta", "crescimento", "subida", "tendencia", "tendência"],
  "trending-down": ["queda", "baixa", "declinio", "declínio"],
  factory: ["fabrica", "fábrica", "industria", "indústria", "planta"],
  users: ["equipe", "time", "pessoas", "colaboradores"],
  star: ["estrela", "favorito"],
  target: ["meta", "alvo", "objetivo"],
  percent: ["percentual", "porcentagem", "%"],
  "dollar-sign": ["financeiro", "dinheiro", "moeda", "receita"],
  package: ["produto", "pacote", "embalagem"],
  "bar-chart-3": ["grafico", "gráfico", "barras", "chart"],
  "line-chart": ["linha", "serie", "série"],
  "alert-triangle": ["alerta", "aviso", "cuidado"],
  "check-circle-2": ["ok", "concluido", "concluído", "sucesso"],
  shield: ["seguranca", "segurança", "protecao", "proteção"],
  activity: ["atividade", "monitor", "sinal"],
  truck: ["caminhao", "caminhão", "logistica", "logística", "frete"],
  warehouse: ["armazem", "armazém", "estoque"],
  settings: ["configuracao", "configuração", "ajustes"],
  search: ["busca", "pesquisar", "procurar"],
  calendar: ["agenda", "calendario", "calendário", "data"],
  clock: ["hora", "tempo", "relogio", "relógio"],
  mail: ["email", "e-mail", "correio"],
  phone: ["telefone", "ligacao", "ligação"],
  heart: ["coracao", "coração", "amor"],
  eye: ["olho", "visualizar", "ver"],
  home: ["inicio", "início", "casa"],
  "building-2": ["empresa", "predio", "prédio", "escritorio", "escritório"],
  "map-pin": ["local", "mapa", "endereco", "endereço"],
  zap: ["energia", "raio", "eletrico", "elétrico"],
  sun: ["sol", "claro", "dia"],
  moon: ["lua", "noite", "escuro"],
};
