export const helpTooltips = {
  list:
    "Aqui ficam os chamados de TI no seu nome, em tabela que preenche a tela e rola por dentro. Aberto, atualizado, resolvido e fechado mostram dia e hora. Acima da grade, o recorte ativo e a ordenação aparecem em chips; o botão de atualizar pede de novo ao helpdesk. Use Colunas para mostrar ou esconder campos — a preferência fica neste navegador. Clique no cabeçalho para ordenar (resolvido inclusive) ou abra a ordenação em níveis (até três). O mais (+) abre chamado; as setas mudam de página; o seletor define 10, 20 ou 50 por página; o X limpa o recorte. Chamado de outra pessoa e da lixeira não aparecem.",
  filters:
    "A busca e os filtros pedem o recorte ao helpdesk. A busca acha no título ou no texto da abertura. O selo de estado usa o número do status (novo, em atendimento, pendente, aguardando aprovação, solucionado, fechado), não o texto. Pendentes e aguardando aprovação têm recorte próprio; Abertos continua incluindo os que esperam aprovação. Aberto de/até filtra pela data de abertura; atualizado de/até, pela última mudança. O construtor de filtros monta várias regras com E (AND) e grava o recorte na URL — o F5 mantém o mesmo critério. Grupos com OU, exportação, seleção em massa e mapa ficam no console do helpdesk. A ordenação também: o clique na coluna não reordena só esta página. Recorte vazio significa que nenhum chamado bate com o filtro, não que você não tenha chamados.",
  link:
    "Na primeira vez, a Minha DELPI entra no helpdesk com o mesmo login. Se o usuário ainda não existir lá, o helpdesk cria a conta. Depois disso, os chamados passam a aparecer aqui.",
  create:
    "À esquerda ficam título e descrição; à direita, categoria, urgência e observadores opcionais. A descrição aceita formatação (negrito, listas, links, título, tabela) — o mesmo editor da resposta. Não dá para colar imagem nem anexar arquivo na abertura. Observadores: números de usuário do helpdesk, separados por vírgula — o BFF só envia o papel observador, sem escolher solicitante nem entidade. O envio fica à direita, no rodapé. A categoria é a lista visível para o seu usuário. A seta no canto superior volta à lista. O chamado fica no seu usuário e na entidade padrão do helpdesk.",
  detail:
    "A conversa preenche a tela e rola. No cartão aparecem aberto, atualizado, resolvido e fechado em dia e hora; TTO/TTR e o observador só se o helpdesk trouxer. A resposta fica no rodapé no mesmo editor rico da abertura, enquanto o chamado aceitar acompanhamento — chamado fechado some o Responder. Aprovar solução, reabrir e pesquisa de satisfação ficam no console do helpdesk: a API nova ainda não entrega esses passos ao solicitante. A formatação do helpdesk aparece na bolha. Imagens do fio abrem em prévia ao clicar. Não dá para colar imagem nem enviar arquivo novo por aqui. A foto da Minha DELPI aparece só nas mensagens que o helpdesk reconhece como suas, pelo usuário ou pelo e-mail, não pelo nome. Nas outras, as iniciais de quem escreveu. A seta no canto superior volta à lista; o ícone de enviar grava a resposta. Arquivos ligados ao chamado ficam abaixo da abertura.",
};
