-- OVs extras SEM pasta no controle maio/2026: residence, tipo LMP, critério de período
-- 000087, 003561, 000102, 002871
WITH
TargetOvs AS (
    SELECT * FROM (VALUES
        ('000087', '02'),
        ('003561', '01'),
        ('000102', '02'),
        ('002871', '01')
    ) AS T(sale_number, branch)
),
EngSupport AS (
    SELECT * FROM (VALUES
        ('000002', '000003'), ('000002', '000008'), ('000002', '000012'),
        ('000003', '000003'), ('000003', '000012')
    ) AS E(AIJ_PROVEN, AIJ_STAGE)
),
LmpAnchor AS (
    SELECT * FROM (VALUES
        ('000002', '000003'), ('000002', '000012'),
        ('000003', '000003'), ('000003', '000012')
    ) AS L(AIJ_PROVEN, AIJ_STAGE)
),
SampleAnchor AS (
    SELECT * FROM (VALUES
        ('000002', '000008'),
        ('000003', '000002'), ('000003', '000008')
    ) AS S(AIJ_PROVEN, AIJ_STAGE)
),
Ad1Active AS (
    SELECT AD1.AD1_FILIAL, AD1.AD1_NROPOR, AD1.AD1_REVISA, RTRIM(AD1.AD1_DESCRI) AS sale_description
    FROM AD1010 AD1
    INNER JOIN TargetOvs T ON T.sale_number = AD1.AD1_NROPOR AND T.branch = AD1.AD1_FILIAL
    WHERE AD1.D_E_L_E_T_ = ''
),
FirstEngGlobal AS (
    SELECT A.AIJ_FILIAL, A.AIJ_NROPOR, MIN(A.AIJ_DTINIC) AS first_eng_global
    FROM AIJ010 A
    INNER JOIN EngSupport E ON E.AIJ_PROVEN = A.AIJ_PROVEN AND E.AIJ_STAGE = A.AIJ_STAGE
    WHERE A.D_E_L_E_T_ = '' AND A.AIJ_DTINIC <> ''
    GROUP BY A.AIJ_FILIAL, A.AIJ_NROPOR
),
AnchorCurrentRev AS (
    SELECT A.AIJ_FILIAL, A.AIJ_NROPOR, A.AIJ_DTINIC AS anchor_start, A.AIJ_STAGE AS anchor_stage,
        A.AIJ_PROVEN AS anchor_process, A.AIJ_REVISA AS anchor_revision,
        ROW_NUMBER() OVER (PARTITION BY A.AIJ_FILIAL, A.AIJ_NROPOR ORDER BY A.AIJ_DTINIC DESC, A.AIJ_HRINIC DESC, A.R_E_C_N_O_ DESC) AS rn
    FROM AIJ010 A
    INNER JOIN Ad1Active AD1 ON AD1.AD1_FILIAL = A.AIJ_FILIAL AND AD1.AD1_NROPOR = A.AIJ_NROPOR AND AD1.AD1_REVISA = A.AIJ_REVISA
    INNER JOIN LmpAnchor L ON L.AIJ_PROVEN = A.AIJ_PROVEN AND L.AIJ_STAGE = A.AIJ_STAGE
    WHERE A.D_E_L_E_T_ = ''
),
AnchorChosen AS (SELECT * FROM AnchorCurrentRev WHERE rn = 1),
HasHomolog AS (
    SELECT DISTINCT A.AIJ_FILIAL, A.AIJ_NROPOR, MIN(A.AIJ_DTINIC) AS first_homolog
    FROM AIJ010 A
    WHERE A.D_E_L_E_T_ = ''
      AND ((A.AIJ_PROVEN='000002' AND A.AIJ_STAGE='000012') OR (A.AIJ_PROVEN='000003' AND A.AIJ_STAGE='000012'))
    GROUP BY A.AIJ_FILIAL, A.AIJ_NROPOR
),
HasSampleAnchor AS (
    SELECT DISTINCT A.AIJ_FILIAL, A.AIJ_NROPOR
    FROM AIJ010 A
    INNER JOIN Ad1Active AD1 ON AD1.AD1_FILIAL = A.AIJ_FILIAL AND AD1.AD1_NROPOR = A.AIJ_NROPOR AND AD1.AD1_REVISA = A.AIJ_REVISA
    INNER JOIN SampleAnchor S ON S.AIJ_PROVEN = A.AIJ_PROVEN AND S.AIJ_STAGE = A.AIJ_STAGE
    WHERE A.D_E_L_E_T_ = ''
),
HomologMay AS (
    SELECT DISTINCT A.AIJ_FILIAL, A.AIJ_NROPOR, MIN(A.AIJ_DTINIC) AS homolog_in_may
    FROM AIJ010 A
    WHERE A.D_E_L_E_T_ = ''
      AND A.AIJ_DTINIC BETWEEN '20260501' AND '20260531'
      AND ((A.AIJ_PROVEN='000002' AND A.AIJ_STAGE='000012') OR (A.AIJ_PROVEN='000003' AND A.AIJ_STAGE='000012'))
    GROUP BY A.AIJ_FILIAL, A.AIJ_NROPOR
),
EngMinutesClosed AS (
    SELECT A.AIJ_FILIAL, A.AIJ_NROPOR,
        SUM(CASE WHEN ISNULL(A.AIJ_DTINIC,'')<>'' AND ISNULL(A.AIJ_HRINIC,'')<>'' AND ISNULL(A.AIJ_DTENCE,'')<>'' AND ISNULL(A.AIJ_HRENCE,'')<>''
            THEN DATEDIFF(MINUTE,
                CAST(CONCAT(SUBSTRING(A.AIJ_DTINIC,1,4),'-',SUBSTRING(A.AIJ_DTINIC,5,2),'-',SUBSTRING(A.AIJ_DTINIC,7,2),' ',A.AIJ_HRINIC,':00') AS DATETIME),
                CAST(CONCAT(SUBSTRING(A.AIJ_DTENCE,1,4),'-',SUBSTRING(A.AIJ_DTENCE,5,2),'-',SUBSTRING(A.AIJ_DTENCE,7,2),' ',A.AIJ_HRENCE,':00') AS DATETIME))
            ELSE 0 END) AS eng_min_closed
    FROM AIJ010 A
    INNER JOIN Ad1Active AD1 ON AD1.AD1_FILIAL = A.AIJ_FILIAL AND AD1.AD1_NROPOR = A.AIJ_NROPOR
    INNER JOIN EngSupport E ON E.AIJ_PROVEN = A.AIJ_PROVEN AND E.AIJ_STAGE = A.AIJ_STAGE
    WHERE A.D_E_L_E_T_ = ''
    GROUP BY A.AIJ_FILIAL, A.AIJ_NROPOR
),
ListingEventMay AS (
    SELECT A.AIJ_FILIAL, A.AIJ_NROPOR, MIN(A.AIJ_DTINIC) AS first_listing_may
    FROM AIJ010 A
    WHERE A.D_E_L_E_T_ = ''
      AND A.AIJ_DTINIC BETWEEN '20260501' AND '20260531'
      AND (
            (A.AIJ_PROVEN='000002' AND A.AIJ_STAGE IN ('000003','000008','000012'))
         OR (A.AIJ_PROVEN='000003' AND A.AIJ_STAGE IN ('000003','000012','000002','000008'))
      )
    GROUP BY A.AIJ_FILIAL, A.AIJ_NROPOR
)
SELECT
    T.sale_number,
    T.branch,
    AD1.sale_description,
    AC.anchor_start,
    AC.anchor_stage,
    AC.anchor_process,
    FE.first_eng_global,
    HM.homolog_in_may,
    HH.first_homolog,
    CASE WHEN HH.AIJ_NROPOR IS NOT NULL THEN 1 ELSE 0 END AS has_lmp_homolog_ever,
    CASE WHEN SA.AIJ_NROPOR IS NOT NULL THEN 1 ELSE 0 END AS has_sample_anchor_current_rev,
    EM.eng_min_closed,
    LM.first_listing_may,
    CASE WHEN AC.anchor_start BETWEEN '20260501' AND '20260531' THEN 1 ELSE 0 END AS anchor_in_may,
    CASE WHEN FE.first_eng_global BETWEEN '20260501' AND '20260531' THEN 1 ELSE 0 END AS first_eng_in_may,
    CASE WHEN HM.homolog_in_may IS NOT NULL THEN 1 ELSE 0 END AS homolog_in_may_flag,
    CASE
        WHEN AC.anchor_start BETWEEN '20260501' AND '20260531' THEN 'INCLUI: ancora_no_mes'
        WHEN FE.first_eng_global BETWEEN '20260501' AND '20260531' THEN 'INCLUI: first_eng_no_mes (OR periodo)'
        ELSE 'NAO_INCLUI_PERIODO'
    END AS motivo_inclusao_periodo,
    CASE
        WHEN HH.AIJ_NROPOR IS NULL THEN 'NAO_LMP (sem homolog 000012)'
        WHEN SA.AIJ_NROPOR IS NOT NULL AND HM.homolog_in_may IS NULL THEN 'REVISAR: amostra+homolog?'
        WHEN HH.AIJ_NROPOR IS NOT NULL THEN 'LMP (homolog 000012 existe)'
        ELSE 'INDEFINIDO'
    END AS classificacao_lmp
FROM TargetOvs T
INNER JOIN Ad1Active AD1 ON AD1.AD1_NROPOR = T.sale_number AND AD1.AD1_FILIAL = T.branch
LEFT JOIN AnchorChosen AC ON AC.AIJ_FILIAL = AD1.AD1_FILIAL AND AC.AIJ_NROPOR = AD1.AD1_NROPOR
LEFT JOIN FirstEngGlobal FE ON FE.AIJ_FILIAL = AD1.AD1_FILIAL AND FE.AIJ_NROPOR = AD1.AD1_NROPOR
LEFT JOIN HasHomolog HH ON HH.AIJ_FILIAL = AD1.AD1_FILIAL AND HH.AIJ_NROPOR = AD1.AD1_NROPOR
LEFT JOIN HasSampleAnchor SA ON SA.AIJ_FILIAL = AD1.AD1_FILIAL AND SA.AIJ_NROPOR = AD1.AD1_NROPOR
LEFT JOIN HomologMay HM ON HM.AIJ_FILIAL = AD1.AD1_FILIAL AND HM.AIJ_NROPOR = AD1.AD1_NROPOR
LEFT JOIN EngMinutesClosed EM ON EM.AIJ_FILIAL = AD1.AD1_FILIAL AND EM.AIJ_NROPOR = AD1.AD1_NROPOR
LEFT JOIN ListingEventMay LM ON LM.AIJ_FILIAL = AD1.AD1_FILIAL AND LM.AIJ_NROPOR = AD1.AD1_NROPOR
ORDER BY T.sale_number;
