"""Compat — reexporta constantes de permissão do domain."""

from app.domain.security.chat_permission_constants import (
    CHAT_ACCESS_PERMISSION,
    CHAT_ADMIN_PERMISSION,
    CHAT_ASK_PERMISSION,
    CHAT_HISTORY_VIEW_PERMISSION,
    CHAT_KNOWLEDGE_MANAGE_PERMISSION,
    CHAT_TOOLS_MANAGE_PERMISSION,
    CHAT_TOOLS_USE_PERMISSION,
)

__all__ = [
    "CHAT_ACCESS_PERMISSION",
    "CHAT_ADMIN_PERMISSION",
    "CHAT_ASK_PERMISSION",
    "CHAT_HISTORY_VIEW_PERMISSION",
    "CHAT_KNOWLEDGE_MANAGE_PERMISSION",
    "CHAT_TOOLS_MANAGE_PERMISSION",
    "CHAT_TOOLS_USE_PERMISSION",
]
