"""Códigos RBAC usados pelos decorators ``delpi_auth.authorization`` na api-delpi."""

from __future__ import annotations

# --- api-delpi (módulo) ---
API_DELPI_ACCESS = "api-delpi.access"
API_DELPI_ACCESS_FULL = "api-delpi.access.full"
API_DELPI_SYSTEM = "api-delpi.system"
API_DELPI_DATA = "api-delpi.data"
API_DELPI_QUALITY_ACCESS = "api-delpi.quality.access"

# --- dashboards KPI (MFE) ---
DASHBOARD_FINANCIAL_VIEW = "dashboard-financial.view"
DASHBOARD_COMMERCIAL_VIEW = "dashboard-commercial.view"
DASHBOARD_PRODUCTION_VIEW = "dashboard-production.view"
DASHBOARD_SUPPLIES_VIEW = "dashboard-supplies.view"
DASHBOARD_QUALITY_VIEW = "dashboard-quality.view"
DASHBOARD_HR_VIEW = "dashboard-hr.view"
DASHBOARD_ENGINEERING_VIEW = "dashboard-engineering.view"
DASHBOARD_LMPS_VIEW = "dashboard-lmps.view"

# --- cadastro kaizen ---
CADASTRO_KAIZEN_VIEW = "cadastro-kaizen.view"
CADASTRO_KAIZEN_MANAGE = "cadastro-kaizen.manage"
CADASTRO_KAIZEN_NOTIFY_SUGGESTIONS = "cadastro-kaizen.notify-suggestions"

# --- planos de ação PAC qualidade ---
QUALITY_ACTION_PLANS_ACCESS = "quality-action-plans.access"
QUALITY_ACTION_PLANS_READ = "quality-action-plans.read"
QUALITY_ACTION_PLANS_WRITE = "quality-action-plans.write"
QUALITY_ACTION_PLANS_MANAGE = "quality-action-plans.manage"
QUALITY_ACTION_PLANS_CLOSE = "quality-action-plans.close"
QUALITY_ACTION_PLANS_VALIDATE_EFFECTIVENESS = "quality-action-plans.validate-effectiveness"
QUALITY_ACTION_PLANS_ADMIN = "quality-action-plans.admin"
API_DELPI_QUALITY_ACTION_PLANS_READ = "api-delpi.quality.action-plans.read"

# --- auditoria 5S ---
AUDITORIA_5S_VIEW_FILIAL_01 = "auditoria-5s.view.filial-01"
AUDITORIA_5S_VIEW_FILIAL_02 = "auditoria-5s.view.filial-02"
AUDITORIA_5S_AUDIT_FILIAL_01 = "auditoria-5s.audit.filial-01"
AUDITORIA_5S_AUDIT_FILIAL_02 = "auditoria-5s.audit.filial-02"
AUDITORIA_5S_ADMIN_FILIAL_01 = "auditoria-5s.admin.filial-01"
AUDITORIA_5S_ADMIN_FILIAL_02 = "auditoria-5s.admin.filial-02"

# --- central agendamento ---
CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES = "central-agendamento.view.filial-es"
CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC = "central-agendamento.view.filial-sc"
CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES = "central-agendamento.manage.filial-es"
CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC = "central-agendamento.manage.filial-sc"
CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES = "central-agendamento.approve.filial-es"
CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC = "central-agendamento.approve.filial-sc"

# --- cultura DELPI ---
CULTURA_DELPI_VIEW = "cultura-delpi.view"
CULTURA_DELPI_MANAGE = "cultura-delpi.manage"

# --- canal de denúncia ---
CANAL_DENUNCIA_ACCESS = "canal-denuncia.access"

# --- guias e procedimentos ---
GUIAS_PROCEDIMENTOS_ACCESS = "guias-procedimentos.access"
GUIAS_PROCEDIMENTOS_MANAGE = "guias-procedimentos.manage"

# --- etiquetas da qualidade ---
QUALITY_LABELS_VIEW = "quality-labels.view"
QUALITY_LABELS_WRITE = "quality-labels.write"

# --- propostas comerciais ---
PROPOSTAS_COMERCIAIS_VIEW = "propostas-comerciais.view"

# --- pedidos de venda em aberto ---
PEDIDOS_VENDA_ABERTOS_ACCESS = "pedidos-venda-abertos.access"

# --- financeiro — despesas por centro de custo ---
FINANCEIRO_CENTRO_CUSTO_ACCESS = "financeiro-centro-custo.access"
FINANCEIRO_CENTRO_CUSTO_VIEW = "financeiro-centro-custo.view"
FINANCEIRO_CENTRO_CUSTO_EXPORT = "financeiro-centro-custo.export"

# --- financeiro — inadimplência ---
# Pendência: cadastrar no RBAC/Keycloak e no manifesto do plugin MFE.
FINANCEIRO_INADIMPLENCIA_ACCESS = "financeiro-inadimplencia.access"
FINANCEIRO_INADIMPLENCIA_VIEW = "financeiro-inadimplencia.view"

# --- inspeções de entrada ---
INSPECOES_ENTRADA_VIEW = "inspecoes-entrada.view"
INSPECOES_ENTRADA_VIEW_FILIAL_01 = "inspecoes-entrada.view.filial-01"
INSPECOES_ENTRADA_VIEW_FILIAL_02 = "inspecoes-entrada.view.filial-02"

# --- inspeções de processo ---
INSPECOES_PROCESSO_VIEW = "inspecoes-processo.view"
INSPECOES_PROCESSO_VIEW_FILIAL_01 = "inspecoes-processo.view.filial-01"
INSPECOES_PROCESSO_VIEW_FILIAL_02 = "inspecoes-processo.view.filial-02"

# --- eficiência fabril ---
EFICIENCIA_FABRIL_VIEW = "eficiencia-fabril.view"
EFICIENCIA_FABRIL_VIEW_FILIAL_SC = "eficiencia-fabril.view.filial-sc"
EFICIENCIA_FABRIL_VIEW_FILIAL_ES = "eficiencia-fabril.view.filial-es"

# --- controle de retrabalhos ---
CONTROLE_RETRABALHO_ACCESS = "controle-retrabalhos.access"
CONTROLE_RETRABALHO_VIEW = "controle-retrabalhos.view"
CONTROLE_RETRABALHO_VIEW_FILIAL_SC = "controle-retrabalhos.view.filial-sc"
CONTROLE_RETRABALHO_VIEW_FILIAL_ES = "controle-retrabalhos.view.filial-es"

# --- scrap monitoring (acompanhamento de refugos) ---
SCRAP_MONITORING_ACCESS = "scrap-monitoring.access"
SCRAP_MONITORING_VIEW = "scrap-monitoring.view"
SCRAP_MONITORING_VIEW_FILIAL_SC = "scrap-monitoring.view.filial-sc"
SCRAP_MONITORING_VIEW_FILIAL_ES = "scrap-monitoring.view.filial-es"

# --- apontamento de produção (production-appointments) ---
PRODUCTION_APPOINTMENTS_ACCESS = "production-appointments.access"
PRODUCTION_APPOINTMENTS_VIEW = "production-appointments.view"
PRODUCTION_APPOINTMENTS_VIEW_FILIAL_SC = "production-appointments.view.filial-sc"
PRODUCTION_APPOINTMENTS_VIEW_FILIAL_ES = "production-appointments.view.filial-es"

# --- análise de estoque de segurança ---
SAFETY_STOCK_ACCESS = "estoque-seguranca.access"
SAFETY_STOCK_VIEW_FILIAL_SC = "estoque-seguranca.view.filial-sc"
SAFETY_STOCK_VIEW_FILIAL_ES = "estoque-seguranca.view.filial-es"

# --- Delpi Reports ---
REPORTS_VIEW = "reports.view"
REPORTS_MANAGE = "reports.manage"
REPORTS_VIEW_FILIAL_SC = "reports.view.filial-sc"
REPORTS_VIEW_FILIAL_ES = "reports.view.filial-es"
REPORTS_MANAGE_FILIAL_SC = "reports.manage.filial-sc"
REPORTS_MANAGE_FILIAL_ES = "reports.manage.filial-es"

# --- conjuntos usados em @require_any_permission ---
KPI_FINANCIAL_ACCESS = [API_DELPI_ACCESS, DASHBOARD_FINANCIAL_VIEW]
KPI_COMMERCIAL_ACCESS = [API_DELPI_ACCESS, DASHBOARD_COMMERCIAL_VIEW]
KPI_PRODUCTION_ACCESS = [API_DELPI_ACCESS, DASHBOARD_PRODUCTION_VIEW]
KPI_SUPPLIES_ACCESS = [API_DELPI_ACCESS, DASHBOARD_SUPPLIES_VIEW]
KPI_QUALITY_ACCESS = [API_DELPI_QUALITY_ACCESS, DASHBOARD_QUALITY_VIEW]
KPI_HR_ACCESS = [API_DELPI_ACCESS, DASHBOARD_HR_VIEW]
ENGINEERING_LMP_ACCESS = [
    API_DELPI_ACCESS,
    DASHBOARD_ENGINEERING_VIEW,
    DASHBOARD_LMPS_VIEW,
]

MAINTENANCE_VIEW = "maintenance.view"
MINI_APPLICATORS_ACCESS = [
    API_DELPI_ACCESS,
    MAINTENANCE_VIEW,
    DASHBOARD_ENGINEERING_VIEW,
]
SYSTEM_METADATA_ACCESS = [API_DELPI_ACCESS_FULL, API_DELPI_SYSTEM]
DATA_SQL_ACCESS = [API_DELPI_ACCESS_FULL, API_DELPI_DATA]

AUDIT_5S_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    AUDITORIA_5S_VIEW_FILIAL_01,
    AUDITORIA_5S_VIEW_FILIAL_02,
    AUDITORIA_5S_AUDIT_FILIAL_01,
    AUDITORIA_5S_AUDIT_FILIAL_02,
    AUDITORIA_5S_ADMIN_FILIAL_01,
    AUDITORIA_5S_ADMIN_FILIAL_02,
]
AUDIT_5S_WRITE_PERMISSIONS = AUDIT_5S_READ_PERMISSIONS
AUDIT_5S_ADMIN_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    AUDITORIA_5S_ADMIN_FILIAL_01,
    AUDITORIA_5S_ADMIN_FILIAL_02,
]
AUDIT_5S_BRANCH_ADMIN_PERMS = {
    "01": AUDITORIA_5S_ADMIN_FILIAL_01,
    "02": AUDITORIA_5S_ADMIN_FILIAL_02,
}

KAIZEN_RECORDS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    DASHBOARD_QUALITY_VIEW,
    CADASTRO_KAIZEN_VIEW,
    CADASTRO_KAIZEN_MANAGE,
]
KAIZEN_RECORDS_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    CADASTRO_KAIZEN_MANAGE,
]

QUALITY_ACTION_PLANS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    API_DELPI_QUALITY_ACTION_PLANS_READ,
    DASHBOARD_QUALITY_VIEW,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_READ,
    QUALITY_ACTION_PLANS_MANAGE,
]
QUALITY_ACTION_PLANS_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]
QUALITY_ACTION_PLANS_CLOSE_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_CLOSE,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]
QUALITY_ACTION_PLANS_VALIDATE_EFFECTIVENESS_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_VALIDATE_EFFECTIVENESS,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]
QUALITY_ACTION_PLANS_ADMIN_DISPATCH_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]

SCHEDULING_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES,
    CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC,
]
SCHEDULING_MANAGE_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
]
SCHEDULING_APPROVE_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC,
]
SCHEDULING_BRANCH_VIEW_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC,
}
SCHEDULING_BRANCH_MANAGE_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
}
SCHEDULING_BRANCH_APPROVE_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC,
}

EFICIENCIA_FABRIL_ACCESS = [
    API_DELPI_ACCESS,
    EFICIENCIA_FABRIL_VIEW,
    EFICIENCIA_FABRIL_VIEW_FILIAL_SC,
    EFICIENCIA_FABRIL_VIEW_FILIAL_ES,
    DASHBOARD_PRODUCTION_VIEW,
]

PEDIDOS_VENDA_ABERTOS_PERMISSIONS = [
    API_DELPI_ACCESS,
    PEDIDOS_VENDA_ABERTOS_ACCESS,
]

FINANCEIRO_CENTRO_CUSTO_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_VIEW,
]

FINANCEIRO_CENTRO_CUSTO_EXPORT_PERMISSIONS = [
    API_DELPI_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_VIEW,
    FINANCEIRO_CENTRO_CUSTO_EXPORT,
]

FINANCEIRO_INADIMPLENCIA_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    FINANCEIRO_INADIMPLENCIA_ACCESS,
    FINANCEIRO_INADIMPLENCIA_VIEW,
]

CONTROLE_RETRABALHO_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    CONTROLE_RETRABALHO_ACCESS,
    CONTROLE_RETRABALHO_VIEW,
    CONTROLE_RETRABALHO_VIEW_FILIAL_SC,
    CONTROLE_RETRABALHO_VIEW_FILIAL_ES,
]

CONTROLE_RETRABALHO_BRANCH_VIEW_PERMS = {
    "01": CONTROLE_RETRABALHO_VIEW_FILIAL_SC,
    "02": CONTROLE_RETRABALHO_VIEW_FILIAL_ES,
}

SCRAP_MONITORING_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    SCRAP_MONITORING_ACCESS,
    SCRAP_MONITORING_VIEW,
    SCRAP_MONITORING_VIEW_FILIAL_SC,
    SCRAP_MONITORING_VIEW_FILIAL_ES,
]

SCRAP_MONITORING_BRANCH_VIEW_PERMS = {
    "01": SCRAP_MONITORING_VIEW_FILIAL_SC,
    "02": SCRAP_MONITORING_VIEW_FILIAL_ES,
}

PRODUCTION_APPOINTMENTS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    PRODUCTION_APPOINTMENTS_ACCESS,
    PRODUCTION_APPOINTMENTS_VIEW,
    PRODUCTION_APPOINTMENTS_VIEW_FILIAL_SC,
    PRODUCTION_APPOINTMENTS_VIEW_FILIAL_ES,
]

PRODUCTION_APPOINTMENTS_BRANCH_VIEW_PERMS = {
    "01": PRODUCTION_APPOINTMENTS_VIEW_FILIAL_SC,
    "02": PRODUCTION_APPOINTMENTS_VIEW_FILIAL_ES,
}

SAFETY_STOCK_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    SAFETY_STOCK_ACCESS,
    SAFETY_STOCK_VIEW_FILIAL_SC,
    SAFETY_STOCK_VIEW_FILIAL_ES,
]

SAFETY_STOCK_BRANCH_VIEW_PERMS = {
    "01": SAFETY_STOCK_VIEW_FILIAL_SC,
    "02": SAFETY_STOCK_VIEW_FILIAL_ES,
}

REPORTS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    REPORTS_VIEW,
    REPORTS_MANAGE,
    REPORTS_VIEW_FILIAL_SC,
    REPORTS_VIEW_FILIAL_ES,
    REPORTS_MANAGE_FILIAL_SC,
    REPORTS_MANAGE_FILIAL_ES,
]

REPORTS_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    REPORTS_MANAGE,
    REPORTS_MANAGE_FILIAL_SC,
    REPORTS_MANAGE_FILIAL_ES,
]

REPORTS_BRANCH_VIEW_PERMS = {
    "01": REPORTS_VIEW_FILIAL_SC,
    "02": REPORTS_VIEW_FILIAL_ES,
}

INSPECOES_ENTRADA_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    INSPECOES_ENTRADA_VIEW,
    INSPECOES_ENTRADA_VIEW_FILIAL_01,
    INSPECOES_ENTRADA_VIEW_FILIAL_02,
]

INSPECOES_ENTRADA_BRANCH_VIEW_PERMS = {
    "01": INSPECOES_ENTRADA_VIEW_FILIAL_01,
    "02": INSPECOES_ENTRADA_VIEW_FILIAL_02,
}

INSPECOES_PROCESSO_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    INSPECOES_PROCESSO_VIEW,
    INSPECOES_PROCESSO_VIEW_FILIAL_01,
    INSPECOES_PROCESSO_VIEW_FILIAL_02,
]

INSPECOES_PROCESSO_BRANCH_VIEW_PERMS = {
    "01": INSPECOES_PROCESSO_VIEW_FILIAL_01,
    "02": INSPECOES_PROCESSO_VIEW_FILIAL_02,
}

CULTURA_DELPI_READ_PERMISSIONS = [
    CULTURA_DELPI_VIEW,
    CULTURA_DELPI_MANAGE,
]

CULTURA_DELPI_WRITE_PERMISSIONS = [
    CULTURA_DELPI_MANAGE,
]

CANAL_DENUNCIA_SUBMIT_PERMISSIONS = [
    CANAL_DENUNCIA_ACCESS,
]

GUIAS_PROCEDIMENTOS_READ_PERMISSIONS = [
    GUIAS_PROCEDIMENTOS_ACCESS,
    GUIAS_PROCEDIMENTOS_MANAGE,
]

GUIAS_PROCEDIMENTOS_WRITE_PERMISSIONS = [
    GUIAS_PROCEDIMENTOS_MANAGE,
]

QUALITY_LABELS_READ_PERMISSIONS = [
    QUALITY_LABELS_VIEW,
    QUALITY_LABELS_WRITE,
]

QUALITY_LABELS_WRITE_PERMISSIONS = [
    QUALITY_LABELS_WRITE,
]

PROPOSTAS_COMERCIAIS_ACCESS = [
    API_DELPI_ACCESS,
    PROPOSTAS_COMERCIAIS_VIEW,
    DASHBOARD_COMMERCIAL_VIEW,
]

API_DELPI_CONSOLE_VIEW = "api-delpi-console.view"
CONSOLE_SMOKE_ACCESS = [API_DELPI_ACCESS, API_DELPI_CONSOLE_VIEW]
SQL_HEALTH_ACCESS = [
    API_DELPI_ACCESS_FULL,
    API_DELPI_SYSTEM,
    API_DELPI_CONSOLE_VIEW,
    API_DELPI_ACCESS,
]
OBSERVABILITY_ACCESS = SQL_HEALTH_ACCESS
