"""Códigos RBAC usados pelos decorators ``delpi_auth.authorization`` na api-delpi."""

from __future__ import annotations

# --- api-delpi (módulo) ---
API_DELPI_ACCESS = "api-delpi.access"
API_DELPI_ACCESS_FULL = "api-delpi.access.full"
API_DELPI_SYSTEM = "api-delpi.system"
API_DELPI_DATA = "api-delpi.data"
API_DELPI_QUALITY_ACCESS = "api-delpi.quality.access"

# --- dashboards KPI (MFE) ---
DASHBOARD_FINANCIAL_VIEW = "dashboard-financial.view"
DASHBOARD_COMMERCIAL_VIEW = "dashboard-commercial.view"
DASHBOARD_PRODUCTION_VIEW = "dashboard-production.view"
DASHBOARD_SUPPLIES_VIEW = "dashboard-supplies.view"
DASHBOARD_QUALITY_VIEW = "dashboard-quality.view"
DASHBOARD_HR_VIEW = "dashboard-hr.view"
DASHBOARD_ENGINEERING_VIEW = "dashboard-engineering.view"
DASHBOARD_LMPS_VIEW = "dashboard-lmps.view"
DASHBOARD_LMPS_NC_WRITE = "dashboard-lmps.nc.write"

# --- kaizometro (legado: cadastro-kaizen.* mantido na janela de migração) ---
KAIZOMETRO_VIEW = "kaizometro.view"
KAIZOMETRO_MANAGE = "kaizometro.manage"
KAIZOMETRO_NOTIFY_SUGGESTIONS = "kaizometro.notify-suggestions"
KAIZOMETRO_BRANCH_01 = "kaizometro.branch-01"
KAIZOMETRO_BRANCH_02 = "kaizometro.branch-02"
CADASTRO_KAIZEN_VIEW = "cadastro-kaizen.view"  # legado
CADASTRO_KAIZEN_MANAGE = "cadastro-kaizen.manage"  # legado
CADASTRO_KAIZEN_NOTIFY_SUGGESTIONS = "cadastro-kaizen.notify-suggestions"  # legado

KAIZOMETRO_BRANCH_VIEW_PERMS = {
    "01": KAIZOMETRO_BRANCH_01,
    "02": KAIZOMETRO_BRANCH_02,
}

# --- planos de ação PAC qualidade ---
QUALITY_ACTION_PLANS_ACCESS = "quality-action-plans.access"
QUALITY_ACTION_PLANS_READ = "quality-action-plans.read"
QUALITY_ACTION_PLANS_WRITE = "quality-action-plans.write"
QUALITY_ACTION_PLANS_MANAGE = "quality-action-plans.manage"
QUALITY_ACTION_PLANS_CLOSE = "quality-action-plans.close"
QUALITY_ACTION_PLANS_VALIDATE_EFFECTIVENESS = "quality-action-plans.validate-effectiveness"
QUALITY_ACTION_PLANS_ADMIN = "quality-action-plans.admin"
API_DELPI_QUALITY_ACTION_PLANS_READ = "api-delpi.quality.action-plans.read"

# --- auditoria 5S ---
AUDITORIA_5S_VIEW_FILIAL_01 = "auditoria-5s.view.filial-01"
AUDITORIA_5S_VIEW_FILIAL_02 = "auditoria-5s.view.filial-02"
AUDITORIA_5S_AUDIT_FILIAL_01 = "auditoria-5s.audit.filial-01"
AUDITORIA_5S_AUDIT_FILIAL_02 = "auditoria-5s.audit.filial-02"
AUDITORIA_5S_ADMIN_FILIAL_01 = "auditoria-5s.admin.filial-01"
AUDITORIA_5S_ADMIN_FILIAL_02 = "auditoria-5s.admin.filial-02"

# --- central agendamento ---
CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES = "central-agendamento.view.filial-es"
CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC = "central-agendamento.view.filial-sc"
CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES = "central-agendamento.manage.filial-es"
CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC = "central-agendamento.manage.filial-sc"
CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES = "central-agendamento.approve.filial-es"
CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC = "central-agendamento.approve.filial-sc"

# --- cultura DELPI ---
CULTURA_DELPI_VIEW = "cultura-delpi.view"
CULTURA_DELPI_MANAGE = "cultura-delpi.manage"

# --- canal de denúncia ---
CANAL_DENUNCIA_ACCESS = "canal-denuncia.access"

# --- guias e procedimentos ---
GUIAS_PROCEDIMENTOS_ACCESS = "guias-procedimentos.access"
GUIAS_PROCEDIMENTOS_MANAGE = "guias-procedimentos.manage"

# --- mural de acessos ---
MURAL_ACESSOS_ACCESS = "mural-acessos.access"
MURAL_ACESSOS_MANAGE = "mural-acessos.manage"

# --- planejamento orçamentário ---
PLANEJAMENTO_ORCAMENTARIO_ACCESS = "planejamento-orcamentario.access"
PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_VIEW = "planejamento-orcamentario.guidance.view"
PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_MANAGE = "planejamento-orcamentario.guidance.manage"
PLANEJAMENTO_ORCAMENTARIO_SCOPES_MANAGE = "planejamento-orcamentario.scopes.manage"
PLANEJAMENTO_ORCAMENTARIO_ADMIN = "planejamento-orcamentario.admin"
PLANEJAMENTO_ORCAMENTARIO_CAPEX_SUBMIT = "planejamento-orcamentario.capex.submit"
PLANEJAMENTO_ORCAMENTARIO_CAPEX_APPROVE = "planejamento-orcamentario.capex.approve"
PLANEJAMENTO_ORCAMENTARIO_CAPEX_CONSOLIDATION_VIEW = (
    "planejamento-orcamentario.capex.consolidation.view"
)
PLANEJAMENTO_ORCAMENTARIO_CAPEX_EXPORT = "planejamento-orcamentario.capex.export"
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_VIEW = "planejamento-orcamentario.personnel.view"
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_EDIT = "planejamento-orcamentario.personnel.edit"
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_SUBMIT = "planejamento-orcamentario.personnel.submit"
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_APPROVE = "planejamento-orcamentario.personnel.approve"

# --- lançamento de notas fiscais ---
LANCAMENTO_NOTAS_FISCAIS_ACCESS = "lancamento-notas-fiscais.access"
LANCAMENTO_NOTAS_FISCAIS_CREATE = "lancamento-notas-fiscais.create"
LANCAMENTO_NOTAS_FISCAIS_VIEW = "lancamento-notas-fiscais.view"
LANCAMENTO_NOTAS_FISCAIS_VIEW_FILIAL_01 = "lancamento-notas-fiscais.view.filial-01"
LANCAMENTO_NOTAS_FISCAIS_VIEW_FILIAL_02 = "lancamento-notas-fiscais.view.filial-02"
LANCAMENTO_NOTAS_FISCAIS_PROCESS = "lancamento-notas-fiscais.process"
LANCAMENTO_NOTAS_FISCAIS_MANAGE = "lancamento-notas-fiscais.manage"

# --- invoice issuance ---
INVOICE_ISSUANCE_ACCESS = "invoice-issuance.access"
INVOICE_ISSUANCE_CREATE = "invoice-issuance.create"
INVOICE_ISSUANCE_VIEW = "invoice-issuance.view"
INVOICE_ISSUANCE_VIEW_FILIAL_01 = "invoice-issuance.view.filial-01"
INVOICE_ISSUANCE_VIEW_FILIAL_02 = "invoice-issuance.view.filial-02"
INVOICE_ISSUANCE_PROCESS = "invoice-issuance.process"
INVOICE_ISSUANCE_MANAGE = "invoice-issuance.manage"

# --- etiquetas da qualidade ---
QUALITY_LABELS_VIEW = "quality-labels.view"
QUALITY_LABELS_WRITE = "quality-labels.write"

# --- propostas comerciais ---
PROPOSTAS_COMERCIAIS_VIEW = "propostas-comerciais.view"

# --- pedidos de venda em aberto ---
PEDIDOS_VENDA_ABERTOS_ACCESS = "pedidos-venda-abertos.access"
PEDIDOS_VENDA_ABERTOS_ADMIN = "pedidos-venda-abertos.admin"

# Portal Comercial — catálogo condensado (3 codes). Plugins irmãos PVA / dashboard
# mantêm os próprios codes nas OR-lists abaixo.
COMMERCIAL_ACCESS = "commercial.access"
COMMERCIAL_MANAGE = "commercial.manage"
COMMERCIAL_BILLING_NOTIFY = "commercial.billing.notify"

# --- financeiro — despesas por centro de custo ---
FINANCEIRO_CENTRO_CUSTO_ACCESS = "financeiro-centro-custo.access"
FINANCEIRO_CENTRO_CUSTO_VIEW = "financeiro-centro-custo.view"
FINANCEIRO_CENTRO_CUSTO_EXPORT = "financeiro-centro-custo.export"

# --- financeiro — inadimplência ---
# Pendência: cadastrar no RBAC/Keycloak e no manifesto do plugin MFE.
FINANCEIRO_INADIMPLENCIA_ACCESS = "financeiro-inadimplencia.access"
FINANCEIRO_INADIMPLENCIA_VIEW = "financeiro-inadimplencia.view"

# --- inspeções de entrada ---
INSPECOES_ENTRADA_VIEW = "inspecoes-entrada.view"
INSPECOES_ENTRADA_VIEW_FILIAL_01 = "inspecoes-entrada.view.filial-01"
INSPECOES_ENTRADA_VIEW_FILIAL_02 = "inspecoes-entrada.view.filial-02"

# --- inspeções de processo ---
INSPECOES_PROCESSO_VIEW = "inspecoes-processo.view"
INSPECOES_PROCESSO_VIEW_FILIAL_01 = "inspecoes-processo.view.filial-01"
INSPECOES_PROCESSO_VIEW_FILIAL_02 = "inspecoes-processo.view.filial-02"

# --- eficiência fabril ---
EFICIENCIA_FABRIL_VIEW = "eficiencia-fabril.view"
EFICIENCIA_FABRIL_VIEW_FILIAL_SC = "eficiencia-fabril.view.filial-sc"
EFICIENCIA_FABRIL_VIEW_FILIAL_ES = "eficiencia-fabril.view.filial-es"

# --- controle de retrabalhos ---
CONTROLE_RETRABALHO_ACCESS = "controle-retrabalhos.access"
CONTROLE_RETRABALHO_VIEW = "controle-retrabalhos.view"
CONTROLE_RETRABALHO_VIEW_FILIAL_SC = "controle-retrabalhos.view.filial-sc"
CONTROLE_RETRABALHO_VIEW_FILIAL_ES = "controle-retrabalhos.view.filial-es"

# --- scrap monitoring (acompanhamento de refugos) ---
SCRAP_MONITORING_ACCESS = "scrap-monitoring.access"
SCRAP_MONITORING_VIEW = "scrap-monitoring.view"
SCRAP_MONITORING_VIEW_FILIAL_SC = "scrap-monitoring.view.filial-sc"
SCRAP_MONITORING_VIEW_FILIAL_ES = "scrap-monitoring.view.filial-es"

# --- apontamento de produção (production-appointments) ---
PRODUCTION_APPOINTMENTS_ACCESS = "production-appointments.access"
PRODUCTION_APPOINTMENTS_VIEW = "production-appointments.view"
PRODUCTION_APPOINTMENTS_VIEW_FILIAL_SC = "production-appointments.view.filial-sc"
PRODUCTION_APPOINTMENTS_VIEW_FILIAL_ES = "production-appointments.view.filial-es"

# --- análise de estoque de segurança ---
SAFETY_STOCK_ACCESS = "estoque-seguranca.access"
SAFETY_STOCK_VIEW_FILIAL_SC = "estoque-seguranca.view.filial-sc"
SAFETY_STOCK_VIEW_FILIAL_ES = "estoque-seguranca.view.filial-es"

# --- materiais de terceiros / beneficiamento ---
THIRD_PARTY_MATERIALS_ACCESS = "materiais-terceiros.access"
THIRD_PARTY_MATERIALS_VIEW_FILIAL_SC = "materiais-terceiros.view.filial-sc"
THIRD_PARTY_MATERIALS_VIEW_FILIAL_ES = "materiais-terceiros.view.filial-es"
THIRD_PARTY_MATERIALS_EXPORT = "materiais-terceiros.export"

# --- Delpi Reports ---
REPORTS_VIEW = "reports.view"
REPORTS_MANAGE = "reports.manage"
REPORTS_NOTES_MANAGE = "reports.notes.manage"
REPORTS_VIEW_FILIAL_SC = "reports.view.filial-sc"
REPORTS_VIEW_FILIAL_ES = "reports.view.filial-es"
REPORTS_MANAGE_FILIAL_SC = "reports.manage.filial-sc"
REPORTS_MANAGE_FILIAL_ES = "reports.manage.filial-es"

# --- conjuntos usados em @require_any_permission ---
KPI_FINANCIAL_ACCESS = [API_DELPI_ACCESS, DASHBOARD_FINANCIAL_VIEW]
KPI_COMMERCIAL_ACCESS = [
    API_DELPI_ACCESS,
    DASHBOARD_COMMERCIAL_VIEW,
    COMMERCIAL_ACCESS,
]
KPI_PRODUCTION_ACCESS = [API_DELPI_ACCESS, DASHBOARD_PRODUCTION_VIEW]
KPI_SUPPLIES_ACCESS = [API_DELPI_ACCESS, DASHBOARD_SUPPLIES_VIEW]
KPI_QUALITY_ACCESS = [API_DELPI_QUALITY_ACCESS, DASHBOARD_QUALITY_VIEW]
KPI_HR_ACCESS = [API_DELPI_ACCESS, DASHBOARD_HR_VIEW]
ENGINEERING_LMP_ACCESS = [
    API_DELPI_ACCESS,
    DASHBOARD_ENGINEERING_VIEW,
    DASHBOARD_LMPS_VIEW,
]
ENGINEERING_LMP_NC_WRITE = [
    API_DELPI_ACCESS,
    DASHBOARD_LMPS_NC_WRITE,
]
TRANSFORMOMETRO_VIEW = "transformometro.view"
ENGINEERING_TRANSFORMOMETRO_ACCESS = [
    *ENGINEERING_LMP_ACCESS,
    TRANSFORMOMETRO_VIEW,
]

MAINTENANCE_VIEW = "maintenance.view"
MINI_APPLICATORS_ACCESS = [
    API_DELPI_ACCESS,
    MAINTENANCE_VIEW,
    DASHBOARD_ENGINEERING_VIEW,
]
SYSTEM_METADATA_ACCESS = [API_DELPI_ACCESS_FULL, API_DELPI_SYSTEM]
DATA_SQL_ACCESS = [API_DELPI_ACCESS_FULL, API_DELPI_DATA]

AUDIT_5S_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    AUDITORIA_5S_VIEW_FILIAL_01,
    AUDITORIA_5S_VIEW_FILIAL_02,
    AUDITORIA_5S_AUDIT_FILIAL_01,
    AUDITORIA_5S_AUDIT_FILIAL_02,
    AUDITORIA_5S_ADMIN_FILIAL_01,
    AUDITORIA_5S_ADMIN_FILIAL_02,
]
AUDIT_5S_WRITE_PERMISSIONS = AUDIT_5S_READ_PERMISSIONS
AUDIT_5S_ADMIN_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    AUDITORIA_5S_ADMIN_FILIAL_01,
    AUDITORIA_5S_ADMIN_FILIAL_02,
]
AUDIT_5S_BRANCH_ADMIN_PERMS = {
    "01": AUDITORIA_5S_ADMIN_FILIAL_01,
    "02": AUDITORIA_5S_ADMIN_FILIAL_02,
}

KAIZEN_RECORDS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    DASHBOARD_QUALITY_VIEW,
    KAIZOMETRO_VIEW,
    KAIZOMETRO_MANAGE,
    KAIZOMETRO_BRANCH_01,
    KAIZOMETRO_BRANCH_02,
    CADASTRO_KAIZEN_VIEW,  # legado (janela de migração)
    CADASTRO_KAIZEN_MANAGE,  # legado
]
KAIZEN_RECORDS_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    KAIZOMETRO_MANAGE,
    CADASTRO_KAIZEN_MANAGE,  # legado
]

QUALITY_ACTION_PLANS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    API_DELPI_QUALITY_ACTION_PLANS_READ,
    DASHBOARD_QUALITY_VIEW,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_READ,
    QUALITY_ACTION_PLANS_MANAGE,
]
QUALITY_ACTION_PLANS_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]
QUALITY_ACTION_PLANS_CLOSE_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_CLOSE,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]
QUALITY_ACTION_PLANS_VALIDATE_EFFECTIVENESS_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_VALIDATE_EFFECTIVENESS,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]
QUALITY_ACTION_PLANS_ADMIN_DISPATCH_PERMISSIONS = [
    API_DELPI_ACCESS,
    API_DELPI_QUALITY_ACCESS,
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_MANAGE,
    QUALITY_ACTION_PLANS_ADMIN,
]

SCHEDULING_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES,
    CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC,
]
SCHEDULING_MANAGE_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
]
SCHEDULING_APPROVE_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC,
]
SCHEDULING_BRANCH_VIEW_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC,
}
SCHEDULING_BRANCH_MANAGE_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
}
SCHEDULING_BRANCH_APPROVE_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_APPROVE_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_APPROVE_FILIAL_SC,
}

EFICIENCIA_FABRIL_ACCESS = [
    API_DELPI_ACCESS,
    EFICIENCIA_FABRIL_VIEW,
    EFICIENCIA_FABRIL_VIEW_FILIAL_SC,
    EFICIENCIA_FABRIL_VIEW_FILIAL_ES,
    DASHBOARD_PRODUCTION_VIEW,
]

# Portal Comercial: access | manage. Plugin irmão PVA: .access | .admin.
# api-delpi.access NÃO concede acesso a pedidos/carteira (evita unrestricted indevido).
PEDIDOS_VENDA_ABERTOS_PERMISSIONS = [
    PEDIDOS_VENDA_ABERTOS_ACCESS,
    PEDIDOS_VENDA_ABERTOS_ADMIN,
    COMMERCIAL_ACCESS,
    COMMERCIAL_MANAGE,
]

# Admin de carteira / escopo irrestrito: somente commercial.manage.
PEDIDOS_VENDA_ABERTOS_ADMIN_PERMISSIONS = [
    COMMERCIAL_MANAGE,
]

FINANCEIRO_CENTRO_CUSTO_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_VIEW,
]

FINANCEIRO_CENTRO_CUSTO_EXPORT_PERMISSIONS = [
    API_DELPI_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_ACCESS,
    FINANCEIRO_CENTRO_CUSTO_VIEW,
    FINANCEIRO_CENTRO_CUSTO_EXPORT,
]

FINANCEIRO_INADIMPLENCIA_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    FINANCEIRO_INADIMPLENCIA_ACCESS,
    FINANCEIRO_INADIMPLENCIA_VIEW,
]

CONTROLE_RETRABALHO_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    CONTROLE_RETRABALHO_ACCESS,
    CONTROLE_RETRABALHO_VIEW,
    CONTROLE_RETRABALHO_VIEW_FILIAL_SC,
    CONTROLE_RETRABALHO_VIEW_FILIAL_ES,
]

CONTROLE_RETRABALHO_BRANCH_VIEW_PERMS = {
    "01": CONTROLE_RETRABALHO_VIEW_FILIAL_SC,
    "02": CONTROLE_RETRABALHO_VIEW_FILIAL_ES,
}

SCRAP_MONITORING_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    SCRAP_MONITORING_ACCESS,
    SCRAP_MONITORING_VIEW,
    SCRAP_MONITORING_VIEW_FILIAL_SC,
    SCRAP_MONITORING_VIEW_FILIAL_ES,
]

SCRAP_MONITORING_BRANCH_VIEW_PERMS = {
    "01": SCRAP_MONITORING_VIEW_FILIAL_SC,
    "02": SCRAP_MONITORING_VIEW_FILIAL_ES,
}

PRODUCTION_APPOINTMENTS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    PRODUCTION_APPOINTMENTS_ACCESS,
    PRODUCTION_APPOINTMENTS_VIEW,
    PRODUCTION_APPOINTMENTS_VIEW_FILIAL_SC,
    PRODUCTION_APPOINTMENTS_VIEW_FILIAL_ES,
]

PRODUCTION_APPOINTMENTS_BRANCH_VIEW_PERMS = {
    "01": PRODUCTION_APPOINTMENTS_VIEW_FILIAL_SC,
    "02": PRODUCTION_APPOINTMENTS_VIEW_FILIAL_ES,
}

SAFETY_STOCK_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    SAFETY_STOCK_ACCESS,
    SAFETY_STOCK_VIEW_FILIAL_SC,
    SAFETY_STOCK_VIEW_FILIAL_ES,
]

SAFETY_STOCK_BRANCH_VIEW_PERMS = {
    "01": SAFETY_STOCK_VIEW_FILIAL_SC,
    "02": SAFETY_STOCK_VIEW_FILIAL_ES,
}

THIRD_PARTY_MATERIALS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    THIRD_PARTY_MATERIALS_ACCESS,
    THIRD_PARTY_MATERIALS_VIEW_FILIAL_SC,
    THIRD_PARTY_MATERIALS_VIEW_FILIAL_ES,
]

THIRD_PARTY_MATERIALS_EXPORT_PERMISSIONS = [
    *THIRD_PARTY_MATERIALS_READ_PERMISSIONS,
    THIRD_PARTY_MATERIALS_EXPORT,
]

THIRD_PARTY_MATERIALS_BRANCH_VIEW_PERMS = {
    "01": THIRD_PARTY_MATERIALS_VIEW_FILIAL_SC,
    "02": THIRD_PARTY_MATERIALS_VIEW_FILIAL_ES,
}

REPORTS_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    REPORTS_VIEW,
    REPORTS_MANAGE,
    REPORTS_VIEW_FILIAL_SC,
    REPORTS_VIEW_FILIAL_ES,
    REPORTS_MANAGE_FILIAL_SC,
    REPORTS_MANAGE_FILIAL_ES,
]

# Leitura mínima para a tela operacional de acompanhamentos (sem admin UI).
REPORTS_FOLLOW_UP_READ_PERMISSIONS = [
    *REPORTS_READ_PERMISSIONS,
    REPORTS_NOTES_MANAGE,
]

REPORTS_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    REPORTS_MANAGE,
    REPORTS_MANAGE_FILIAL_SC,
    REPORTS_MANAGE_FILIAL_ES,
]

REPORTS_NOTES_WRITE_PERMISSIONS = [
    API_DELPI_ACCESS,
    REPORTS_NOTES_MANAGE,
    REPORTS_MANAGE,
    REPORTS_MANAGE_FILIAL_SC,
    REPORTS_MANAGE_FILIAL_ES,
]

REPORTS_BRANCH_VIEW_PERMS = {
    "01": REPORTS_VIEW_FILIAL_SC,
    "02": REPORTS_VIEW_FILIAL_ES,
}

REPORTS_BRANCH_MANAGE_PERMS = {
    "01": REPORTS_MANAGE_FILIAL_SC,
    "02": REPORTS_MANAGE_FILIAL_ES,
}

INSPECOES_ENTRADA_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    INSPECOES_ENTRADA_VIEW,
    INSPECOES_ENTRADA_VIEW_FILIAL_01,
    INSPECOES_ENTRADA_VIEW_FILIAL_02,
]

INSPECOES_ENTRADA_BRANCH_VIEW_PERMS = {
    "01": INSPECOES_ENTRADA_VIEW_FILIAL_01,
    "02": INSPECOES_ENTRADA_VIEW_FILIAL_02,
}

INSPECOES_PROCESSO_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    INSPECOES_PROCESSO_VIEW,
    INSPECOES_PROCESSO_VIEW_FILIAL_01,
    INSPECOES_PROCESSO_VIEW_FILIAL_02,
]

INSPECOES_PROCESSO_BRANCH_VIEW_PERMS = {
    "01": INSPECOES_PROCESSO_VIEW_FILIAL_01,
    "02": INSPECOES_PROCESSO_VIEW_FILIAL_02,
}

CULTURA_DELPI_READ_PERMISSIONS = [
    CULTURA_DELPI_VIEW,
    CULTURA_DELPI_MANAGE,
]

CULTURA_DELPI_WRITE_PERMISSIONS = [
    CULTURA_DELPI_MANAGE,
]

CANAL_DENUNCIA_SUBMIT_PERMISSIONS = [
    CANAL_DENUNCIA_ACCESS,
]

GUIAS_PROCEDIMENTOS_READ_PERMISSIONS = [
    GUIAS_PROCEDIMENTOS_ACCESS,
    GUIAS_PROCEDIMENTOS_MANAGE,
]

GUIAS_PROCEDIMENTOS_WRITE_PERMISSIONS = [
    GUIAS_PROCEDIMENTOS_MANAGE,
]

MURAL_ACESSOS_READ_PERMISSIONS = [
    MURAL_ACESSOS_ACCESS,
    MURAL_ACESSOS_MANAGE,
]

MURAL_ACESSOS_WRITE_PERMISSIONS = [
    MURAL_ACESSOS_MANAGE,
]

LANCAMENTO_NOTAS_FISCAIS_BRANCH_VIEW_PERMS = {
    "01": LANCAMENTO_NOTAS_FISCAIS_VIEW_FILIAL_01,
    "02": LANCAMENTO_NOTAS_FISCAIS_VIEW_FILIAL_02,
}

LANCAMENTO_NOTAS_FISCAIS_READ_PERMISSIONS = [
    LANCAMENTO_NOTAS_FISCAIS_ACCESS,
    LANCAMENTO_NOTAS_FISCAIS_CREATE,
    LANCAMENTO_NOTAS_FISCAIS_VIEW,
    LANCAMENTO_NOTAS_FISCAIS_VIEW_FILIAL_01,
    LANCAMENTO_NOTAS_FISCAIS_VIEW_FILIAL_02,
    LANCAMENTO_NOTAS_FISCAIS_PROCESS,
    LANCAMENTO_NOTAS_FISCAIS_MANAGE,
]

LANCAMENTO_NOTAS_FISCAIS_CREATE_PERMISSIONS = [
    LANCAMENTO_NOTAS_FISCAIS_CREATE,
    LANCAMENTO_NOTAS_FISCAIS_PROCESS,
    LANCAMENTO_NOTAS_FISCAIS_MANAGE,
]

LANCAMENTO_NOTAS_FISCAIS_PROCESS_PERMISSIONS = [
    LANCAMENTO_NOTAS_FISCAIS_PROCESS,
    LANCAMENTO_NOTAS_FISCAIS_MANAGE,
]

INVOICE_ISSUANCE_BRANCH_VIEW_PERMS = {
    "01": INVOICE_ISSUANCE_VIEW_FILIAL_01,
    "02": INVOICE_ISSUANCE_VIEW_FILIAL_02,
}

INVOICE_ISSUANCE_READ_PERMISSIONS = [
    INVOICE_ISSUANCE_ACCESS,
    INVOICE_ISSUANCE_CREATE,
    INVOICE_ISSUANCE_VIEW,
    INVOICE_ISSUANCE_VIEW_FILIAL_01,
    INVOICE_ISSUANCE_VIEW_FILIAL_02,
    INVOICE_ISSUANCE_PROCESS,
    INVOICE_ISSUANCE_MANAGE,
]

INVOICE_ISSUANCE_CREATE_PERMISSIONS = [
    INVOICE_ISSUANCE_CREATE,
    INVOICE_ISSUANCE_PROCESS,
    INVOICE_ISSUANCE_MANAGE,
]

INVOICE_ISSUANCE_PROCESS_PERMISSIONS = [
    INVOICE_ISSUANCE_PROCESS,
    INVOICE_ISSUANCE_MANAGE,
]

QUALITY_LABELS_READ_PERMISSIONS = [
    QUALITY_LABELS_VIEW,
    QUALITY_LABELS_WRITE,
]

QUALITY_LABELS_WRITE_PERMISSIONS = [
    QUALITY_LABELS_WRITE,
]

PROPOSTAS_COMERCIAIS_ACCESS = [
    API_DELPI_ACCESS,
    PROPOSTAS_COMERCIAIS_VIEW,
    DASHBOARD_COMMERCIAL_VIEW,
    COMMERCIAL_ACCESS,
]

PLANEJAMENTO_ORCAMENTARIO_ACCESS_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_ACCESS,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
    PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_VIEW,
    PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_MANAGE,
]
PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_VIEW_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_ACCESS,
    PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_VIEW,
    PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_MANAGE,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_MANAGE_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_GUIDANCE_MANAGE,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_SCOPES_MANAGE_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_SCOPES_MANAGE,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_ADMIN_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_CAPEX_SUBMIT_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_CAPEX_SUBMIT,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_CAPEX_APPROVE_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_CAPEX_APPROVE,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_CAPEX_CONSOLIDATION_VIEW_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_CAPEX_CONSOLIDATION_VIEW,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
    # Gestor comum consulta consolidação limitada ao próprio escopo (use case).
    PLANEJAMENTO_ORCAMENTARIO_ACCESS,
    PLANEJAMENTO_ORCAMENTARIO_CAPEX_SUBMIT,
]
PLANEJAMENTO_ORCAMENTARIO_CAPEX_EXPORT_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_CAPEX_EXPORT,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_VIEW_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_VIEW,
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_EDIT,
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_SUBMIT,
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_APPROVE,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
    PLANEJAMENTO_ORCAMENTARIO_ACCESS,
]
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_EDIT_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_EDIT,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_SUBMIT_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_SUBMIT,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]
PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_APPROVE_PERMISSIONS = [
    PLANEJAMENTO_ORCAMENTARIO_PERSONNEL_APPROVE,
    PLANEJAMENTO_ORCAMENTARIO_ADMIN,
]

API_DELPI_CONSOLE_VIEW = "api-delpi-console.view"
CONSOLE_SMOKE_ACCESS = [API_DELPI_ACCESS, API_DELPI_CONSOLE_VIEW]
SQL_HEALTH_ACCESS = [
    API_DELPI_ACCESS_FULL,
    API_DELPI_SYSTEM,
    API_DELPI_CONSOLE_VIEW,
    API_DELPI_ACCESS,
]
OBSERVABILITY_ACCESS = SQL_HEALTH_ACCESS
