"""Códigos RBAC usados pelos decorators ``delpi_auth.authorization`` na api-delpi."""

from __future__ import annotations

# --- api-delpi (módulo) ---
API_DELPI_ACCESS = "api-delpi.access"
API_DELPI_ACCESS_FULL = "api-delpi.access.full"
API_DELPI_SYSTEM = "api-delpi.system"
API_DELPI_DATA = "api-delpi.data"
API_DELPI_QUALITY_ACCESS = "api-delpi.quality.access"

# --- dashboards KPI (MFE) ---
DASHBOARD_FINANCIAL_VIEW = "dashboard-financial.view"
DASHBOARD_COMMERCIAL_VIEW = "dashboard-commercial.view"
DASHBOARD_PRODUCTION_VIEW = "dashboard-production.view"
DASHBOARD_SUPPLIES_VIEW = "dashboard-supplies.view"
DASHBOARD_QUALITY_VIEW = "dashboard-quality.view"
DASHBOARD_HR_VIEW = "dashboard-hr.view"
DASHBOARD_ENGINEERING_VIEW = "dashboard-engineering.view"
DASHBOARD_LMPS_VIEW = "dashboard-lmps.view"

# --- central agendamento ---
CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES = "central-agendamento.view.filial-es"
CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC = "central-agendamento.view.filial-sc"
CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES = "central-agendamento.manage.filial-es"
CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC = "central-agendamento.manage.filial-sc"

# --- eficiência fabril ---
EFICIENCIA_FABRIL_VIEW = "eficiencia-fabril.view"
EFICIENCIA_FABRIL_VIEW_FILIAL_SC = "eficiencia-fabril.view.filial-sc"
EFICIENCIA_FABRIL_VIEW_FILIAL_ES = "eficiencia-fabril.view.filial-es"

# --- conjuntos usados em @require_any_permission ---
KPI_FINANCIAL_ACCESS = [API_DELPI_ACCESS, DASHBOARD_FINANCIAL_VIEW]
KPI_COMMERCIAL_ACCESS = [API_DELPI_ACCESS, DASHBOARD_COMMERCIAL_VIEW]
KPI_PRODUCTION_ACCESS = [API_DELPI_ACCESS, DASHBOARD_PRODUCTION_VIEW]
KPI_SUPPLIES_ACCESS = [API_DELPI_ACCESS, DASHBOARD_SUPPLIES_VIEW]
KPI_QUALITY_ACCESS = [API_DELPI_QUALITY_ACCESS, DASHBOARD_QUALITY_VIEW]
KPI_HR_ACCESS = [API_DELPI_ACCESS, DASHBOARD_HR_VIEW]
ENGINEERING_LMP_ACCESS = [
    API_DELPI_ACCESS,
    DASHBOARD_ENGINEERING_VIEW,
    DASHBOARD_LMPS_VIEW,
]
SYSTEM_METADATA_ACCESS = [API_DELPI_ACCESS_FULL, API_DELPI_SYSTEM]
DATA_SQL_ACCESS = [API_DELPI_ACCESS_FULL, API_DELPI_DATA]

SCHEDULING_READ_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES,
    CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
]
SCHEDULING_MANAGE_PERMISSIONS = [
    API_DELPI_ACCESS,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
]
SCHEDULING_BRANCH_VIEW_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_VIEW_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_VIEW_FILIAL_SC,
}
SCHEDULING_BRANCH_MANAGE_PERMS = {
    "ES": CENTRAL_AGENDAMENTO_MANAGE_FILIAL_ES,
    "SC": CENTRAL_AGENDAMENTO_MANAGE_FILIAL_SC,
}

EFICIENCIA_FABRIL_ACCESS = [
    API_DELPI_ACCESS,
    EFICIENCIA_FABRIL_VIEW,
    EFICIENCIA_FABRIL_VIEW_FILIAL_SC,
    EFICIENCIA_FABRIL_VIEW_FILIAL_ES,
    DASHBOARD_PRODUCTION_VIEW,
]

API_DELPI_CONSOLE_VIEW = "api-delpi-console.view"
CONSOLE_SMOKE_ACCESS = [API_DELPI_ACCESS, API_DELPI_CONSOLE_VIEW]
SQL_HEALTH_ACCESS = [
    API_DELPI_ACCESS_FULL,
    API_DELPI_SYSTEM,
    API_DELPI_CONSOLE_VIEW,
    API_DELPI_ACCESS,
]
OBSERVABILITY_ACCESS = SQL_HEALTH_ACCESS
