export const copy = {
  productName: "Portal PCP",
  railAria: "Subplugins do Portal PCP",
  home: {
    title: "Gestão à vista",
    kicker: "Portal PCP",
    subtitle: "O que a fábrica precisa de atenção agora — OTD, faturamento do dia e fila de OPs atrasadas.",
    heroLead: "Planejamento e controle da produção, com exceções na frente.",
    loading: "Montando a gestão à vista…",
    loadingHint: "Consultando OTD, pedidos a faturar e ordens PCP no TOTVS.",
    loadError: "Não foi possível carregar o painel inicial.",
    refresh: "Atualizar",
    otdTitle: "OTD",
    otdHint: "On-time delivery da filial no mês corrente (OPs mãe sequencia 001, TOTVS SC2).",
    otdChart: "OTD no mês",
    otdEmptyChart: "Sem pontos de OTD no mês corrente.",
    otdLateOps: (n: number) => `${n} OP${n === 1 ? "" : "s"} mãe atrasada${n === 1 ? "" : "s"} no OTD`,
    volumeTitle: "Volume de produção",
    volumeHint:
      "Quantidade produzida de PAs por dia (última operação do roteiro — entrada em estoque), mesma regra do apontamento.",
    volumeSeries: "Produzida",
    volumeSeriesPrior: "Ano anterior",
    volumeEmpty: "Sem produção apontada de PA no período.",
    volumeTotal: (qty: string) => `Total no período: ${qty}`,
    volumePriorTotal: (qty: string) => `Ano anterior: ${qty}`,
    volumeWeekdayAverage: (qty: string, days: number) =>
      `Média diária (dias úteis): ${qty} · ${days} dia${days === 1 ? "" : "s"}`,
    volumeViewAria: "Visualização do volume de produção",
    volumeViewDay: "Dia",
    volumeViewMonthYoy: "Mês × ano ant.",
    delayedTitle: "OPs em atraso",
    delayedHint: "Ordens abertas atrasadas na view PCP, só produtos cujo código começa com 8 ou 9.",
    delayedListTitle: "Fila de atraso",
    delayedListHint:
      "Produto, OP e saldo pendente (códigos 8… e 9…). Clique para rastrear a OP na Carga máquina.",
    delayedEmpty: "Nenhuma OP atrasada neste recorte.",
    billingDueTitle: "A faturar até hoje",
    billingDueHint:
      "Pedidos com data de entrega até hoje. Check amarelo = coberto por estoque; verde = faturado no TOTVS hoje.",
    billingDueEmpty: "Nenhum pedido com entrega até hoje nesta filial.",
    billingDueSummary: (pending: number, stock: number, invoiced: number) =>
      `${pending} pendente${pending === 1 ? "" : "s"} · ${stock} com estoque · ${invoiced} faturado${invoiced === 1 ? "" : "s"}`,
    billingDueProgressLabel: (pct: number) => `${pct}% faturado`,
    billingDueProgressAria: (pct: number, invoiced: number, total: number) =>
      `Progresso do faturamento do dia: ${pct} por cento — ${invoiced} de ${total} linha${total === 1 ? "" : "s"} faturada${invoiced === 1 ? "" : "s"}.`,
    billingDueOrder: "Pedido",
    billingDueQty: "Saldo",
    billingDueCheckStock: "Coberto por estoque — pronto para faturar",
    billingDueCheckInvoiced: "Faturado hoje",
    billingDueCheckPending: "Sem cobertura de estoque",
    billingDueDetail: {
      title: "Pedido a faturar",
      customerOrder: "Pedido do cliente",
      order: "Pedido",
      due: "Entrega",
      dispatch: "Despacho",
      invoice: "Faturamento",
      ordered: "Quantidade",
      delivered: "Entregue",
      open: "Saldo",
      productStock: "Estoque do produto",
      stock: "Estoque alocado",
      uncovered: "Sem cobertura",
      machineLoadLink: "Abrir na carga máquina",
      demandLink: "Abrir na demanda",
      close: "Fechar",
    },
    qty: "Qtd.",
    pending: "Saldo",
    daysLate: "Atraso",
  },
  machineLoad: {
    title: "Carga máquina",
    subtitle: "Sequenciamento das operações alocadas, uma aba por centro de trabalho.",
    loading: "Montando a fila dos centros de trabalho…",
    loadingHint: "Consultando operações alocadas no TOTVS.",
    loadError: "Não foi possível carregar a carga máquina.",
    refresh: "Atualizar",
    refreshConfirmTitle: "Atualizar carga máquina?",
    refreshConfirmMessage:
      "A fila congelada e a sequência manual deste período serão substituídas pelos dados atuais do TOTVS.",
    refreshConfirmAction: "Atualizar agora",
    refreshCancel: "Cancelar",
    refreshBusy: "Atualizando a partir do TOTVS…",
    refreshedAt: (when: string) => `Congelada em ${when}`,
    sequenceUpdatedAt: (when: string) => `Sequência ajustada em ${when}`,
    sequenceHint: "Arraste as linhas para reordenar · Ctrl+Z desfaz · Ctrl+Shift+Z refaz",
    sequenceSaving: "Salvando sequência…",
    sequenceSaved: "Sequência salva.",
    sequenceError: "Não foi possível salvar a sequência.",
    dragHandle: "Reordenar",
    operatorLink: "Link do operador",
    operatorLinkHint:
      "Copia o link público do cockpit desta filial para o operador acompanhar a fila em tempo real.",
    operatorLinkCopied: "Link copiado!",
    operatorLinkError: "Não foi possível copiar o link.",
    periodLabel: "Entrega do PA",
    periodFrom: "De",
    periodTo: "até",
    periodApply: "Aplicar",
    periodReset: "Voltar ao padrão",
    periodHint: (from: string, to: string) =>
      `Fila puxada por entrega do PA: ${from} até ${to}. «De/até» filtra o que já está congelado — use Atualizar para puxar outro horizonte do TOTVS.`,
    periodHintOpenStart: (to: string) =>
      `Fila puxada por entrega do PA até ${to}, incluindo o que está atrasado. «De/até» filtra o que já está congelado — use Atualizar para puxar outro horizonte do TOTVS.`,
    periodMissingDueDate: (n: number) =>
      `${n} operaç${n === 1 ? "ão" : "ões"} sem data de entrega do PA — verifique o vínculo com a OP mãe no TOTVS.`,
    optimizeDelivery: {
      label: "Otimizar por entrega",
      hint: "Reordena a fila de todos os centros pela data de entrega do PA, sem ultrapassar operação já iniciada.",
      confirmTitle: "Reordenar a fila pela entrega do PA?",
      confirmMessage:
        "Todos os centros de trabalho desta filial são resequenciados da entrega mais próxima para a mais distante. Operações já iniciadas continuam onde estão, e conjuntos fora da programação não voltam à fila.",
      confirmAction: "Otimizar fila",
      cancel: "Cancelar",
      busy: "Otimizando a fila…",
      error: "Não foi possível otimizar a fila pela entrega do PA.",
    },
    hideFinished: {
      show: "Ocultar finalizadas",
      hide: "Mostrar finalizadas",
      hintShow: "Esconde da vista as operações já apontadas. Elas continuam na fila congelada.",
      hintHide: "Volta a exibir as operações já apontadas nesta fila.",
      withCount: (count: number) =>
        count === 1 ? "Ocultar finalizadas (1)" : `Ocultar finalizadas (${count})`,
      showingHidden: (count: number) =>
        count === 1 ? "Mostrar finalizadas (1)" : `Mostrar finalizadas (${count})`,
      empty: "Todas as operações deste centro já foram apontadas.",
      reorderDisabled: "Desative «Ocultar finalizadas» para reordenar a fila.",
    },
    tabsAria: "Centros de trabalho",
    emptyCenters: "Nenhuma operação alocada no período.",
    emptyCentersHint: "Ajuste o recorte de entrega ou atualize a carga máquina a partir do TOTVS.",
    emptyOperations: "Nenhuma operação alocada neste centro de trabalho no período.",
    summary: (centers: number, operations: number) =>
      `${centers} centro${centers === 1 ? "" : "s"} · ${operations} operaç${operations === 1 ? "ão" : "ões"}`,
    inProductionSummary: (running: number) =>
      `${running} em produção agora`,
    locate: {
      label: "Rastreio",
      placeholder: "Conjunto (OP) ou produto (PA)…",
      search: "Buscar",
      searching: "Rastreando…",
      clear: "Limpar rastreio",
      close: "Fechar",
      emptyQuery: "Informe o número do conjunto (OP) ou o código do produto (PA).",
      panelTitle: "Previsão de produção",
      /** Conjunto = C2_NUM (6 dígitos): todas as OPs que começam com esse número. */
      journeyConjunto: (c2Num: string) => `Conjunto ${c2Num}`,
      /** Código do PA = produto do conjunto, não o conjunto em si. */
      journeyProduct: (pa: string) => `Produto ${pa}`,
      stops: (n: number) => `${n} parad${n === 1 ? "a" : "as"}`,
      due: (when: string) => `Entrega ${when}`,
      position: (pos: number, size: number) => `Posição ${pos}/${size}`,
      schedule: "Programada",
      goToQueue: "Ir à fila",
      progressLabel: "Progresso",
      hint: "Conjunto = C2_NUM (6 primeiros dígitos da OP). Ex.: 10840401003 rastreia todas as OPs 108404…. Produto (PA) lista os conjuntos daquele acabado.",
    },
    rowActions: {
      menuAria: "Ações da operação",
      traceConjunto: "Rastrear produção do conjunto",
      traceConjuntoDisabled: "Rastrear conjunto (sem OP neste registro)",
      traceConjuntoTitle: (c2Num: string) => `Produção do conjunto ${c2Num}`,
      traceConjuntoLead: (pa: string | null) =>
        pa
          ? `Todas as ordens do mesmo C2_NUM (prefixo de 6 dígitos) na fila do período. Produto do conjunto: ${pa}.`
          : "Todas as ordens do mesmo C2_NUM (prefixo de 6 dígitos) na fila do período.",
      prioritizeConjunto: "Priorizar conjunto",
      prioritizeConjuntoDisabled: "Priorizar conjunto (sem OP neste registro)",
      prioritizeConfirmTitle: (c2Num: string) => `Priorizar conjunto ${c2Num}?`,
      prioritizeConfirmMessage:
        "Todas as OPs deste conjunto vão para o topo da fila nos seus centros de trabalho. Operações já iniciadas continuam à frente — o conjunto entra logo depois delas.",
      prioritizeConfirmAction: "Priorizar",
      prioritizeCancel: "Cancelar",
      prioritizeError: "Não foi possível priorizar o conjunto.",
      withdrawConjunto: "Retirar conjunto da programação",
      withdrawConjuntoDisabled: "Retirar conjunto (sem OP neste registro)",
      withdrawConfirmTitle: (c2Num: string) => `Retirar o conjunto ${c2Num} da programação?`,
      withdrawConfirmMessage:
        "Todas as OPs deste conjunto saem da fila em todos os centros de trabalho e deixam de aparecer no cockpit do operador. Você pode devolvê-las depois pelo botão «Fora da programação».",
      withdrawConfirmAction: "Retirar da programação",
      withdrawCancel: "Cancelar",
      withdrawError: "Não foi possível retirar o conjunto da programação.",
      restoreError: "Não foi possível devolver o conjunto à fila.",
      transferConjunto: "Enviar conjunto para outro centro de trabalho",
      transferConjuntoDisabled: "Enviar conjunto (sem OP neste registro)",
      transferOperation: "Enviar item para outro centro de trabalho",
      transferOperationDisabled: "Enviar item (sem OP neste registro)",
      transferError: "Não foi possível transferir para outro centro de trabalho.",
    },
    transfer: {
      modalTitle: "Enviar item para outro centro de trabalho",
      modalTitleConjunto: "Enviar conjunto para outro centro de trabalho",
      lead: "A operação sai da fila do centro atual e entra no fim da fila do destino. Depois é só reordenar ou priorizar por lá.",
      leadConjunto:
        "Só as OPs deste conjunto que estão neste centro de trabalho vão para o destino. OPs do mesmo conjunto em outros CTs permanecem onde estão.",
      operationSummary: (order: string, operation: string) => `OP ${order} · operação ${operation}`,
      conjuntoSummary: (conjunto: string, center: string) =>
        `Conjunto ${conjunto} · apenas no centro ${center}`,
      currentCenter: (center: string) => `Centro atual: ${center}`,
      selectLabel: "Centro de trabalho de destino",
      selectPlaceholder: "Escolha o centro de destino",
      selectHint: "A lista traz os centros com fila neste período.",
      noTargets: "Não há outro centro de trabalho com fila neste período.",
      confirmAction: "Enviar",
      cancel: "Cancelar",
      originBadge: (center: string) => `veio de ${center}`,
      originBadgeTitle: (center: string) => `Operação transferida do centro ${center}`,
    },
    withdrawn: {
      openButton: (count: number) =>
        count === 1 ? "Fora da programação (1)" : `Fora da programação (${count})`,
      openButtonEmpty: "Fora da programação",
      modalTitle: "Conjuntos fora da programação",
      lead: "Estes conjuntos não aparecem na fila do PCP nem no cockpit do operador. Devolver recoloca cada OP na posição original.",
      empty: "Nenhum conjunto fora da programação neste período.",
      conjuntoLabel: (c2Num: string) => `Conjunto ${c2Num}`,
      productLabel: (pa: string) => `Produto ${pa}`,
      operations: (count: number) =>
        count === 1 ? "1 operação" : `${count} operações`,
      centers: (centers: string[]) => centers.join(", "),
      withdrawnBy: (who: string | null, when: string | null) => {
        if (who && when) return `Retirado por ${who} em ${when}`;
        if (who) return `Retirado por ${who}`;
        if (when) return `Retirado em ${when}`;
        return "Retirado da programação";
      },
      restoreAction: "Devolver à fila",
      locateBadge: "Fora da programação",
    },
    manualTool: "Mão de obra",
    columns: {
      schedule: "Programação",
      productionOrder: "OP",
      product: "Produto",
      quantity: "Quantidade",
      tool: "Ferramenta",
      operation: "Operação",
      paCode: "PA",
      paDueDate: "Entrega do PA",
      status: "Situação",
    },
    status: {
      inProgress: "Em produção",
      started: "Já apontada",
      notStarted: "Não iniciada",
      startedAt: (time: string) => `Início ${time}`,
      operatorPrefix: "Operador",
      inProductionTabAria: (center: string, running: number) =>
        `${center}: ${running} operaç${running === 1 ? "ão" : "ões"} em produção`,
    },
  },
  kpi: {
    goalPrefix: "Meta",
    iddScorePrefix: "IDD",
    badgesStatus: "Indicadores do cartão",
  },
  problemAnalysis: {
    title: "Análise de problemas",
    subtitle: "Detectores de exceção da fábrica — escolha um cartão para ver os registros.",
    detectorsAria: "Detectores de problema",
    loadError: "Não foi possível carregar a análise de problemas.",
    loading: "Rodando os detectores…",
    loadingHint: "Cruzando estruturas de produto e ordens de produção no TOTVS.",
    itemsLoading: "Carregando registros do detector…",
    refresh: "Atualizar",
    critical: "Crítico",
    attention: "Atenção",
    ok: "Em dia",
    days: "dias",
    order: "Ordem",
    noDetectors: "Nenhum detector disponível para esta filial.",
    detectorCount: (n: number) => (n === 1 ? "1 registro" : `${n} registros`),
    detectorClear: "Nada a corrigir",
    detectorSelect: "Ver registros",
    incompleteSets: {
      empty: "Nenhum conjunto furado neste recorte.",
      emptyHint:
        "Todo conjunto aberto tem uma OP para cada intermediário da estrutura do produto raiz.",
      emptyFilter: (query: string) =>
        `Nenhum produto raiz correspondente a «${query}».`,
      rootFilterLabel: "Produto raiz",
      rootFilterPlaceholder: "Código ou descrição do PA…",
      rootFilterAria: "Filtrar conjuntos pelo produto raiz",
      rootFilterClear: "Limpar filtro",
      checked: (n: number) => `${n} conjunto${n === 1 ? "" : "s"} conferido${n === 1 ? "" : "s"}`,
      breakdown: (missing: number, extra: number) =>
        `${missing} com falta · ${extra} com sobra`,
      issuedFrom: (date: string) => `Emitidos a partir de ${date}`,
      columns: {
        set: "Conjunto",
        root: "Produto raiz",
        due: "Entrega",
        orders: "OPs",
        missing: "Falta",
        extra: "Sobra",
      },
      missingLabel: "Faltando:",
      extraLabel: "Sobrando:",
      componentOrder: (order: string) => `OP ${order}`,
      componentLevel: (level: number) => `nível ${level}`,
      openOrders: (open: number, total: number) => `${open} de ${total} em aberto`,
    },
  },
  demand: {
    title: "Demanda",
    subtitle: "Carteira a entregar — o que a fábrica precisa cobrir, por cliente e data.",
    loading: "Montando a carteira a entregar…",
    loadingHint: "Cruzando saldo de pedidos, estoque e ordens de produção em aberto.",
    loadError: "Não foi possível carregar a demanda.",
    empty: "Nenhuma linha em aberto neste recorte.",
    tableTitle: "Linhas em aberto",
    tableHint: "Clique em uma linha para ver a cobertura por estoque e OP.",
    searchPlaceholder: "Cliente, pedido, pedido do cliente ou produto…",
    searchAria: "Buscar na carteira a entregar",
    filtersAria: "Filtros da demanda",
    dueFromLabel: "Entrega de",
    dueToLabel: "até",
    clearFilters: "Limpar filtros",
    statusAll: "Todos os status",
    exportLabel: "Exportar Excel",
    exportFileName: (branch: string) => `demanda-filial-${branch}`,
    exportSheetTitle: "Demanda",
    exportEmpty: "Não há linhas para exportar em Excel.",
    kpi: {
      sectionAria: "Indicadores da demanda",
      openQuantity: "Saldo a entregar",
      openQuantityHint: "Soma das quantidades ainda não entregues nas linhas do recorte.",
      lateLines: "Linhas atrasadas",
      lateLinesHint: "Entrega prometida já venceu e o saldo continua aberto.",
      uncovered: "Sem cobertura",
      uncoveredHint: "Saldo que não tem estoque nem OP aberta para atender.",
      nextDue: "Próxima entrega",
      nextDueHint: "Data de entrega mais próxima ainda em aberto.",
      lines: (n: number) => `${n} linha${n === 1 ? "" : "s"}`,
      customers: (n: number) => `${n} cliente${n === 1 ? "" : "s"}`,
      products: (n: number) => `${n} produto${n === 1 ? "" : "s"}`,
      none: "—",
    },
    chart: {
      title: "Saldo por semana de entrega",
      hint: "Quanto a fábrica precisa entregar em cada semana; o primeiro grupo é o que já venceu.",
      empty: "Nenhuma linha com data de entrega neste recorte.",
      series: "Saldo",
      lateLabel: "Atrasado",
      weekLabel: (date: string) => `Semana de ${date}`,
    },
    status: {
      late: "Atrasada",
      at_risk: "Em risco",
      covered_by_order: "Coberta por OP",
      covered_by_stock: "Coberta por estoque",
    },
    columns: {
      due: "Entrega",
      customer: "Cliente",
      order: "Pedido",
      product: "Produto",
      open: "Saldo",
      coverage: "Cobertura",
      status: "Situação",
    },
    lateBadge: (days: number) => `${days} dia${days === 1 ? "" : "s"} de atraso`,
    coverage: {
      stock: (qty: string) => `${qty} do estoque`,
      orders: (qty: string, count: number) =>
        `${qty} em ${count} OP${count === 1 ? "" : "s"}`,
      uncovered: (qty: string) => `${qty} sem cobertura`,
      none: "Sem cobertura",
    },
    detail: {
      title: "Linha da demanda",
      orderSection: "Pedido",
      qtySection: "Quantidades",
      coverageSection: "Como o saldo é coberto",
      customer: "Cliente",
      customerOrder: "Pedido do cliente",
      order: "Pedido / item",
      product: "Produto",
      due: "Entrega prometida",
      dispatch: "Data de emissão",
      ordered: "Pedida",
      delivered: "Entregue",
      open: "Saldo aberto",
      stock: "Do estoque",
      coveredByOrders: "Das OPs",
      uncovered: "Ainda sem cobertura",
      coverageTitle: "OPs que atendem este saldo",
      coverageEmpty: "Nenhuma OP aberta alocada a este saldo.",
      coverageOrder: "OP",
      coverageQuantity: "Qtd.",
      coverageDate: "Fim previsto",
      opAfterDue: "depois da entrega",
      reasonLate: (days: number) =>
        `Entrega já venceu há ${days} dia${days === 1 ? "" : "s"}.`,
      reasonStock: "Saldo atendido pelo estoque disponível (FIFO).",
      reasonOrder: (when: string) =>
        when !== "—"
          ? `Saldo atendido por OP(s); a mais tardia termina em ${when}.`
          : "Saldo atendido por ordem(ns) de produção.",
      reasonUncovered: (qty: string) =>
        `Faltam ${qty} sem estoque nem OP alocada — precisa programar.`,
      reasonLateOp: (coverage: string, due: string) =>
        `Há OP alocada, mas o fim previsto (${coverage}) passa da entrega (${due}).`,
      reasonAtRisk: "Cobertura insuficiente para a entrega prometida.",
      machineLoadLink: "Abrir na carga máquina",
      close: "Fechar",
    },
  },
  materials: {
    title: "Materiais",
    subtitle:
      "Excesso e falta de solicitações de matéria-prima em relação ao estoque de segurança, e consulta de ruptura de MP no conjunto do PA.",
    consultEyebrow: "consulta",
    loading: "Cruzando solicitações, saldo, pedidos, empenhos e ESTSEG…",
    loadingHint: "Consultando SC1 de MP, cobertura do produto e estoque de segurança no TOTVS.",
    loadError: "Não foi possível carregar a análise de materiais.",
    issuesAria: "Problemas de solicitações de matéria-prima",
    issueCount: (count: number) =>
      count === 1 ? "1 produto" : `${count} produtos`,
    empty: "Nenhuma solicitação inteira pode ser eliminada neste recorte.",
    shortageEmpty: "Nenhum produto com solicitações abaixo do estoque de segurança neste recorte.",
    tableTitle: "Solicitações em excesso",
    tableHint:
      "Só entram documentos 100% desnecessários depois de cobrir o ESTSEG. Clique para ver a conta.",
    shortageTableTitle: "Solicitações insuficientes",
    shortageTableHint:
      "Produtos cuja cobertura + SC1 em aberto não chega no estoque de segurança. Clique para ver a conta.",
    searchPlaceholder: "Produto, solicitação ou fornecedor…",
    shortageSearchPlaceholder: "Produto…",
    searchAria: "Buscar solicitações",
    exportLabel: "Exportar Excel",
    exportFileName: (branch: string, view: string) =>
      view === "shortage" ? `materiais-insuficientes-filial-${branch}` : `materiais-excesso-filial-${branch}`,
    exportSheetTitle: "Materiais",
    exportEmpty: "Não há linhas para exportar em Excel.",
    columns: {
      request: "Solicitação",
      product: "Produto",
      open: "Aberto",
      openSc1: "SC1 aberta",
      stock: "Estoque",
      safety: "ESTSEG",
      orders: "Pedidos",
      commitments: "Empenhos",
      projected: "Projetado",
      shortage: "Falta",
      required: "Necessidade",
    },
    detail: {
      title: "Solicitação em excesso",
      shortageTitle: "Solicitações insuficientes",
      formula: "Estoque + pedidos − empenhos, comparado ao ESTSEG",
      request: "Solicitação / item",
      product: "Produto",
      supplier: "Fornecedor",
      warehouse: "Armazém",
      unit: "UM",
      required: "Data de necessidade",
      issued: "Emissão",
      open: "Saldo aberto",
      openSc1: "SC1 em aberto",
      stock: "Estoque disponível",
      safety: "Estoque de segurança",
      orders: "Pedidos em aberto",
      commitments: "Empenhos em aberto",
      projected: "Saldo projetado",
      needed: "Necessário da SC1",
      shortage: "Falta após a SC1",
      reason:
        "O saldo + pedidos já cobrem os empenhos e o estoque de segurança. Esta solicitação inteira pode sair do sistema.",
      reasonNeeded: (qty: string) =>
        `O produto ainda precisa de ${qty} em solicitações mais antigas para o ESTSEG; esta ficou inteira sobrando.`,
      shortageReason: (qty: string) =>
        `Mesmo com o saldo, os pedidos e as SC1 em aberto, ainda faltam ${qty} para atingir o estoque de segurança.`,
      close: "Fechar",
    },
    paShortage: {
      title: "Ruptura no conjunto",
      howTitle: "Como funciona",
      searchLabel: "Código do PA",
      searchPlaceholder: "90263114",
      searchAria: "Informar o código do produto acabado",
      submit: "Ver conjunto",
      exampleHint: "Exemplo: 90263114",
      invalidCode: "Informe o código do PA com pelo menos 8 dígitos.",
      loading: "Cruzando estrutura, extrato e OPs mãe…",
      loadingHint: "Lendo a BOM de MP e o extrato saldo + pedidos − empenhos no TOTVS.",
      loadError: "Não foi possível consultar a ruptura de matéria-prima no conjunto.",
      emptyIdle: "Informe o PA para ver quais conjuntos vão faltar matéria-prima.",
      steps: [
        {
          step: 1,
          title: "Você informa o PA",
          body: "O código do produto acabado abre só os conjuntos (OPs mãe) ainda em aberto nesta filial.",
        },
        {
          step: 2,
          title: "Lemos a estrutura (só MP)",
          body: "A explosão vigente da SG1 entra só com matéria-prima. Intermediário não conta como falta de material.",
        },
        {
          step: 3,
          title: "No extrato, o empenho do conjunto decide",
          body: "Saldo 01+98+99 + pedidos − empenhos. Se o saldo projetado fica negativo no empenho daquele conjunto, a OP falta material.",
        },
      ],
      kpiSets: "Conjuntos",
      kpiAtRisk: "Em risco",
      kpiShortMp: "MPs em falta",
      kpiFirst: "1ª ruptura",
      kpiAvailability: "Disponibilidade",
      availabilityCount: (ok: number, total: number) =>
        `${ok} de ${total} ${total === 1 ? "material disponível" : "materiais disponíveis"}`,
      availabilityPercent: (percent: number) => `${percent}% de disponibilidade`,
      chipShortage: "Em risco",
      chipNoCommitment: "Sem empenho",
      chipOk: "Saldo OK",
      chipAll: "Todos",
      chipsAria: "Filtrar matérias-primas do conjunto",
      statusShortage: "Crítico",
      statusNoCommitment: "Sem empenho",
      statusOk: "Ok",
      statusRisk: "Risco da OP",
      materialOk: "Saldo OK",
      materialShortage: "Falta",
      materialNoCommitment: "Sem empenho",
      materialsAria: "Matérias-primas do conjunto",
      opPrefix: "OP",
      columns: {
        code: "Código",
        material: "Matéria-prima",
        needed: "Necessidade",
        available: "Disponível",
        deficit: "Déficit",
        rupture: "Ruptura",
        status: "Status",
      },
      emptyTab: "Nenhuma matéria-prima neste recorte.",
      covered: (count: number) =>
        count === 1 ? "1 MP coberta" : `${count} MPs cobertas`,
      shortageQty: (qty: string, when: string) => `Falta ${qty} em ${when}`,
      consumingOp: (op: string) => `OP consome ${op}`,
      openMaterialExtract: (code: string) => `Ver extrato de ${code}`,
      start: "Início",
      delivery: "Entrega",
      openExtract: "Ver extrato",
      machineLoad: "Carga máquina",
      deliveryMap: "Mapa de entrega",
      safetyStock: "Estoque de segurança",
      exportLabel: "Exportar Excel",
      exportFileName: (branch: string, product: string) =>
        `ruptura-conjunto-${product}-filial-${branch}`,
      exportSheetTitle: "Ruptura no conjunto",
      exportEmpty: "Não há conjuntos para exportar em Excel.",
      ledgerTitle: (code: string) => `Extrato ${code}`,
      ledgerHint: "Saldo inicial → pedidos → empenhos. A linha do conjunto consultado fica em destaque.",
      ledgerDate: "Data",
      ledgerOrigin: "Origem",
      ledgerReference: "Referência",
      ledgerIn: "Entrada",
      ledgerOut: "Saída",
      ledgerBalance: "Saldo",
      close: "Fechar",
    },
  },
  deliveryMap: {
    title: "Mapa de entrega",
    subtitle:
      "Ordens de produção de PA com saldo a entregar, agrupadas pela data prevista de entrega.",
    loading: "Montando o mapa de entrega…",
    loadingHint: "Consultando OPs em aberto no TOTVS e aplicando o agrupamento por entrega.",
    loadError: "Não foi possível carregar o mapa de entrega.",
    empty: "Nenhuma OP de PA com saldo neste recorte.",
    searchPlaceholder: "OP, produto ou observação…",
    searchAria: "Buscar no mapa de entrega",
    searchAction: "Buscar",
    frozenAt: (when: string) => `Congelado em ${when}`,
    orderCount: (count: number) =>
      count === 1 ? "1 OP" : `${count} OPs`,
    sectionCount: (count: number) =>
      count === 1 ? "1 OP" : `${count} OPs`,
    refreshConfirmTitle: "Atualizar mapa de entrega?",
    refreshConfirmBody:
      "A lista será repuxada do TOTVS. MP-OK e Feedback das OPs que continuarem na lista serão preservados.",
    refreshConfirmAction: "Atualizar",
    columns: [
      { key: "op", label: "Número" },
      { key: "product", label: "Produto" },
      { key: "due", label: "Dt. prevista" },
      { key: "planned", label: "Quant. original" },
      { key: "pending", label: "Saldo a entregar" },
      { key: "mpOk", label: "MP-OK" },
      { key: "feedback", label: "Feedback" },
      { key: "obs", label: "Observações" },
    ],
    mpOkAria: (productionOrder: string) => `MP-OK da OP ${productionOrder}`,
    feedbackAria: (productionOrder: string) => `Feedback da OP ${productionOrder}`,
    exportLabel: "Excel",
    exportSheetTitle: "Mapa de entrega",
    exportEmpty: "Não há OPs para exportar em Excel.",
    excelColumns: [
      { key: "numero", label: "NUMERO" },
      { key: "produto", label: "PRODUTO" },
      { key: "due", label: "DT. PREVISTA" },
      { key: "planned", label: "QUANT. ORIGINAL" },
      { key: "pending", label: "SALDO A ENTREGAR" },
      { key: "mpOk", label: "MP-OK" },
      { key: "feedback", label: "FEEDBACK" },
      { key: "obs", label: "OBSERVAÇÕES" },
    ],
    progressAria: (progress: {
      percent: number;
      completed: number;
      in_progress: number;
      total: number;
    }) => {
      if (progress.in_progress > 0) {
        return `Progresso do conjunto: ${progress.percent}% (${progress.completed} de ${progress.total} operações apontadas, ${progress.in_progress} em produção)`;
      }
      return `Progresso do conjunto: ${progress.percent}% (${progress.completed} de ${progress.total} operações apontadas)`;
    },
    publicLink: "Link público",
    publicLinkHint:
      "Copia o link público do mapa de entrega desta filial para consulta somente leitura.",
    publicLinkCopied: "Link copiado!",
    publicLinkError: "Não foi possível copiar o link.",
    drawingOpenLabel: "Ver desenho técnico",
    drawingOpenAria: (productCode: string) => `Ver desenho técnico do produto ${productCode}`,
    drawingModalTitle: (productCode: string) => `Desenho ${productCode}`,
    drawingModalTitleFallback: "Desenho técnico",
    drawingLoading: "Carregando desenho…",
    drawingLoadError: "Desenho não encontrado para este PA.",
  },
  branch: {
    label: "Filial",
    "01": "SC · 01",
    "02": "ES · 02",
  },
  comingSoon: "Em breve",
  table: {
    empty: "Sem linhas relacionadas.",
    loading: "Carregando…",
    sort: (header: string) => `Ordenar por ${header}`,
    help: (header: string) => `Ajuda: ${header}`,
  },
  tableSection: {
    emptyMessage: "Nenhum registro encontrado.",
    loadingMessage: "Carregando…",
    sortByAriaLabel: (header: string) => `Ordenar por ${header}`,
    headerHelpAriaLabel: (header: string) => `Ajuda: ${header}`,
    searchPlaceholder: "Buscar na tabela…",
    searchAriaLabel: "Filtrar registros da tabela",
    searchHelpAriaLabel: "Ajuda: busca na tabela",
    recordsCount: (total: number) => `${total} registro${total === 1 ? "" : "s"}`,
    refreshLoadingTitle: "Atualizando tabela",
    refreshLoadingDescription: "Mantendo os dados visíveis enquanto a consulta é aplicada.",
    initialLoadingTitle: "Carregando registros",
    initialLoadingDescription: "Aguarde enquanto os dados da tabela são obtidos.",
    titleHelpAriaLabel: (title: string) => `Ajuda: ${title}`,
  },
  pagination: {
    navigationAriaLabel: "Paginação",
    pagesAriaLabel: "Páginas",
    previous: "Anterior",
    next: "Próxima",
    info: ({
      rangeStart,
      rangeEnd,
      total,
    }: {
      rangeStart: number;
      rangeEnd: number;
      total: number;
      page: number;
      totalPages: number;
    }) => `${rangeStart}–${rangeEnd} de ${total}`,
    jumpLabel: "Ir para",
    jumpInputAriaLabel: "Número da página",
    jumpError: (reason: string, totalPages: number) =>
      reason === "out_of_range" ? `Informe uma página entre 1 e ${totalPages}.` : "Página inválida.",
    pageSizeLabel: "Por página",
    pageSizeAria: "Registros por página",
  },
} as const;
