/* Controle de materiais de terceiros / beneficiamento (SB6).
   Somente leitura. Relaciona remessa → retornos por FILIAL + PRODUTO + IDENT.
   NÃO usar B6_TPCF nem B6_IDENTB6 como chave.
   NÃO excluir produtos de teste nesta view (ex.: 99999999) — filtro na aplicação.
   Homolog atual: TIPO_PARCEIRO_RETORNO existe; COD/LOJA do retorno NÃO
   (API não seleciona essas colunas). ARMAZEM / MOVIMENTOU_ESTOQUE existem
   na view live e não são consumidos na v1. B1_REFEREN (Ref. Cliente) também
   não está na view live — a API faz LEFT JOIN SB1010 independentemente.

   Doc: api-delpi/docs/api/padroes-totvs/materiais-terceiros-sb6.md
*/
CREATE OR ALTER VIEW dbo.VW_PD3_BENEF_RETORNOS
AS
WITH Remessas AS (
    SELECT
        R.R_E_C_N_O_ AS RECNO_REMESSA,
        LTRIM(RTRIM(R.B6_FILIAL)) AS FILIAL,
        LTRIM(RTRIM(R.B6_IDENT)) AS ID_REMESSA,
        LTRIM(RTRIM(R.B6_DOC)) AS NF_RECEBIMENTO,
        LTRIM(RTRIM(R.B6_SERIE)) AS SERIE_RECEBIMENTO,
        TRY_CONVERT(date, NULLIF(LTRIM(RTRIM(R.B6_EMISSAO)), ''), 112) AS EMISSAO_RECEBIMENTO,
        TRY_CONVERT(date, NULLIF(LTRIM(RTRIM(R.B6_DTDIGIT)), ''), 112) AS DIGITACAO_RECEBIMENTO,
        LTRIM(RTRIM(R.B6_TES)) AS TES_RECEBIMENTO,
        LTRIM(RTRIM(R.B6_PRODUTO)) AS PRODUTO,
        LTRIM(RTRIM(R.B6_TPCF)) AS TIPO_PARCEIRO,
        LTRIM(RTRIM(R.B6_CLIFOR)) AS COD_PARCEIRO,
        LTRIM(RTRIM(R.B6_LOJA)) AS LOJA_PARCEIRO,
        CAST(R.B6_QUANT AS decimal(28, 8)) AS QTD_RECEBIDA,
        CAST(R.B6_SALDO AS decimal(28, 8)) AS SALDO_A_ENTREGAR,
        CAST(R.B6_QUANT AS decimal(28, 8)) - CAST(R.B6_SALDO AS decimal(28, 8)) AS QTD_DEVOLVIDA_TOTAL,
        LTRIM(RTRIM(R.B6_ATEND)) AS IND_ATENDIDO
    FROM SB6010 R WITH (NOLOCK)
    WHERE R.D_E_L_E_T_ = ' '
      AND R.B6_PODER3 = 'R'
      AND R.B6_TIPO = 'D'
),
Retornos AS (
    SELECT
        D.R_E_C_N_O_ AS RECNO_RETORNO,
        LTRIM(RTRIM(D.B6_FILIAL)) AS FILIAL,
        LTRIM(RTRIM(D.B6_PRODUTO)) AS PRODUTO,
        LTRIM(RTRIM(D.B6_IDENT)) AS ID_REMESSA,
        LTRIM(RTRIM(D.B6_DOC)) AS NF_RETORNO,
        LTRIM(RTRIM(D.B6_SERIE)) AS SERIE_RETORNO,
        TRY_CONVERT(date, NULLIF(LTRIM(RTRIM(D.B6_EMISSAO)), ''), 112) AS EMISSAO_RETORNO,
        TRY_CONVERT(date, NULLIF(LTRIM(RTRIM(D.B6_DTDIGIT)), ''), 112) AS DIGITACAO_RETORNO,
        LTRIM(RTRIM(D.B6_TES)) AS TES_RETORNO,
        CAST(D.B6_QUANT AS decimal(28, 8)) AS QTD_RETORNO,
        LTRIM(RTRIM(D.B6_TPCF)) AS TIPO_PARCEIRO_RETORNO
    FROM SB6010 D WITH (NOLOCK)
    WHERE D.D_E_L_E_T_ = ' '
      AND D.B6_PODER3 = 'D'
      AND D.B6_TIPO = 'D'
),
RetornosAgg AS (
    SELECT
        FILIAL,
        PRODUTO,
        ID_REMESSA,
        CAST(SUM(QTD_RETORNO) AS decimal(28, 8)) AS QTD_RETORNOS_SOMADA
    FROM Retornos
    GROUP BY FILIAL, PRODUTO, ID_REMESSA
),
RetornosOrdenados AS (
    SELECT
        RET.*,
        CAST(
            SUM(RET.QTD_RETORNO) OVER (
                PARTITION BY RET.FILIAL, RET.PRODUTO, RET.ID_REMESSA
                ORDER BY RET.EMISSAO_RETORNO, RET.DIGITACAO_RETORNO, RET.RECNO_RETORNO
                ROWS UNBOUNDED PRECEDING
            ) AS decimal(28, 8)
        ) AS QTD_DEVOLVIDA_ACUMULADA
    FROM Retornos RET
)
SELECT
    REM.RECNO_REMESSA,
    REM.FILIAL,
    REM.ID_REMESSA,
    REM.NF_RECEBIMENTO,
    REM.SERIE_RECEBIMENTO,
    REM.EMISSAO_RECEBIMENTO,
    REM.DIGITACAO_RECEBIMENTO,
    REM.TES_RECEBIMENTO,
    REM.PRODUTO,
    LTRIM(RTRIM(SB1.B1_REFEREN)) AS REFERENCIA_CLIENTE,
    LTRIM(RTRIM(SB1.B1_DESC)) AS DESCRICAO_PRODUTO,
    LTRIM(RTRIM(SB1.B1_UM)) AS UNIDADE_MEDIDA,
    LTRIM(RTRIM(SB1.B1_TIPO)) AS TIPO_PRODUTO,
    LTRIM(RTRIM(SB1.B1_GRUPO)) AS GRUPO_PRODUTO,
    CASE
        WHEN LTRIM(RTRIM(ISNULL(SB1.B1_MSBLQL, ''))) = '1' THEN 'S'
        ELSE 'N'
    END AS PRODUTO_BLOQUEADO,
    REM.TIPO_PARCEIRO,
    REM.COD_PARCEIRO,
    REM.LOJA_PARCEIRO,
    LTRIM(RTRIM(SA1.A1_NOME)) AS NOME_PARCEIRO,
    LTRIM(RTRIM(SA1.A1_NREDUZ)) AS NOME_REDUZIDO_PARCEIRO,
    CASE
        WHEN LTRIM(RTRIM(ISNULL(SA1.A1_MSBLQL, ''))) = '1' THEN 'S'
        ELSE 'N'
    END AS PARCEIRO_BLOQUEADO,
    REM.QTD_RECEBIDA,
    REM.QTD_DEVOLVIDA_TOTAL,
    REM.SALDO_A_ENTREGAR,
    CASE
        WHEN ISNULL(AGG.QTD_RETORNOS_SOMADA, 0) = 0 THEN 'SEM RETORNO'
        WHEN REM.SALDO_A_ENTREGAR > 0.000001 THEN 'PARCIAL'
        ELSE 'CONCLUIDO'
    END AS STATUS_REMESSA,
    CASE
        WHEN REM.SALDO_A_ENTREGAR > 0.000001 THEN 'S'
        ELSE 'N'
    END AS POSSUI_SALDO,
    REM.IND_ATENDIDO,
    CAST(ISNULL(AGG.QTD_RETORNOS_SOMADA, 0) AS decimal(28, 8)) AS QTD_RETORNOS_SOMADA,
    CAST(
        REM.QTD_DEVOLVIDA_TOTAL - ISNULL(AGG.QTD_RETORNOS_SOMADA, 0) AS decimal(28, 8)
    ) AS DIFERENCA_CONTROLE,
    ORD.RECNO_RETORNO,
    ORD.NF_RETORNO,
    ORD.SERIE_RETORNO,
    ORD.EMISSAO_RETORNO,
    ORD.DIGITACAO_RETORNO,
    ORD.TES_RETORNO,
    ORD.QTD_RETORNO,
    ORD.QTD_DEVOLVIDA_ACUMULADA,
    CAST(
        REM.QTD_RECEBIDA - ISNULL(ORD.QTD_DEVOLVIDA_ACUMULADA, 0) AS decimal(28, 8)
    ) AS SALDO_APOS_RETORNO,
    ORD.TIPO_PARCEIRO_RETORNO
FROM Remessas REM
LEFT JOIN RetornosAgg AGG
    ON AGG.FILIAL = REM.FILIAL
   AND AGG.PRODUTO = REM.PRODUTO
   AND AGG.ID_REMESSA = REM.ID_REMESSA
LEFT JOIN RetornosOrdenados ORD
    ON ORD.FILIAL = REM.FILIAL
   AND ORD.PRODUTO = REM.PRODUTO
   AND ORD.ID_REMESSA = REM.ID_REMESSA
LEFT JOIN SB1010 SB1 WITH (NOLOCK)
    ON SB1.B1_COD = REM.PRODUTO
   AND LTRIM(RTRIM(SB1.B1_FILIAL)) = ''
   AND SB1.D_E_L_E_T_ = ' '
LEFT JOIN SA1010 SA1 WITH (NOLOCK)
    ON SA1.A1_COD = REM.COD_PARCEIRO
   AND SA1.A1_LOJA = REM.LOJA_PARCEIRO
   AND LTRIM(RTRIM(SA1.A1_FILIAL)) = ''
   AND SA1.D_E_L_E_T_ = ' ';
