"""Evidence / epistemic coordination domain (C3-T2R1).

Implements frozen semantics from `21` §4B + thematic `38`.
No Evidence store, repository, LLM, RAG, planner, or conversation runtime.
"""

from app.domain.evidence.model import (
    AuthorityPolicySnapshot,
    EntityRef,
    EvidenceConflictSet,
    EvidenceItem,
    EvidencePresence,
    EvidenceRef,
    EpistemicClass,
    FactQualificationCriteria,
    FreshnessClass,
    ModelRef,
    PredictionRef,
    PredictionResult,
    ScenarioRef,
    SimulationResult,
    SourceRef,
    TypedResultKind,
)
from app.domain.evidence.rules import (
    absorb_external_content_into_authority,
    assert_no_chain_of_thought,
    build_conflict_set,
    can_qualify_as_fact,
    create_evidence_item,
    default_class_for_input_kind,
    derive_evidence,
    evidence_ref_grants_source_permission,
    missing_means_negative_fact,
    recommendation_authorizes_act,
    reject_secret_bearing_payload,
    rename_provider_preserves_identity,
    source_ref_grants_provider_access,
    try_automatic_observation_to_fact,
)

__all__ = [
    "AuthorityPolicySnapshot",
    "EntityRef",
    "EvidenceConflictSet",
    "EvidenceItem",
    "EvidencePresence",
    "EvidenceRef",
    "EpistemicClass",
    "FactQualificationCriteria",
    "FreshnessClass",
    "ModelRef",
    "PredictionRef",
    "PredictionResult",
    "ScenarioRef",
    "SimulationResult",
    "SourceRef",
    "TypedResultKind",
    "absorb_external_content_into_authority",
    "assert_no_chain_of_thought",
    "build_conflict_set",
    "can_qualify_as_fact",
    "create_evidence_item",
    "default_class_for_input_kind",
    "derive_evidence",
    "evidence_ref_grants_source_permission",
    "missing_means_negative_fact",
    "recommendation_authorizes_act",
    "reject_secret_bearing_payload",
    "rename_provider_preserves_identity",
    "source_ref_grants_provider_access",
    "try_automatic_observation_to_fact",
]
