export const COLLABORATION_SECTION_LABELS: Record<string, string> = {
  processo: "Dados do processo",
  diagrama_macro: "Diagrama macro",
  decomposicao: "Mapeamento do processo",
  arquivos: "Arquivos do processo",
  instancia: "Melhoria",
  decomposicao_escopo: "Escopo no mapeamento",
  diagrama_escopo: "Escopo no diagrama",
  instancia_contexto: "Contexto operacional",
  decomposicao_revisao: "Mapeamento da revisão",
  diagrama_revisao: "Diagrama da revisão",
  vigencia: "Vigência",
  medicao: "Medição",
  investimentos: "Investimentos",
  recursos: "Recursos",
  evidencias: "Evidências",
  filial: "Unidade",
  setor: "Departamento",
  recurso: "Recurso",
  custos: "Custos",
};
