"""Motor declarativo de fast paths — operational_route_registry (DOCIE Fase 0–3)."""

from __future__ import annotations

from typing import Callable

from app.domain.services.chat_message_normalization_service import (
    ChatMessageNormalizationService,
)
from app.domain.services.chat_product_query_intent_service import (
    ChatProductQueryIntent,
    ChatProductQueryIntentService,
)
from app.domain.services.chat_production_operational_intent_service import (
    ChatProductionOperationalIntentService,
    ProductionOperationalIntentKind,
)
from app.domain.services.external_actions.external_action_response_content_service import (
    ExternalActionResponseContentService,
)
from app.domain.services.operational_route_matcher_service import (
    OperationalRouteMatcherService,
)
from app.domain.services.operational_route_registry_service import (
    OperationalRouteRegistryService,
)


class ExternalActionOperationalRouteSelectionService:
    def __init__(self, catalog) -> None:
        self._catalog = catalog

    def select(
        self,
        message: str,
        normalized: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        merge_date_parameters: Callable[..., dict] | None = None,
        previous_messages: list | None = None,
        path_lookup_loader: Callable[..., list[dict]] | None = None,
    ) -> dict | None:
        selected = self.select_production_operational(
            message,
            allowed_action_ids=allowed_action_ids,
            previous_messages=previous_messages,
            candidates_loader=candidates_loader,
            build_date_branch_parameters=build_date_branch_parameters,
            path_lookup_loader=path_lookup_loader,
        )

        if selected:
            return selected

        for route in OperationalRouteRegistryService.vocabulary_routes():
            selected = self._try_vocabulary_route(
                route,
                message,
                normalized,
                allowed_action_ids,
                candidates_loader=candidates_loader,
                build_date_branch_parameters=build_date_branch_parameters,
                merge_date_parameters=merge_date_parameters,
                previous_messages=previous_messages,
            )

            if selected:
                return selected

        return None

    def select_auto_tier_c(
        self,
        message: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        rank_candidates: Callable[..., list[dict]] | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        previous_messages: list | None = None,
    ) -> dict | None:
        if not allowed_action_ids or not candidates_loader or not rank_candidates:
            return None

        candidates = candidates_loader(
            message,
            allowed_action_ids=allowed_action_ids,
            limit=120,
        )

        if not candidates:
            return None

        ranked = rank_candidates(
            message,
            candidates,
            allowed_action_ids=allowed_action_ids,
        )

        if not ranked:
            return None

        top = ranked[0]
        operation_id = str(top.get("operationId") or "").strip()

        if top.get("selectionScore") is None or not operation_id:
            return None

        route = OperationalRouteRegistryService.route_by_operation_id(operation_id)

        if not route or not route.get("autoGenerated"):
            return None

        return self._resolve_route_action(
            route,
            message,
            allowed_action_ids,
            candidates=[top],
            candidates_loader=candidates_loader,
            previous_messages=previous_messages,
            build_date_branch_parameters=build_date_branch_parameters,
        )

    def select_by_department_kpi(
        self,
        message: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        previous_messages: list | None = None,
    ) -> dict | None:
        from app.domain.models.operational_api_route_spec import OperationalApiRouteSpec
        from app.domain.services.chat_department_kpi_intent_service import (
            ChatDepartmentKpiIntentService,
        )

        match = ChatDepartmentKpiIntentService.resolve(message)

        if not match:
            return None

        spec = OperationalApiRouteSpec.from_department_kpi(match)
        route = self._virtual_department_kpi_route(spec)

        selected = self._resolve_route_action(
            route,
            message,
            allowed_action_ids,
            candidates_loader=candidates_loader,
            previous_messages=previous_messages,
            build_date_branch_parameters=build_date_branch_parameters,
        )

        if selected and spec.reason:
            selected["reason"] = spec.reason

        return selected

    @staticmethod
    def _virtual_department_kpi_route(spec) -> dict:
        path_markers: list[str] = []

        for token in spec.path_tokens:
            normalized_token = str(token or "").strip().lower()

            if not normalized_token:
                continue

            if normalized_token.startswith("/"):
                path_markers.append(normalized_token)
                continue

            for prefix in spec.path_prefixes:
                path_markers.append(
                    f"{str(prefix).rstrip('/').lower()}/{normalized_token}"
                )

            if not spec.path_prefixes:
                path_markers.append(normalized_token)

        for prefix in spec.path_prefixes:
            normalized_prefix = str(prefix or "").strip().lower()

            if normalized_prefix and normalized_prefix not in path_markers:
                path_markers.append(normalized_prefix)

        return {
            "presentation": {"reasonKey": "departmentKpi"},
            "parameters": {"strategy": spec.parameter_strategy},
            "route": {
                "pathMarkers": path_markers or list(spec.path_prefixes),
                "operationIdMarkers": list(spec.operation_tokens),
                "method": spec.method,
            },
        }

    def select_by_intent(
        self,
        message: str,
        product_code: str,
        intent: str,
        allowed_action_ids: list[str],
        *,
        route_segment: str | None = None,
        candidates_loader: Callable[..., list[dict]] | None = None,
    ) -> dict | None:
        normalized_intent = str(intent or "").strip().lower()
        normalized_segment = str(route_segment or "").strip().lower()

        if not normalized_intent or not str(product_code or "").strip():
            return None

        segment_intent = OperationalRouteRegistryService.refinement_intent_by_route_segment().get(
            normalized_segment
        )

        if segment_intent and segment_intent != normalized_intent:
            normalized_segment = ""

        for route in OperationalRouteRegistryService.intent_bound_routes():
            binding = str(route.get("intentBinding") or "").strip().lower()

            if binding != normalized_intent:
                continue

            route_segment_spec = str(route.get("routeSegment") or "").strip().lower()

            if normalized_segment and route_segment_spec:
                if route_segment_spec != normalized_segment:
                    continue
            elif normalized_segment in ("inbound-invoice", "outbound-invoice"):
                continue

            selected = self._resolve_route_action(
                route,
                message,
                allowed_action_ids,
                identifier=product_code,
                candidates_loader=candidates_loader,
            )

            if selected:
                return selected

        return None

    def select_by_route_segment(
        self,
        message: str,
        product_code: str,
        route_segment: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        previous_messages: list | None = None,
    ) -> dict | None:
        normalized_segment = str(route_segment or "").strip().lower()

        if not normalized_segment or not str(product_code or "").strip():
            return None

        for route in OperationalRouteRegistryService.routes_by_segment(normalized_segment):
            selected = self._resolve_route_action(
                route,
                message,
                allowed_action_ids,
                identifier=product_code,
                candidates_loader=candidates_loader,
                previous_messages=previous_messages,
            )

            if selected:
                return selected

        return None

    def select_production_operational(
        self,
        message: str,
        *,
        allowed_action_ids: list[str],
        previous_messages: list | None = None,
        candidates_loader: Callable[..., list[dict]] | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        path_lookup_loader: Callable[..., list[dict]] | None = None,
    ) -> dict | None:
        kind = ChatProductionOperationalIntentService.resolve(message)

        if not kind:
            return None

        route = OperationalRouteRegistryService.route_by_production_operational_kind(
            kind.value
        )

        if not route:
            return None

        candidate_sets: list[list[dict]] = [
            self._catalog.load_candidates(
                message,
                allowed_action_ids=allowed_action_ids,
                candidates_loader=candidates_loader,
            )
        ]

        path_token = ChatProductionOperationalIntentService.path_token_for(kind)

        if path_lookup_loader and path_token:
            path_candidates = path_lookup_loader(
                path_token=path_token,
                allowed_action_ids=allowed_action_ids,
            )

            if path_candidates:
                candidate_sets.append(path_candidates)

        for candidates in candidate_sets:
            selected = self._resolve_route_action(
                route,
                message,
                allowed_action_ids,
                candidates=candidates,
                previous_messages=previous_messages,
                build_date_branch_parameters=build_date_branch_parameters,
                production_kind=kind,
            )

            if selected:
                return selected

        return None

    def select_sale_orders(
        self,
        message: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        merge_date_parameters: Callable[..., dict] | None = None,
    ) -> dict | None:
        if not merge_date_parameters:
            return None

        route = OperationalRouteRegistryService.route_by_id("commercialSaleOrders")

        if not route:
            return None

        normalized = ChatMessageNormalizationService.normalize_for_matching(message)

        return self._try_vocabulary_route(
            route,
            message,
            normalized,
            allowed_action_ids,
            candidates_loader=candidates_loader,
            merge_date_parameters=merge_date_parameters,
        )

    def select_transforma(
        self,
        message: str,
        allowed_action_ids: list[str],
        *,
        previous_messages: list | None = None,
        candidates_loader: Callable[..., list[dict]] | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
    ) -> dict | None:
        if not build_date_branch_parameters:
            return None

        normalized = ChatMessageNormalizationService.normalize_for_matching(message)

        for route_id in ("engineeringTransformaSummary", "engineeringTransformaProcesses"):
            route = OperationalRouteRegistryService.route_by_id(route_id)

            if not route:
                continue

            selected = self._try_vocabulary_route(
                route,
                message,
                normalized,
                allowed_action_ids,
                candidates_loader=candidates_loader,
                previous_messages=previous_messages,
                build_date_branch_parameters=build_date_branch_parameters,
            )

            if selected:
                return selected

        return None

    def select_lmp(
        self,
        message: str,
        normalized: str,
        allowed_action_ids: list[str],
        *,
        conversation_context: str | None = None,
        candidates_loader: Callable[..., list[dict]] | None = None,
        merge_date_parameters: Callable[..., dict] | None = None,
    ) -> dict | None:
        for route in OperationalRouteRegistryService.lmp_routes():
            selected = self._try_vocabulary_route(
                route,
                message,
                normalized,
                allowed_action_ids,
                candidates_loader=candidates_loader,
                merge_date_parameters=merge_date_parameters,
                conversation_context=conversation_context,
            )

            if selected:
                return selected

        return None

    def select_product_with_code(
        self,
        message: str,
        product_code: str,
        allowed_action_ids: list[str],
        *,
        intent: str = ChatProductQueryIntent.FULL,
        route_segment: str | None = None,
        candidates_loader: Callable[..., list[dict]] | None = None,
        previous_messages: list | None = None,
    ) -> dict | None:
        normalized = ChatMessageNormalizationService.normalize_for_matching(message or "")
        route_segment_value = str(route_segment or "").strip().lower()
        bound_intent = str(intent or ChatProductQueryIntent.FULL).strip().lower()

        if route_segment_value:
            selected = self.select_by_route_segment(
                message,
                product_code,
                route_segment_value,
                allowed_action_ids,
                candidates_loader=candidates_loader,
                previous_messages=previous_messages,
            )

            if selected:
                return selected

        if bound_intent == ChatProductQueryIntent.FULL:
            if not ChatProductQueryIntentService.has_actionable_product_route_intent(
                message,
                normalized=normalized,
            ):
                return None

            refined = ChatProductQueryIntentService.refine_operational_intent_from_full(
                message,
                normalized=normalized,
            )

            if refined != ChatProductQueryIntent.FULL:
                bound_intent = refined
        elif bound_intent == ChatProductQueryIntent.SALES:
            route_segment_value = route_segment_value or "sales"

            if route_segment_value in ("outbound-invoice", "inbound-invoice"):
                bound_intent = ChatProductQueryIntent.FULL

        if bound_intent != ChatProductQueryIntent.FULL:
            selected = self.select_by_intent(
                message,
                product_code,
                bound_intent,
                allowed_action_ids,
                route_segment=route_segment_value or None,
                candidates_loader=candidates_loader,
            )

            if selected:
                return selected

            if (
                bound_intent == ChatProductQueryIntent.SALES
                and ChatProductQueryIntentService.extract_product_code(message)
            ):
                return None

            if bound_intent in {
                ChatProductQueryIntent.DESCRIPTION,
                ChatProductQueryIntent.ANALYSER,
            }:
                selected = self.select_by_intent(
                    message,
                    product_code,
                    ChatProductQueryIntent.ANALYSER,
                    allowed_action_ids,
                    candidates_loader=candidates_loader,
                )

                if selected:
                    return selected

        for route in OperationalRouteRegistryService.product_identifier_routes():
            selected = self._try_vocabulary_route(
                route,
                message,
                normalized,
                allowed_action_ids,
                identifier=product_code,
                candidates_loader=candidates_loader,
                previous_messages=previous_messages,
            )

            if selected:
                return selected

        from app.domain.services.chat_product_overview_intent_service import (
            ChatProductOverviewIntentService,
        )

        if ChatProductOverviewIntentService.is_product_overview_message(message):
            selected = self.select_by_intent(
                message,
                product_code,
                ChatProductQueryIntent.ANALYSER,
                allowed_action_ids,
                candidates_loader=candidates_loader,
            )

            if selected:
                return selected

        return None

    def select_product_search(
        self,
        message: str,
        normalized: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        description_override: str | None = None,
    ) -> dict | None:
        from app.domain.services.chat_product_search_intent_service import (
            ChatProductSearchIntentService,
        )

        if not ChatProductSearchIntentService.looks_like_product_search(normalized):
            return None

        for route in OperationalRouteRegistryService.product_search_routes():
            selected = self._try_vocabulary_route(
                route,
                message,
                normalized,
                allowed_action_ids,
                candidates_loader=candidates_loader,
                description_override=description_override,
            )

            if selected:
                return selected

        return None

    def select_system_metadata(
        self,
        message: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
    ) -> dict | None:
        normalized = ChatMessageNormalizationService.normalize_for_matching(message)

        for route in OperationalRouteRegistryService.system_metadata_routes():
            selected = self._try_vocabulary_route(
                route,
                message,
                normalized,
                allowed_action_ids,
                candidates_loader=candidates_loader,
            )

            if selected:
                return selected

        return None

    def _try_vocabulary_route(
        self,
        route: dict,
        message: str,
        normalized: str,
        allowed_action_ids: list[str],
        *,
        candidates_loader: Callable[..., list[dict]] | None = None,
        previous_messages: list | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        merge_date_parameters: Callable[..., dict] | None = None,
        conversation_context: str | None = None,
        description_override: str | None = None,
        identifier: str | None = None,
    ) -> dict | None:
        match_spec = route.get("match")

        if not isinstance(match_spec, dict):
            return None

        if not OperationalRouteMatcherService.matches(
            match_spec,
            message=message,
            normalized=normalized,
        ):
            return None

        resolved_identifier = str(identifier or "").strip()

        if match_spec.get("requiresProductIdentifier"):
            if not resolved_identifier:
                resolved_identifier = str(
                    ChatProductQueryIntentService.extract_product_code(message or "") or ""
                ).strip()

            if not resolved_identifier:
                return None

        parameters_spec = route.get("parameters")

        if (
            not resolved_identifier
            and isinstance(parameters_spec, dict)
            and str(parameters_spec.get("strategy") or "").strip().lower() == "product_code"
        ):
            resolved_identifier = str(
                ChatProductQueryIntentService.resolve_product_code(
                    message,
                    conversation_context,
                    previous_messages=previous_messages,
                )
                or ""
            ).strip()

            if not resolved_identifier:
                return None

        return self._resolve_route_action(
            route,
            message,
            allowed_action_ids,
            identifier=resolved_identifier or None,
            candidates_loader=candidates_loader,
            previous_messages=previous_messages,
            build_date_branch_parameters=build_date_branch_parameters,
            merge_date_parameters=merge_date_parameters,
            conversation_context=conversation_context,
            description_override=description_override,
        )

    def _resolve_route_action(
        self,
        route: dict,
        message: str,
        allowed_action_ids: list[str],
        *,
        identifier: str | None = None,
        candidates: list[dict] | None = None,
        candidates_loader: Callable[..., list[dict]] | None = None,
        previous_messages: list | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        merge_date_parameters: Callable[..., dict] | None = None,
        production_kind: ProductionOperationalIntentKind | None = None,
        conversation_context: str | None = None,
        description_override: str | None = None,
    ) -> dict | None:
        route_spec = route.get("route")

        if not isinstance(route_spec, dict):
            return None

        path_markers = [
            str(marker).lower()
            for marker in (route_spec.get("pathMarkers") or [])
            if str(marker).strip()
        ]
        operation_markers = [
            str(marker).lower()
            for marker in (route_spec.get("operationIdMarkers") or [])
            if str(marker).strip()
        ]
        exclude_path_markers = [
            str(marker).lower()
            for marker in (route_spec.get("excludePathMarkers") or [])
            if str(marker).strip()
        ]
        path_exact_end = str(route_spec.get("pathExactEnd") or "").strip().lower()
        path_suffix = str(route_spec.get("pathSuffix") or "").strip().lower()

        if (
            not path_markers
            and not operation_markers
            and not path_exact_end
            and not path_suffix
        ):
            return None

        if candidates is None:
            candidates = self._catalog.find_allowed_actions_by_markers(
                path_markers=path_markers or ([path_exact_end] if path_exact_end else []),
                operation_markers=operation_markers,
                allowed_action_ids=allowed_action_ids,
            )

            if not candidates:
                candidates = self._catalog.load_candidates(
                    message,
                    allowed_action_ids=allowed_action_ids,
                    candidates_loader=candidates_loader,
                )

        candidates = self._catalog.stable_sort_by_allowed_action_ids(
            candidates or [],
            allowed_action_ids,
        )

        expected_method = str(route_spec.get("method") or "GET").upper()

        normalized = ChatMessageNormalizationService.normalize_for_matching(message or "")

        for action in candidates:
            if str(action.get("method") or "GET").upper() != expected_method:
                continue

            path = str(action.get("path") or "").lower()
            operation_id = str(action.get("operationId") or "").lower()

            if path_exact_end and not path.rstrip("/").endswith(path_exact_end.rstrip("/")):
                continue

            if path_suffix and not path.rstrip("/").endswith(path_suffix.rstrip("/")):
                if not operation_markers or not any(
                    marker in operation_id for marker in operation_markers
                ):
                    continue

            if path_markers and not any(marker in path for marker in path_markers):
                if not (
                    path_suffix
                    and path.rstrip("/").endswith(path_suffix.rstrip("/"))
                ):
                    if not operation_markers or not any(
                        marker in operation_id for marker in operation_markers
                    ):
                        continue

            if exclude_path_markers and any(marker in path for marker in exclude_path_markers):
                continue

            if operation_markers and not any(
                marker in operation_id for marker in operation_markers
            ):
                if path_markers or path_exact_end or path_suffix:
                    if not path_markers or not any(marker in path for marker in path_markers):
                        if not path_suffix or not path.rstrip("/").endswith(
                            path_suffix.rstrip("/")
                        ):
                            continue

            if (
                not path_markers
                and not path_exact_end
                and not path_suffix
                and operation_markers
                and not any(marker in operation_id for marker in operation_markers)
            ):
                continue

            if "search" in path and not path_markers and not path_exact_end and not path_suffix:
                continue

            parameters = self._build_parameters(
                route,
                action,
                message=message,
                identifier=identifier,
                normalized=normalized,
                previous_messages=previous_messages,
                build_date_branch_parameters=build_date_branch_parameters,
                merge_date_parameters=merge_date_parameters,
                production_kind=production_kind,
                conversation_context=conversation_context,
                description_override=description_override,
            )

            if parameters is None:
                continue

            reason = self._resolve_presentation_reason(
                route,
                parameters,
                message=message,
                normalized=normalized,
                description_override=description_override,
            )

            if not reason:
                continue

            return {
                "name": "execute_external_action",
                "arguments": {
                    "actionId": action["actionId"],
                    "parameters": parameters,
                },
                "reason": reason,
            }

        return None

    def _resolve_presentation_reason(
        self,
        route: dict,
        parameters: dict,
        *,
        message: str,
        normalized: str,
        description_override: str | None = None,
    ) -> str:
        presentation = route.get("presentation") or {}
        reason_format_key = str(presentation.get("reasonFormatKey") or "").strip()

        if reason_format_key:
            reason_format_param = str(presentation.get("reasonFormatParam") or "").strip()

            if reason_format_param == "group_code":
                group_code = parameters.get("group_code") or parameters.get("groupCode")

                if group_code:
                    return ExternalActionResponseContentService.format(
                        "selectionReasons",
                        reason_format_key,
                        group_code=group_code,
                    )
            elif reason_format_param == "description_query":
                from app.application.services.external_actions.external_action_product_search_route_selection_service import (
                    ExternalActionProductSearchRouteSelectionService,
                )

                description_query = (
                    parameters.get("description")
                    or parameters.get("query")
                    or parameters.get("q")
                    or description_override
                    or ExternalActionProductSearchRouteSelectionService.extract_search_description(
                        message
                    )
                )

                if description_query:
                    return ExternalActionResponseContentService.format(
                        "selectionReasons",
                        reason_format_key,
                        description_query=description_query,
                    )

        reason_key = str(presentation.get("reasonKey") or route.get("id") or "").strip()

        if not reason_key:
            return ""

        return ExternalActionResponseContentService.get(
            "selectionReasons",
            reason_key,
        )

    def _build_parameters(
        self,
        route: dict,
        action: dict,
        *,
        message: str,
        identifier: str | None,
        normalized: str | None = None,
        previous_messages: list | None = None,
        build_date_branch_parameters: Callable[..., dict] | None = None,
        merge_date_parameters: Callable[..., dict] | None = None,
        production_kind: ProductionOperationalIntentKind | None = None,
        conversation_context: str | None = None,
        description_override: str | None = None,
    ) -> dict | None:
        parameters_spec = route.get("parameters") or {}
        strategy = str(parameters_spec.get("strategy") or "").strip()
        normalized_text = normalized or ChatMessageNormalizationService.normalize_for_matching(
            message or ""
        )

        if strategy == "product_search":
            from app.application.services.external_actions.external_action_product_search_route_selection_service import (
                ExternalActionProductSearchRouteSelectionService,
            )

            path = str(action.get("path") or "").lower()
            operation_id = str(action.get("operationId") or "").lower()

            if "search" not in path and "search" not in operation_id:
                return None

            return ExternalActionProductSearchRouteSelectionService.build_search_parameters(
                message,
                normalized_text,
                action,
                description_override=description_override,
            )

        if strategy == "lmp":
            from app.domain.services.operational_route_matcher_service import (
                OperationalRouteMatcherService,
            )

            path = str(action.get("path") or "")
            sale_number = OperationalRouteMatcherService.extract_lmp_sale_number(
                message
            ) or OperationalRouteMatcherService.extract_lmp_sale_number(conversation_context)

            if sale_number and "{sale_number}" in path:
                for parameter in action.get("parametersSchema") or []:
                    name = parameter.get("name")

                    if name and name.lower() in {"sale_number", "ordem", "ov"}:
                        return {name: sale_number}

                return {"sale_number": sale_number}

            parameters: dict = {}

            for parameter in action.get("parametersSchema") or []:
                name = parameter.get("name")

                if not name:
                    continue

                lowered = name.lower()

                if lowered in {"page"}:
                    parameters[name] = 1
                elif lowered in {"page_size", "pagesize", "limit"}:
                    parameters[name] = 50
                elif lowered == "status" and "/dashboard" in path:
                    parameters[name] = "Todos"

            if not parameters:
                parameters = {"page": 1, "page_size": 50}

            if merge_date_parameters:
                return merge_date_parameters(action, message, parameters)

            return parameters

        if strategy == "product_code":
            if not identifier:
                identifier = ChatProductQueryIntentService.extract_product_code(message or "")

            if not identifier:
                identifier = ChatProductQueryIntentService.resolve_product_code(
                    message or "",
                    conversation_context,
                    previous_messages=previous_messages,
                )

            if not identifier:
                return None

            return self._catalog.build_product_parameters(
                action,
                identifier,
                message=message,
                previous_messages=previous_messages,
            )

        if strategy == "exclusive_catalog":
            normalized = message.lower()

            return self._catalog.build_exclusive_catalog_parameters(
                action,
                message=message,
                normalized=normalized,
            )

        if strategy == "date_branch":
            parameters: dict = {}

            if build_date_branch_parameters:
                parameters = build_date_branch_parameters(
                    action,
                    message,
                    previous_messages=previous_messages,
                )

            if production_kind in {
                ProductionOperationalIntentKind.LOSSES_TOP,
                ProductionOperationalIntentKind.LOSSES_RECORDS,
            }:
                loss_type = ChatProductionOperationalIntentService.infer_loss_type(
                    ChatMessageNormalizationService.normalize_for_matching(message)
                )

                if loss_type:
                    parameters["loss_type"] = loss_type

            if production_kind == ProductionOperationalIntentKind.CONSUMPTION_BY_ITEM:
                product_code = ChatProductQueryIntentService.extract_product_code(message)

                if product_code:
                    parameters["code"] = product_code

            if production_kind == ProductionOperationalIntentKind.SCHEDULE_TODAY:
                filter_code = ChatProductQueryIntentService.resolve_schedule_product_filter_code(
                    message,
                    product_code=ChatProductQueryIntentService.extract_product_code(message),
                )

                if filter_code:
                    parameters["presentationDetailFilter"] = {
                        "product_code_prefix": filter_code,
                    }

            if not parameters:
                parameters = {}

            parameters = ExternalActionProductRouteCatalogService.filter_parameters_to_schema(
                action,
                parameters,
            )

            return parameters

        if strategy == "sale_orders":
            from app.domain.services.operational_api_parameter_builder_service import (
                OperationalApiParameterBuilderService,
            )

            return OperationalApiParameterBuilderService().build_sale_orders(
                action,
                message,
                previous_messages=previous_messages,
            )

        if strategy == "system_metadata":
            from app.domain.services.chat_system_metadata_intent_service import (
                ChatSystemMetadataIntentService,
            )

            return ChatSystemMetadataIntentService.build_parameters(message, action)

        if strategy == "supplies_stock":
            from app.domain.services.operational_api_parameter_builder_service import (
                OperationalApiParameterBuilderService,
            )

            return OperationalApiParameterBuilderService.build_supplies_stock(action)

        if strategy in {"none", "semantic"}:
            return {}

        return None
