/**
 * Textos do hub Administração (Painel · Carteiras · Equipe · Grupos · SLAs).
 */
export const ADMINISTRATION_CONTENT = {
  breadcrumbRoot: "Administração",
  subnavAriaLabel: "Seções da Administração",
  panel: {
    navLabel: "Painel",
    eyebrow: "Administração",
    title: "Painel",
    description: "Carteiras, equipe e grupos operacionais.",
    refresh: "Atualizar",
    loading: "Carregando resumo das carteiras.",
    loadError: "Não foi possível carregar o resumo da Administração.",
    actionsTitle: "Ações rápidas",
    openPortfolios: "Abrir Carteiras",
    openTeam: "Equipe",
    openGroups: "Grupos",
    /** @deprecated use openTeam */
    openMembers: "Equipe",
    newPortfolio: "Nova carteira",
    bulkTransfer: "Transferência em massa",
    newPortfolioHint: "Abre a lista de carteiras para cadastrar uma nova.",
    bulkTransferHint: "Abre a lista de carteiras para iniciar a transferência.",
  },
  portfolios: {
    navLabel: "Carteiras",
  },
  team: {
    navLabel: "Equipe",
    eyebrow: "Administração",
    title: "Equipe",
    description: "Pessoas com acesso ao portal, grupos e carteiras.",
    refresh: "Atualizar",
    loading: "Carregando equipe.",
    loadError: "Não foi possível carregar a equipe.",
    emptyTitle: "Nenhuma pessoa encontrada.",
    emptyDescription: "Ajuste os filtros ou cadastre carteiras e grupos.",
    openPortfolios: "Ir para Carteiras",
    openGroups: "Ir para Grupos",
    viewProfile: "Ver perfil",
    colPerson: "Pessoa",
    colOnline: "Status",
    colGroups: "Grupos",
    colPortfolios: "Carteiras",
    statusOnline: "Online",
    statusOffline: "Offline",
    filterSearch: "Buscar",
    filterSearchPlaceholder: "Nome ou e-mail",
    filterGroup: "Grupo",
    filterPortfolio: "Carteira",
    filterOnline: "Presença",
    filterOnlineAll: "Todos",
    filterOnlineOnly: "Online",
    filterOfflineOnly: "Offline",
    filterAllOption: "Todos",
    viewList: "Lista",
    viewOrg: "Diagrama",
    viewToggleAria: "Modo Lista ou Diagrama",
    orgTitle: "Diagrama de grupos",
    orgSubtitle: "Relação entre grupos operacionais e pessoas da equipe.",
    orgEmpty: "Sem vínculos de grupo para exibir com os filtros atuais.",
    orgAriaLabel: "Organização da equipe por grupo",
  },
  /** Alias legado — preferir `team`. */
  members: {
    navLabel: "Equipe",
  },
  groups: {
    navLabel: "Grupos",
    eyebrow: "Administração",
    title: "Grupos",
    description: "Grupos operacionais e membros — não são papéis RBAC.",
    refresh: "Atualizar",
    create: "Criar grupo",
    creating: "Criando…",
    createPlaceholder: "Nome do grupo",
    createNameRequired: "Informe o nome do grupo.",
    createSuccess: "Grupo criado.",
    deleteGroup: "Excluir grupo",
    deleting: "Excluindo…",
    deleteConfirmTitle: "Excluir grupo?",
    deleteConfirmMessage:
      "O grupo «{name}» será removido e os membros perderão esse vínculo. Esta ação não pode ser desfeita.",
    deleteSuccess: "Grupo excluído.",
    loading: "Carregando grupos.",
    loadError: "Não foi possível carregar os grupos.",
    emptyTitle: "Nenhum grupo cadastrado.",
    emptyDescription:
      "Crie o primeiro grupo operacional e adicione os membros da equipe.",
    createFormTitle: "Novo grupo",
    closeCreate: "Fechar",
    rename: "Renomear",
    renameSave: "Salvar nome",
    renaming: "Salvando…",
    renameCancel: "Cancelar",
    renameSuccess: "Grupo renomeado.",
    renameNameRequired: "Informe o nome do grupo.",
    membersTitle: "Membros",
    viewList: "Lista",
    viewOrg: "Diagrama",
    viewToggleAria: "Modo Lista ou Diagrama",
    orgTitle: "Diagrama de grupos",
    orgSubtitle: "Relação entre grupos operacionais e membros.",
    orgEmpty: "Nenhum vínculo de membro para exibir.",
    orgAriaLabel: "Organização dos grupos e membros",
    addMember: "Adicionar membro",
    addMemberPlaceholder: "Buscar para adicionar…",
    removeMember: "Remover",
    removing: "Removendo…",
    adding: "Adicionando…",
    noMembers: "Nenhum membro neste grupo.",
    memberCount: "{count} membro(s)",
    openGroupWall: "Mural do grupo",
    openGroupWallOpening: "Abrindo mural…",
    openGroupWallError: "Não foi possível abrir o mural do grupo.",
    membersFacepileAria: "Membros do grupo {name}",
  },
  slas: {
    navLabel: "SLAs",
    eyebrow: "Administração",
    title: "SLAs",
    description:
      "Políticas de prazo por domínio (tarefa, amostra, confirmação de pedido, etapa de oferta). Cadastre após homologar os prazos com as áreas.",
    refresh: "Atualizar",
    create: "Nova política",
    emptyTitle: "Nenhuma política de SLA",
    emptyDescription:
      "Cadastre políticas depois que o Comercial homologar os prazos. Até lá a lista fica vazia.",
    loading: "Carregando políticas de SLA.",
    loadError: "Não foi possível carregar as políticas de SLA.",
  },
  metrics: {
    total: "Carteiras",
    active: "Ativas",
    inactive: "Inativas",
    customers: "Clientes",
    overlapping: "Overlapping",
    uncovered: "Sem cobertura",
  },
} as const;
