/**
 * Textos do hub Administração (Painel · Carteiras · Equipe · Grupos).
 */
export const ADMINISTRATION_CONTENT = {
  breadcrumbRoot: "Administração",
  subnavAriaLabel: "Seções da Administração",
  panel: {
    navLabel: "Painel",
    eyebrow: "Administração",
    title: "Painel",
    description: "Cadastre carteiras, gerencie a equipe e os grupos operacionais.",
    refresh: "Atualizar",
    loading: "Carregando resumo das carteiras.",
    loadError: "Não foi possível carregar o resumo da Administração.",
    actionsTitle: "Ações rápidas",
    openPortfolios: "Abrir Carteiras",
    openTeam: "Equipe",
    openGroups: "Grupos",
    /** @deprecated use openTeam */
    openMembers: "Equipe",
    newPortfolio: "Nova carteira",
    bulkTransfer: "Transferência em massa",
    newPortfolioHint: "Abre a lista de carteiras para cadastrar uma nova.",
    bulkTransferHint: "Abre a lista de carteiras para iniciar a transferência.",
  },
  portfolios: {
    navLabel: "Carteiras",
  },
  team: {
    navLabel: "Equipe",
    eyebrow: "Administração",
    title: "Equipe",
    description: "Pessoas com acesso ao Portal Comercial, grupos e carteiras.",
    refresh: "Atualizar",
    loading: "Carregando equipe.",
    loadError: "Não foi possível carregar a equipe.",
    emptyTitle: "Nenhuma pessoa encontrada.",
    emptyDescription: "Ajuste os filtros ou cadastre carteiras e grupos.",
    openPortfolios: "Ir para Carteiras",
    openGroups: "Ir para Grupos",
    viewProfile: "Ver perfil",
    colPerson: "Pessoa",
    colOnline: "Status Online",
    colEmail: "E-mail",
    colGroups: "Grupos",
    colPortfolios: "Carteiras",
    statusOnline: "Online",
    statusOffline: "Offline",
    filterSearch: "Buscar",
    filterSearchPlaceholder: "Nome ou e-mail",
    filterGroup: "Grupo",
    filterPortfolio: "Carteira",
    filterOnline: "Presença",
    filterOnlineAll: "Todos",
    filterOnlineOnly: "Online",
    filterOfflineOnly: "Offline",
    filterAllOption: "Todos",
  },
  /** Alias legado — preferir `team`. */
  members: {
    navLabel: "Equipe",
  },
  groups: {
    navLabel: "Grupos",
    eyebrow: "Administração",
    title: "Grupos",
    description:
      "Crie grupos operacionais e adicione ou remova pessoas. Não são papéis RBAC.",
    refresh: "Atualizar",
    create: "Criar grupo",
    creating: "Criando…",
    createPlaceholder: "Nome do grupo",
    createNameRequired: "Informe o nome do grupo.",
    createSuccess: "Grupo criado.",
    deleteGroup: "Excluir grupo",
    deleting: "Excluindo…",
    deleteConfirmTitle: "Excluir grupo?",
    deleteConfirmMessage:
      "O grupo «{name}» será removido e os membros perderão esse vínculo. Esta ação não pode ser desfeita.",
    deleteSuccess: "Grupo excluído.",
    loading: "Carregando grupos.",
    loadError: "Não foi possível carregar os grupos.",
    emptyTitle: "Nenhum grupo cadastrado.",
    emptyDescription:
      "Crie o primeiro grupo operacional e adicione os membros da equipe.",
    createFormTitle: "Novo grupo",
    closeCreate: "Fechar",
    membersTitle: "Membros",
    addMember: "Adicionar membro",
    addMemberPlaceholder: "Buscar para adicionar…",
    removeMember: "Remover",
    removing: "Removendo…",
    adding: "Adicionando…",
    noMembers: "Nenhum membro neste grupo.",
    memberCount: "{count} membro(s)",
    membersFacepileAria: "Membros do grupo {name}",
  },
  metrics: {
    total: "Carteiras",
    active: "Ativas",
    inactive: "Inativas",
    customers: "Clientes",
    overlapping: "Overlapping",
    uncovered: "Sem cobertura",
  },
} as const;
