/**
 * Textos do hub Administração (Painel · Carteiras · Membros).
 */
export const ADMINISTRATION_CONTENT = {
  breadcrumbRoot: "Administração",
  subnavAriaLabel: "Seções da Administração",
  panel: {
    navLabel: "Painel",
    eyebrow: "Administração",
    title: "Painel",
    description: "Cadastre carteiras, gerencie membros e monitore cobertura.",
    refresh: "Atualizar",
    loading: "Carregando resumo das carteiras.",
    loadError: "Não foi possível carregar o resumo da Administração.",
    actionsTitle: "Ações rápidas",
    openPortfolios: "Abrir Carteiras",
    openMembers: "Membros",
    newPortfolio: "Nova carteira",
    bulkTransfer: "Transferência em massa",
    newPortfolioHint: "Abre a lista de carteiras para cadastrar uma nova.",
    bulkTransferHint: "Abre a lista de carteiras para iniciar a transferência.",
  },
  portfolios: {
    navLabel: "Carteiras",
  },
  members: {
    navLabel: "Membros",
    eyebrow: "Administração",
    title: "Membros",
    description: "Pessoas com acesso às carteiras do Portal.",
    refresh: "Atualizar",
    loading: "Carregando membros das carteiras.",
    loadError: "Não foi possível carregar os membros.",
    emptyTitle: "Nenhuma carteira ativa.",
    emptyDescription: "Cadastre ou reative carteiras para ver o roster de membros.",
    openPortfolios: "Ir para Carteiras",
    openPortfolio: "Abrir carteira",
    colPerson: "Pessoa",
    colEmail: "E-mail",
    colPortfolios: "Carteiras",
    colRole: "Papel",
    roleOwner: "Responsável",
    roleMember: "Membro",
  },
  metrics: {
    total: "Carteiras",
    active: "Ativas",
    inactive: "Inativas",
    customers: "Clientes",
    overlapping: "Overlapping",
    uncovered: "Sem cobertura",
  },
} as const;
