export const ANALYTICS_CONTENT = {
  nav: {
    overview: "Visão geral",
    otd: "OTD",
    equipe: "Equipe",
    oportunidades: "Oportunidades",
  },
  overview: {
    title: "Visão geral",
    subtitle:
      "Indicadores do período, evolução de ROL e funil de conversão. OTD e Oportunidades abrem pelo Início.",
    filters:
      "Período, unidade (Santa Catarina / Espírito Santo) e segmento aplicados a todos os painéis desta página.",
    rolKpi: "ROL consolidado versus meta no período filtrado.",
    branchRolKpi: "ROL por unidade versus meta no período filtrado.",
    closingKpi: "Taxa de conversão: propostas ganhas ÷ total de propostas.",
    otdKpi: "On-time delivery de linhas de pedido de venda.",
    newBusinessKpi: "Participação de novos negócios no ROL do período.",
    rolSeries:
      "Evolução do ROL no período (respeita o filtro de unidade).",
    comparePriorYear: "Comparar ano anterior",
    compareYearsTrigger: "Comparar anos",
    compareYearsPanelTitle: "Comparação com anos anteriores",
    compareYearsNone: "Sem comparação",
    compareYearsDepth1: "Ano anterior",
    compareYearsDepth2: "Até −2 anos",
    compareYearsDepth3: "Até −3 anos",
    compareYearsPlus2: "+2 anos",
    compareYearsPlus3: "+3 anos",
    chartGranularityLabel: "Agrupamento",
    chartOverlaysLabel: "Opções",
    chartTypeLabel: "Tipo",
    chartOverlaysPanelTitle: "Opções do gráfico",
    chartOverlaysEmpty: "Opções",
    funnel: "Funil de conversão (propostas → ganhas).",
    funnelFootnote:
      "Largura das etapas proporcional ao volume; números absolutos em cada faixa. Ganhas = propostas com status TOTVS 9 e aceite (AD1_DTASSI) no período filtrado.",
    chartEmpty: {
      rolLoading: "Carregando evolução de ROL…",
      rolError: "Erro ao carregar série de ROL.",
      rolTitle: "Sem evolução no período",
      rolMessage:
        "Não há pontos de ROL para os filtros atuais. Ajuste datas, unidade ou segmento.",
      conversionLoading: "Carregando evolução da taxa de conversão…",
      conversionError: "Erro ao carregar série da taxa de conversão.",
      conversionTitle: "Sem série de conversão no período",
      conversionMessage:
        "Não há pontos de hit rate para os filtros atuais. Ajuste datas ou segmento.",
      funnelTitle: "Sem funil no período",
      funnelMessage: "Não há propostas no período filtrado para montar o funil de conversão.",
    },
  },
  otd: {
    title: "Pontualidade (OTD)",
    subtitle: "Painel de on-time delivery por linha de pedido de venda.",
    lineDetail: "Detalhe da linha de pedido selecionada.",
    linesSearchPlaceholder: "Pedido, cliente ou produto",
    statusAll: "Todos",
    statusOnTime: "No prazo",
    statusLate: "Atrasadas",
    insightsRecurrence: "Reincidência (clientes)",
    insightsWorst: "Piores atrasos",
    insightsUpcoming: "Próximas promessas",
    seriesTitle: "Série OTD",
    emptyLines: "Nenhuma linha no recorte.",
  },
  equipe: {
    title: "Equipe",
    subtitle: "Carteiras ativas com contagem de clientes e resumo de pedidos em aberto.",
  },
  oportunidades: {
    title: "Oportunidades",
    subtitle:
      "Visão Por colaborador ou Por oportunidade, com filtros do período. Personalize colunas, fonte e export na toolbar de cada tabela.",
    accountHint:
      "Oportunidades (OV) deste cliente. Clique na linha ou no número para abrir o detalhe.",
    detail:
      "Detalhe da oportunidade: indicadores, dados comerciais, produtos, estrutura de componentes e histórico.",
    openProposal: "Abrir proposta",
    openProposalBusy: "Abrindo…",
    openProposalEmpty:
      "Não há documento ADY vinculado a esta OV. A proposta pode não ter sido gerada ainda.",
    openProposalError: "Não foi possível localizar a proposta ADY desta OV.",
    openProposalMultipleHint: "Há mais de um documento ADY; abrimos o mais recente.",
    openProposalReturnLabel: "Oportunidade",
    statusFilterAriaLabel: "Filtrar oportunidades por status",
    statusFilterLabel: "Status",
    statusAll: "Todas",
    statusOpen: "Abertas",
    statusWon: "Ganhas",
    statusLost: "Perdidas",
    statusOther: "Outras",
    searchLabel: "Buscar OV",
    searchPlaceholder: "Número da OV, revisão…",
    dateStartLabel: "Período — início",
    dateEndLabel: "Período — fim",
    productCodeLabel: "Produto",
    productCodePlaceholder: "Código do produto…",
    productGroupLabel: "Família",
    productGroupPlaceholder: "Grupo (4 dígitos)…",
    accountFiltersAriaLabel: "Filtros de oportunidades da conta",
    emptyFiltered: "Nenhuma oportunidade corresponde aos filtros.",
  },
  filters: {
    start: "Data inicial",
    end: "Data final",
    competence: "Competência (mês)",
    periodPreset: "Período rápido",
    branch: "Unidade (indicadores)",
    segment: "Segmento",
    segmentAll: "Todos",
    segmentWeg: "WEG",
    segmentNewBusiness: "Novos negócios",
    customer: "Cliente",
    customerAll: "Todos os clientes",
  },
};

export const PROPOSALS_CONTENT = {
  list: {
    title: "Propostas comerciais",
    subtitle: "Consulta de propostas comerciais ativas (documentos).",
    scopeNote:
      "O menu do usuário no topo leva a Minha Carteira filtrada; esta lista de propostas-documento não filtra por carteira — é o catálogo com permissão de propostas.",
    search: "Buscar por OV, proposta interna, oportunidade ou cliente.",
    empty: "Nenhuma proposta encontrada.",
    emptySearch: "Ajuste a busca ou limpe o filtro para ver a lista completa.",
  },
  detail: {
    title: "Proposta comercial",
    exportPdf: "Emitir PDF",
    back: "Voltar",
    items: "Itens",
    pdfSection: "PDF revisável",
    pdfSectionHint:
      "Escolha um contato e ajuste nome, departamento, e-mail e telefone só para este PDF. Alterações não gravam na Conta nem na proposta.",
    pdfContactLabel: "Contato base",
    pdfContactEmpty: "Nenhum contato disponível para esta conta. Cadastre contatos na ficha do cliente.",
    pdfContactFieldsHint: "Somente emissão do PDF — não altera o cadastro da Conta.",
    pdfContactNomeLabel: "Nome no PDF",
    pdfContactDepartamentoLabel: "Departamento no PDF",
    pdfContactEmailLabel: "E-mail no PDF",
    pdfContactTelefoneLabel: "Telefone no PDF",
    pdfObservacoesLabel: "Observações no PDF",
  },
};
