/** Copy da sala de interação (MFE) — labels PT fora do kit. */
export const INTERACTION_ROOMS_CONTENT = {
  inboxTitle: "Sala de interação",
  inboxSubtitle: "Conversas por pedido, conta, processo e murais da equipe.",
  inboxEmptyTitle: "Nenhuma sala ainda",
  inboxEmptyDescription:
    "Abra um pedido ou conta e use a sala na ficha, ou aguarde a caixa de entrada ser preenchida.",
  inboxListAriaLabel: "Salas de interação",
  inboxToolbarTitle: "Conversas",
  filtersAriaLabel: "Filtros da caixa de entrada",
  searchPlaceholder: "Buscar por título da sala",
  reloadLabel: "Atualizar",
  inboxMetaYesterday: "Ontem",
  selectRoomTitle: "Selecione uma sala",
  selectRoomDescription: "Escolha uma conversa na lista para ler e responder.",
  inboxResizeAriaLabel: "Redimensionar lista de salas",
  inboxCollapseAriaLabel: "Recolher lista de salas",
  inboxExpandAriaLabel: "Mostrar lista de salas",
  loadingLabel: "Carregando salas…",
  loadError: "Não foi possível carregar as salas.",
  unreadBadge: "{count} não lidas",
  filterAll: "Todas",
  filterUnread: "Não lidas",
  filterMentioned: "Menções",
  filterProcess: "Processos",
  filterWall: "Murais",
  kindEntity: "Entidade",
  kindProcess: "Processo",
  kindWall: "Mural",
  roomFallbackTitle: "Sala",
  roomEmptyTitle: "Nenhuma mensagem ainda",
  roomEmptyDescription: "Escreva a primeira mensagem nesta sala.",
  roomMissingId: "Sala inválida.",
  roomLoadingLabel: "Carregando a sala…",
  roomLoadError: "Não foi possível carregar a sala.",
  roomSendError: "Não foi possível enviar a mensagem.",
  roomMembersAriaLabel: "Participantes da sala",
  roomMessagesAriaLabel: "Mensagens da sala",
  messageDeleted: "Mensagem removida.",
  createTaskActionLabel: "Criar tarefa",
  createTaskOk: "Tarefa criada a partir da mensagem.",
  createTaskError: "Não foi possível criar a tarefa a partir da mensagem.",
  pinActionLabel: "Fixar",
  unpinActionLabel: "Desafixar",
  pinOk: "Mensagem fixada.",
  unpinOk: "Mensagem desafixada.",
  pinError: "Não foi possível alterar o pin da mensagem.",
  contextAbout: "Sobre",
  contextParticipants: "Participantes",
  contextPins: "Fixadas",
  contextPinsEmpty: "Nenhuma mensagem fixada",
  contextMembersEmpty: "Ninguém listado",
  contextSelectRoom: "Selecione uma sala para ver o contexto.",
  contextOpenEntity: "Abrir",
  contextToggle: "Neste chat",
  contextCloseAriaLabel: "Fechar contexto",
  contextSubtitleParticipantOne: "1 participante",
  contextSubtitleParticipants: "{count} participantes",
  contextSubtitlePinOne: "1 fixada",
  contextSubtitlePins: "{count} fixadas",
  roomAlertsAriaLabel: "Avisos da sala",
  alertDismissMs: 4000,
  composerPlaceholder: "Escreva uma mensagem… Use @ para mencionar.",
  composerSendAriaLabel: "Enviar mensagem",
  composerAttachAriaLabel: "Anexar arquivo",
  formatToggleAriaLabel: "Formatar",
  formatBoldAriaLabel: "Negrito",
  formatItalicAriaLabel: "Itálico",
  formatStrikeAriaLabel: "Riscado",
  formatUnderlineAriaLabel: "Sublinhado",
  formatListAriaLabel: "Lista",
  formatOrderedListAriaLabel: "Lista numerada",
  formatCodeAriaLabel: "Código",
  formatQuoteAriaLabel: "Citação",
  formatLinkAriaLabel: "Link",
  formatFontSizeAriaLabel: "Tamanho da fonte",
  formatFontSizeDecreaseAriaLabel: "Diminuir fonte",
  formatFontSizeIncreaseAriaLabel: "Aumentar fonte",
  formatUndoAriaLabel: "Desfazer",
  formatRedoAriaLabel: "Refazer",
  formatEmojiAriaLabel: "Emoji",
  emojiMenuAriaLabel: "Inserir emoji",
  composerMentionListAriaLabel: "Sugestões de menção",
  composerMentionEmptyLabel: "Nenhuma sugestão",
  panelTitle: "Sala de interação",
  panelOpenRoom: "Abrir sala",
  panelLoadingLabel: "Abrindo a sala…",
  panelResolveError: "Não foi possível abrir a sala nesta ficha.",
  panelEmptyTitle: "Nenhuma mensagem ainda",
  panelEmptyDescription: "A conversa deste registro fica registrada aqui.",
  panelMissingKey: "Registro incompleto para abrir a sala.",
  attachmentOnlyBody: "Anexo.",
  dropOverlayLabel: "Solte o arquivo para anexar",
  dropzoneHint: "PDF, imagem, TXT, Word ou Excel · máx. 10 MB",
  dropzoneBusyTitle: "Enviando anexos…",
  pendingAttachmentsHeading: "Arquivos a enviar",
  attachUploadError: "A mensagem foi enviada, mas um anexo falhou.",
  mentionKindGroupFallback: "Outros",
  mentionKindGroupLabels: {
    user: "Pessoas",
    customer: "Clientes",
    portfolio: "Carteiras",
    order: "Pedidos",
    opportunity: "Oportunidades",
    proposal: "Propostas",
    production_order: "Ordens de produção",
    otd_line: "Linhas OTD",
    invoice: "Notas fiscais",
    product: "Produtos",
  },
  unfurlPreviewKinds: [
    "customer",
    "portfolio",
    "order",
    "opportunity",
    "proposal",
    "production_order",
    "otd_line",
    "invoice",
    "product",
    "kpi",
    "goal",
    "raw_material",
  ],
  unfurlDeniedTitle: "Registro",
  unfurlDeniedLabel: "Sem acesso a este registro. Peça visibilidade da carteira.",
  unfurlOpenLabel: "Abrir",
  unfurlSubtitleFieldLabel: "Detalhe",
  unfurlFieldLabels: {
    status: "Status",
    um: "UM",
    value: "Valor",
  },
  panelNarrowHint: "Abra a conversa em um painel sem cobrir o menu do portal.",
  panelOpenDrawer: "Abrir conversa",
  drawerCloseAriaLabel: "Fechar sala",
} as const;

export function formatInteractionRoomContextSubtitle(
  entityKey: string | null | undefined,
  participantCount: number,
  pinCount: number,
): string {
  const bits: string[] = [];
  const key = (entityKey ?? "").trim();
  if (key) bits.push(key);
  if (participantCount === 1) {
    bits.push(INTERACTION_ROOMS_CONTENT.contextSubtitleParticipantOne);
  } else if (participantCount > 1) {
    bits.push(
      INTERACTION_ROOMS_CONTENT.contextSubtitleParticipants.replace(
        "{count}",
        String(participantCount),
      ),
    );
  }
  if (pinCount === 1) {
    bits.push(INTERACTION_ROOMS_CONTENT.contextSubtitlePinOne);
  } else if (pinCount > 1) {
    bits.push(
      INTERACTION_ROOMS_CONTENT.contextSubtitlePins.replace(
        "{count}",
        String(pinCount),
      ),
    );
  }
  return bits.join(" · ");
}
