/** Copy da sala de interação (MFE) — labels PT fora do kit. */
export const INTERACTION_ROOMS_CONTENT = {
  inboxTitle: "Sala de interação",
  inboxSubtitle: "Conversas por pedido, conta, processo e murais da equipe.",
  inboxEmptyTitle: "Nenhuma sala ainda",
  inboxEmptyDescription:
    "Abra um pedido ou conta e use a sala na ficha, ou aguarde a caixa de entrada ser preenchida.",
  inboxListAriaLabel: "Salas de interação",
  filtersAriaLabel: "Filtros da caixa de entrada",
  searchPlaceholder: "Buscar por título da sala",
  reloadLabel: "Atualizar",
  loadingLabel: "Carregando salas…",
  loadError: "Não foi possível carregar as salas.",
  unreadBadge: "{count} não lidas",
  filterAll: "Todas",
  filterUnread: "Não lidas",
  filterMentioned: "Menções",
  filterProcess: "Processos",
  filterWall: "Murais",
  kindEntity: "Entidade",
  kindProcess: "Processo",
  kindWall: "Mural",
  roomFallbackTitle: "Sala",
  roomEmptyTitle: "Nenhuma mensagem ainda",
  roomEmptyDescription: "Escreva a primeira mensagem nesta sala.",
  roomMissingId: "Sala inválida.",
  roomLoadingLabel: "Carregando a sala…",
  roomLoadError: "Não foi possível carregar a sala.",
  roomSendError: "Não foi possível enviar a mensagem.",
  roomMembersAriaLabel: "Participantes da sala",
  roomMessagesAriaLabel: "Mensagens da sala",
  messageDeleted: "Mensagem removida.",
  composerPlaceholder: "Escreva uma mensagem… Use @ para mencionar.",
  composerSendAriaLabel: "Enviar mensagem",
  composerAttachAriaLabel: "Anexar arquivo",
  composerMentionListAriaLabel: "Sugestões de menção",
  composerMentionEmptyLabel: "Nenhuma sugestão",
  panelTitle: "Sala de interação",
  panelOpenRoom: "Abrir sala",
  panelLoadingLabel: "Abrindo a sala…",
  panelResolveError: "Não foi possível abrir a sala nesta ficha.",
  panelEmptyTitle: "Nenhuma mensagem ainda",
  panelEmptyDescription: "A conversa deste registro fica registrada aqui.",
  panelMissingKey: "Registro incompleto para abrir a sala.",
} as const;
