"""Constants for DAVI dynamic governed READ (MCP broker tools)."""

from __future__ import annotations

MCP_TOOL_DISCOVER_DELPI_INFORMATION = "discover_delpi_information"
MCP_TOOL_DISCOVER_DELPI_INFORMATION_TITLE = "Discover DELPI information"
MCP_TOOL_EXECUTE_DELPI_INFORMATION = "execute_delpi_information"
MCP_TOOL_EXECUTE_DELPI_INFORMATION_TITLE = "Execute DELPI information"

STATUS_DAVI_ELIGIBLE_READ = "DAVI_ELIGIBLE_READ"
STATUS_NEEDS_MODEL_SAFE_PROJECTION = "NEEDS_MODEL_SAFE_PROJECTION"
STATUS_NEEDS_NESTED_PROJECTION_SUPPORT = "NEEDS_NESTED_PROJECTION_SUPPORT"
STATUS_NEEDS_BACKEND_AUTHZ_EVIDENCE = "NEEDS_BACKEND_AUTHZ_EVIDENCE"
STATUS_NEEDS_BOUNDED_EXECUTION = "NEEDS_BOUNDED_EXECUTION"
STATUS_EXPLICIT_PROCESSING_PROHIBITION = "EXPLICIT_PROCESSING_PROHIBITION"
STATUS_WRITE_OUT_OF_SCOPE = "WRITE_OUT_OF_SCOPE"
STATUS_DESTRUCTIVE_OUT_OF_SCOPE = "DESTRUCTIVE_OUT_OF_SCOPE"
STATUS_STREAM_BINARY_OUT_OF_SCOPE = "STREAM_BINARY_OUT_OF_SCOPE"
STATUS_GENERIC_SQL_FORBIDDEN = "GENERIC_SQL_FORBIDDEN"
STATUS_ADMIN_OUT_OF_SCOPE = "ADMIN_OUT_OF_SCOPE"
STATUS_LEGACY_UNSAFE = "LEGACY_UNSAFE"
STATUS_NOT_RELEVANT = "NOT_RELEVANT"
STATUS_INCONCLUSIVE = "INCONCLUSIVE"
STATUS_SEMANTICALLY_REDUNDANT = "SEMANTICALLY_REDUNDANT"

# Historical / superseded statuses (kept for residual evidence compatibility).
STATUS_NEEDS_EXTERNAL_PROJECTION = "NEEDS_EXTERNAL_PROJECTION"  # alias → MODEL_SAFE
STATUS_NEEDS_DATA_CLASSIFICATION = "NEEDS_DATA_CLASSIFICATION"  # SUPERSEDED as universal gate
STATUS_NEEDS_EXTERNAL_PROCESSING_APPROVAL = (
    "NEEDS_EXTERNAL_PROCESSING_APPROVAL"  # SUPERSEDED as universal gate
)
STATUS_NEEDS_AUTHZ_EVIDENCE = "NEEDS_AUTHZ_EVIDENCE"  # alias → BACKEND_AUTHZ
STATUS_NEEDS_BRANCH_AUTHZ_EVIDENCE = (
    "NEEDS_BRANCH_AUTHZ_EVIDENCE"  # SUPERSEDED by DAVI-READ-AUTHZ-REBASELINE-001
)

CLASSIFICATION_STATUSES = frozenset(
    {
        STATUS_DAVI_ELIGIBLE_READ,
        STATUS_NEEDS_MODEL_SAFE_PROJECTION,
        STATUS_NEEDS_NESTED_PROJECTION_SUPPORT,
        STATUS_NEEDS_BACKEND_AUTHZ_EVIDENCE,
        STATUS_NEEDS_BOUNDED_EXECUTION,
        STATUS_EXPLICIT_PROCESSING_PROHIBITION,
        STATUS_SEMANTICALLY_REDUNDANT,
        STATUS_NEEDS_EXTERNAL_PROJECTION,
        STATUS_NEEDS_DATA_CLASSIFICATION,
        STATUS_NEEDS_EXTERNAL_PROCESSING_APPROVAL,
        STATUS_NEEDS_AUTHZ_EVIDENCE,
        STATUS_NEEDS_BRANCH_AUTHZ_EVIDENCE,
        STATUS_WRITE_OUT_OF_SCOPE,
        STATUS_DESTRUCTIVE_OUT_OF_SCOPE,
        STATUS_STREAM_BINARY_OUT_OF_SCOPE,
        STATUS_GENERIC_SQL_FORBIDDEN,
        STATUS_ADMIN_OUT_OF_SCOPE,
        STATUS_LEGACY_UNSAFE,
        STATUS_NOT_RELEVANT,
        STATUS_INCONCLUSIVE,
    }
)
