export const copy = {
  productName: "Portal Financeiro",
  railAria: "Subplugins do Portal Financeiro",
  railBrand: "FIN",
  comingSoon: "Em breve",
  subpluginsError: "Não foi possível carregar os subplugins.",
  refresh: "Atualizar",
  retry: "Tentar novamente",
  empty: "Sem dados neste recorte.",
  branch: {
    label: "Filial",
    "01": "SC · 01",
    "02": "ES · 02",
    all: "Consolidado",
  },
  period: {
    label: "Período",
    from: "De",
    to: "até",
    apply: "Aplicar",
    reset: "Voltar ao padrão",
    shortcutsAria: "Atalhos de período",
    presets: {
      thisMonth: "Este mês",
      thisSemester: "Este semestre",
      thisYear: "Este ano",
    },
  },
  home: {
    title: "Gestão à vista",
    subtitle: "Resultado, caixa e disciplina financeira em uma tela só.",
    loading: "Montando a gestão à vista…",
    loadingHint: "Consultando resultado, inadimplência, despesas e indicadores.",
    loadError: "Não foi possível carregar a gestão à vista.",
    delinquencyTitle: "Inadimplência",
    delinquencySeries: "Pontualidade por mês",
    delinquencyEmpty: "Sem títulos baixados no período.",
    onTimeLabel: "Pontualidade",
    lateAmountLabel: "Valor em atraso",
    lateTitlesLabel: "Títulos em atraso",
    costCentersTitle: "Top centros de custo",
    costCentersEmpty: "Sem lançamentos no período.",
    costCentersTotal: "Total no período",
    indicatorsTitle: "Indicadores do Financeiro",
    indicatorsEmpty: "Nenhum indicador publicado nesta competência.",
    iddLabel: "IDD do Financeiro",
    goalLabel: "Meta",
    seeAll: "Ver tudo",
  },
  delinquency: {
    title: "Inadimplência",
    subtitle: "Pontualidade de pagamento dos clientes, por faixa de atraso e título.",
    loading: "Carregando a inadimplência…",
    loadError: "Não foi possível carregar a inadimplência.",
    kpiAria: "Indicadores de inadimplência",
    titlesLabel: "Títulos baixados",
    onTimeLabel: "Pagos em dia",
    lateLabel: "Pagos em atraso",
    punctualityLabel: "Pontualidade",
    averageDaysLate: "Atraso médio",
    seriesTitle: "Pontualidade por mês",
    seriesEmpty: "Sem títulos baixados no período.",
    agingTitle: "Maiores inadimplentes",
    agingEmpty: "Nenhum cliente com títulos em atraso neste recorte.",
    agingMetric: "Inadimplência (%)",
    customersTitle: "Clientes",
    customersEmpty: "Nenhum cliente neste recorte.",
    customersHint: "Clique em um cliente para ver os títulos baixados.",
    customerLabel: "Cliente",
    allCustomersOption: "Todos os clientes",
    customerOptionsError: "Não foi possível carregar a lista de clientes.",
    onlyWithDelays: "Só quem atrasou",
    scopeNotice: "A inadimplência é consolidada na origem: os valores somam as duas filiais.",
    periodPartial: "Informe início e fim do período juntos.",
    periodInvalid: "Informe datas válidas no formato AAAA-MM-DD.",
    periodInverted: "A data inicial não pode ser posterior à data final.",
    columns: {
      customer: "Cliente",
      titles: "Títulos",
      lateTitles: "Em atraso",
      totalAmount: "Valor total",
      lateAmount: "Valor em atraso",
      punctuality: "Pontualidade",
    },
    modal: {
      title: "Títulos do cliente",
      close: "Fechar",
      statusAll: "Todos",
      statusOnTime: "Em dia",
      statusLate: "Em atraso",
      empty: "Nenhum título neste recorte.",
      columns: {
        title: "Título",
        issue: "Emissão",
        due: "Vencimento",
        payment: "Baixa",
        amount: "Valor",
        delay: "Atraso",
      },
      onTime: "Em dia",
      daysLate: (days: number) => `${days} dia${days === 1 ? "" : "s"}`,
    },
    exportLabel: "Exportar Excel",
    exportFileName: "inadimplencia-clientes",
    exportSheetTitle: "Clientes",
    exportEmpty: "Não há clientes para exportar.",
  },
  costCenters: {
    title: "Despesas por centro de custo",
    subtitle: "Para onde o dinheiro foi: centro de custo, fornecedor e lançamento.",
    loading: "Carregando as despesas…",
    loadError: "Não foi possível carregar as despesas por centro de custo.",
    filtersAria: "Filtros de despesas por centro de custo",
    costCenterLabel: "Centro de custo",
    supplierLabel: "Fornecedor",
    allOption: "Todos",
    clearFilters: "Limpar filtros",
    excludeMpLabel: "Desconsiderar matérias-primas (MP)",
    kpiAria: "Indicadores de despesas",
    totalLabel: "Total no período",
    entriesLabel: "Lançamentos",
    centersLabel: "Centros de custo",
    suppliersLabel: "Fornecedores",
    averageTicketLabel: "Ticket médio",
    largestEntryLabel: "Maior lançamento",
    seriesTitle: "Despesa por mês",
    seriesEmpty: "Sem lançamentos no período.",
    rankingCentersTitle: "Centros de custo",
    rankingSuppliersTitle: "Fornecedores",
    rankingPreviewHint: "Top 10 no período",
    rankingExpand: "Expandir",
    rankingExpandCentersAria: "Expandir ranking de centros de custo",
    rankingExpandSuppliersAria: "Expandir ranking de fornecedores",
    rankingExpandedCentersSubtitle: "Top 50 centros de custo no período filtrado",
    rankingExpandedSuppliersSubtitle: "Top 50 fornecedores no período filtrado",
    rankingExpandedLoadError: "Não foi possível carregar o ranking expandido.",
    rankingDetailTitle: "Detalhamento",
    rankingEmpty: "Sem ranking no período.",
    rankingColumns: {
      rank: "#",
      code: "Código",
      store: "Código / loja",
      totalAmount: "Valor total",
      entryCount: "Lançamentos",
      percentage: "% do período",
    },
    entriesTitle: "Lançamentos",
    entriesEmpty: "Nenhum lançamento neste recorte.",
    entriesHint: "Clique em um lançamento para ver a nota, o item e o rateio.",
    searchPlaceholder: "Produto, documento, fornecedor…",
    columns: {
      issueDate: "Emissão",
      costCenter: "Centro de custo",
      supplier: "Fornecedor",
      document: "Documento",
      product: "Produto",
      notes: "Observações",
      quantity: "Qtd.",
      totalAmount: "Valor",
    },
    detail: {
      title: "Lançamento",
      close: "Fechar",
      documentSection: "Documento",
      productSection: "Produto",
      accountingSection: "Contabilização",
      branch: "Filial",
      issueDate: "Emissão",
      document: "Documento / série",
      purchaseOrder: "Pedido de compra",
      supplier: "Fornecedor",
      costCenter: "Centro de custo",
      product: "Produto",
      quantity: "Quantidade",
      unitAmount: "Valor unitário",
      totalAmount: "Valor total",
      ledgerAccount: "Conta contábil",
      apportionment: "Rateio",
      tes: "TES",
      cfop: "CFOP",
      documentType: "Tipo de documento",
      notes: "Observações",
    },
    exportLabel: "Exportar Excel",
    exportFileName: "despesas-centro-custo",
    exportSheetTitle: "Lançamentos",
    exportEmpty: "Não há lançamentos para exportar.",
  },
  indicators: {
    title: "Indicadores estratégicos",
    subtitle: "Nota IDD do Financeiro e IGD da Delpi, com meta e realizado por indicador.",
    loading: "Carregando os indicadores…",
    loadError: "Não foi possível carregar os indicadores estratégicos.",
    igdTitle: "IGD da Delpi",
    iddTitle: "IDD do Financeiro",
    unavailable: "Indicador indisponível no momento.",
    contribution: "Contribuição no IGD",
    bestDepartment: "Melhor departamento",
    primaryRisk: "Principal risco",
    competence: "Competência",
    tableTitle: "Indicadores do departamento",
    tableEmpty: "Nenhum indicador publicado nesta competência.",
    columns: {
      indicator: "Indicador",
      weight: "Peso",
      goal: "Meta",
      value: "Realizado",
      gap: "Gap",
      score: "Nota",
    },
    openDepartment: "Abrir ficha no Indicadores estratégicos",
    noValue: "—",
  },
  scoreOutOfTen: (score: string) => `${score} / 10`,
  table: {
    empty: "Sem linhas relacionadas.",
    loading: "Carregando…",
    sort: (header: string) => `Ordenar por ${header}`,
    sortByAriaLabel: (header: string) => `Ordenar por ${header}`,
    headerHelpAriaLabel: (header: string) => `Ajuda: ${header}`,
    searchPlaceholder: "Buscar na tabela…",
    searchAriaLabel: "Filtrar registros da tabela",
    searchHelpAriaLabel: "Ajuda: busca na tabela",
    recordsCount: (total: number) => `${total} cliente(s)`,
    refreshLoadingTitle: "Atualizando tabela",
    refreshLoadingDescription:
      "Mantendo os dados visíveis enquanto a nova consulta é aplicada.",
    initialLoadingTitle: "Carregando clientes",
    initialLoadingDescription: "Aguarde enquanto a lista de clientes é obtida.",
    titleHelpAriaLabel: (title: string) => `Ajuda: ${title}`,
  },
  pagination: {
    navigationAriaLabel: "Paginação",
    pagesAriaLabel: "Páginas",
    previous: "Anterior",
    next: "Próxima",
    info: ({
      rangeStart,
      rangeEnd,
      total,
    }: {
      rangeStart: number;
      rangeEnd: number;
      total: number;
      page: number;
      totalPages: number;
    }) => `${rangeStart}–${rangeEnd} de ${total}`,
    jumpLabel: "Ir para",
    jumpInputAriaLabel: "Número da página",
    jumpError: (reason: string, totalPages: number) =>
      reason === "out_of_range" ? `Informe uma página entre 1 e ${totalPages}.` : "Página inválida.",
    pageSizeLabel: "Por página",
    pageSizeAria: "Registros por página",
  },
} as const;
