export const copy = {
  productName: "Portal Financeiro",
  railAria: "Subplugins do Portal Financeiro",
  railBrand: "FIN",
  periodFilter: {
    title: "Período da consulta",
    from: "De",
    to: "Até",
    apply: "Aplicar",
    reset: "Voltar ao padrão",
    openAria: "Alterar período da consulta",
    closeAria: "Fechar filtro de período",
    invalid: "Informe datas válidas (AAAA-MM-DD).",
    inverted: "A data inicial não pode ser depois da final.",
  },
  comingSoon: "Em breve",
  subpluginsError: "Não foi possível carregar os subplugins.",
  refresh: "Atualizar",
  retry: "Tentar novamente",
  empty: "Sem dados neste recorte.",
  branch: {
    label: "Filial",
    "01": "SC · 01",
    "02": "ES · 02",
    all: "Consolidado",
  },
  period: {
    label: "Período",
    from: "De",
    to: "até",
    apply: "Aplicar",
    reset: "Voltar ao padrão",
    shortcutsAria: "Atalhos de período",
    presets: {
      thisMonth: "Este mês",
      thisSemester: "Este semestre",
      thisYear: "Este ano",
    },
  },
  home: {
    title: "Gestão à vista",
    subtitle: "Resultado, caixa e disciplina financeira em uma tela só.",
    loading: "Montando a gestão à vista…",
    loadingHint: "Consultando resultado, inadimplência, despesas e indicadores.",
    loadError: "Não foi possível carregar a gestão à vista.",
    delinquencyTitle: "Inadimplência",
    delinquencySeries: "Pontualidade por mês",
    delinquencyEmpty: "Sem títulos baixados no período.",
    onTimeLabel: "Pontualidade",
    lateAmountLabel: "Valor em atraso",
    lateTitlesLabel: "Títulos em atraso",
    costCentersTitle: "Top centros de custo",
    costCentersEmpty: "Sem lançamentos no período.",
    costCentersTotal: "Total no período",
    indicatorsTitle: "Indicadores do Financeiro",
    indicatorsEmpty: "Nenhum indicador publicado nesta competência.",
    iddLabel: "IDD do Financeiro",
    goalLabel: "Meta",
    seeAll: "Ver tudo",
    openBilling: "Abrir faturamento",
  },
  billing: {
    title: "Faturamento",
    subtitle: "De onde vem a receita: composição da ROL, evolução e quem fatura no período.",
    loading: "Montando o faturamento…",
    loadingHint: "Consultando receita bruta, impostos, série e ranking de clientes.",
    loadError: "Não foi possível carregar o faturamento.",
    heroEyebrow: "Receita operacional líquida",
    vsGoal: "versus meta",
    gapAbove: "acima da meta",
    gapBelow: "abaixo da meta",
    onTrack: "No ritmo da meta",
    offTrack: "Abaixo da meta",
    noGoal: "Sem meta cadastrada neste recorte.",
    kpiAria: "Indicadores de faturamento",
    grossLabel: "Receita bruta",
    taxesLabel: "Impostos",
    returnsLabel: "Devoluções",
    discountsLabel: "Descontos",
    gapLabel: "Gap vs meta",
    seriesTitle: "Evolução da ROL",
    seriesHint: "Últimos 12 meses na visão mensal, independente do período filtrado nos demais painéis.",
    seriesEmpty: "Sem pontos de faturamento no período.",
    series01: "Santa Catarina",
    series02: "Espírito Santo",
    granularityAria: "Granularidade da série",
    granularity: {
      day: "Dia",
      week: "Semana",
      month: "Mês",
      year: "Ano",
    },
    waterfallTitle: "Cálculo da ROL",
    waterfallHint: "Demonstração do bruto até a receita líquida.",
    statementMovement: "Movimento",
    statementBalance: "Saldo",
    statementPlus: "+",
    statementMinus: "−",
    statementEquals: "=",
    taxMixTitle: "Impostos na nota",
    taxMixEmpty: "Sem impostos destacados neste recorte.",
    unitsTitle: "Unidades",
    unitsEmpty: "Sem faturamento por unidade no período.",
    customersTitle: "Quem mais fatura",
    customersEmpty: "Nenhum cliente com faturamento neste recorte.",
    customersHint: "Participação na ROL do período.",
    rolShort: "ROL",
    othersLabel: "Demais clientes",
    detailTitle: "Composição completa",
    detailEmpty: "Sem composição de ROL para o período.",
    columns: {
      component: "Componente",
      value: "Valor",
      customer: "Cliente",
      share: "Share",
      unit: "Unidade",
    },
    exportLabel: "Exportar composição",
    exportFileName: "faturamento-rol",
    exportSheetTitle: "Composição",
    exportEmpty: "Não há linhas para exportar.",
    exportExtractLabel: "Extrato de títulos",
    exportExtractBusy: "Gerando extrato…",
    exportExtractFileName: "extrato-titulos-rol",
    exportExtractSheetTitle: "Títulos",
    exportExtractEmpty: "Não há notas no período para exportar.",
    exportExtractError: "Não foi possível gerar o extrato de títulos.",
    exportExtractTruncated:
      "O extrato atingiu o limite de notas deste recorte. A soma do Excel pode ficar abaixo da ROL da tela.",
    extractColumns: {
      kind: "Tipo",
      branch: "Filial",
      issueDate: "Emissão",
      invoiceNumber: "Nota",
      series: "Série",
      customerCode: "Código",
      customerStore: "Loja",
      customerName: "Cliente",
      gross: "Receita bruta",
      discounts: "Descontos",
      returns: "Devolução",
      taxes: "Impostos",
      rol: "ROL",
    },
  },
  delinquency: {
    title: "Inadimplência",
    subtitle: "Pontualidade de pagamento dos clientes, por faixa de atraso e título.",
    loading: "Carregando a inadimplência…",
    loadError: "Não foi possível carregar a inadimplência.",
    kpiAria: "Indicadores de inadimplência",
    titlesLabel: "Títulos baixados",
    onTimeLabel: "Pagos em dia",
    lateLabel: "Pagos em atraso",
    punctualityLabel: "Pontualidade",
    averageDaysLate: "Atraso médio",
    seriesTitle: "Pontualidade por mês",
    seriesHint: "Últimos 12 meses, independente do período filtrado nos demais painéis.",
    seriesEmpty: "Sem títulos baixados nos últimos 12 meses.",
    agingTitle: "Maiores inadimplentes do mês",
    agingEmpty: "Nenhum cliente com títulos em atraso neste mês.",
    agingMetric: "Inadimplência (%)",
    customersTitle: "Clientes",
    customersEmpty: "Nenhum cliente neste recorte.",
    customersHint: "Clique em um cliente para ver os títulos baixados.",
    customerLabel: "Cliente",
    allCustomersOption: "Todos os clientes",
    customerOptionsError: "Não foi possível carregar a lista de clientes.",
    onlyWithDelays: "Só quem atrasou",
    scopeNotice: "A inadimplência é consolidada na origem: os valores somam as duas filiais.",
    periodPartial: "Informe início e fim do período juntos.",
    periodInvalid: "Informe datas válidas no formato AAAA-MM-DD.",
    periodInverted: "A data inicial não pode ser posterior à data final.",
    columns: {
      customer: "Cliente",
      titles: "Títulos",
      lateTitles: "Em atraso",
      totalAmount: "Valor total",
      lateAmount: "Valor em atraso",
      punctuality: "Pontualidade",
    },
    modal: {
      title: "Títulos do cliente",
      close: "Fechar",
      statusAll: "Todos",
      statusOnTime: "Em dia",
      statusLate: "Em atraso",
      empty: "Nenhum título neste recorte.",
      columns: {
        title: "Título",
        issue: "Emissão",
        due: "Vencimento",
        payment: "Baixa",
        amount: "Valor",
        delay: "Atraso",
      },
      onTime: "Em dia",
      daysLate: (days: number) => `${days} dia${days === 1 ? "" : "s"}`,
    },
    exportLabel: "Exportar Excel",
    exportFileName: "inadimplencia-clientes",
    exportSheetTitle: "Clientes",
    exportEmpty: "Não há clientes para exportar.",
  },
  costCenters: {
    title: "Despesas por centro de custo",
    subtitle: "Para onde o dinheiro foi: centro de custo, fornecedor e lançamento.",
    loading: "Carregando as despesas…",
    loadError: "Não foi possível carregar as despesas por centro de custo.",
    filtersAria: "Filtros de despesas por centro de custo",
    costCenterLabel: "Centro de custo",
    supplierLabel: "Fornecedor",
    allOption: "Todos",
    clearFilters: "Limpar filtros",
    excludeMpLabel: "Desconsiderar matérias-primas (MP)",
    kpiAria: "Indicadores de despesas",
    totalLabel: "Total no período",
    entriesLabel: "Lançamentos",
    centersLabel: "Centros de custo",
    suppliersLabel: "Fornecedores",
    averageTicketLabel: "Ticket médio",
    largestEntryLabel: "Maior lançamento",
    seriesTitle: "Despesa por mês",
    seriesHint:
      "Últimos 12 meses, respeitando filial, centro de custo e fornecedor selecionados. Clique no mês para ver o detalhamento.",
    seriesEmpty: "Sem lançamentos no período.",
    rankingCentersTitle: "Centros de custo",
    rankingSuppliersTitle: "Fornecedores",
    rankingPreviewHint: "Top 10 no período",
    rankingExpand: "Expandir",
    rankingExpandCentersAria: "Expandir ranking de centros de custo",
    rankingExpandSuppliersAria: "Expandir ranking de fornecedores",
    rankingExpandedCentersSubtitle: "Top 50 centros de custo no período filtrado",
    rankingExpandedSuppliersSubtitle: "Top 50 fornecedores no período filtrado",
    rankingExpandedLoadError: "Não foi possível carregar o ranking expandido.",
    rankingDetailTitle: "Detalhamento",
    rankingEmpty: "Sem ranking no período.",
    rankingColumns: {
      rank: "#",
      code: "Código",
      store: "Código / loja",
      totalAmount: "Valor total",
      entryCount: "Lançamentos",
      percentage: "% do período",
    },
    entriesTitle: "Lançamentos",
    entriesEmpty: "Nenhum lançamento neste recorte.",
    entriesHint: "Clique em um lançamento para ver a nota, o item e o rateio.",
    searchPlaceholder: "Produto, documento, fornecedor…",
    columns: {
      issueDate: "Emissão",
      costCenter: "Centro de custo",
      supplier: "Fornecedor",
      document: "Documento",
      product: "Produto",
      notes: "Observações",
      quantity: "Qtd.",
      totalAmount: "Valor",
    },
    detail: {
      title: "Lançamento",
      close: "Fechar",
      documentSection: "Documento",
      productSection: "Produto",
      accountingSection: "Contabilização",
      branch: "Filial",
      issueDate: "Emissão",
      document: "Documento / série",
      purchaseOrder: "Pedido de compra",
      supplier: "Fornecedor",
      costCenter: "Centro de custo",
      product: "Produto",
      quantity: "Quantidade",
      unitAmount: "Valor unitário",
      totalAmount: "Valor total",
      ledgerAccount: "Conta contábil",
      apportionment: "Rateio",
      tes: "TES",
      cfop: "CFOP",
      documentType: "Tipo de documento",
      notes: "Observações",
    },
    exportLabel: "Exportar Excel",
    exportFileName: "despesas-centro-custo",
    exportSheetTitle: "Lançamentos",
    exportEmpty: "Não há lançamentos para exportar.",
    monthDetail: {
      title: (month: string) => `Despesas de ${month}`,
      subtitle: "Detalhamento do mês: centros de custo, fornecedores e cada lançamento.",
      loading: "Carregando o detalhamento do mês…",
      invalidMonth: "Mês inválido para o detalhamento de despesas.",
      back: "Voltar",
      backAria: "Voltar para as despesas por centro de custo",
      heroLabel: "Total no mês",
      heroCompare: (month: string) => `vs ${month}`,
      heroNoBase: "Sem base de comparação no mês anterior.",
      totalLabel: "Total no mês",
      kpiAria: "Indicadores do mês",
      rankingPreviewHint: "Top 10 no mês",
      rankingExpandedCentersSubtitle: "Top 50 centros de custo no mês",
      rankingExpandedSuppliersSubtitle: "Top 50 fornecedores no mês",
      entriesTitle: "Lançamentos do mês",
      exportFileName: (month: string) => `despesas-${month}`,
      filtersLabel: {
        costCenter: (label: string) => `Centro ${label}`,
        supplier: (label: string) => `Fornecedor ${label}`,
        excludeMp: "Sem matérias-primas",
      },
    },
  },
  freight: {
    title: "Frete das compras",
    subtitle:
      "Quanto o frete pesa em cada nota de compra: CT-es amarrados, rateio proporcional e quem passou do limite.",
    loading: "Analisando o frete das compras…",
    loadingHint: "Buscando vínculos NF × CT-e no Protheus e rateando o valor bruto.",
    loadError: "Não foi possível carregar o frete das compras.",
    filtersAria: "Filtros do frete das compras",
    issuePeriodLabel: "Emissão da NF",
    entryPeriodLabel: "Digitação da NF",
    supplierLabel: "Fornecedor",
    invoiceLabel: "Nota fiscal",
    freightDocumentLabel: "CT-e",
    situationLabel: "Situação",
    clearFilters: "Limpar filtros",
    periodRequired: "Informe um intervalo de emissão ou de digitação da nota fiscal.",
    situations: {
      all: "Todas",
      normal: "Dentro do limite",
      above_limit: "Acima do limite",
      inconsistent: "Inconsistente",
    },
    kpiAria: "Indicadores de frete das compras",
    invoiceCountLabel: "NFs com frete",
    goodsTotalLabel: "Total de mercadoria",
    freightTotalLabel: "Total de frete rateado",
    freightPercentLabel: "% frete do período",
    aboveLimitLabel: "NFs acima do limite",
    inconsistentLabel: "Vínculos inconsistentes",
    limitsTitle: "Limites por filial",
    limitsHint: "Percentual máximo aceito de frete sobre o valor da mercadoria.",
    invoicesTitle: "Notas de compra com frete",
    invoicesHint: "Clique na nota para ver os CT-es amarrados e o rateio de cada um.",
    invoicesEmpty: "Nenhuma nota de compra com frete neste recorte.",
    truncatedNotice:
      "O volume de vínculos atingiu o limite da consulta. Reduza o período para conferir os totais.",
    noLimitBadge: "Sem limite configurado",
    columns: {
      branch: "Filial",
      invoice: "NF",
      supplier: "Fornecedor",
      issueDate: "Emissão",
      entryDate: "Digitação",
      goodsValue: "Mercadoria",
      freightTotal: "Frete rateado",
      freightPercent: "% frete",
      freightLimit: "Limite",
      situation: "Situação",
      freightDocumentCount: "CT-es",
    },
    detail: {
      title: "Frete da nota",
      close: "Fechar",
      invoiceSection: "Nota de compra",
      allocationsSection: "CT-es amarrados",
      branch: "Filial",
      invoice: "NF / série",
      supplier: "Fornecedor",
      issueDate: "Emissão",
      entryDate: "Digitação",
      goodsValue: "Valor da mercadoria",
      freightTotal: "Frete rateado",
      freightPercent: "% frete",
      freightLimit: "Limite da filial",
      situation: "Situação",
      reasons: "Ressalvas",
      partialBase: "base dividida com outras notas",
      empty: "Nenhum CT-e amarrado a esta nota.",
      columns: {
        freightDocument: "CT-e",
        carrier: "Transportadora",
        freightIssueDate: "Emissão",
        freightGrossValue: "Valor bruto",
        allocationBase: "Base do rateio",
        allocatedValue: "Rateado nesta NF",
        linkedInvoiceCount: "NFs no CT-e",
      },
    },
    inconsistencies: {
      title: "Vínculos inconsistentes",
      hint: "Vínculos que não entram no percentual — precisam de correção no Protheus.",
      empty: "Nenhuma inconsistência neste recorte.",
      loadError: "Não foi possível carregar as inconsistências de frete.",
      show: "Ver inconsistências",
      hide: "Ocultar inconsistências",
      columns: {
        reason: "Motivo",
        branch: "Filial",
        invoice: "NF",
        supplier: "Fornecedor",
        freightDocument: "CT-e",
        carrier: "Transportadora",
        goodsValue: "Mercadoria",
        freightGrossValue: "Valor bruto do CT-e",
      },
      totalsTitle: "Inconsistências por motivo",
      countLabel: "Vínculos",
      exportLabel: "Exportar inconsistências",
      exportBusy: "Gerando inconsistências…",
      exportFileName: "frete-inconsistencias",
      exportSheetTitle: "Inconsistências",
      exportEmpty: "Não há inconsistências para exportar.",
      exportError: "Não foi possível exportar as inconsistências de frete.",
    },
    exportLabel: "Exportar Excel",
    exportBusy: "Gerando Excel…",
    exportFileName: "frete-compras",
    exportSheetTitle: "Notas com frete",
    exportEmpty: "Não há notas para exportar.",
    exportError: "Não foi possível exportar o frete das compras.",
  },
  indicators: {
    title: "Indicadores estratégicos",
    subtitle: "Nota IDD do Financeiro e IGD da Delpi, com meta e realizado por indicador.",
    loading: "Carregando os indicadores…",
    loadError: "Não foi possível carregar os indicadores estratégicos.",
    igdTitle: "IGD da Delpi",
    iddTitle: "IDD do Financeiro",
    unavailable: "Indicador indisponível no momento.",
    contribution: "Contribuição no IGD",
    bestDepartment: "Melhor departamento",
    primaryRisk: "Principal risco",
    competence: "Competência",
    tableTitle: "Indicadores do departamento",
    tableEmpty: "Nenhum indicador publicado nesta competência.",
    columns: {
      indicator: "Indicador",
      weight: "Peso",
      goal: "Meta",
      value: "Realizado",
      gap: "Gap",
      score: "Nota",
    },
    openDepartment: "Abrir ficha no Indicadores estratégicos",
    noValue: "—",
  },
  scoreOutOfTen: (score: string) => `${score} / 10`,
  table: {
    empty: "Sem linhas relacionadas.",
    loading: "Carregando…",
    sort: (header: string) => `Ordenar por ${header}`,
    sortByAriaLabel: (header: string) => `Ordenar por ${header}`,
    headerHelpAriaLabel: (header: string) => `Ajuda: ${header}`,
    searchPlaceholder: "Buscar na tabela…",
    searchAriaLabel: "Filtrar registros da tabela",
    searchHelpAriaLabel: "Ajuda: busca na tabela",
    recordsCount: (total: number) => `${total} cliente(s)`,
    refreshLoadingTitle: "Atualizando tabela",
    refreshLoadingDescription:
      "Mantendo os dados visíveis enquanto a nova consulta é aplicada.",
    initialLoadingTitle: "Carregando clientes",
    initialLoadingDescription: "Aguarde enquanto a lista de clientes é obtida.",
    titleHelpAriaLabel: (title: string) => `Ajuda: ${title}`,
  },
  pagination: {
    navigationAriaLabel: "Paginação",
    pagesAriaLabel: "Páginas",
    previous: "Anterior",
    next: "Próxima",
    info: ({
      rangeStart,
      rangeEnd,
      total,
    }: {
      rangeStart: number;
      rangeEnd: number;
      total: number;
      page: number;
      totalPages: number;
    }) => `${rangeStart}–${rangeEnd} de ${total}`,
    jumpLabel: "Ir para",
    jumpInputAriaLabel: "Número da página",
    jumpError: (reason: string, totalPages: number) =>
      reason === "out_of_range" ? `Informe uma página entre 1 e ${totalPages}.` : "Página inválida.",
    pageSizeLabel: "Por página",
    pageSizeAria: "Registros por página",
  },
} as const;
