import type { CatalogFamily } from "./types";

/**
 * Inventário canônico de componentes React visuais exportados por `@delpi/plugin-ui`.
 * O catálogo deve ter uma entrada por `exportName` (teste de cobertura).
 * Helpers BEM, factories `create*`, tipos e constantes não entram aqui.
 */
export type VisualComponentSpec = {
  family: CatalogFamily;
  exportName: string;
  description?: string;
};

export const VISUAL_COMPONENTS: VisualComponentSpec[] = [
  // help
  { family: "help", exportName: "HelpTooltip" },
  { family: "help", exportName: "FieldLabel" },
  { family: "help", exportName: "SectionHintLabel" },
  { family: "help", exportName: "TabHintCell" },
  { family: "help", exportName: "HintAction" },
  { family: "help", exportName: "TitleWithHelp" },
  // layout
  { family: "layout", exportName: "PageHeader" },
  { family: "layout", exportName: "PanelCard" },
  { family: "layout", exportName: "ContentCard" },
  { family: "layout", exportName: "KpiCard" },
  { family: "layout", exportName: "DelpiKpiCard" },
  { family: "layout", exportName: "SimpleKpiCard" },
  { family: "layout", exportName: "MetricKpiCard" },
  { family: "layout", exportName: "ChartCard" },
  { family: "layout", exportName: "ChartToolbar" },
  { family: "layout", exportName: "ChartGranularityToggle" },
  { family: "layout", exportName: "FiltersRow" },
  { family: "layout", exportName: "FilterBar" },
  { family: "layout", exportName: "FilterBarShell" },
  { family: "layout", exportName: "FilterInputField" },
  { family: "layout", exportName: "FilterSelectField" },
  { family: "layout", exportName: "SectionCard" },
  { family: "layout", exportName: "SectionBlock" },
  { family: "layout", exportName: "EditableSectionCard" },
  { family: "layout", exportName: "DetailCard" },
  { family: "layout", exportName: "DetailFieldGrid" },
  { family: "layout", exportName: "FormGrid" },
  { family: "layout", exportName: "FormActions" },
  { family: "layout", exportName: "FormatPaneShell" },
  { family: "layout", exportName: "FormatPaneSection" },
  { family: "layout", exportName: "FitText" },
  // feedback
  { family: "feedback", exportName: "EmptyState" },
  { family: "feedback", exportName: "LoadingState" },
  { family: "feedback", exportName: "LoadingActivityCard" },
  { family: "feedback", exportName: "StateBanner" },
  { family: "feedback", exportName: "StateBoxPanel" },
  { family: "feedback", exportName: "InfoStatePanel" },
  { family: "feedback", exportName: "StatusBadge" },
  { family: "feedback", exportName: "ModalShell" },
  { family: "feedback", exportName: "DrawerShell" },
  { family: "feedback", exportName: "ConfirmModalPanel" },
  // data
  { family: "data", exportName: "DataTable" },
  { family: "data", exportName: "DataTableSection" },
  { family: "data", exportName: "Pagination" },
  { family: "data", exportName: "CompactPagination" },
  { family: "data", exportName: "TablePaginationNav" },
  { family: "data", exportName: "TablePageSizeSelect" },
  { family: "data", exportName: "TableHeaderCell" },
  { family: "data", exportName: "TableHeaderContent" },
  { family: "data", exportName: "ConfigurablePresentationTable" },
  { family: "data", exportName: "ConfigurableTable" },
  { family: "data", exportName: "DataRouteCatalogPanel" },
  // forms
  { family: "forms", exportName: "SelectField" },
  { family: "forms", exportName: "SelectControl" },
  { family: "forms", exportName: "DateField" },
  { family: "forms", exportName: "TextField" },
  { family: "forms", exportName: "TextAreaField" },
  { family: "forms", exportName: "MultiSelectField" },
  { family: "forms", exportName: "ReadOnlyField" },
  { family: "forms", exportName: "FileDropzone" },
  { family: "forms", exportName: "FilterCheckboxField" },
  { family: "forms", exportName: "FormFieldShell" },
  { family: "forms", exportName: "FormSelectControl" },
  { family: "forms", exportName: "ToolbarSelectField" },
  { family: "forms", exportName: "ToolbarSelectControl" },
  { family: "forms", exportName: "NativeTextField" },
  { family: "forms", exportName: "NativeTextAreaField" },
  { family: "forms", exportName: "NativeSelectField" },
  { family: "forms", exportName: "NativeTextControl" },
  { family: "forms", exportName: "NativeTextAreaControl" },
  { family: "forms", exportName: "NativeSelectControl" },
  { family: "forms", exportName: "NativeCheckboxControl" },
  { family: "forms", exportName: "NativeSwitchControl" },
  { family: "data", exportName: "TableColumnVisibilityMenu" },
  { family: "forms", exportName: "ComboboxNumberControl" },
  { family: "forms", exportName: "EditableTableCell" },
  { family: "forms", exportName: "LucideIconPicker" },
  { family: "forms", exportName: "LucideIconGridPanel" },
  { family: "forms", exportName: "LucideIconByName" },
  // export
  { family: "export", exportName: "TabularExportButtons" },
  { family: "export", exportName: "DocumentExportActions" },
  { family: "export", exportName: "ExcelExportButton" },
  // charts
  { family: "charts", exportName: "ConfigurableSeriesChart" },
  { family: "charts", exportName: "LineSeriesChart" },
  { family: "charts", exportName: "BarSeriesChart" },
  { family: "charts", exportName: "SeriesChartPrimitive" },
  { family: "charts", exportName: "ImpactEffortMatrix" },
  { family: "charts", exportName: "ImpactEffortMatrixLegend" },
  { family: "charts", exportName: "ChartTypeCatalogPanel" },
  { family: "charts", exportName: "TableInsertCatalogPanel" },
  // preview
  { family: "preview", exportName: "FilePreviewModal" },
  { family: "preview", exportName: "FilePreviewView" },
  { family: "preview", exportName: "FilePreviewMetaFooter" },
  { family: "preview", exportName: "CenteredScaledPreview" },
  { family: "preview", exportName: "SpreadsheetPreview" },
  { family: "preview", exportName: "DocxPreview" },
  // diagram
  { family: "diagram", exportName: "FlowchartEditor" },
  { family: "diagram", exportName: "DiagramMermaidPreview" },
  { family: "diagram", exportName: "DiagramFullscreenFrame" },
  { family: "diagram", exportName: "TabPanelTransition" },
  // shape
  { family: "shape", exportName: "ShapeFillMenu" },
  { family: "shape", exportName: "ShapeOutlineMenu" },
  { family: "shape", exportName: "ShapeEffectsMenu" },
  { family: "shape", exportName: "ShapeShadowMenu" },
  { family: "shape", exportName: "ShapeStyleMenu" },
  { family: "shape", exportName: "ShapeStyleGallery" },
  { family: "shape", exportName: "ColorDialog" },
  { family: "shape", exportName: "ColorPickerPopover" },
  { family: "shape", exportName: "RibbonColorPicker" },
  { family: "shape", exportName: "ColorThemeGrid" },
  { family: "shape", exportName: "ColorStandardRow" },
  { family: "shape", exportName: "ColorSwatch" },
  // menu
  { family: "menu", exportName: "ContextMenu" },
  { family: "menu", exportName: "ContextMenuItem" },
  { family: "menu", exportName: "ContextMenuDivider" },
  { family: "menu", exportName: "ContextMenuToolbar" },
  { family: "menu", exportName: "ContextMenuToolbarButton" },
];
