import type { ShapeColorLabels } from "./types";

export const DEFAULT_SHAPE_COLOR_LABELS: Required<ShapeColorLabels> = {
  themeColors: "Cores do Tema",
  recentColors: "Cores recentes",
  standardColors: "Cores Padrão",
  noFill: "Sem fundo",
  noOutline: "Sem contorno",
  automatic: "Automático",
  moreColors: "Mais cores…",
  eyedropper: "Conta-gotas",
  image: "Imagem…",
  gradient: "Gradiente…",
  texture: "Textura…",
  fill: "Preenchimento",
  outline: "Contorno",
  thickness: "Espessura",
  dashed: "Esboçado",
  lineStyle: "Traços",
  arrows: "Setas",
  effects: "Efeitos",
  preset: "Predefinição",
  shadow: "Sombra",
  shadowOffsetX: "X",
  shadowOffsetY: "Y",
  shadowBlur: "Desfoque",
  shadowSpread: "Expansão",
  shadowOpacity: "Opacidade %",
  shadowColor: "Cor da sombra",
  shadowCustom: "Personalizada",
  shadowOuter: "Externa",
  shadowInner: "Interna",
  shadowLayer: "Camada",
  shadowAddLayer: "Camada",
  shadowRemoveLayer: "Remover",
  shadowPreview: "Pré-visualização",
  reflection: "Reflexo",
  glow: "Brilho",
  softEdges: "Bordas suaves",
  bevel: "Bisel",
  rotation3d: "Rotação 3D",
  themeStyles: "Estilos de Tema",
  presets: "Predefinições",
  colorDialogTitle: "Cores",
  tabStandard: "Padrão",
  tabCustom: "Personalizar",
  newColor: "Nova",
  currentColor: "Atual",
  red: "Vermelho",
  green: "Verde",
  blue: "Azul",
  hex: "Hex",
  transparency: "Transparência",
  colorModel: "Modelo de Cores:",
  ok: "OK",
  cancel: "Cancelar",
};

export function mergeShapeColorLabels(labels?: ShapeColorLabels): Required<ShapeColorLabels> {
  return { ...DEFAULT_SHAPE_COLOR_LABELS, ...labels };
}
