BEGIN;

-- Awaiting requester confirmation: only the owner may cancel; staff must wait for confirm/reject.

UPDATE my_requests.request_types
SET
    workflow_definition = '{"initialStatus":"submitted","terminalStatuses":["completed","cancelled","rejected"],"fileImmutableStatuses":["awaiting_requester_confirmation"],"statusAliases":{"submitted":"pending","needs_information":"returned","awaiting_requester_confirmation":"awaiting_confirmation","completed":"issued"},"journey":{"stages":[{"id":"intake","label":"Solicitação criada"},{"id":"service","label":"Em atendimento"},{"id":"closure","label":"Conclusão"}],"statusMappings":[{"statuses":["submitted"],"stageId":"intake","progressPercent":33,"outcome":"in_progress"},{"statuses":["in_progress"],"stageId":"service","progressPercent":66,"outcome":"in_progress"},{"statuses":["needs_information"],"stageId":"service","progressPercent":66,"outcome":"waiting_requester","summary":"Aguardando informação do solicitante"},{"statuses":["awaiting_requester_confirmation"],"stageId":"closure","progressPercent":90,"outcome":"waiting_requester","summary":"Aguardando confirmação do solicitante"},{"statuses":["completed"],"stageId":"closure","progressPercent":100,"outcome":"succeeded"},{"statuses":["cancelled"],"stageId":"service","progressPercent":66,"outcome":"cancelled","summary":"Solicitação cancelada"},{"statuses":["rejected"],"stageId":"service","progressPercent":66,"outcome":"rejected","summary":"Solicitação rejeitada"}]},"computedActions":[{"action":"view","requires":{"ownershipOr":["view_all","process","manage"]}},{"action":"edit","whenStatus":["needs_information"],"requires":{"permissions":["create"],"ownership":true}}],"transitions":[{"action":"start","from":["submitted"],"to":"in_progress","requires":{"permissionsAny":["process","manage"]},"assignSelf":true},{"action":"return","from":["in_progress"],"to":"needs_information","requires":{"permissionsAny":["process","manage"],"fields":["return_reason"]}},{"action":"resubmit","from":["needs_information"],"to":"submitted","requires":{"permissions":["create"],"ownership":true}},{"action":"complete","from":["in_progress"],"to":"awaiting_requester_confirmation","requires":{"permissionsAny":["process","manage"],"artifacts":{"minCount":1,"kindsAny":["invoice_pdf"]}},"actionAlias":"issue"},{"action":"confirm_fulfillment","from":["awaiting_requester_confirmation"],"to":"completed","requires":{"permissions":["create"],"ownership":true}},{"action":"reject_fulfillment","from":["awaiting_requester_confirmation"],"to":"in_progress","requires":{"permissions":["create"],"ownership":true,"fields":["return_reason"]}},{"action":"cancel","from":["submitted","in_progress","needs_information","awaiting_requester_confirmation"],"to":"cancelled","requires":{"anyOf":[{"permissions":["create"],"ownership":true,"from":["submitted","awaiting_requester_confirmation"]},{"permissions":["process"],"from":["in_progress"]},{"permissions":["manage"],"from":["submitted","in_progress","needs_information"]}],"fields":["cancel_justification"]}}]}'::jsonb,
    updated_at = NOW()
WHERE code = 'invoice-issuance';

COMMIT;
