"""Fragmentos SQL compartilhados para OEE (eficiência por tempos em SH6010)."""

from app.domain.production.production_efficiency_valid_range import (
    PRODUCTION_EFFICIENCY_VALID_MAX_PCT,
    PRODUCTION_EFFICIENCY_VALID_MIN_PCT,
)

OEE_REAL_HOURS_EXPR = """
CASE
    WHEN H6.H6_DATAINI IS NOT NULL
     AND H6.H6_DATAFIN IS NOT NULL
     AND LTRIM(RTRIM(H6.H6_DATAINI)) <> ''
     AND LTRIM(RTRIM(H6.H6_DATAFIN)) <> ''
    THEN CAST(
        DATEDIFF(
            MINUTE,
            CAST(H6.H6_DATAINI AS DATETIME)
                + COALESCE(TRY_CAST(H6.H6_HORAINI AS DATETIME), CAST('00:00' AS DATETIME)),
            CAST(H6.H6_DATAFIN AS DATETIME)
                + COALESCE(TRY_CAST(H6.H6_HORAFIN AS DATETIME), CAST('00:00' AS DATETIME))
        ) AS FLOAT
    ) / 60.0
    ELSE TRY_CAST(REPLACE(LTRIM(RTRIM(H6.H6_TEMPO)), ',', '.') AS FLOAT)
END
"""

OEE_SETUP_HOURS_EXPR = """
COALESCE(
    TRY_CAST(REPLACE(LTRIM(RTRIM(SHY.HY_SETUP)), ',', '.') AS FLOAT),
    TRY_CAST(REPLACE(LTRIM(RTRIM(SG2.G2_SETUP)), ',', '.') AS FLOAT),
    0
)
"""

OEE_STANDARD_TIME_FACTOR_EXPR = """
COALESCE(
    TRY_CAST(REPLACE(LTRIM(RTRIM(SHY.HY_TEMPOM)), ',', '.') AS FLOAT),
    TRY_CAST(REPLACE(LTRIM(RTRIM(SG2.G2_TEMPAD)), ',', '.') AS FLOAT) / 1000.0,
    0
)
"""

OEE_PLANNED_HOURS_EXPR = f"""
CASE
    WHEN NULLIF(TRY_CAST(REPLACE(LTRIM(RTRIM(SC2.C2_QUANT)), ',', '.') AS FLOAT), 0) IS NOT NULL
    THEN ROUND(
        ({OEE_SETUP_HOURS_EXPR})
        + ({OEE_STANDARD_TIME_FACTOR_EXPR})
          * (
              TRY_CAST(REPLACE(LTRIM(RTRIM(H6.H6_QTDPROD)), ',', '.') AS FLOAT)
              / NULLIF(TRY_CAST(REPLACE(LTRIM(RTRIM(SC2.C2_QUANT)), ',', '.') AS FLOAT), 0)
          ),
        6
    )
    ELSE ROUND(
        ({OEE_SETUP_HOURS_EXPR})
        + ({OEE_STANDARD_TIME_FACTOR_EXPR})
          * TRY_CAST(REPLACE(LTRIM(RTRIM(H6.H6_QTDPROD)), ',', '.') AS FLOAT),
        6
    )
END
"""

OEE_EFFICIENCY_FROM_TIMES_EXPR = f"""
CASE
    WHEN ({OEE_REAL_HOURS_EXPR}) > 0
    THEN ({OEE_PLANNED_HOURS_EXPR}) * 100.0 / ({OEE_REAL_HOURS_EXPR})
    ELSE NULL
END
"""

OEE_PCT_EXPR = OEE_EFFICIENCY_FROM_TIMES_EXPR

OEE_PCT_EXPR_PLAIN = OEE_EFFICIENCY_FROM_TIMES_EXPR

OEE_VALID_PCT_EXPR = f"""
CASE
    WHEN {OEE_PCT_EXPR} BETWEEN {PRODUCTION_EFFICIENCY_VALID_MIN_PCT} AND {PRODUCTION_EFFICIENCY_VALID_MAX_PCT}
    THEN {OEE_PCT_EXPR}
    ELSE NULL
END
"""

OEE_VALID_PCT_EXPR_PLAIN = f"""
CASE
    WHEN {OEE_PCT_EXPR_PLAIN} BETWEEN {PRODUCTION_EFFICIENCY_VALID_MIN_PCT} AND {PRODUCTION_EFFICIENCY_VALID_MAX_PCT}
    THEN {OEE_PCT_EXPR_PLAIN}
    ELSE NULL
END
"""

OEE_STATUS_EXPR = f"""
CASE
    WHEN {OEE_PCT_EXPR} BETWEEN {PRODUCTION_EFFICIENCY_VALID_MIN_PCT} AND {PRODUCTION_EFFICIENCY_VALID_MAX_PCT} THEN 'valid'
    ELSE 'outlier'
END
"""

OEE_APPOINTMENTS_JOINS = """
FROM SH6010 H6 WITH (NOLOCK)
LEFT JOIN SB1010 SB1 WITH (NOLOCK)
    ON SB1.B1_COD = H6.H6_PRODUTO
   AND SB1.D_E_L_E_T_ = ''
LEFT JOIN SH1010 SH1 WITH (NOLOCK)
    ON SH1.H1_FILIAL = H6.H6_FILIAL
   AND SH1.H1_CODIGO = H6.H6_RECURSO
   AND SH1.D_E_L_E_T_ = ''
LEFT JOIN SC2010 SC2 WITH (NOLOCK)
    ON SC2.D_E_L_E_T_ = ''
   AND SC2.C2_FILIAL = H6.H6_FILIAL
   AND RTRIM(LTRIM(SC2.C2_OP)) = RTRIM(LTRIM(H6.H6_OP))
LEFT JOIN SHY010 SHY WITH (NOLOCK)
    ON SHY.D_E_L_E_T_ = ''
   AND SHY.HY_FILIAL = H6.H6_FILIAL
   AND RTRIM(LTRIM(SHY.HY_OP)) = RTRIM(LTRIM(H6.H6_OP))
   AND RTRIM(LTRIM(SHY.HY_OPERAC)) = RTRIM(LTRIM(H6.H6_OPERAC))
LEFT JOIN SG2010 SG2 WITH (NOLOCK)
    ON SG2.D_E_L_E_T_ = ''
   AND SG2.G2_FILIAL = H6.H6_FILIAL
   AND SG2.G2_PRODUTO = H6.H6_PRODUTO
   AND RTRIM(LTRIM(SG2.G2_OPERAC)) = RTRIM(LTRIM(H6.H6_OPERAC))
"""

OEE_APPOINTMENTS_SELECT = f"""
SELECT
    CAST(H6.R_E_C_N_O_ AS BIGINT) AS appointment_id,
    RTRIM(LTRIM(H6.H6_FILIAL)) AS branch,
    RTRIM(LTRIM(H6.H6_OP)) AS production_order,
    RTRIM(LTRIM(H6.H6_PRODUTO)) AS product_code,
    RTRIM(LTRIM(SB1.B1_DESC)) AS product_description,
    RTRIM(LTRIM(SB1.B1_TIPO)) AS product_type,
    RTRIM(LTRIM(SH1.H1_CTRAB)) AS work_center,
    RTRIM(LTRIM(H6.H6_OPERAC)) AS operation,
    RTRIM(LTRIM(H6.H6_RECURSO)) AS resource_code,
    RTRIM(LTRIM(SH1.H1_DESCRI)) AS resource_name,
    RTRIM(LTRIM(H6.H6_OPERADO)) AS operator_code,
    CONVERT(VARCHAR(10), CONVERT(DATE, H6.H6_DTPROD, 112), 23) AS production_date,
    RTRIM(LTRIM(H6.H6_HORAINI)) AS start_time,
    RTRIM(LTRIM(H6.H6_HORAFIN)) AS end_time,
    ROUND({OEE_PCT_EXPR}, 2) AS oee_pct,
    CAST(H6.H6_QTDPROD AS FLOAT) AS produced_qty,
    {OEE_STATUS_EXPR} AS status
{OEE_APPOINTMENTS_JOINS}
"""

OEE_APPOINTMENT_DETAIL_SELECT = f"""
SELECT
    CAST(H6.R_E_C_N_O_ AS BIGINT) AS appointment_id,
    RTRIM(LTRIM(H6.H6_FILIAL)) AS branch,
    RTRIM(LTRIM(H6.H6_OP)) AS production_order,
    RTRIM(LTRIM(H6.H6_PRODUTO)) AS product_code,
    RTRIM(LTRIM(SB1.B1_DESC)) AS product_description,
    RTRIM(LTRIM(SB1.B1_TIPO)) AS product_type,
    RTRIM(LTRIM(SB1.B1_UM)) AS unit,
    RTRIM(LTRIM(SH1.H1_CTRAB)) AS work_center,
    RTRIM(LTRIM(H6.H6_OPERAC)) AS operation,
    RTRIM(LTRIM(SG2.G2_DESCRI)) AS operation_description,
    RTRIM(LTRIM(H6.H6_RECURSO)) AS resource_code,
    RTRIM(LTRIM(SH1.H1_DESCRI)) AS resource_name,
    RTRIM(LTRIM(H6.H6_OPERADO)) AS operator_code,
    CONVERT(VARCHAR(10), CONVERT(DATE, H6.H6_DTPROD, 112), 23) AS production_date,
    CONVERT(VARCHAR(10), CONVERT(DATE, H6.H6_DTAPONT, 112), 23) AS appointment_date,
    RTRIM(LTRIM(H6.H6_DATAINI)) AS start_date,
    RTRIM(LTRIM(H6.H6_HORAINI)) AS start_time,
    RTRIM(LTRIM(H6.H6_DATAFIN)) AS end_date,
    RTRIM(LTRIM(H6.H6_HORAFIN)) AS end_time,
    ROUND({OEE_PCT_EXPR}, 2) AS oee_pct,
    CAST(H6.H6_QTDPROD AS FLOAT) AS produced_qty,
    CAST(H6.H6_QTDPERD AS FLOAT) AS lost_qty,
    RTRIM(LTRIM(H6.H6_PT)) AS production_point_type,
    RTRIM(LTRIM(H6.H6_TIPO)) AS appointment_type,
    {OEE_STATUS_EXPR} AS status,
    CAST(SC2.C2_QUANT AS FLOAT) AS order_planned_qty,
    CAST(SC2.C2_QUJE AS FLOAT) AS order_produced_qty,
    RTRIM(LTRIM(SC2.C2_NUM)) AS order_number,
    RTRIM(LTRIM(SC2.C2_ITEM)) AS order_item,
    RTRIM(LTRIM(SG2.G2_CODIGO)) AS route_code,
    ROUND({OEE_SETUP_HOURS_EXPR}, 6) AS setup_hours,
    ROUND({OEE_STANDARD_TIME_FACTOR_EXPR}, 6) AS standard_time_factor,
    ROUND({OEE_REAL_HOURS_EXPR}, 6) AS real_hours,
    ROUND({OEE_PLANNED_HOURS_EXPR}, 6) AS planned_hours,
    ROUND(({OEE_REAL_HOURS_EXPR}) - ({OEE_PLANNED_HOURS_EXPR}), 6) AS time_variance_hours,
    ROUND({OEE_EFFICIENCY_FROM_TIMES_EXPR}, 2) AS efficiency_from_times_pct,
    ROUND(
        CASE
            WHEN ({OEE_PLANNED_HOURS_EXPR}) > 0
            THEN ({OEE_REAL_HOURS_EXPR}) - ({OEE_PLANNED_HOURS_EXPR})
            ELSE NULL
        END,
        6
    ) AS time_gained_lost_hours
{OEE_APPOINTMENTS_JOINS}
"""
