"""Gerador declarativo OpenAPI → autoTierCRoutes — DOCIE Fase 20+ (todo GET não manual)."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.domain.services.chat_operational_api_domain_service import (
    ChatOperationalApiDomainService,
)
from app.domain.services.chat_presentation_coverage_service import (
    ChatPresentationCoverageService,
    PresentationCoverageRow,
)
from app.domain.services.operational_route_registry_service import (
    OperationalRouteRegistryService,
)

_AUTO_TIER_C_DOMAIN = "autoTierC"
_AUTO_TIER_C_ID_PREFIX = "autoTierC"
_DEFAULT_PRESENTATION_REASON = "genericSemanticFallback"
_OPERATION_ID_SUFFIXES = ("_get", "_post", "_put", "_patch", "_delete")
_ROUTE_ID_MAX_PARTS = 6


@dataclass(frozen=True)
class AutoTierCGenerationReport:
    generated_count: int
    skipped_manual_count: int
    skipped_non_tier_c_count: int
    uncovered_tier_c_count: int
    ok: bool
    gaps: tuple[str, ...] = ()


class OperationalRouteRegistryGeneratorService:
    @classmethod
    def default_registry_path(cls) -> Path:
        return (
            Path(__file__).resolve().parents[2]
            / "content"
            / "pt-BR"
            / "assistant"
            / "operational_route_registry.json"
        )

    @classmethod
    def generate_routes(
        cls,
        *,
        openapi_baseline_path: Path | None = None,
    ) -> list[dict[str, Any]]:
        rows = ChatPresentationCoverageService.build_matrix(
            baseline_path=openapi_baseline_path,
        )
        generated: list[dict[str, Any]] = []

        for row in rows:
            if row.method != "GET":
                continue

            if cls.is_operation_covered_by_manual_registry(
                operation_id=row.operation_id,
                path=row.path,
            ):
                continue

            generated.append(cls.build_route_entry(row))

        generated.sort(key=lambda route: str(route.get("operationId") or ""))
        return generated

    @classmethod
    def build_route_entry(cls, row: PresentationCoverageRow) -> dict[str, Any]:
        operation_id = str(row.operation_id or "").strip()
        path = str(row.path or "").strip()
        strategy = cls.infer_parameter_strategy(path=path, entity=row.entity)

        return {
            "id": cls.route_id_from_operation_id(operation_id),
            "domain": _AUTO_TIER_C_DOMAIN,
            "autoGenerated": True,
            "operationId": operation_id,
            "priority": 1,
            "route": {
                "pathMarkers": cls.path_markers(path),
                "operationIdMarkers": cls.operation_id_markers(operation_id),
                "method": "GET",
            },
            "parameters": {
                "strategy": strategy,
            },
            "presentation": {
                "reasonKey": _DEFAULT_PRESENTATION_REASON,
            },
            "openapi": {
                "tier": row.tier,
                "entity": row.entity,
                "tags": list(row.tags),
            },
        }

    @classmethod
    def infer_parameter_strategy(
        cls,
        *,
        path: str,
        entity: str | None,
    ) -> str:
        lowered = str(path or "").lower()

        if "{code}" in lowered or entity == "product":
            return "product_code"

        domain = ChatOperationalApiDomainService.classify_path(path)
        strategy = ChatOperationalApiDomainService.parameter_strategy_for_domain(domain)

        if strategy == "semantic":
            return "none"

        return strategy

    @classmethod
    def route_id_from_operation_id(cls, operation_id: str) -> str:
        normalized = str(operation_id or "").strip().lower()

        for suffix in _OPERATION_ID_SUFFIXES:
            if normalized.endswith(suffix):
                normalized = normalized[: -len(suffix)]
                break

        if "_route_" in normalized:
            normalized = normalized.split("_route_", maxsplit=1)[0]

        parts = [
            part
            for part in re.split(r"[_\W]+", normalized)
            if part and part not in {"get", "list", "route", "api", "delpi"}
        ]

        if not parts:
            parts = ["operation"]

        camel = "".join(part[:1].upper() + part[1:] for part in parts[:_ROUTE_ID_MAX_PARTS])
        return f"{_AUTO_TIER_C_ID_PREFIX}{camel}"

    @classmethod
    def operation_id_markers(cls, operation_id: str) -> list[str]:
        lowered = str(operation_id or "").strip().lower()

        if not lowered:
            return []

        markers: list[str] = []
        route_match = re.match(r"^(.+?)_route_", lowered)

        if route_match:
            markers.append(route_match.group(1))

        parts = [part for part in lowered.split("_") if part]

        if len(parts) >= 2:
            markers.append("_".join(parts[:2]))

        markers.append(parts[0] if parts else lowered)

        deduped = list(dict.fromkeys(marker for marker in markers if marker))
        return deduped[:3]

    @classmethod
    def path_markers(cls, path: str) -> list[str]:
        normalized = str(path or "").strip()

        if not normalized:
            return []

        segments = [
            segment
            for segment in normalized.split("/")
            if segment and not segment.startswith("{")
        ]

        if len(segments) >= 2:
            return [f"/{'/'.join(segments[-2:])}"]

        if segments:
            return [f"/{segments[-1]}"]

        return [normalized]

    @classmethod
    def is_operation_covered_by_manual_registry(
        cls,
        *,
        operation_id: str,
        path: str,
    ) -> bool:
        lowered_operation_id = str(operation_id or "").strip().lower()
        lowered_path = str(path or "").strip().lower()

        if not lowered_operation_id:
            return False

        for route in OperationalRouteRegistryService.manual_routes():
            if cls._manual_route_covers(route, lowered_operation_id, lowered_path):
                return True

        return False

    @classmethod
    def _manual_route_covers(
        cls,
        route: dict[str, Any],
        operation_id: str,
        path: str,
    ) -> bool:
        route_spec = route.get("route")

        if not isinstance(route_spec, dict):
            return False

        operation_markers = [
            str(marker).lower()
            for marker in (route_spec.get("operationIdMarkers") or [])
            if str(marker).strip()
        ]

        for marker in operation_markers:
            if marker in operation_id:
                return True

        path_markers = [
            str(marker).lower()
            for marker in (route_spec.get("pathMarkers") or [])
            if str(marker).strip()
        ]

        if path_markers:
            if not all(marker in path for marker in path_markers):
                return False

            return True

        path_suffix = str(route_spec.get("pathSuffix") or "").strip().lower()

        if path_suffix and path.rstrip("/").endswith(path_suffix.rstrip("/")):
            return True

        path_exact_end = str(route_spec.get("pathExactEnd") or "").strip().lower()

        if path_exact_end and path.rstrip("/").endswith(path_exact_end.rstrip("/")):
            return True

        return False

    @classmethod
    def build_meta(
        cls,
        routes: list[dict[str, Any]],
        *,
        openapi_baseline_path: Path | None = None,
    ) -> dict[str, Any]:
        baseline = (
            openapi_baseline_path
            or ChatPresentationCoverageService.default_openapi_baseline_path()
        )

        return {
            "generatedAt": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "sourceBaseline": str(baseline),
            "operationCount": len(routes),
        }

    @classmethod
    def validate_get_auto_coverage(
        cls,
        *,
        openapi_baseline_path: Path | None = None,
    ) -> AutoTierCGenerationReport:
        """Valida que todo GET não coberto pelo registry manual tem entrada autoTierCRoutes."""
        rows = ChatPresentationCoverageService.build_matrix(
            baseline_path=openapi_baseline_path,
        )
        gaps: list[str] = []
        generated_count = 0
        skipped_manual = 0

        stored_by_operation = {
            str(route.get("operationId") or "").strip(): route
            for route in OperationalRouteRegistryService.auto_tier_c_routes()
            if str(route.get("operationId") or "").strip()
        }

        for row in rows:
            if row.method != "GET":
                continue

            if cls.is_operation_covered_by_manual_registry(
                operation_id=row.operation_id,
                path=row.path,
            ):
                skipped_manual += 1
                continue

            generated_count += 1
            stored = stored_by_operation.get(row.operation_id)

            if stored is None:
                gaps.append(
                    f"{row.operation_id} ({row.path}) sem entrada autoTierCRoutes"
                )

        return AutoTierCGenerationReport(
            generated_count=generated_count,
            skipped_manual_count=skipped_manual,
            skipped_non_tier_c_count=0,
            uncovered_tier_c_count=len(gaps),
            ok=not gaps,
            gaps=tuple(gaps),
        )

    @classmethod
    def validate_tier_c_coverage(
        cls,
        *,
        openapi_baseline_path: Path | None = None,
    ) -> AutoTierCGenerationReport:
        rows = ChatPresentationCoverageService.build_matrix(
            baseline_path=openapi_baseline_path,
        )
        gaps: list[str] = []
        generated_count = 0
        skipped_manual = 0
        skipped_non_tier_c = 0

        stored_by_operation = {
            str(route.get("operationId") or "").strip(): route
            for route in OperationalRouteRegistryService.auto_tier_c_routes()
            if str(route.get("operationId") or "").strip()
        }

        for row in rows:
            if row.method != "GET":
                continue

            if cls.is_operation_covered_by_manual_registry(
                operation_id=row.operation_id,
                path=row.path,
            ):
                skipped_manual += 1
                continue

            generated_count += 1
            stored = stored_by_operation.get(row.operation_id)

            if stored is None:
                gaps.append(
                    f"{row.operation_id} ({row.path}) sem entrada autoTierCRoutes"
                )

        return AutoTierCGenerationReport(
            generated_count=generated_count,
            skipped_manual_count=skipped_manual,
            skipped_non_tier_c_count=skipped_non_tier_c,
            uncovered_tier_c_count=len(gaps),
            ok=not gaps,
            gaps=tuple(gaps),
        )

    @classmethod
    def compare_generated_to_stored(
        cls,
        stored_routes: list[dict[str, Any]],
        generated_routes: list[dict[str, Any]],
    ) -> tuple[bool, list[str]]:
        stored_payload = cls._normalize_routes_for_compare(stored_routes)
        generated_payload = cls._normalize_routes_for_compare(generated_routes)

        if stored_payload == generated_payload:
            return True, []

        errors: list[str] = []
        stored_ids = {route["operationId"] for route in stored_payload}
        generated_ids = {route["operationId"] for route in generated_payload}

        missing = sorted(generated_ids - stored_ids)
        extra = sorted(stored_ids - generated_ids)

        for operation_id in missing[:10]:
            errors.append(f"autoTierCRoutes desatualizado — falta {operation_id}")

        for operation_id in extra[:10]:
            errors.append(f"autoTierCRoutes desatualizado — sobra {operation_id}")

        if len(missing) > 10:
            errors.append(f"... e mais {len(missing) - 10} operação(ões) faltando")

        if len(extra) > 10:
            errors.append(f"... e mais {len(extra) - 10} operação(ões) extra")

        if not missing and not extra and stored_payload != generated_payload:
            errors.append("autoTierCRoutes diverge do gerador (campos diferentes)")

        return False, errors

    @classmethod
    def _normalize_routes_for_compare(
        cls,
        routes: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        normalized: list[dict[str, Any]] = []

        for route in routes:
            if not isinstance(route, dict):
                continue

            operation_id = str(route.get("operationId") or "").strip()

            if not operation_id:
                continue

            clone = json.loads(json.dumps(route, ensure_ascii=False))
            clone.pop("priority", None)
            openapi_meta = clone.get("openapi")

            if isinstance(openapi_meta, dict):
                tags = openapi_meta.get("tags")

                if isinstance(tags, list):
                    openapi_meta["tags"] = sorted(str(tag) for tag in tags)

            normalized.append(clone)

        normalized.sort(key=lambda item: str(item.get("operationId") or ""))
        return normalized

    @classmethod
    def write_auto_tier_c_section(
        cls,
        *,
        registry_path: Path | None = None,
        openapi_baseline_path: Path | None = None,
    ) -> AutoTierCGenerationReport:
        path = registry_path or cls.default_registry_path()
        generated = cls.generate_routes(openapi_baseline_path=openapi_baseline_path)
        payload = json.loads(path.read_text(encoding="utf-8"))

        if not isinstance(payload, dict):
            raise ValueError(f"Registry inválido: {path}")

        payload["autoTierCRoutesMeta"] = cls.build_meta(
            generated,
            openapi_baseline_path=openapi_baseline_path,
        )
        payload["autoTierCRoutes"] = generated

        if "autoTierCRoutes" not in (payload.get("dispatchOrder") or []):
            order = payload.get("dispatchOrder")

            if isinstance(order, list):
                updated: list[str] = []

                for phase in order:
                    updated.append(str(phase))

                    if str(phase).strip() == "sqlFallback":
                        updated.append("autoTierCRoutes")

                if "autoTierCRoutes" not in updated:
                    updated.append("autoTierCRoutes")

                payload["dispatchOrder"] = updated

        path.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

        from app.domain.services.operational_route_registry_service import (
            invalidate_operational_route_registry_cache,
        )

        invalidate_operational_route_registry_cache()

        return cls.validate_tier_c_coverage(openapi_baseline_path=openapi_baseline_path)
