from app.composition.content_composer import configure_domain_infrastructure_ports
from app.domain.services.chat_presentation_coverage_service import (
    ChatPresentationCoverageService,
)
from app.domain.services.operational_route_registry_generator_service import (
    OperationalRouteRegistryGeneratorService,
)
from app.domain.services.operational_route_registry_service import (
    OperationalRouteRegistryService,
)


def setup_module() -> None:
    configure_domain_infrastructure_ports()


def test_generate_auto_tier_c_routes_from_openapi_baseline() -> None:
    routes = OperationalRouteRegistryGeneratorService.generate_routes()

    assert routes
    assert all(route.get("autoGenerated") is True for route in routes)
    assert all(route.get("domain") == "autoTierC" for route in routes)
    assert all(str(route.get("operationId") or "").strip() for route in routes)


def test_tier_c_coverage_is_complete_in_registry() -> None:
    report = OperationalRouteRegistryGeneratorService.validate_tier_c_coverage()

    assert report.ok, report.gaps


def test_get_auto_coverage_is_complete_in_registry() -> None:
    report = OperationalRouteRegistryGeneratorService.validate_get_auto_coverage()

    assert report.ok, report.gaps
    manual = OperationalRouteRegistryService.manual_routes()
    assert len(manual) >= 1


def test_stored_auto_tier_c_matches_generator() -> None:
    generated = OperationalRouteRegistryGeneratorService.generate_routes()
    stored = OperationalRouteRegistryService.ci_auto_tier_c_routes()
    ok, errors = OperationalRouteRegistryGeneratorService.compare_generated_to_stored(
        stored,
        generated,
    )

    assert ok, errors


def test_route_id_from_operation_id_is_stable() -> None:
    route_id = OperationalRouteRegistryGeneratorService.route_id_from_operation_id(
        "get_audit_5s_dashboard_quality_audit_5s_analytics_dashboard_get"
    )

    assert route_id.startswith("autoTierC")
    assert "Audit" in route_id


def test_infer_parameter_strategy_from_openapi_path() -> None:
    # E11.S3 — OpenAPI schema is authority; stub always returns schema.
    assert (
        OperationalRouteRegistryGeneratorService.infer_parameter_strategy(
            path="/production/orders/by-op/{production_order}",
            entity=None,
        )
        == "schema"
    )
    assert (
        OperationalRouteRegistryGeneratorService.infer_parameter_strategy(
            path="/cultura-delpi/content",
            entity=None,
        )
        == "schema"
    )


def test_manual_registry_no_longer_covers_via_technical_catalog_after_j_r8() -> None:
    """J-R8 emptied route.operationIds/pathMarkers — coverage via parallel catalog = 0."""
    rows = ChatPresentationCoverageService.build_matrix()
    product_rows = [
        row
        for row in rows
        if row.tier == "A"
        and row.method == "GET"
        and "/products/" in row.path
        and "{code}" in row.path
    ]

    assert product_rows
    assert all(
        not OperationalRouteRegistryGeneratorService.is_operation_covered_by_manual_registry(
            operation_id=row.operation_id,
            path=row.path,
        )
        for row in product_rows[:5]
    )


def test_route_by_operation_id_resolves_auto_entry() -> None:
    stored = OperationalRouteRegistryService.ci_auto_tier_c_routes()

    assert stored
    sample = stored[0]
    resolved = OperationalRouteRegistryService.route_by_operation_id(
        str(sample.get("operationId") or "")
    )

    assert resolved is not None
    assert resolved["id"] == sample["id"]


def test_manual_route_technical_markers_removed_after_j_r8() -> None:
    lmp_route = OperationalRouteRegistryService.route_by_id("engineeringLmpDashboard")
    assert lmp_route is not None
    route_spec = lmp_route.get("route") or {}
    assert (route_spec.get("operationIds") or []) == []
    assert not (route_spec.get("pathMarkers") or [])

    # Without technical catalog fields, generator does not claim manual coverage.
    assert OperationalRouteRegistryGeneratorService._manual_route_covers(
        lmp_route,
        "get_quality_action_plans_dashboard",
        "/quality/action-plans/dashboard",
    ) is False
    assert OperationalRouteRegistryGeneratorService._manual_route_covers(
        lmp_route,
        "list_lmps_dashboard",
        "/engineering/lmps/dashboard",
    ) is False


def test_manual_route_does_not_cover_process_inspection_plans() -> None:
    """Marker «inspection» / «/products/» não engole process-inspection-plans."""
    assert (
        OperationalRouteRegistryGeneratorService.is_operation_covered_by_manual_registry(
            operation_id="get_process_inspection_plans_summary",
            path="/process-inspection-plans/summary",
        )
        is False
    )
    assert (
        OperationalRouteRegistryGeneratorService.is_operation_covered_by_manual_registry(
            operation_id="get_process_inspection_plans_product",
            path="/process-inspection-plans/product/{code}",
        )
        is False
    )
