// AUTO-GENERATED — não editar manualmente.
// Fonte: minha-delpi-ai-api/app/content/pt-BR/assistant/personality_playbook.json
// Comando: python minha-delpi-ai-api/scripts/generate_chat_feedback_reasons_ts.py --write

export type ChatFeedbackReason = {
  id: string;
  label: string;
};

export const CHAT_FEEDBACK_REASONS: ChatFeedbackReason[] = [
  { id: "lost_context", label: "Perdeu o contexto" },
  { id: "wrong_product", label: "Usou produto errado" },
  { id: "bad_format", label: "Não seguiu o formato pedido" },
  { id: "forgot_previous", label: "Não lembrou a resposta anterior" },
  { id: "wrong_query", label: "Consulta errada" },
  { id: "wrong_intent", label: "Entendeu a intenção errada" },
  { id: "routing_wrong_intent", label: "Interpretou errado o pedido" },
  { id: "routing_wrong_api", label: "Chamou consulta errada" },
  { id: "routing_should_api", label: "Deveria ter usado API/dados" },
  { id: "routing_should_not_api", label: "Não deveria ter usado API" },
  { id: "routing_should_web", label: "Deveria ter pesquisado na web" },
  { id: "routing_unneeded_web", label: "Pesquisou na web sem necessidade" },
  { id: "routing_lost_context", label: "Perdeu contexto no roteamento" },
  { id: "routing_repeated_question", label: "Perguntou algo que já informei" },
  { id: "routing_wrong_format", label: "Usou formato errado (tabela/gráfico)" },
  { id: "routing_missed_text_task", label: "Não entendeu que era tarefa de texto" },
  { id: "too_long", label: "Resposta muito longa" },
  { id: "too_technical", label: "Resposta muito técnica" },
  { id: "wrong_data", label: "Dados incorretos" },
  { id: "missing_source", label: "Faltou fonte" },
  { id: "web_bad_source", label: "Fonte ruim na pesquisa web" },
  { id: "web_outdated_source", label: "Fonte desatualizada" },
  { id: "web_missing_official", label: "Faltou fonte oficial" },
  { id: "web_superficial", label: "Pesquisa superficial" },
  { id: "web_should_english", label: "Deveria buscar em inglês" },
  { id: "web_mixed_internal", label: "Misturou dado interno com web" },
  { id: "web_no_sources_shown", label: "Não mostrou fontes" },
  { id: "web_divergence_unexplained", label: "Fontes divergentes sem explicar" },
  { id: "presentation_bad_format", label: "Formato ruim" },
  { id: "presentation_wrong_chart", label: "Gráfico errado" },
  { id: "presentation_confusing_table", label: "Tabela confusa" },
  { id: "presentation_missing_chart", label: "Faltou gráfico" },
  { id: "presentation_missing_table", label: "Faltou tabela" },
  { id: "presentation_missing_kpi", label: "Faltou KPI" },
  { id: "presentation_missing_insight", label: "Faltou insight" },
  { id: "presentation_hard_to_read", label: "Difícil de ler" },
  { id: "presentation_too_much_info", label: "Informação demais" },
  { id: "presentation_slow", label: "Visualização lenta" },
  { id: "presentation_no_export", label: "Não exportou" },
  { id: "presentation_no_canvas", label: "Não colocou na lousa" },
  { id: "no_answer", label: "Não respondeu" },
  { id: "too_short", label: "Muito curto" },
  { id: "other", label: "Outro" },
  { id: "email_wrong_tone", label: "Tom inadequado no e-mail" },
  { id: "email_artificial", label: "Frase artificial no e-mail" },
  { id: "email_invented_signature", label: "Inventou assinatura" },
  { id: "email_invented_info", label: "Inventou informação no e-mail" },
  { id: "email_weak_subject", label: "Assunto ruim" },
  { id: "email_too_generic", label: "E-mail muito genérico" },
  { id: "text_correction_changed_meaning", label: "Mudou o sentido" },
  { id: "text_correction_over_corrected", label: "Corrigiu demais" },
  { id: "text_correction_under_corrected", label: "Corrigiu de menos" },
  { id: "text_correction_style_lost", label: "Não preservou meu estilo" },
  { id: "text_meaning_changed", label: "Mudou o sentido" },
  { id: "text_artificial", label: "Texto artificial" },
  { id: "text_wrong_tone", label: "Tom inadequado" },
  { id: "text_too_formal", label: "Muito formal" },
  { id: "text_too_informal", label: "Muito informal" },
  { id: "text_too_long", label: "Muito longo" },
  { id: "text_too_short", label: "Muito curto" },
  { id: "text_code_not_preserved", label: "Não preservou código" },
  { id: "text_name_not_preserved", label: "Não preservou nome" },
  { id: "text_invented_info", label: "Inventou informação" },
  { id: "text_wrong_format", label: "Não seguiu formato" },
  { id: "text_unclear", label: "Faltou clareza" },
  { id: "text_bad_translation", label: "Tradução ruim" },
  { id: "text_correction_artificial", label: "Texto ficou artificial" },
  { id: "text_correction_too_formal", label: "Formal demais" },
  { id: "text_correction_too_informal", label: "Informal demais" },
  { id: "text_correction_missed_error", label: "Não corrigiu erro importante" },
  { id: "text_correction_altered_code", label: "Alterou código ou nome" },
  { id: "text_correction_over_explained", label: "Explicou demais" },
  { id: "text_correction_under_explained", label: "Faltou explicar alterações" },
  { id: "memory_wrong_context", label: "Usou contexto errado" },
  { id: "memory_ignored_preference", label: "Não respeitou preferência" },
  { id: "memory_forgot_product", label: "Esqueceu produto anterior" },
  { id: "memory_forgot_period", label: "Esqueceu período anterior" },
  { id: "memory_wrong_canvas", label: "Colocou item errado na lousa" },
  { id: "memory_wrong_attachment", label: "Confundiu arquivo" },
  { id: "memory_repeated_question", label: "Perguntou algo que já informei" },
  { id: "memory_stale_context", label: "Manteve contexto que queria limpar" },
];

export const CHAT_FEEDBACK_PRIMARY_REASON_IDS: string[] = [
  "no_answer",
  "wrong_data",
  "wrong_query",
  "lost_context",
  "missing_source",
  "bad_format",
  "text_artificial",
  "too_long",
  "too_short",
  "chip_irrelevant",
  "other",
];
