export type ChatFeedbackReason = {
  id: string;
  label: string;
};

export const CHAT_FEEDBACK_REASONS: ChatFeedbackReason[] = [
  { id: "lost_context", label: "Perdeu o contexto" },
  { id: "wrong_product", label: "Usou produto errado" },
  { id: "bad_format", label: "Não seguiu o formato pedido" },
  { id: "forgot_previous", label: "Não lembrou a resposta anterior" },
  { id: "wrong_query", label: "Consulta errada" },
  { id: "wrong_intent", label: "Entendeu a intenção errada" },
  { id: "routing_wrong_intent", label: "Interpretou errado o pedido" },
  { id: "routing_wrong_api", label: "Chamou consulta errada" },
  { id: "routing_should_api", label: "Deveria ter usado API/dados" },
  { id: "routing_should_not_api", label: "Não deveria ter usado API" },
  { id: "routing_should_web", label: "Deveria ter pesquisado na web" },
  { id: "routing_unneeded_web", label: "Pesquisou na web sem necessidade" },
  { id: "routing_lost_context", label: "Perdeu contexto no roteamento" },
  { id: "routing_repeated_question", label: "Perguntou algo que já informei" },
  { id: "routing_wrong_format", label: "Usou formato errado (tabela/gráfico)" },
  { id: "routing_missed_text_task", label: "Não entendeu que era tarefa de texto" },
  { id: "text_meaning_changed", label: "Mudou o sentido" },
  { id: "text_artificial", label: "Texto artificial" },
  { id: "text_wrong_tone", label: "Tom inadequado" },
  { id: "text_too_formal", label: "Muito formal" },
  { id: "text_too_informal", label: "Muito informal" },
  { id: "text_too_long", label: "Muito longo" },
  { id: "text_too_short", label: "Muito curto" },
  { id: "text_code_not_preserved", label: "Não preservou código" },
  { id: "text_name_not_preserved", label: "Não preservou nome" },
  { id: "text_invented_info", label: "Inventou informação" },
  { id: "text_wrong_format", label: "Não seguiu formato" },
  { id: "text_unclear", label: "Faltou clareza" },
  { id: "text_bad_translation", label: "Tradução ruim" },
  { id: "text_correction_changed_meaning", label: "Correção mudou o sentido" },
  { id: "text_correction_over_corrected", label: "Corrigiu demais" },
  { id: "text_correction_under_corrected", label: "Corrigiu de menos" },
  { id: "text_correction_style_lost", label: "Não preservou meu estilo" },
  { id: "text_correction_artificial", label: "Texto ficou artificial" },
  { id: "text_correction_too_formal", label: "Formal demais" },
  { id: "text_correction_too_informal", label: "Informal demais" },
  { id: "text_correction_missed_error", label: "Não corrigiu erro importante" },
  { id: "text_correction_altered_code", label: "Alterou código ou nome" },
  { id: "text_correction_over_explained", label: "Explicou demais" },
  { id: "text_correction_under_explained", label: "Faltou explicar alterações" },
  { id: "too_long", label: "Resposta muito longa" },
  { id: "too_technical", label: "Resposta muito técnica" },
  { id: "wrong_data", label: "Dados incorretos" },
  { id: "missing_source", label: "Faltou fonte" },
  { id: "no_answer", label: "Não respondeu" },
  { id: "too_short", label: "Muito curto" },
  { id: "other", label: "Outro" },
  { id: "attachment_not_used", label: "Não usou o arquivo" },
  { id: "attachment_wrong_file", label: "Leu o arquivo errado" },
  { id: "attachment_incomplete_summary", label: "Resumo incompleto" },
  { id: "canvas_not_updated", label: "Não colocou na lousa" },
  { id: "canvas_overwrote", label: "Sobrescreveu a lousa" },
  { id: "canvas_lost_format", label: "Perdeu formatação na lousa" },
  { id: "error_message_confusing", label: "Mensagem de erro confusa" },
  { id: "error_no_explanation", label: "Não explicou o problema" },
  { id: "error_no_alternative", label: "Não sugeriu alternativa" },
  { id: "error_false_nonexistence", label: "Disse que não existe, mas era erro" },
  { id: "error_repeated_question", label: "Pediu informação que eu já tinha dado" },
  { id: "error_no_retry", label: "Não tentou novamente" },
  { id: "error_too_technical", label: "Erro técnico demais" },
  { id: "error_wrong_agent", label: "Deveria ter usado outro agente" },
  { id: "error_should_widen_search", label: "Deveria ter ampliado busca" },
  { id: "error_invented_result", label: "Inventou resultado" },
  { id: "error_partial_not_disclosed", label: "Não avisou que era parcial" },
];
