"""add knowledge chunks vector

Revision ID: cc5430afe5fb
Revises: f21312123f02
Create Date: 2026-05-11 11:38:23.134660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'cc5430afe5fb'
down_revision = 'f21312123f02'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_ai_knowledge_chunks_document_index')
    )
    with op.batch_alter_table('ai_knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_knowledge_chunks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_knowledge_chunks_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_knowledge_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_ai_knowledge_chunks_created_at'))

    op.drop_table('ai_knowledge_chunks')
    # ### end Alembic commands ###
