"""initial ai schema

Revision ID: f21312123f02
Revises: 
Create Date: 2026-05-11 10:31:49.494467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f21312123f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=128), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_context'), ['context'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_prompt_hash'), ['prompt_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chat_sessions_context'), ['context'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chat_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('ai_knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_knowledge_documents_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_knowledge_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_knowledge_documents_source_type'), ['source_type'], unique=False)

    op.create_table('ai_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chat_messages_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_chat_messages_role'))
        batch_op.drop_index(batch_op.f('ix_ai_chat_messages_created_at'))

    op.drop_table('ai_chat_messages')
    with op.batch_alter_table('ai_knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_knowledge_documents_source_type'))
        batch_op.drop_index(batch_op.f('ix_ai_knowledge_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_knowledge_documents_active'))

    op.drop_table('ai_knowledge_documents')
    with op.batch_alter_table('ai_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_chat_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_chat_sessions_context'))

    op.drop_table('ai_chat_sessions')
    with op.batch_alter_table('ai_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_prompt_hash'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_context'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_action'))

    op.drop_table('ai_audit_logs')
    # ### end Alembic commands ###
