"""Frozen V1 constants for api-delpi Custom GPT Actions (LEGACY_TRANSITIONAL)."""

from __future__ import annotations

from app.application.external_capabilities.constants import (
    PRODUCT_SEARCH_DEFAULT_PAGE_SIZE,
    PRODUCT_SEARCH_DENIED_QUERY_PARAMS,
    PRODUCT_SEARCH_FIELD_MAP,
    PRODUCT_SEARCH_MAX_PAGE_SIZE,
    PRODUCT_SEARCH_RESPONSE_FIELDS,
)

GPT_ACTIONS_BASE_PATH = "/gpt-actions/v1"
GPT_ACTIONS_GATEWAY_ROOT = "/apps/api-delpi"
GPT_ACTIONS_PUBLIC_FALLBACK_ORIGIN = "https://minhadelpi.com.br"
GPT_ACTIONS_STATUS = "LEGACY_TRANSITIONAL"

# Imported schema operationIds (openapi.json HTTP id stays outside paths).
GPT_ACTIONS_OPERATION_IDS: tuple[str, ...] = (
    "gpt_get_catalog",
    "gpt_search_products",
)
GPT_ACTIONS_SCHEMA_HTTP_OPERATION_ID = "gpt_get_openapi_schema"

GPT_PRODUCT_SEARCH_MAX_PAGE_SIZE = PRODUCT_SEARCH_MAX_PAGE_SIZE
GPT_PRODUCT_SEARCH_DEFAULT_PAGE_SIZE = PRODUCT_SEARCH_DEFAULT_PAGE_SIZE

GPT_SEARCH_FIELD_MAP = PRODUCT_SEARCH_FIELD_MAP
GPT_SEARCH_RESPONSE_FIELDS = PRODUCT_SEARCH_RESPONSE_FIELDS
GPT_SEARCH_DENIED_QUERY_PARAMS = PRODUCT_SEARCH_DENIED_QUERY_PARAMS
