export type {
  KpiCardFlatOptions as ComunicadoKpiFlatOptions,
  KpiCardInteraction as ComunicadoKpiInteraction,
  KpiPartRef as ComunicadoKpiPartRef,
  KpiPartsMap as ComunicadoKpiPartsMap,
  KpiPartState as ComunicadoKpiPartState,
  KpiPartStyle as ComunicadoKpiPartStyle,
  KpiElementId,
  KpiElementDefinition,
} from "@delpi/plugin-ui/index";

export {
  KPI_PART_DATA_ATTR,
  KPI_ELEMENT_CATALOG,
  applyKpiElementVisibility,
  bindKpiPartPointer,
  deleteKpiPart,
  findKpiPartFromTarget,
  getKpiPartState,
  isKpiElementEnabled,
  isKpiElementOpenForPart,
  isKpiPartRefEqual,
  isKpiPartVisible,
  kpiElementIdForPartRef,
  kpiElementPrimaryPartRef,
  kpiOptionsToParts,
  kpiPartAllowsDelete,
  kpiPartAllowsEdit,
  kpiPartCapabilities,
  mergeKpiPartsWithOptions,
  normalizeKpiPartsForLoad,
  parseKpiPartRef,
  partsToKpiOptions,
  serializeKpiPartRef,
  setKpiElementEnabled,
  upsertKpiPartState,
} from "@delpi/plugin-ui/index";
