export type {
  KpiCardFlatOptions as ComunicadoKpiFlatOptions,
  KpiCardInteraction as ComunicadoKpiInteraction,
  KpiPartFrame as ComunicadoKpiPartFrame,
  KpiPartRef as ComunicadoKpiPartRef,
  KpiPartResizeHandle as ComunicadoKpiPartResizeHandle,
  KpiPartsMap as ComunicadoKpiPartsMap,
  KpiPartState as ComunicadoKpiPartState,
  KpiPartStyle as ComunicadoKpiPartStyle,
  KpiElementId,
  KpiElementDefinition,
  KpiFramePartKind,
  KpiTextPartKind,
} from "@delpi/plugin-ui/index";

export {
  KPI_ICON_DEFAULT_FRAME,
  KPI_ICON_DEFAULT_RADIUS_PX,
  KPI_ICON_DEFAULT_SIZE_PX,
  KPI_PART_DEFAULT_FRAMES,
  KPI_PART_FONT_SIZE_DEFAULTS,
  KPI_PART_DATA_ATTR,
  KPI_PART_RESIZE_HANDLES,
  KPI_ELEMENT_CATALOG,
  applyKpiElementVisibility,
  bindKpiPartPointer,
  clampKpiPartFrame,
  defaultKpiPartFrame,
  deleteKpiPart,
  findKpiPartFromTarget,
  getKpiPartState,
  isKpiElementEnabled,
  isKpiElementOpenForPart,
  isKpiPartRefEqual,
  isKpiPartVisible,
  kpiElementIdForPartRef,
  kpiElementPrimaryPartRef,
  kpiOptionsToParts,
  kpiPartAllowsDelete,
  kpiPartAllowsEdit,
  kpiPartAllowsFrame,
  kpiPartAllowsMove,
  kpiPartAllowsResize,
  kpiPartCapabilities,
  kpiPartCornerAdjFromLocalX,
  kpiPartCornerAdjustCssPosition,
  resolveKpiShapeChromePartRef,
  mergeKpiPartsWithOptions,
  normalizeKpiPartsForLoad,
  parseKpiPartRef,
  partsToKpiOptions,
  resizeKpiPartFrame,
  borderRadiusPxToKpiCornerAdj,
  kpiCornerAdjToBorderRadiusPx,
  resolveKpiIconBoxStyle,
  resolveKpiIconFrame,
  resolveKpiPartFontSize,
  resolveKpiPartFrame,
  resolveKpiPartFrameRoot,
  resolveKpiPartLayoutStyle,
  serializeKpiPartRef,
  setKpiElementEnabled,
  upsertKpiPartState,
} from "@delpi/plugin-ui/index";
