export {
  TABLE_PART_DATA_ATTR,
  bindTablePartPointer,
  deleteTablePart,
  findTablePartFromTarget,
  getTablePartState,
  isTablePartRefEqual,
  mergeTablePartsWithOptions,
  parseTablePartRef,
  partsToTableOptions,
  serializeTablePartRef,
  tableElementPrimaryPartRef,
  tableOptionsToParts,
  tablePartAllowsDelete,
  tablePartAllowsEdit,
  tablePartCapabilities,
  tablePartDomProps,
  upsertTablePartState,
  type TableInteraction as ComunicadoTableInteraction,
  type TablePartCapabilities as ComunicadoTablePartCapabilities,
  type TablePartRef as ComunicadoTablePartRef,
  type TablePartState as ComunicadoTablePartState,
  type TablePartStyle as ComunicadoTablePartStyle,
  type TablePartsMap as ComunicadoTablePartsMap,
} from "@delpi/plugin-ui/index";
