import "./native-screens.css";

export { usePresentationEngine } from "./usePresentationEngine";
export {
  PRESENTATION_CHROME_HIDE_MS,
  usePresentationChromeVisibility,
} from "./usePresentationChromeVisibility";
export { PresentationStageControls } from "./PresentationStageControls";
export {
  buildAdminPresentationWsUrl,
  buildPresentationWsUrl,
  buildPublicPresentationWsUrl,
  parsePresentationRealtimeEvent,
  usePresentationRealtime,
} from "./usePresentationRealtime";
export type {
  PresentationPresencePeer,
  PresentationPresenceRole,
  PresentationRealtimeEvent,
  PresentationSelectionUpdateEvent,
  PresentationSlideDraftEvent,
} from "./usePresentationRealtime";
export { useFullscreenStage } from "./useFullscreenStage";
export { NativeSlideView } from "./NativeScreens";
export {
  DesignViewportStage,
  computeDesignViewportScale,
  computeDesignViewportBleedSize,
  DESIGN_VIEWPORT_BLEED_RATIO,
} from "./DesignViewportStage";
export { RichComunicadoStage } from "./RichComunicadoStage";
export { RichComunicadoMasterLogo } from "./RichComunicadoMasterLogo";
export type { DesignViewportFitMode, DesignViewportBleedSize } from "./DesignViewportStage";
export {
  resolveViewportPixelSize,
  type ViewportPixelSize,
} from "./viewportPixelSize";
export {
  clampFramePositionPercent,
  clampFrameSizePercent,
  COMUNICADO_FRAME_MIN_SIZE_PCT,
  DEFAULT_HEADING_INSERT_SIZE_PX,
  DEFAULT_ICON_INSERT_SIZE_PX,
  DEFAULT_SHAPE_INSERT_SIZE_PX,
  DEFAULT_TEXT_INSERT_SIZE_PX,
  designPxToPercent,
  formatDesignPx,
  FRAME_POSITION_SOFT_MAX,
  FRAME_POSITION_SOFT_MIN,
  frameDesignPxToPercent,
  framePercentToDesignPx,
  hostDesignSizeFromFramePercent,
  patchComunicadoFrame,
  patchComunicadoFrameDesignPx,
  percentToDesignPx,
  squareFrameFromDesignPx,
} from "./frameDesignPixels";
export {
  TABLE_VIEW_DEFAULT_FONT_SIZE_PX,
  applyComplexBlockFrameWithTypography,
  contentFillFrameScale,
  scaleChartPartTypographyOnResize,
  scaleChartPartsTypography,
  scaleComplexBlockOnResize,
  scaleFontPx,
  scaleInputPartTypographyOnResize,
  scaleInputPartsTypography,
  scaleKpiPartTypographyOnResize,
  scaleKpiPartsTypography,
  scaleTableOptionsFontSize,
  uniformFrameScale,
  type FrameSize,
} from "./scaleComplexBlockTypography";
export {
  COMPLEX_VIEW_BLOCK_TYPES,
  isComplexViewBlock,
  isComplexViewBlockType,
  type ComplexViewBlock,
  type ComplexViewBlockType,
} from "./complexViewBlocks";
export {
  designYBottomLeftToTopLeft,
  designYTopLeftToBottomLeft,
  framePercentToPageBottomLeftPx,
  hostFramePageBottomLeftOrigin,
  hostRelativeFrameToPageBottomLeftPx,
  patchComunicadoFramePageBottomLeftPx,
  patchHostRelativeFramePageBottomLeftPx,
} from "./framePageCoordinates";
export { formatPct, formatNumber, formatCurrency } from "./nativeFormat";
export type {
  PresentationMeta,
  PresentationPayloadLike,
  PresentationPlaylist,
  PresentationSlide,
} from "./types";
export type { UsePresentationEngineOptions } from "./usePresentationEngine";
export {
  PRESENTATION_TRANSITION_STYLES,
  isPresentationTransitionStyle,
  resolveSlideTransitionStyle,
  type PresentationTransitionStyle,
} from "./presentationTransition";
export type {
  ComunicadoBackground,
  ComunicadoBlock,
  ComunicadoBlockAnimation,
  ComunicadoBlockAnimationDirection,
  ComunicadoBlockAnimationEasing,
  ComunicadoBlockAnimationKind,
  ComunicadoBlockStyle,
  ComunicadoCanvasTableBlock,
  ComunicadoInputBlock,
  ComunicadoInputTargetScope,
  ComunicadoConfig,
  ComunicadoCustomFontRef,
  ComunicadoContentRun,
  ComunicadoContentRunStyle,
  ComunicadoDataBinding,
  ComunicadoDataBlock,
  ComunicadoDataDisplayMode,
  ComunicadoDataFilters,
  ComunicadoDataResolved,
  ComunicadoFrame,
  ComunicadoIconBlock,
  ComunicadoListType,
  ComunicadoMediaBlock,
  ComunicadoNamedTextStyle,
  ComunicadoScreenData,
  ComunicadoShapeBlock,
  ComunicadoShapeKind,
  ComunicadoShapeConnector,
  ComunicadoConnectorRouting,
  ComunicadoGeometryVertex,
  ComunicadoTextBlock,
  ComunicadoTextDecoration,
} from "./comunicadoTypes";
export type { ComunicadoImageCrop } from "./comunicadoImageCrop";
export {
  COMUNICADO_IMAGE_CROP_FULL,
  comunicadoImageCropCssProperties,
  isFullComunicadoImageCrop,
  normalizeComunicadoImageCrop,
} from "./comunicadoImageCrop";
export {
  COMUNICADO_FONT_FAMILIES,
  COMUNICADO_FONT_SIZE_MAX,
  COMUNICADO_FONT_SIZE_MIN,
  COMUNICADO_FONT_SIZE_PRESETS,
  COMUNICADO_FONT_SIZE_STEP,
  COMUNICADO_ICON_OPTIONS,
  COMUNICADO_LINE_HEIGHT_OPTIONS,
} from "./comunicadoTypes";
export {
  COMUNICADO_LINE_TOOLS,
  COMUNICADO_SHAPE_CATALOG,
  COMUNICADO_SHAPE_CATALOG_CATEGORIES,
  COMUNICADO_SHAPE_KINDS,
  COMUNICADO_SHAPE_KIND_VALUES,
  COMUNICADO_SHAPE_LIBRARY_FLYOUT_CATEGORIES,
  comunicadoShapeLabel,
  isComunicadoLineToolId,
  isComunicadoShapeKind,
  type ComunicadoLineToolDefinition,
  type ComunicadoLineToolId,
  type ComunicadoShapeCatalogCategory,
  type ComunicadoShapeCatalogEntry,
} from "./comunicadoShapeCatalog";
export {
  defaultStrokeWidthForPrimitive,
  isAreaShapeKind,
  isLineShapeKind,
  isPointShapeKind,
  resolveShapePrimitive,
  shapeSupportsFill,
  shapeSupportsStroke,
  type ComunicadoVisualPrimitive,
} from "./comunicadoVisualPrimitive";
export {
  COMUNICADO_LINE_VISUAL_PAD_PCT,
  COMUNICADO_MARKER_RADIUS_DEFAULT,
  COMUNICADO_POINT_HIT_SIZE_PCT,
  applyLineEndpointAt,
  applyLineEndpoints,
  applyLinePolyline,
  clampFrameForBlock,
  clampFrameForShapeBlock,
  frameFromLineEndpoints,
  geometryBoundingFrame,
  geometryToPersistedFrame,
  initialLineVerticesFromFrame,
  lineEndpointsFromFrame,
  minimumVertexCount,
  resolveBlockHitFrame,
  resolveBlockPlacementStyle,
  resolveLineEndpoints,
  resolveShapeGeometry,
  shapeBlockAllowsResize,
  syncLineVerticesFromFrame,
  translateLineEndpoints,
  type ComunicadoShapeGeometry,
} from "./comunicadoShapeGeometry";
export {
  ComunicadoShapeGraphic,
  ComunicadoShapePreview,
  lineArrowHeadPolygonPoints,
  resolveLineArrowHeadSize,
  type LineArrowHeadSize,
} from "./comunicadoShapeGraphic";
export {
  CONNECTION_SITE_SNAP_PCT,
  blockAcceptsConnectionSites,
  distancePct,
  findNearestConnectionSite,
  pickNearestAnchorsBetweenBlocks,
  resolveAllConnectionSites,
  resolveBlockConnectionSites,
  type ConnectionSite,
  type ConnectionSiteId,
} from "./comunicadoConnectionSites";
export {
  applyConnectorGeometry,
  attachConnectorEndpoint,
  canConnectBlocks,
  connectorsReferencingBlock,
  createConnectorBlock,
  detachConnector,
  detachConnectorEndpoint,
  isConnectorShapeBlock,
  normalizeConnectorAnchor,
  normalizeShapeConnector,
  pruneOrphanConnectors,
  reconcileConnectorsAfterDrag,
  resolveBlockAnchorPoint,
  resolveConnectorEndpoints,
  syncAllConnectors,
  type ComunicadoConnectorAnchor,
} from "./comunicadoConnectors";
export {
  buildCurveControlPoint,
  buildElbowRoutePoints,
  buildRoutedLinePoints,
  normalizeConnectorRouting,
} from "./comunicadoConnectorRouting";
export {
  createDrawnLineBlock,
  createFreeformPathBlock,
  isClickPathDrawTool,
  isDragLineDrawTool,
  isLineDrawToolId,
  lineToolRouting,
  lineToolShapeKind,
  previewDrawnLinePoints,
  sampleQuadraticCurve,
  snapPointToConnectionSite,
  type DrawnLineAttach,
  type LineDrawToolKind,
} from "./comunicadoLineDraw";
export {
  pathLength,
  simplifyPolyline,
  smoothCurveThroughPoints,
} from "./comunicadoFreeformPath";
export {
  adjustmentHandleCssPosition,
  borderRadiusPxToCornerAdjustment,
  cornerAdjustmentToBorderRadiusPx,
  defaultShapeAdjustments,
  patchShapeAdjustment,
  resolveShapeAdjustments,
  shapeAdjustmentSpecs,
  shapeHasAdjustments,
  type ShapeAdjustmentSpec,
} from "./comunicadoShapeAdjustments";
export {
  applyBlockShapeChromeAdjustment,
  applyBlockShapeChromeStyle,
  BLOCK_SHAPE_CHROME_NO_SHADOW,
  blockShapeChromeAdjustmentSpecs,
  blockSupportsShapeChromeHandles,
  blockUsesInnerShapeChrome,
  isInnerShapeChromeStyleKey,
  normalizeBlockShapeChromeBoxShadow,
  resolveBlockSelectionBorderRadiusPx,
  resolveBlockShapeChromeAdjustmentValues,
  resolveBlockShapeChromeBoxShadow,
  resolveBlockShapeChromeCornerPx,
  resolveBlockShapeChromeStyle,
  type BlockShapeChromeStyle,
  type BlockShapeChromeStylePatch,
} from "./comunicadoBlockShapeChrome";
export {
  COMUNICADO_GOOGLE_FONT_CATALOG,
  buildGoogleFontsStylesheetUrl,
  collectFontFamiliesFromComunicadoConfig,
  comunicadoFontFamilyOptions,
  listComunicadoFontFamilyOptions,
  ensureComunicadoGoogleFontsLoaded,
  resolveGoogleFontEntry,
  useComunicadoGoogleFonts,
  type ComunicadoFontFamilyOption,
  type ComunicadoGoogleFontEntry,
} from "./comunicadoGoogleFonts";
export {
  buildCustomFontFamilyCss,
  comunicadoCustomFontFamilyOptions,
  ensureComunicadoCustomFontsLoaded,
  useComunicadoCustomFonts,
  type ComunicadoLoadedCustomFont,
} from "./comunicadoCustomFonts";
export { comunicadoBackgroundCssProperties } from "./comunicadoBackgroundStyle";
export {
  blockTypeForDisplayMode,
  defaultDisplayModeForInsert,
  displayModeLabel,
  displayModeOptionLabel,
  listDataPresentationOptions,
  UNIVERSAL_DISPLAY_MODES,
} from "./comunicadoDataPresentation";
export {
  buildDataPreviewFingerprint,
  DATA_REFRESH_SEC_DEFAULT,
  DATA_REFRESH_SEC_MAX,
  DATA_REFRESH_SEC_MIN,
  resolveDataBlockRefreshSec,
  resolvePreviewRefreshSourceIds,
  resolveStaleSourceIdsForPreviewChange,
} from "./dataRefresh";
export {
  applyRuntimeInputValue,
  collectInputFilterContributions,
  emptyInputFilterContributions,
  hasInputFilterContributions,
  intersectParamSchemaKeys,
  isComunicadoInputBlock,
  isInputBlockType,
  isValueAllowedByParamSchema,
  listFetchableSourceIds,
  mergeFilterLayers,
  pruneSlideDataFiltersAfterInputRemoval,
  resolveInputParamSchemaField,
  resolveInputRefreshSourceIds,
  resolveInputTargetScope,
  resolveRemovedInputRefreshSourceIds,
  type InputFilterContributions,
  type InputParamSchema,
  type InputParamSchemaField,
} from "./comunicadoInputFilters";
export type { DataPresentationOption } from "./comunicadoDataPresentation";
export {
  blockCssStyle,
  buildTextDecoration,
  clampFontSize,
  clampFrame,
  COMUNICADO_EDITOR_FONT_SCALE,
  comunicadoTextInnerStyle,
  createBlock,
  createDataBlock,
  createDataSourceBlock,
  isDataSourceInheritedChromeColor,
  sanitizeDataSourceStyle,
  createChartViewBlock,
  createCanvasTableBlock,
  createInputBlock,
  createTableViewBlock,
  createKpiViewBlock,
  createIconBlock,
  createShapeBlock,
  defaultDataBlockTypeForRoute,
  defaultFrame,
  defaultStyle,
  defaultTextBlockStyle,
  defaultVerticalAlignForBlock,
  frameStyle,
  normalizeIconBlockStyle,
  isDataBlockType,
  isDataSourceBlockType,
  isDataViewBlockType,
  isDataBoundEditorBlockType,
  isTextDataBoundBlockType,
  isCanvasTableDataBoundBlockType,
  isFetchableDataBlockType,
  getLinkedDataSourceIds,
  shouldHideDataSourceOnStage,
  filterBlocksVisibleOnStage,
  filterStageSelectableIds,
  isBlockHiddenOnStage,
  isBlockSelectableOnStage,
  listViewsLinkedToDataSource,
  resolveBlockStageHideReason,
  resolveStageSelectionTargetId,
  listDataSourceBlocks,
  dataSourceOptionsForInspector,
  resolveDataSourceLabel,
  resolvePreferredDataSourceId,
  mergeDataFilters,
  nextZIndex,
  parseComunicadoConfig,
  parseTextDecorationFlags,
  newBlockId,
  serializeComunicadoConfig,
  sortBlocksByZIndex,
  normalizeCanvasTableCells,
  normalizeCanvasTableCell,
  canvasTableCellDisplayRuns,
  canvasTableCellsToStringMatrix,
  canvasTableCellPlainText,
  inferCanvasTableCellFromText,
  mergeCanvasTableOptions,
  canvasTablePresetOptions,
  resolveCanvasTableFontSize,
  resolveCanvasTableHostStyle,
  parseCanvasTableOptions,
  formatCanvasTableNumber,
  buildCanvasTableSparklinePath,
  resolveColumnSparklineAxis,
  CANVAS_TABLE_MIN_ROWS,
  CANVAS_TABLE_MAX_ROWS,
  CANVAS_TABLE_MIN_COLS,
  CANVAS_TABLE_MAX_COLS,
} from "./comunicadoHelpers";
export type {
  CanvasTableCell,
  CanvasTableCellKind,
  CanvasTableCellRef,
  CanvasTableOptions,
  CanvasTableStylePresetId,
  CanvasTableNumberFormat,
} from "./comunicadoHelpers";
export type { StageHideReason } from "./comunicadoStageVisibility";
export { ComunicadoBlockView } from "./comunicadoBlockView";
export {
  ComunicadoIconGraphic,
  resolveComunicadoIconChromeStyle,
  resolveComunicadoIconColor,
  resolveComunicadoIconStrokeWidth,
  resolveComunicadoLucideIcon,
} from "./comunicadoIconView";
export { ComunicadoCanvasTableView } from "./ComunicadoCanvasTableView";
export type { ComunicadoCanvasTableInteraction } from "./ComunicadoCanvasTableView";
export {
  ComunicadoInputBlockView,
  resolveInputControlKind,
} from "./ComunicadoInputBlockView";
export type { InputControlKind, InputResolvedField } from "./ComunicadoInputBlockView";
export { ComunicadoVisualBoxView } from "./ComunicadoVisualBoxView";
export {
  type ComunicadoVisualBoxBlock,
  type ComunicadoVisualBoxChrome,
  type ComunicadoVisualBoxMode,
  type ComunicadoVisualBoxProfile,
  defaultVerticalAlignForVisualBox,
  isComunicadoVisualBoxBlock,
  resolveVisualBoxChrome,
  resolveVisualBoxContentLayoutStyle,
  VISUAL_BOX_CONTENT_INSET,
  resolveVisualBoxProfile,
  resolveVisualBoxShapeKind,
  visualBoxBlockModifierClasses,
  visualBoxEnsureRichTextBlock,
  visualBoxSupportsInlineTextEditing,
  visualBoxSupportsShapeFormatting,
  visualBoxSupportsTextFormatting,
} from "./comunicadoVisualBox";
export { ComunicadoTextRunsView } from "./ComunicadoTextRunsView";
export {
  ComunicadoTextSurface,
  resolveTextSurfaceDisplay,
  textSurfaceNeedsRichPaint,
} from "./ComunicadoTextSurface";
export {
  clearVisualBoxTextFormatting,
  isClearableVisualBox,
} from "./clearVisualBoxTextFormatting";
export {
  contentRunStyleToCss,
  contentRunsFromPlainText,
  hasRichTextRuns,
  normalizeContentRuns,
  plainTextFromContentRuns,
  serializeContentRuns,
  shouldPersistContentRuns,
  syncTextBlockFields,
} from "./comunicadoContentRuns";
export {
  COMUNICADO_TEXT_SHADOW_PRESETS,
  applyComunicadoTextEffectsToCss,
  resolveTextShadowPresetId,
  type ComunicadoTextEffectFields,
  type ComunicadoTextShadowPreset,
} from "./comunicadoTextEffects";
export {
  applyContentRunStyleInRange,
  compactContentRuns,
  contentRunInlineStyleProperties,
  contentRunsFromEditableRoot,
  getEditableTextSelectionOffsets,
  hasPersistableContentRuns,
  insertLineBreakAtOffset,
  insertDataRefAtOffset,
  renderContentRunsHtml,
  restoreEditableTextSelection,
  selectionListTypeState,
  selectionRunStyleState,
  syncTextBlockFromRuns,
  toggleContentRunStyleInRange,
  toggleListTypeInRange,
  toggleListTypeOnAllLines,
  type ContentRunListSelectionState,
  type ContentRunSelectionStyleState,
  type ContentRunStylePatch,
  type ContentRunStyleToggleKey,
  type TextDisplaySegment,
} from "./comunicadoContentRunEditing";
export {
  groupContentRunsForDisplay,
  hasListContentRuns,
  splitContentRunsIntoLines,
} from "./comunicadoContentList";
export {
  applyNamedStyleInRange,
  applyNamedStyleOnAllLines,
  COMUNICADO_NAMED_TEXT_STYLE_OPTIONS,
  defaultNamedStyleForBlockType,
  hasNamedStyleContentRuns,
  namedTextStylePreset,
  resolveEffectiveRunStyle,
  resolveNamedStyleSelectionForBlock,
  selectionNamedStyleState,
  type ContentRunNamedStyleSelectionState,
} from "./comunicadoNamedTextStyles";
export {
  BLOCK_ENTRANCE_DELAY_MAX_MS,
  BLOCK_ENTRANCE_DELAY_MIN_MS,
  BLOCK_ENTRANCE_DELAY_STEP_MS,
  BLOCK_ENTRANCE_DURATION_DEFAULT_MS,
  BLOCK_ENTRANCE_DURATION_MAX_MS,
  BLOCK_ENTRANCE_DURATION_MIN_MS,
  BLOCK_ENTRANCE_DURATION_STEP_MS,
  BLOCK_ENTRANCE_PRESET_OPTIONS,
  blockEntranceAnimationClass,
  blockEntranceAnimationStyle,
  assignStaggeredEntranceDelays,
  clearEntranceAnimations,
  syncEntranceDelaysSameInstant,
  entranceAnimationFromPreset,
  entrancePresetValue,
  normalizeBlockAnimations,
  resolveEntranceAnimation,
  serializeBlockAnimations,
} from "./comunicadoBlockAnimations";
export {
  appendHrefLineToRuns,
  hrefLineStyle,
  isLikelyExternalUrl,
  normalizeHrefInput,
  partitionTextBlockRunsAndHref,
  renderTextBlockEditorHtml,
} from "./comunicadoTextBlockLink";
export { TvDataBlockView } from "./tvDataBlockView";
export { ChartViewBlockView } from "./chartViewBlockView";
export { KpiViewBlockView } from "./kpiViewBlockView";
export {
  DEFAULT_COMUNICADO_KPI_OPTIONS,
  mergeComunicadoKpiOptions,
  type ComunicadoKpiOptions,
} from "./comunicadoKpiOptions";
export {
  resolveKpiViewPresentation,
  type KpiViewPresentation,
} from "./resolveKpiPresentation";
export {
  KPI_ELEMENT_CATALOG,
  KPI_LAYOUT_PRESET_FRAMES,
  KPI_ICON_DEFAULT_FRAME,
  KPI_ICON_DEFAULT_RADIUS_PX,
  KPI_ICON_DEFAULT_SIZE_PX,
  KPI_PART_DEFAULT_FRAMES,
  KPI_PART_FONT_SIZE_DEFAULTS,
  KPI_PART_DATA_ATTR,
  KPI_PART_RESIZE_HANDLES,
  applyKpiAddElementChoice,
  applyKpiAddElementChoiceWithParts,
  applyKpiElementVisibility,
  applyKpiLayoutPreset,
  clampKpiPartFrame,
  defaultKpiPartFrame,
  deleteKpiPart,
  getKpiPartState,
  isKpiAddElementChoiceActive,
  isKpiElementEnabled,
  isKpiElementOpenForPart,
  isKpiPartRefEqual,
  isKpiPartSelected,
  kpiElementIdForAddChoice,
  kpiElementPrimaryPartRef,
  kpiPartAllowsDelete,
  kpiPartAllowsEdit,
  kpiPartAllowsFrame,
  kpiPartAllowsMove,
  kpiPartAllowsResize,
  kpiPartBoxChromeLabels,
  kpiPartHasBoxPaint,
  kpiPartSupportsTypography,
  kpiPartCornerAdjFromLocalX,
  kpiPartCornerAdjustCssPosition,
  resolveKpiShapeChromePartRef,
  mergeKpiPartsWithOptions,
  normalizeKpiPartsForLoad,
  partsToKpiOptions,
  resizeKpiPartFrame,
  borderRadiusPxToKpiCornerAdj,
  kpiCornerAdjToBorderRadiusPx,
  resolveKpiIconBoxStyle,
  resolveKpiIconFrame,
  resolveKpiPartFontSize,
  resolveKpiPartFrame,
  resolveKpiPartFrameRoot,
  resolveKpiPartLayoutStyle,
  kpiPartUsesAutoFitFont,
  kpiPartStyleWithAutoFont,
  kpiPartStyleWithFixedFontSize,
  mergeKpiPartStyle,
  serializeKpiPartRef,
  upsertKpiPartState,
  applyKpiPartStyleToSiblingParts,
  clearKpiPartsFreeLayoutFrames,
  materializeMissingKpiPartFramesFromRoot,
  seedKpiPartsFreeLayoutFrames,
  isKpiTextPartKind,
  KPI_TEXT_PART_KINDS,
  KPI_FREE_LAYOUT_PART_KINDS,
  type ComunicadoKpiInteraction,
  type ComunicadoKpiPartFrame,
  type ComunicadoKpiPartRef,
  type ComunicadoKpiPartResizeHandle,
  type ComunicadoKpiPartsMap,
  type ComunicadoKpiPartState,
  type ComunicadoKpiPartStyle,
  type KpiAddElementChoiceId,
  type KpiElementId,
  type KpiFramePartKind,
  type KpiPartTypographyMode,
  type KpiTextPartKind,
} from "./comunicadoKpiParts";
export {
  INPUT_FREE_LAYOUT_PART_KINDS,
  INPUT_ICON_DEFAULT_SIZE_PX,
  INPUT_PART_DATA_ATTR,
  INPUT_PART_DEFAULT_FRAMES,
  INPUT_PART_FONT_SIZE_DEFAULTS,
  INPUT_PART_RESIZE_HANDLES,
  INPUT_TEXT_PART_KINDS,
  INPUT_ELEMENT_CATALOG,
  bindInputPartPointer,
  clearInputPartsFreeLayoutFrames,
  clampInputPartFrame,
  defaultInputPartFrame,
  defaultInputPartsMap,
  findInputContentPartNearPoint,
  findInputPartFromTarget,
  getInputPartState,
  inputElementIdForPartRef,
  inputElementPrimaryPartRef,
  inputPartAllowsDelete,
  inputPartAllowsFrame,
  inputPartAllowsMove,
  inputPartAllowsResize,
  inputPartBoxChromeLabels,
  inputPartCapabilities,
  inputPartSupportsTypography,
  isInputElementEnabled,
  isInputPartRefEqual,
  isInputPartSelected,
  isInputPartVisible,
  isInputTextPartKind,
  findInputBlockHostInDocument,
  materializeInputPartsFreeLayoutFromRoot,
  materializeMissingInputPartFramesFromRoot,
  mergeInputParts,
  normalizeInputPartsForLoad,
  parseInputPartRef,
  resizeInputPartFrame,
  resolveInputBlockPaintCssVars,
  resolveInputControlPaintCssVars,
  resolveInputContrastBackground,
  resolveInputFrameStateWithDefaults,
  resolveInputIconBoxStyle,
  resolveInputPartFontSize,
  resolveInputPartFrame,
  resolveInputPartFrameRoot,
  resolveInputPartLayoutStyle,
  resolveInputShapeChromePartRef,
  seedInputPartsFreeLayoutFrames,
  serializeInputPartRef,
  setInputElementEnabled,
  upsertInputPartState,
  type ComunicadoInputInteraction,
  type ComunicadoInputPartFrame,
  type ComunicadoInputPartRef,
  type ComunicadoInputPartResizeHandle,
  type ComunicadoInputPartsMap,
  type ComunicadoInputPartState,
  type ComunicadoInputPartStyle,
  type InputElementDefinition,
  type InputElementId,
  type InputTextPartKind,
} from "./comunicadoInputParts";
export { TableViewBlockView } from "./tableViewBlockView";
export { DataSourceBlockView } from "./dataSourceBlockView";
export {
  resolveDataBlockErrorText,
  type DataResolvedErrorFields,
} from "./resolveDataBlockErrorText";
export {
  DATA_SOURCE_DATE_RANGE_PRESET_LABELS,
  DATA_SOURCE_PARAM_LABELS,
  formatDataSourceBindingSummary,
  formatDataSourceFilterLines,
  type DataSourceBindingSummary,
  type FormatDataSourceBindingSummaryOptions,
} from "./formatDataSourceBindingSummary";
export {
  CHART_ELEMENT_CATALOG,
  isChartElementApplicable,
  isChartElementEnabled,
  setChartElementEnabled,
  applyChartElementVisibility,
  applyChartAddElementChoice,
  applyChartAddElementChoiceWithParts,
  chartAddElementChoiceRootId,
  chartAddElementMoreOptionsPartRef,
  isChartAddElementChoiceActive,
  chartElementPartRefs,
  chartElementPrimaryPartRef,
  chartElementIdForPartRef,
  isChartElementOpenForPart,
  type ChartAddElementChoiceId,
  type ChartElementDefinition,
  type ChartElementId,
} from "./chartElementCatalog";
export {
  CHART_MARKER_RADIUS,
  CHART_PART_DATA_ATTR,
  CHART_SERIES_LINE_STROKE_WIDTH,
  applyMarkerStyleToAll,
  bindChartPartPointer,
  chartOptionsToParts,
  chartPartAllowsDelete,
  chartPartAllowsEdit,
  chartPartAllowsFrame,
  chartPartAllowsMove,
  chartPartAllowsResize,
  chartPartCapabilities,
  clampChartPartFrame,
  defaultChartPartFrame,
  deleteChartPart,
  filterVisibleSeriesPoints,
  findChartPartFromTarget,
  getChartPartState,
  isChartPartRefEqual,
  isChartPartInteractionSelected,
  mergeChartPartsWithOptions,
  mergeSeriesChartOptionsWithParts,
  normalizeChartPartsForLoad,
  nudgeChartPartFrame,
  parseChartPartRef,
  partsToChartOptions,
  resizeChartPartFrame,
  resolveChartAreaStyle,
  resolveChartPartFontSize,
  resolveChartPartFrameRoot,
  resolvePlotAreaStyle,
  serializeChartPartRef,
  upsertChartPartState,
  chartPartVisualPrimitive,
  chartPrimitiveSupportsFill,
  chartPrimitiveSupportsStroke,
  CHART_PART_FONT_SIZE_DEFAULTS,
  isChartTextPartKind,
  type ComunicadoChartPartCapabilities,
  type ComunicadoChartInteraction,
  type ComunicadoChartPartFrame,
  type ComunicadoChartPartRef,
  type ComunicadoChartPartResizeHandle,
  type ComunicadoChartPartsMap,
  type ComunicadoChartTextPartKind,
} from "./comunicadoChartParts";
export {
  chartTypeLabel,
  tablePresetLabel,
  chartTypeToLegacyDisplayMode,
  chartTypeHasBasicRender,
  toSeriesChartKind,
  pieInnerRadiusForChartType,
} from "./comunicadoChartView";
export {
  CHART_LEGEND_POSITION_OPTIONS,
  CHART_VALUE_FORMAT_OPTIONS,
  DEFAULT_COMUNICADO_CHART_OPTIONS,
  OFFICE_CHART_AREA_FILL,
  OFFICE_CHART_AREA_STROKE,
  OFFICE_CHART_PLOT_FILL,
  OFFICE_CHART_PLOT_STROKE,
  OFFICE_CHART_SERIES_COLOR,
  formatSeriesChartValue,
  mergeComunicadoChartOptions,
  resolveChartDisplayOptions,
  type ComunicadoChartLegendPosition,
  type ComunicadoChartOptions,
  type ComunicadoChartValueFormat,
} from "./comunicadoChartOptions";
export {
  DEFAULT_COMUNICADO_TABLE_OPTIONS,
  TABLE_TEXT_ALIGN_OPTIONS,
  TABLE_VALUE_FORMAT_OPTIONS,
  formatTableCellValue,
  mergeComunicadoTableOptions,
  presetDefaultTableOptions,
  resolveTableDisplayOptions,
  type ComunicadoTableOptions,
  type ComunicadoTableTextAlign,
  type ComunicadoTableValueFormat,
} from "./comunicadoTableOptions";
export {
  TABLE_PART_DATA_ATTR,
  deleteTablePart,
  getTablePartState,
  isTablePartRefEqual,
  isTablePartSelected,
  mergeTablePartsWithOptions,
  migrateLegacyTableChromeToFrame,
  normalizeTablePartsForLoad,
  parseTablePartRef,
  selectedTableColumnIndexes,
  partsToTableOptions,
  resolveTableFrameStyle,
  resolveTableHeaderCellPaintStyle,
  resolveTablePartPaintStyle,
  serializeTablePartRef,
  tableElementPrimaryPartRef,
  tableOptionsToParts,
  tablePartAllowsDelete,
  tablePartAllowsEdit,
  tablePartAllowsStroke,
  resolveTableShapeChromePartRef,
  upsertTablePartState,
  applyTablePartStyleToSiblingParts,
  type TableGridDimensions,
  type ComunicadoTableInteraction,
  type ComunicadoTablePartRef,
  type ComunicadoTablePartsMap,
} from "./comunicadoTableParts";
export {
  TABLE_ELEMENT_CATALOG,
  isTableElementEnabled,
  setTableElementEnabled,
  type TableElementDefinition,
  type TableElementId,
} from "./tableElementCatalog";
export { ConfigurableSeriesChart } from "./ConfigurableSeriesChart";
export { ConfigurableTable } from "./ConfigurableTable";
export type { ComunicadoChartType, ComunicadoTablePreset, ComunicadoDataSourceBlock, ComunicadoChartViewBlock, ComunicadoTableViewBlock, ComunicadoKpiViewBlock } from "./comunicadoTypes";
export {
  applyDataTransformSteps,
  applyDataTransformToPayload,
  coercePayloadToTable,
  dataTransformStepFormula,
  dataTransformStepLabel,
  evaluateSafeArithmeticExpr,
  evaluateSafeColumnExpr,
  isDataTransformV1,
  isDataTransformV2,
  normalizeDataTransform,
  type DataTransform,
  type DataTransformV1,
  type DataTransformV2,
  type DataQueryDiagnosticDto,
  type DataTransformAgg,
  type DataTransformCmp,
  type DataTransformContext,
  type DataTransformStep,
  type DataTableSnapshot,
  type MColumnSchemaDto,
  type MTypeKind,
  type SourceRangeDto,
  type TransformOperationDto,
  type TransformPlanDto,
  type TransformPlanStepDto,
} from "./dataTransform";
// Parser pseudo-M legado: mantido apenas para fixtures/testes diretos.
// Não reexportar no entrypoint de runtime; a autoridade semântica é a API.
export {
  resolveChartType,
  resolveEffectiveDisplayMode,
  resolveTableColumns,
  type TvDataTableColumn,
} from "./tvDataPresentation";
export {
  TABLE_VIEW_MAX_COLS_CAP,
  TABLE_VIEW_MAX_ROWS_CAP,
  applyTableViewDisplayLimits,
  normalizeTableViewLimit,
} from "./tableViewLimits";
export {
  applyMetricSelectionToResolved,
  filterKpiMetrics,
  normalizeSelectedValueFields,
  resolveSelectedMetricFields,
  type MetricSelection,
} from "./resolveKpiMetrics";
export {
  VIEW_AGGREGATION_OPTIONS,
  aggregateValues,
  applyViewProjection,
  chartProjectionFromSelectedFields,
  columnValuesFromRows,
  discoverResolvedFieldOptions,
  kpiProjectionFromSelectedFields,
  normalizeChartProjection,
  normalizeKpiProjection,
  normalizeTableProjection,
  suggestDefaultProjections,
  tableProjectionFromSelectedFields,
  type ChartSeriesProjection,
  type ChartViewProjection,
  type KpiMetricProjection,
  type KpiViewProjection,
  type TableColumnProjection,
  type TableViewProjection,
  type ViewAggregation,
  type ViewProjectionSelection,
} from "./viewProjection";
export {
  parseProjectionNumber,
  FIELD_LIST_JOIN,
  TEXT_FIELD_AGGREGATION_OPTIONS,
  aggregateProjectionValues,
  extractProjectionFieldRawValue,
  extractProjectionFieldValues,
  isCampoValorDumpTable,
  isNumericAggregation,
  resolveProjectedField,
  suggestDefaultAggregationForField,
  suggestPreferredProjectionField,
  type ProjectedFieldResolution,
} from "./fieldValueProjection";
export {
  applyFieldLabelsToResolved,
  isAutoBakedFieldLabel,
  lookupFieldLabel,
  normalizeFieldLabels,
  patchFieldLabels,
  resolveFieldDisplayLabel,
  suggestEditableFields,
  type EditableFieldOption,
  type FieldLabelsMap,
  type ResolveFieldDisplayLabelInput,
} from "./fieldLabelRegistry";
export {
  distributeTableProjectionColumnWidths,
  resizeTableProjectionColumn,
  resizeTableProjectionColumns,
  resolveEditableTableProjectionColumns,
  selectedTableProjectionColumnKeys,
} from "./tableProjectionEditing";
export {
  mergeComunicadoDataPages,
  resolveComunicadoDataPageState,
  type ComunicadoDataPageState,
} from "./dataPagination";
export {
  duplicateBlocksWithDataPolicy,
  enrichClipboardWithLinkedDataSources,
  isLegacyFetchableDataBlock,
  mustCloneDataSourcesForTarget,
  needsDataSourceDuplicateChoice,
  referencedDataSourceIds,
  resolveBlockPasteDataPolicy,
  type DataSourceDuplicatePolicy,
  type ResolveBlockPasteDataPolicyResult,
} from "./duplicateBlocksWithDataPolicy";
export {
  buildViewDataLinkPatch,
  buildViewFrameFitPatch,
  countViewLayoutItems,
  framesDiffer,
  isNearDefaultKpiFrame,
  suggestViewFrameSize,
  syncDataViewBlocksWithResolved,
  viewHasProjectionConfigured,
  type BuildViewDataLinkPatchInput,
  type DataViewBlockType,
  type ViewFieldTypes,
} from "./syncViewDataLink";
export {
  buildTextDataLinkPatch,
  formatTextProjectionValue,
  isTextDataBoundBlock,
  normalizeTextDataRef,
  normalizeTextProjection,
  patchTextProjectionFromEditedDisplay,
  resolveTextBlockDisplayRuns,
  resolveTextDataRefValue,
  resolveTextDisplayValue,
  resolveVisualBoxDisplayText,
  splitEditedDisplayAroundCoreValue,
  suggestDefaultTextProjection,
  syncTextBlocksWithResolved,
  textBlockHasDataBinding,
  textProjectionHasField,
  viewHasTextProjectionConfigured,
  type BuildTextDataLinkPatchInput,
  type TextDataBoundBlock,
} from "./textViewProjection";
export {
  applyCanvasTableDataRef,
  buildCanvasTableDataLinkPatch,
  canvasTableCellHasDataRef,
  canvasTableHasDataBinding,
  isCanvasTableDataBoundBlock,
  resolveCanvasTableCellDisplay,
  suggestCanvasTableCellDataRef,
  syncCanvasTableBlocksWithResolved,
  type ApplyCanvasTableDataRefScope,
  type BuildCanvasTableDataLinkPatchInput,
  type CanvasTableCellDisplay,
} from "./canvasTableProjection";
export type {
  ComunicadoTextDataRef,
  ComunicadoTextProjection,
  TextProjectionFormat,
} from "./comunicadoTypes";
export { ComunicadoMediaPlaceholder } from "./ComunicadoMediaPlaceholder";
export type { KpiScreenData, NativeSlidePayload } from "./NativeScreens";
