import "./native-screens.css";

export { usePresentationEngine } from "./usePresentationEngine";
export {
  PRESENTATION_CHROME_HIDE_MS,
  usePresentationChromeVisibility,
} from "./usePresentationChromeVisibility";
export { PresentationStageControls } from "./PresentationStageControls";
export {
  buildAdminPresentationWsUrl,
  buildPresentationWsUrl,
  buildPublicPresentationWsUrl,
  parsePresentationRealtimeEvent,
  usePresentationRealtime,
} from "./usePresentationRealtime";
export type {
  PresentationPresencePeer,
  PresentationPresenceRole,
  PresentationRealtimeEvent,
} from "./usePresentationRealtime";
export { useFullscreenStage } from "./useFullscreenStage";
export { NativeSlideView } from "./NativeScreens";
export { DesignViewportStage, computeDesignViewportScale } from "./DesignViewportStage";
export type { DesignViewportFitMode } from "./DesignViewportStage";
export {
  resolveViewportPixelSize,
  type ViewportPixelSize,
} from "./viewportPixelSize";
export {
  clampFramePositionPercent,
  designPxToPercent,
  formatDesignPx,
  FRAME_POSITION_SOFT_MAX,
  FRAME_POSITION_SOFT_MIN,
  frameDesignPxToPercent,
  framePercentToDesignPx,
  hostDesignSizeFromFramePercent,
  patchComunicadoFrame,
  patchComunicadoFrameDesignPx,
  percentToDesignPx,
} from "./frameDesignPixels";
export {
  TABLE_VIEW_DEFAULT_FONT_SIZE_PX,
  applyComplexBlockFrameWithTypography,
  scaleChartPartTypographyOnResize,
  scaleChartPartsTypography,
  scaleComplexBlockOnResize,
  scaleFontPx,
  scaleInputPartTypographyOnResize,
  scaleInputPartsTypography,
  scaleKpiPartTypographyOnResize,
  scaleKpiPartsTypography,
  scaleTableOptionsFontSize,
  uniformFrameScale,
  type FrameSize,
} from "./scaleComplexBlockTypography";
export {
  COMPLEX_VIEW_BLOCK_TYPES,
  isComplexViewBlock,
  isComplexViewBlockType,
  type ComplexViewBlock,
  type ComplexViewBlockType,
} from "./complexViewBlocks";
export {
  designYBottomLeftToTopLeft,
  designYTopLeftToBottomLeft,
  framePercentToPageBottomLeftPx,
  hostFramePageBottomLeftOrigin,
  hostRelativeFrameToPageBottomLeftPx,
  patchComunicadoFramePageBottomLeftPx,
  patchHostRelativeFramePageBottomLeftPx,
} from "./framePageCoordinates";
export { formatPct, formatNumber } from "./nativeFormat";
export type {
  PresentationMeta,
  PresentationPayloadLike,
  PresentationPlaylist,
  PresentationSlide,
} from "./types";
export type { UsePresentationEngineOptions } from "./usePresentationEngine";
export {
  PRESENTATION_TRANSITION_STYLES,
  isPresentationTransitionStyle,
  resolveSlideTransitionStyle,
  type PresentationTransitionStyle,
} from "./presentationTransition";
export type {
  ComunicadoBackground,
  ComunicadoBlock,
  ComunicadoBlockAnimation,
  ComunicadoBlockAnimationDirection,
  ComunicadoBlockAnimationEasing,
  ComunicadoBlockAnimationKind,
  ComunicadoBlockStyle,
  ComunicadoCanvasTableBlock,
  ComunicadoInputBlock,
  ComunicadoInputTargetScope,
  ComunicadoConfig,
  ComunicadoCustomFontRef,
  ComunicadoContentRun,
  ComunicadoContentRunStyle,
  ComunicadoDataBinding,
  ComunicadoDataBlock,
  ComunicadoDataDisplayMode,
  ComunicadoDataFilters,
  ComunicadoDataResolved,
  ComunicadoFrame,
  ComunicadoIconBlock,
  ComunicadoListType,
  ComunicadoMediaBlock,
  ComunicadoNamedTextStyle,
  ComunicadoScreenData,
  ComunicadoShapeBlock,
  ComunicadoShapeKind,
  ComunicadoShapeConnector,
  ComunicadoGeometryVertex,
  ComunicadoTextBlock,
  ComunicadoTextDecoration,
} from "./comunicadoTypes";
export type { ComunicadoImageCrop } from "./comunicadoImageCrop";
export {
  COMUNICADO_IMAGE_CROP_FULL,
  comunicadoImageCropCssProperties,
  isFullComunicadoImageCrop,
  normalizeComunicadoImageCrop,
} from "./comunicadoImageCrop";
export {
  COMUNICADO_FONT_FAMILIES,
  COMUNICADO_FONT_SIZE_MAX,
  COMUNICADO_FONT_SIZE_MIN,
  COMUNICADO_FONT_SIZE_PRESETS,
  COMUNICADO_FONT_SIZE_STEP,
  COMUNICADO_ICON_OPTIONS,
  COMUNICADO_LINE_HEIGHT_OPTIONS,
} from "./comunicadoTypes";
export {
  COMUNICADO_SHAPE_CATALOG,
  COMUNICADO_SHAPE_CATALOG_CATEGORIES,
  COMUNICADO_SHAPE_KINDS,
  COMUNICADO_SHAPE_KIND_VALUES,
  comunicadoShapeLabel,
  isComunicadoShapeKind,
} from "./comunicadoShapeCatalog";
export {
  defaultStrokeWidthForPrimitive,
  isAreaShapeKind,
  isLineShapeKind,
  isPointShapeKind,
  resolveShapePrimitive,
  shapeSupportsFill,
  shapeSupportsStroke,
  type ComunicadoVisualPrimitive,
} from "./comunicadoVisualPrimitive";
export {
  COMUNICADO_LINE_VISUAL_PAD_PCT,
  COMUNICADO_MARKER_RADIUS_DEFAULT,
  COMUNICADO_POINT_HIT_SIZE_PCT,
  clampFrameForBlock,
  clampFrameForShapeBlock,
  geometryBoundingFrame,
  geometryToPersistedFrame,
  minimumVertexCount,
  resolveBlockHitFrame,
  resolveBlockPlacementStyle,
  resolveShapeGeometry,
  shapeBlockAllowsResize,
  syncLineVerticesFromFrame,
  type ComunicadoShapeGeometry,
} from "./comunicadoShapeGeometry";
export {
  ComunicadoShapeGraphic,
  ComunicadoShapePreview,
  lineArrowHeadPolygonPoints,
} from "./comunicadoShapeGraphic";
export {
  applyConnectorGeometry,
  canConnectBlocks,
  connectorsReferencingBlock,
  createConnectorBlock,
  detachConnector,
  isConnectorShapeBlock,
  normalizeConnectorAnchor,
  normalizeShapeConnector,
  pruneOrphanConnectors,
  reconcileConnectorsAfterDrag,
  resolveBlockAnchorPoint,
  resolveConnectorEndpoints,
  syncAllConnectors,
  type ComunicadoConnectorAnchor,
} from "./comunicadoConnectors";
export {
  adjustmentHandleCssPosition,
  borderRadiusPxToCornerAdjustment,
  cornerAdjustmentToBorderRadiusPx,
  defaultShapeAdjustments,
  patchShapeAdjustment,
  resolveShapeAdjustments,
  shapeAdjustmentSpecs,
  shapeHasAdjustments,
  type ShapeAdjustmentSpec,
} from "./comunicadoShapeAdjustments";
export {
  applyBlockShapeChromeAdjustment,
  applyBlockShapeChromeStyle,
  BLOCK_SHAPE_CHROME_NO_SHADOW,
  blockShapeChromeAdjustmentSpecs,
  blockSupportsShapeChromeHandles,
  blockUsesInnerShapeChrome,
  isInnerShapeChromeStyleKey,
  normalizeBlockShapeChromeBoxShadow,
  resolveBlockSelectionBorderRadiusPx,
  resolveBlockShapeChromeAdjustmentValues,
  resolveBlockShapeChromeBoxShadow,
  resolveBlockShapeChromeCornerPx,
  resolveBlockShapeChromeStyle,
  type BlockShapeChromeStyle,
  type BlockShapeChromeStylePatch,
} from "./comunicadoBlockShapeChrome";
export {
  COMUNICADO_GOOGLE_FONT_CATALOG,
  buildGoogleFontsStylesheetUrl,
  collectFontFamiliesFromComunicadoConfig,
  comunicadoFontFamilyOptions,
  listComunicadoFontFamilyOptions,
  ensureComunicadoGoogleFontsLoaded,
  resolveGoogleFontEntry,
  useComunicadoGoogleFonts,
  type ComunicadoFontFamilyOption,
  type ComunicadoGoogleFontEntry,
} from "./comunicadoGoogleFonts";
export {
  buildCustomFontFamilyCss,
  comunicadoCustomFontFamilyOptions,
  ensureComunicadoCustomFontsLoaded,
  useComunicadoCustomFonts,
  type ComunicadoLoadedCustomFont,
} from "./comunicadoCustomFonts";
export { comunicadoBackgroundCssProperties } from "./comunicadoBackgroundStyle";
export {
  blockTypeForDisplayMode,
  defaultDisplayModeForInsert,
  displayModeLabel,
  displayModeOptionLabel,
  listDataPresentationOptions,
  UNIVERSAL_DISPLAY_MODES,
} from "./comunicadoDataPresentation";
export {
  buildDataPreviewFingerprint,
  DATA_REFRESH_SEC_DEFAULT,
  DATA_REFRESH_SEC_MAX,
  DATA_REFRESH_SEC_MIN,
  resolveDataBlockRefreshSec,
  resolveStaleSourceIdsForPreviewChange,
} from "./dataRefresh";
export {
  applyRuntimeInputValue,
  collectInputFilterContributions,
  emptyInputFilterContributions,
  hasInputFilterContributions,
  intersectParamSchemaKeys,
  isComunicadoInputBlock,
  isInputBlockType,
  isValueAllowedByParamSchema,
  listFetchableSourceIds,
  mergeFilterLayers,
  pruneSlideDataFiltersAfterInputRemoval,
  resolveInputParamSchemaField,
  resolveInputRefreshSourceIds,
  resolveInputTargetScope,
  resolveRemovedInputRefreshSourceIds,
  type InputFilterContributions,
  type InputParamSchema,
  type InputParamSchemaField,
} from "./comunicadoInputFilters";
export type { DataPresentationOption } from "./comunicadoDataPresentation";
export {
  blockCssStyle,
  buildTextDecoration,
  clampFontSize,
  clampFrame,
  COMUNICADO_EDITOR_FONT_SCALE,
  comunicadoTextInnerStyle,
  createBlock,
  createDataBlock,
  createDataSourceBlock,
  isDataSourceInheritedChromeColor,
  sanitizeDataSourceStyle,
  createChartViewBlock,
  createCanvasTableBlock,
  createInputBlock,
  createTableViewBlock,
  createKpiViewBlock,
  createIconBlock,
  createShapeBlock,
  defaultDataBlockTypeForRoute,
  defaultFrame,
  defaultStyle,
  defaultTextBlockStyle,
  defaultVerticalAlignForBlock,
  frameStyle,
  isDataBlockType,
  isDataSourceBlockType,
  isDataViewBlockType,
  isDataBoundEditorBlockType,
  isFetchableDataBlockType,
  getLinkedDataSourceIds,
  shouldHideDataSourceOnStage,
  filterBlocksVisibleOnStage,
  filterStageSelectableIds,
  isBlockHiddenOnStage,
  isBlockSelectableOnStage,
  listViewsLinkedToDataSource,
  resolveBlockStageHideReason,
  resolveStageSelectionTargetId,
  listDataSourceBlocks,
  dataSourceOptionsForInspector,
  resolveDataSourceLabel,
  resolvePreferredDataSourceId,
  mergeDataFilters,
  nextZIndex,
  parseComunicadoConfig,
  parseTextDecorationFlags,
  newBlockId,
  serializeComunicadoConfig,
  sortBlocksByZIndex,
  normalizeCanvasTableCells,
  CANVAS_TABLE_MIN_ROWS,
  CANVAS_TABLE_MAX_ROWS,
  CANVAS_TABLE_MIN_COLS,
  CANVAS_TABLE_MAX_COLS,
} from "./comunicadoHelpers";
export type { StageHideReason } from "./comunicadoStageVisibility";
export { ComunicadoBlockView } from "./comunicadoBlockView";
export { ComunicadoCanvasTableView } from "./ComunicadoCanvasTableView";
export {
  ComunicadoInputBlockView,
  resolveInputControlKind,
} from "./ComunicadoInputBlockView";
export type { InputControlKind, InputResolvedField } from "./ComunicadoInputBlockView";
export { ComunicadoVisualBoxView } from "./ComunicadoVisualBoxView";
export {
  type ComunicadoVisualBoxBlock,
  type ComunicadoVisualBoxChrome,
  type ComunicadoVisualBoxMode,
  type ComunicadoVisualBoxProfile,
  defaultVerticalAlignForVisualBox,
  isComunicadoVisualBoxBlock,
  resolveVisualBoxChrome,
  resolveVisualBoxContentLayoutStyle,
  resolveVisualBoxProfile,
  resolveVisualBoxShapeKind,
  visualBoxBlockModifierClasses,
  visualBoxEnsureRichTextBlock,
  visualBoxSupportsInlineTextEditing,
  visualBoxSupportsShapeFormatting,
  visualBoxSupportsTextFormatting,
} from "./comunicadoVisualBox";
export { ComunicadoTextRunsView } from "./ComunicadoTextRunsView";
export {
  contentRunStyleToCss,
  contentRunsFromPlainText,
  hasRichTextRuns,
  normalizeContentRuns,
  plainTextFromContentRuns,
  resolveTextBlockDisplayRuns,
  serializeContentRuns,
  shouldPersistContentRuns,
  syncTextBlockFields,
} from "./comunicadoContentRuns";
export {
  COMUNICADO_TEXT_SHADOW_PRESETS,
  applyComunicadoTextEffectsToCss,
  resolveTextShadowPresetId,
  type ComunicadoTextEffectFields,
  type ComunicadoTextShadowPreset,
} from "./comunicadoTextEffects";
export {
  compactContentRuns,
  contentRunInlineStyleProperties,
  contentRunsFromEditableRoot,
  getEditableTextSelectionOffsets,
  hasPersistableContentRuns,
  insertLineBreakAtOffset,
  renderContentRunsHtml,
  restoreEditableTextSelection,
  selectionListTypeState,
  selectionRunStyleState,
  syncTextBlockFromRuns,
  toggleContentRunStyleInRange,
  toggleListTypeInRange,
  toggleListTypeOnAllLines,
  type ContentRunListSelectionState,
  type ContentRunSelectionStyleState,
  type ContentRunStyleToggleKey,
  type TextDisplaySegment,
} from "./comunicadoContentRunEditing";
export {
  groupContentRunsForDisplay,
  hasListContentRuns,
  splitContentRunsIntoLines,
} from "./comunicadoContentList";
export {
  applyNamedStyleInRange,
  applyNamedStyleOnAllLines,
  COMUNICADO_NAMED_TEXT_STYLE_OPTIONS,
  defaultNamedStyleForBlockType,
  hasNamedStyleContentRuns,
  namedTextStylePreset,
  resolveEffectiveRunStyle,
  resolveNamedStyleSelectionForBlock,
  selectionNamedStyleState,
  type ContentRunNamedStyleSelectionState,
} from "./comunicadoNamedTextStyles";
export {
  BLOCK_ENTRANCE_DELAY_MAX_MS,
  BLOCK_ENTRANCE_DELAY_MIN_MS,
  BLOCK_ENTRANCE_DELAY_STEP_MS,
  BLOCK_ENTRANCE_DURATION_DEFAULT_MS,
  BLOCK_ENTRANCE_DURATION_MAX_MS,
  BLOCK_ENTRANCE_DURATION_MIN_MS,
  BLOCK_ENTRANCE_DURATION_STEP_MS,
  BLOCK_ENTRANCE_PRESET_OPTIONS,
  blockEntranceAnimationClass,
  blockEntranceAnimationStyle,
  assignStaggeredEntranceDelays,
  clearEntranceAnimations,
  syncEntranceDelaysSameInstant,
  entranceAnimationFromPreset,
  entrancePresetValue,
  normalizeBlockAnimations,
  resolveEntranceAnimation,
  serializeBlockAnimations,
} from "./comunicadoBlockAnimations";
export {
  appendHrefLineToRuns,
  hrefLineStyle,
  isLikelyExternalUrl,
  normalizeHrefInput,
  partitionTextBlockRunsAndHref,
  renderTextBlockEditorHtml,
} from "./comunicadoTextBlockLink";
export { TvDataBlockView } from "./tvDataBlockView";
export { ChartViewBlockView } from "./chartViewBlockView";
export { KpiViewBlockView } from "./kpiViewBlockView";
export {
  DEFAULT_COMUNICADO_KPI_OPTIONS,
  mergeComunicadoKpiOptions,
  type ComunicadoKpiOptions,
} from "./comunicadoKpiOptions";
export {
  resolveKpiViewPresentation,
  type KpiViewPresentation,
} from "./resolveKpiPresentation";
export {
  KPI_ELEMENT_CATALOG,
  KPI_ICON_DEFAULT_FRAME,
  KPI_ICON_DEFAULT_RADIUS_PX,
  KPI_ICON_DEFAULT_SIZE_PX,
  KPI_PART_DEFAULT_FRAMES,
  KPI_PART_FONT_SIZE_DEFAULTS,
  KPI_PART_DATA_ATTR,
  KPI_PART_RESIZE_HANDLES,
  applyKpiElementVisibility,
  clampKpiPartFrame,
  defaultKpiPartFrame,
  deleteKpiPart,
  getKpiPartState,
  isKpiElementEnabled,
  isKpiElementOpenForPart,
  isKpiPartRefEqual,
  kpiElementPrimaryPartRef,
  kpiPartAllowsDelete,
  kpiPartAllowsEdit,
  kpiPartAllowsFrame,
  kpiPartAllowsMove,
  kpiPartAllowsResize,
  kpiPartBoxChromeLabels,
  kpiPartHasBoxPaint,
  kpiPartSupportsTypography,
  kpiPartCornerAdjFromLocalX,
  kpiPartCornerAdjustCssPosition,
  resolveKpiShapeChromePartRef,
  mergeKpiPartsWithOptions,
  normalizeKpiPartsForLoad,
  partsToKpiOptions,
  resizeKpiPartFrame,
  borderRadiusPxToKpiCornerAdj,
  kpiCornerAdjToBorderRadiusPx,
  resolveKpiIconBoxStyle,
  resolveKpiIconFrame,
  resolveKpiPartFontSize,
  resolveKpiPartFrame,
  resolveKpiPartFrameRoot,
  resolveKpiPartLayoutStyle,
  serializeKpiPartRef,
  upsertKpiPartState,
  applyKpiPartStyleToSiblingParts,
  clearKpiPartsFreeLayoutFrames,
  materializeMissingKpiPartFramesFromRoot,
  seedKpiPartsFreeLayoutFrames,
  isKpiTextPartKind,
  KPI_TEXT_PART_KINDS,
  KPI_FREE_LAYOUT_PART_KINDS,
  type ComunicadoKpiInteraction,
  type ComunicadoKpiPartFrame,
  type ComunicadoKpiPartRef,
  type ComunicadoKpiPartResizeHandle,
  type ComunicadoKpiPartsMap,
  type ComunicadoKpiPartState,
  type ComunicadoKpiPartStyle,
  type KpiElementId,
  type KpiFramePartKind,
  type KpiTextPartKind,
} from "./comunicadoKpiParts";
export {
  INPUT_FREE_LAYOUT_PART_KINDS,
  INPUT_ICON_DEFAULT_SIZE_PX,
  INPUT_PART_DATA_ATTR,
  INPUT_PART_DEFAULT_FRAMES,
  INPUT_PART_FONT_SIZE_DEFAULTS,
  INPUT_PART_RESIZE_HANDLES,
  INPUT_TEXT_PART_KINDS,
  INPUT_ELEMENT_CATALOG,
  bindInputPartPointer,
  clearInputPartsFreeLayoutFrames,
  clampInputPartFrame,
  defaultInputPartFrame,
  defaultInputPartsMap,
  findInputContentPartNearPoint,
  findInputPartFromTarget,
  getInputPartState,
  inputElementIdForPartRef,
  inputElementPrimaryPartRef,
  inputPartAllowsDelete,
  inputPartAllowsFrame,
  inputPartAllowsMove,
  inputPartAllowsResize,
  inputPartBoxChromeLabels,
  inputPartCapabilities,
  inputPartSupportsTypography,
  isInputElementEnabled,
  isInputPartRefEqual,
  isInputPartVisible,
  isInputTextPartKind,
  findInputBlockHostInDocument,
  materializeInputPartsFreeLayoutFromRoot,
  materializeMissingInputPartFramesFromRoot,
  mergeInputParts,
  normalizeInputPartsForLoad,
  parseInputPartRef,
  resizeInputPartFrame,
  resolveInputBlockPaintCssVars,
  resolveInputControlPaintCssVars,
  resolveInputContrastBackground,
  resolveInputFrameStateWithDefaults,
  resolveInputIconBoxStyle,
  resolveInputPartFontSize,
  resolveInputPartFrame,
  resolveInputPartFrameRoot,
  resolveInputPartLayoutStyle,
  resolveInputShapeChromePartRef,
  seedInputPartsFreeLayoutFrames,
  serializeInputPartRef,
  setInputElementEnabled,
  upsertInputPartState,
  type ComunicadoInputInteraction,
  type ComunicadoInputPartFrame,
  type ComunicadoInputPartRef,
  type ComunicadoInputPartResizeHandle,
  type ComunicadoInputPartsMap,
  type ComunicadoInputPartState,
  type ComunicadoInputPartStyle,
  type InputElementDefinition,
  type InputElementId,
  type InputTextPartKind,
} from "./comunicadoInputParts";
export { TableViewBlockView } from "./tableViewBlockView";
export { DataSourceBlockView } from "./dataSourceBlockView";
export {
  resolveDataBlockErrorText,
  type DataResolvedErrorFields,
} from "./resolveDataBlockErrorText";
export {
  DATA_SOURCE_DATE_RANGE_PRESET_LABELS,
  DATA_SOURCE_PARAM_LABELS,
  formatDataSourceBindingSummary,
  formatDataSourceFilterLines,
  type DataSourceBindingSummary,
  type FormatDataSourceBindingSummaryOptions,
} from "./formatDataSourceBindingSummary";
export {
  CHART_ELEMENT_CATALOG,
  isChartElementApplicable,
  isChartElementEnabled,
  setChartElementEnabled,
  applyChartElementVisibility,
  applyChartAddElementChoice,
  applyChartAddElementChoiceWithParts,
  chartAddElementChoiceRootId,
  chartAddElementMoreOptionsPartRef,
  isChartAddElementChoiceActive,
  chartElementPartRefs,
  chartElementPrimaryPartRef,
  chartElementIdForPartRef,
  isChartElementOpenForPart,
  type ChartAddElementChoiceId,
  type ChartElementDefinition,
  type ChartElementId,
} from "./chartElementCatalog";
export {
  CHART_MARKER_RADIUS,
  CHART_PART_DATA_ATTR,
  CHART_SERIES_LINE_STROKE_WIDTH,
  applyMarkerStyleToAll,
  bindChartPartPointer,
  chartOptionsToParts,
  chartPartAllowsDelete,
  chartPartAllowsEdit,
  chartPartAllowsFrame,
  chartPartAllowsMove,
  chartPartAllowsResize,
  chartPartCapabilities,
  clampChartPartFrame,
  defaultChartPartFrame,
  deleteChartPart,
  filterVisibleSeriesPoints,
  findChartPartFromTarget,
  getChartPartState,
  isChartPartRefEqual,
  isChartPartInteractionSelected,
  mergeChartPartsWithOptions,
  mergeSeriesChartOptionsWithParts,
  normalizeChartPartsForLoad,
  nudgeChartPartFrame,
  parseChartPartRef,
  partsToChartOptions,
  resizeChartPartFrame,
  resolveChartAreaStyle,
  resolveChartPartFontSize,
  resolveChartPartFrameRoot,
  resolvePlotAreaStyle,
  serializeChartPartRef,
  upsertChartPartState,
  chartPartVisualPrimitive,
  chartPrimitiveSupportsFill,
  chartPrimitiveSupportsStroke,
  CHART_PART_FONT_SIZE_DEFAULTS,
  isChartTextPartKind,
  type ComunicadoChartPartCapabilities,
  type ComunicadoChartInteraction,
  type ComunicadoChartPartFrame,
  type ComunicadoChartPartRef,
  type ComunicadoChartPartResizeHandle,
  type ComunicadoChartPartsMap,
  type ComunicadoChartTextPartKind,
} from "./comunicadoChartParts";
export {
  chartTypeLabel,
  tablePresetLabel,
  chartTypeToLegacyDisplayMode,
  chartTypeHasBasicRender,
  toSeriesChartKind,
  pieInnerRadiusForChartType,
} from "./comunicadoChartView";
export {
  CHART_LEGEND_POSITION_OPTIONS,
  CHART_VALUE_FORMAT_OPTIONS,
  DEFAULT_COMUNICADO_CHART_OPTIONS,
  OFFICE_CHART_AREA_FILL,
  OFFICE_CHART_AREA_STROKE,
  OFFICE_CHART_PLOT_FILL,
  OFFICE_CHART_PLOT_STROKE,
  OFFICE_CHART_SERIES_COLOR,
  formatSeriesChartValue,
  mergeComunicadoChartOptions,
  resolveChartDisplayOptions,
  type ComunicadoChartLegendPosition,
  type ComunicadoChartOptions,
  type ComunicadoChartValueFormat,
} from "./comunicadoChartOptions";
export {
  DEFAULT_COMUNICADO_TABLE_OPTIONS,
  TABLE_TEXT_ALIGN_OPTIONS,
  TABLE_VALUE_FORMAT_OPTIONS,
  formatTableCellValue,
  mergeComunicadoTableOptions,
  presetDefaultTableOptions,
  resolveTableDisplayOptions,
  type ComunicadoTableOptions,
  type ComunicadoTableTextAlign,
  type ComunicadoTableValueFormat,
} from "./comunicadoTableOptions";
export {
  TABLE_PART_DATA_ATTR,
  deleteTablePart,
  getTablePartState,
  isTablePartRefEqual,
  mergeTablePartsWithOptions,
  migrateLegacyTableChromeToFrame,
  normalizeTablePartsForLoad,
  parseTablePartRef,
  partsToTableOptions,
  resolveTableFrameStyle,
  resolveTableHeaderCellPaintStyle,
  resolveTablePartPaintStyle,
  serializeTablePartRef,
  tableElementPrimaryPartRef,
  tableOptionsToParts,
  tablePartAllowsDelete,
  tablePartAllowsEdit,
  tablePartAllowsStroke,
  resolveTableShapeChromePartRef,
  upsertTablePartState,
  applyTablePartStyleToSiblingParts,
  type TableGridDimensions,
  type ComunicadoTableInteraction,
  type ComunicadoTablePartRef,
  type ComunicadoTablePartsMap,
} from "./comunicadoTableParts";
export {
  TABLE_ELEMENT_CATALOG,
  isTableElementEnabled,
  setTableElementEnabled,
  type TableElementDefinition,
  type TableElementId,
} from "./tableElementCatalog";
export { ConfigurableSeriesChart } from "./ConfigurableSeriesChart";
export { ConfigurableTable } from "./ConfigurableTable";
export type { ComunicadoChartType, ComunicadoTablePreset, ComunicadoDataSourceBlock, ComunicadoChartViewBlock, ComunicadoTableViewBlock, ComunicadoKpiViewBlock } from "./comunicadoTypes";
export {
  applyDataTransformSteps,
  applyDataTransformToPayload,
  coercePayloadToTable,
  evaluateSafeArithmeticExpr,
  normalizeDataTransform,
  type DataTransform,
  type DataTransformCmp,
  type DataTransformStep,
  type DataTableSnapshot,
} from "./dataTransform";
export {
  resolveChartType,
  resolveEffectiveDisplayMode,
  resolveTableColumns,
  type TvDataTableColumn,
} from "./tvDataPresentation";
export {
  TABLE_VIEW_MAX_COLS_CAP,
  TABLE_VIEW_MAX_ROWS_CAP,
  applyTableViewDisplayLimits,
  normalizeTableViewLimit,
} from "./tableViewLimits";
export {
  applyMetricSelectionToResolved,
  filterKpiMetrics,
  normalizeSelectedValueFields,
  resolveSelectedMetricFields,
  type MetricSelection,
} from "./resolveKpiMetrics";
export {
  VIEW_AGGREGATION_OPTIONS,
  aggregateValues,
  applyViewProjection,
  chartProjectionFromSelectedFields,
  columnValuesFromRows,
  discoverResolvedFieldOptions,
  kpiProjectionFromSelectedFields,
  normalizeChartProjection,
  normalizeKpiProjection,
  normalizeTableProjection,
  suggestDefaultProjections,
  tableProjectionFromSelectedFields,
  type ChartSeriesProjection,
  type ChartViewProjection,
  type KpiMetricProjection,
  type KpiViewProjection,
  type TableColumnProjection,
  type TableViewProjection,
  type ViewAggregation,
  type ViewProjectionSelection,
} from "./viewProjection";
export {
  buildViewDataLinkPatch,
  buildViewFrameFitPatch,
  countViewLayoutItems,
  framesDiffer,
  isNearDefaultKpiFrame,
  suggestViewFrameSize,
  syncDataViewBlocksWithResolved,
  viewHasProjectionConfigured,
  type BuildViewDataLinkPatchInput,
  type DataViewBlockType,
  type ViewFieldTypes,
} from "./syncViewDataLink";
export type { ComunicadoDataKpiMetric } from "./comunicadoTypes";
export { ComunicadoMediaPlaceholder } from "./ComunicadoMediaPlaceholder";
export type { KpiScreenData, NativeSlidePayload } from "./NativeScreens";
