import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));

describe("InteractionRoomPage", () => {
  it("compõe Shell do kit + RoomHeader + MessageThread + composer com anexos", () => {
    const source = readFileSync(join(dir, "InteractionRoomPage.tsx"), "utf8");
    expect(source).toMatch(/CommercialRoomConversationShell/);
    expect(source).toMatch(/CommercialRoomConversationChatColumn/);
    expect(source).toMatch(/commercialRoomConversationClassNames\.root/);
    expect(source).toMatch(/wrapRoot=\{false\}/);
    expect(source).not.toMatch(/InteractionRoomConversationShell/);
    expect(source).toMatch(/CommercialRoomHeader/);
    expect(source).not.toMatch(/CommercialUnderlineNav/);
    expect(source).toMatch(/onTitleClick/);
    expect(source).toMatch(/titleActionLabel/);
    expect(source).not.toMatch(/ExternalLink/);
    expect(source).toMatch(/MessageSquare/);
    expect(source).toMatch(/Files/);
    expect(source).toMatch(/InteractionRoomSharedView/);
    expect(source).toMatch(/CommercialRoomMessageFindPanel/);
    expect(source).toMatch(/authorAvatar/);
    expect(source).toMatch(/sidePanelMode/);
    expect(source).toMatch(/listInteractionMessages/);
    expect(source).toMatch(/roomView/);
    expect(source).toMatch(/CommercialViewTransition/);
    expect(source).toMatch(/transitionKey=\{roomId\.trim\(\)\}/);
    expect(source).toMatch(/transitionKey=\{sidePanelMode \?\? "closed"\}/);
    expect(source).toMatch(/nav=\{/);
    expect(source).toMatch(/navAriaLabel=\{content\.roomViewNavAriaLabel\}/);
    expect(source).not.toMatch(/cm-room-thread__view-nav/);
    expect(source).toMatch(/interactionRoomAuthorAvatarFields/);
    expect(source).toMatch(/interactionRoomParticipantAvatar/);
    expect(source).toMatch(/CommercialMessageThread/);
    expect(source).toMatch(/CommercialEmptyGuidance/);
    expect(source).toMatch(/emptyContent/);
    expect(source).toMatch(/resolveThreadLoadingState/);
    expect(source).toMatch(/roomRefreshingLabel/);
    expect(source).toMatch(/resolveActions/);
    expect(source).toMatch(/resolveActionExtras/);
    expect(source).toMatch(/portalScopeClassName=\{CM_PORTAL_SCOPE\}/);
    expect(source).toMatch(/messageActionsToolbarAriaLabel/);
    expect(source).toMatch(/InteractionRoomMessageReactionQuickBar/);
    expect(source).toMatch(/CommercialMessageThread/);
    expect(source).not.toMatch(/cm-message-thread__actions/);
    expect(source).toMatch(/createTaskFromInteractionMessage/);
    expect(source).toMatch(/InteractionRoomMessageComposer/);
    expect(source).toMatch(/useDirectoryUserLabels/);
    expect(source).toMatch(/useUserProfilePhotoUrls/);
    expect(source).toMatch(/photoByUserId/);
    expect(source).toMatch(/nameFor/);
    expect(source).toMatch(/usePortfolioScope/);
    expect(source).toMatch(/mine:/);
    expect(source).not.toMatch(/CommercialConversationFileDropLayer/);
    expect(source).toMatch(/CommercialRoomContextPanel/);
    expect(source).toMatch(/CommercialRoomSidePanel/);
    expect(source).toMatch(/showTitle=\{sidePanelMode !== "find"\}/);
    expect(source).not.toMatch(/CommercialSectionCard/);
    expect(source).toMatch(/embedded/);
    expect(source).toMatch(/flush/);
    expect(source).not.toMatch(/CommercialHostDrawer/);
    expect(source).not.toMatch(/portalTarget/);
    expect(source).not.toMatch(/CommercialAlertQueue/);
    expect(source).toMatch(/pushRoomNotice/);
    expect(source).not.toMatch(/cm-room-alert-host/);
    expect(source).toMatch(/onRoomTitle/);
    expect(source).toMatch(/contextToggle/);
    expect(source).not.toMatch(/CommercialStateBanner/);
    expect(source).not.toMatch(/CommercialStatusBadge/);
    expect(source).not.toMatch(/aria-hidden \/>\s*\{content\.contextToggle\}/);
    expect(source).toMatch(/scrollThreadMessageIntoView/);
    expect(source).toMatch(/shouldStickThreadToBottom/);
    expect(source).toMatch(/useInteractionRoomSync/);
    expect(source).toMatch(/applyInteractionRoomRealtime/);
    expect(source).not.toMatch(/cm-message-bubble/);
    expect(source).toMatch(/mode=\{editingMessageId \? "edit" : "compose"\}/);
    expect(source).toMatch(/editBanner=\{editBanner\}/);
    expect(source).toMatch(/buildEditComposerBanner/);
    expect(source).not.toMatch(/editingId=\{editingMessageId\}/);
    expect(source).not.toMatch(/renderEditSlot=/);
    expect(source).not.toMatch(/disabled=\{Boolean\(editingMessageId\)\}/);
    expect(source).toMatch(/messageEditedAtTemplate/);
    expect(source).toMatch(/formatInteractionMessageCreatedAtLabel/);
    expect(source).toMatch(/onEditMessage:/);
    expect(source).toMatch(/onDeleteMessage:/);
    expect(source).toMatch(/useCommercialConfirm/);
    expect(source).toMatch(/deleteInteractionMessage/);
    expect(source).toMatch(/deleteInteractionRoom/);
    expect(source).toMatch(/InteractionRoomMoreMenu/);
    expect(source).toMatch(/CommercialSegmentToggle/);
    expect(source).toMatch(/InteractionRoomRenameDialog/);
    expect(source).toMatch(/renameInteractionRoom/);
    expect(source).toMatch(/room\.deleted/);
    expect(source).toMatch(/canManagePortfolios/);
    expect(source).not.toMatch(/Trash2/);
    expect(source).not.toMatch(/window\.confirm/);
    expect(source).toMatch(/onReplyMessage:/);
    expect(source).toMatch(/replyToMessageId=/);
    expect(source).toMatch(/InteractionRoomMessageReactions/);
    expect(source).toMatch(/InteractionRoomMessageAttachments/);
    expect(source).toMatch(/onMessageAttachmentsSettled/);
    expect(source).toMatch(/room\.attachment/);
    expect(source).not.toMatch(/<textarea/);
  });
});
