"""add constraints to app_versions

Revision ID: 22107e172073
Revises: f0a3bee812c3
Create Date: 2026-02-24 12:50:23.072984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22107e172073'
down_revision = 'f0a3bee812c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_app_version', ['app_id', 'version'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_app_version', type_='unique')

    # ### end Alembic commands ###
