"""fix app_routes permission_id uuid + add order

Revision ID: 8242b103d8e6
Revises: 8960f9f0ebb2
Create Date: 2026-02-17 14:06:59.278217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8242b103d8e6'
down_revision = '8960f9f0ebb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('show_in_menu',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_app_routes_app_id'))
        batch_op.drop_constraint(batch_op.f('app_routes_app_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'])
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('app_routes_app_id_fkey'), 'apps', ['app_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_app_routes_app_id'), ['app_id'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('show_in_menu',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('order')

    # ### end Alembic commands ###
