"""add name to permissions

Revision ID: ca0e2d648294
Revises: 8242b103d8e6
Create Date: 2026-02-17 16:20:57.572239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0e2d648294'
down_revision = '8242b103d8e6'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'permissions',
        sa.Column('name', sa.String(length=150), nullable=True)
    )

    # Define name = code para registros antigos
    op.execute("UPDATE permissions SET name = code")

    # Depois torna NOT NULL
    op.alter_column('permissions', 'name', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
