"""Listagem eficiência fabril com appointment_id (mesmo vínculo SH6010 do OEE)."""

from app.domain.production.production_fabril_appointment_scope import EFICIENCIA_FABRIL_VIEW
from app.infrastructure.persistence.totvs.production_fabril.production_fabril_sh6010_apply import (
    FABRIL_SH6010_OUTER_APPLY,
)

EF_FABRIL_ITEMS_FROM = f"""
FROM {EFICIENCIA_FABRIL_VIEW} EF WITH (NOLOCK)
{FABRIL_SH6010_OUTER_APPLY}
"""

EF_FABRIL_ITEMS_SELECT = """
    H6.appointment_id AS appointment_id,
    RTRIM(LTRIM(EF.FILIAL)) AS FILIAL,
    RTRIM(LTRIM(EF.OP)) AS OP,
    RTRIM(LTRIM(EF.PRODUTO)) AS PRODUTO,
    RTRIM(LTRIM(EF.DESCRICAO_PRODUTO)) AS DESCRICAO_PRODUTO,
    RTRIM(LTRIM(EF.CENTRO_TRABALHO)) AS CENTRO_TRABALHO,
    RTRIM(LTRIM(EF.OPERACAO)) AS OPERACAO,
    RTRIM(LTRIM(EF.COD_OPERADOR)) AS COD_OPERADOR,
    RTRIM(LTRIM(EF.LOGIN_OPERADOR)) AS LOGIN_OPERADOR,
    RTRIM(LTRIM(EF.NOME_OPERADOR)) AS NOME_OPERADOR,
    EF.DATA_PRODUCAO AS DATA_PRODUCAO,
    RTRIM(LTRIM(EF.HORA_INICIO)) AS HORA_INICIO,
    RTRIM(LTRIM(EF.HORA_FINAL)) AS HORA_FINAL,
    TRY_CAST(EF.QTD_APONTADA AS FLOAT) AS QTD_APONTADA,
    TRY_CAST(EF.TEMPO_REAL_HORAS AS FLOAT) AS TEMPO_REAL_HORAS,
    TRY_CAST(EF.TEMPO_PREVISTO_HORAS AS FLOAT) AS TEMPO_PREVISTO_HORAS,
    TRY_CAST(EF.EFICIENCIA_PERCENTUAL AS FLOAT) AS EFICIENCIA_PERCENTUAL,
    TRY_CAST(EF.VALOR_MOD_HORA AS FLOAT) AS VALOR_MOD_HORA,
    TRY_CAST(EF.TEMPO_GANHO_PERDIDO_HORAS AS FLOAT) AS TEMPO_GANHO_PERDIDO_HORAS,
    TRY_CAST(EF.RESULTADO_MOD AS FLOAT) AS RESULTADO_MOD,
    TRY_CAST(EF.LUCRO_MOD AS FLOAT) AS LUCRO_MOD,
    TRY_CAST(EF.PREJUIZO_MOD AS FLOAT) AS PREJUIZO_MOD,
    RTRIM(LTRIM(EF.STATUS_RESULTADO_MOD)) AS STATUS_RESULTADO_MOD,
    RTRIM(LTRIM(EF.STATUS_REGISTRO)) AS STATUS_REGISTRO
"""
