export type {
  PerformanceDirection,
  GoalPerformanceTone,
  GoalScopeBadgeTone,
  GoalPerformanceBadge,
  GoalScopeBadge,
  DashboardGoalFields,
  KpiGoalPresentation,
  BranchMetricSlice,
  PerBranchMetricSlices,
} from "@delpi/plugin-ui/index";

export {
  formatDashboardMetricValue,
  calculateIndicatorIddScore,
  formatIndicatorIddScore,
  resolveIndicatorIddScoreLabelFromSi,
  buildSiIndicatorScoreMap,
  pickSiIddScoreLabel,
  resolveAverageSiIddScoreLabel,
  applySiIddScoreLabel,
  resolveIddScoreLabel,
  resolveConsolidatedIddScoreLabel,
  applyConsolidatedBranchIddScore,
  buildKpiGoalPresentationWithBranchIdd,
  fetchPerBranchMetricSlices,
  formatGoalScopeLabel,
  resolveGoalScopeBadge,
  formatPerformanceDirectionLabel,
  isGoalOnTrack,
  resolveOffTrackStatusLabel,
  resolveGoalPerformanceBadge,
  resolveGoalLabel,
  resolveLevelUnitGoalValue,
  resolveAccumulatedGoalPrefix,
  resolveGoalPeriodPartial,
  resolveGoalPeriodKind,
  buildKpiGoalPresentation,
  formatGoalSubtitle,
  formatKpiGoalExportFragments,
  joinKpiExportContext,
} from "@delpi/plugin-ui/index";
