# -----------------
# portal - DOCKERFILE DEV
# -----------------

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY docker-entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh

# permitir que vite veja variáveis VITE_*
ENV NODE_ENV=development

EXPOSE 5173

CMD ["/entrypoint.dev.sh"]