# -----------------
# portal - DOCKERFILE PROD
# -----------------
# -------- build stage --------
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

# corrigir permissões dos binários
RUN chmod -R +x node_modules/.bin

ARG VITE_KC_URL
ARG VITE_KC_REALM
ARG VITE_KC_CLIENT_ID
ARG VITE_KC_REDIRECT_URI
ENV VITE_KC_URL=$VITE_KC_URL
ENV VITE_KC_REALM=$VITE_KC_REALM
ENV VITE_KC_CLIENT_ID=$VITE_KC_CLIENT_ID
ENV VITE_KC_REDIRECT_URI=$VITE_KC_REDIRECT_URI

RUN npm run build

# -------- runtime --------
FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist

EXPOSE 5173

CMD ["npx", "serve", "dist", "-l", "5173"]