export { DeckEditorHeaderActions } from "./DeckEditorHeaderActions";
export { ComunicadoElementInspector } from "./ComunicadoElementInspector";
export { ComunicadoSlideBackgroundPanel } from "./ComunicadoSlideBackgroundPanel";
export { DeckActionRow } from "./DeckActionRow";
export { DeckElementSidePanel } from "./DeckElementSidePanel";
export { DeckField } from "./DeckField";
export { DeckInspectorLayout } from "./DeckInspectorLayout";
export { DeckPropertySection } from "./DeckPropertySection";
export { DeckRibbonGroup } from "./DeckRibbonGroup";
export { DeckRibbonLargeButton } from "./DeckRibbonLargeButton";
export { DeckRibbonShell } from "./DeckRibbonShell";
export { DeckRibbonTile } from "./DeckRibbonTile";
export type { DeckRibbonTabId } from "./deckRibbonTabMeta";
export { DECK_RIBBON_TABS, resolveDeckRibbonTabs } from "./deckRibbonTabMeta";
