SET NOCOUNT ON;
-- === SA2010 profile (empresa 01, active records) ===
SELECT 'total_active' k, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*';
SELECT 'filial_dist' k, A2_FILIAL d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_FILIAL ORDER BY 3 DESC;
SELECT 'loja_dist' k, A2_LOJA d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_LOJA ORDER BY 3 DESC;
SELECT 'tipo_dist' k, A2_TIPO d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_TIPO;
SELECT 'msblql_dist' k, A2_MSBLQL d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_MSBLQL;
SELECT 'status_dist' k, A2_STATUS d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_STATUS;
SELECT 'tpessoa_dist' k, A2_TPESSOA d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_TPESSOA;
SELECT 'est_top' k, A2_EST d, COUNT(*) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_EST ORDER BY 3 DESC;

-- fill rates for candidate-required fields (blank or null counted)
SELECT 'fill' k, f, COUNT(*) tot,
  SUM(CASE WHEN v IS NULL OR LTRIM(RTRIM(v))='' THEN 0 ELSE 1 END) filled
FROM SA2010 WITH (NOLOCK) CROSS APPLY (VALUES
  ('A2_COD',CONVERT(VARCHAR(60),A2_COD)),('A2_LOJA',CONVERT(VARCHAR(60),A2_LOJA)),
  ('A2_NOME',CONVERT(VARCHAR(60),A2_NOME)),('A2_NREDUZ',CONVERT(VARCHAR(60),A2_NREDUZ)),
  ('A2_CGC',CONVERT(VARCHAR(60),A2_CGC)),('A2_INSCR',CONVERT(VARCHAR(60),A2_INSCR)),
  ('A2_END',CONVERT(VARCHAR(60),A2_END)),('A2_BAIRRO',CONVERT(VARCHAR(60),A2_BAIRRO)),
  ('A2_MUN',CONVERT(VARCHAR(60),A2_MUN)),('A2_EST',CONVERT(VARCHAR(60),A2_EST)),
  ('A2_CEP',CONVERT(VARCHAR(60),A2_CEP)),('A2_COD_MUN',CONVERT(VARCHAR(60),A2_COD_MUN)),
  ('A2_DDD',CONVERT(VARCHAR(60),A2_DDD)),('A2_TEL',CONVERT(VARCHAR(60),A2_TEL)),
  ('A2_EMAIL',CONVERT(VARCHAR(60),A2_EMAIL)),('A2_CONTATO',CONVERT(VARCHAR(60),A2_CONTATO)),
  ('A2_BANCO',CONVERT(VARCHAR(60),A2_BANCO)),('A2_AGENCIA',CONVERT(VARCHAR(60),A2_AGENCIA)),
  ('A2_NUMCON',CONVERT(VARCHAR(60),A2_NUMCON)),('A2_COND',CONVERT(VARCHAR(60),A2_COND)),
  ('A2_NATUREZ',CONVERT(VARCHAR(60),A2_NATUREZ)),('A2_CONTA',CONVERT(VARCHAR(60),A2_CONTA)),
  ('A2_GRUPO',CONVERT(VARCHAR(60),A2_GRUPO)),('A2_PAIS',CONVERT(VARCHAR(60),A2_PAIS)),
  ('A2_CODPAIS',CONVERT(VARCHAR(60),A2_CODPAIS)),('A2_TIPO',CONVERT(VARCHAR(60),A2_TIPO)),
  ('A2_MSBLQL',CONVERT(VARCHAR(60),A2_MSBLQL)),('A2_FORMPAG',CONVERT(VARCHAR(60),A2_FORMPAG)),
  ('A2_TIPCTA',CONVERT(VARCHAR(60),A2_TIPCTA)),('A2_CODFAV',CONVERT(VARCHAR(60),A2_CODFAV)),
  ('A2_NR_END',CONVERT(VARCHAR(60),A2_NR_END)),('A2_ENDCOMP',CONVERT(VARCHAR(60),A2_ENDCOMP)),
  ('A2_YROHS',CONVERT(VARCHAR(60),A2_YROHS)),('A2_YFGEN',CONVERT(VARCHAR(60),A2_YFGEN)),
  ('A2_ZTABPRC',CONVERT(VARCHAR(60),A2_ZTABPRC)),('A2_PFISICA',CONVERT(VARCHAR(60),A2_PFISICA)),
  ('A2_INSCRM',CONVERT(VARCHAR(60),A2_INSCRM)),('A2_CNAE',CONVERT(VARCHAR(60),A2_CNAE))
) AS x(f,v) WHERE D_E_L_E_T_<>'*' GROUP BY f ORDER BY f;

-- duplicates analysis
SELECT 'dup_cgc' k, COUNT(*) v FROM (
  SELECT A2_CGC FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' AND LTRIM(RTRIM(A2_CGC))<>''
  GROUP BY A2_CGC HAVING COUNT(*)>1) d;
SELECT 'dup_cod' k, COUNT(*) v FROM (
  SELECT A2_COD FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*'
  GROUP BY A2_COD HAVING COUNT(*)>1) d;
SELECT 'dup_cod_loja' k, COUNT(*) v FROM (
  SELECT A2_COD, A2_LOJA FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*'
  GROUP BY A2_COD, A2_LOJA HAVING COUNT(*)>1) d;
SELECT 'dup_nome' k, COUNT(*) v FROM (
  SELECT A2_NOME FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' AND LTRIM(RTRIM(A2_NOME))<>''
  GROUP BY A2_NOME HAVING COUNT(*)>1) d;

-- A2_COD pattern / sequence evidence
SELECT 'cod_max' k, MAX(A2_COD) v FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*';
SELECT 'cod_samples' k, A2_COD v, A2_LOJA d FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*'
  AND A2_COD IN (SELECT TOP 8 A2_COD FROM SA2010 WHERE D_E_L_E_T_<>'*' ORDER BY A2_COD DESC) ORDER BY A2_COD DESC;

-- loja semantics: how many suppliers have >1 loja
SELECT 'multi_loja_suppliers' k, COUNT(*) v FROM (
  SELECT A2_COD FROM SA2010 WITH (NOLOCK) WHERE D_E_L_E_T_<>'*' GROUP BY A2_COD HAVING COUNT(*)>1) d;
