SET NOCOUNT ON;
-- Full SX3 schema of material cadastral/related tables (empresa 01 dictionary)
SELECT X3_ARQUIVO, X3_ORDEM, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_TITULO,
       X3_VALID, X3_RELACAO, X3_F3, X3_CBOX, X3_WHEN, X3_OBRIGAT, X3_PROPRI, X3_CONDSQL
FROM SX3010 WHERE D_E_L_E_T_<>'*'
AND X3_ARQUIVO IN ('DKI','D30','AIA','AIB','SAD','CPW','CPX','DD1','FV6','G4R','G4S','COP','D2C')
ORDER BY X3_ARQUIVO, X3_ORDEM;

-- SX2 entries for those tables
SELECT X2_CHAVE, X2_ARQUIVO, X2_NOME, X2_MODO, X2_MODOUN, X2_UNICO, X2_ROTINA
FROM SX2010 WHERE X2_CHAVE IN ('DKI','D30','AIA','AIB','SAD','CPW','CPX','DD1','FV6','G4R','G4S','COP','D2C','SA5','SA6','SE4','SED','SA4','SYA','CC2','CCH','ACJ','SA1','SRA','SA3','AI5');

-- PIX / bank detail search across dictionary
SELECT 'PIX' k, X3_ARQUIVO, X3_CAMPO, X3_TITULO FROM SX3010
WHERE D_E_L_E_T_<>'*' AND (X3_TITULO LIKE '%PIX%' OR X3_DESCRIC LIKE '%PIX%' OR X3_CAMPO LIKE '%PIX%')
ORDER BY X3_ARQUIVO;

-- supplier reference fields in core transactional tables
SELECT 'TXN' k, X3_ARQUIVO, X3_CAMPO, X3_TITULO FROM SX3010
WHERE D_E_L_E_T_<>'*' AND X3_ARQUIVO IN ('SC1','SC7','SC8','SD1','SF1','SE2','SF3','SFT','SCY','SC6','SD2','SE5','SE1','SE8','SCE','SCD','SDB','SC3','SFJ','SDS')
AND (X3_CAMPO LIKE '%FORN%' OR X3_CAMPO LIKE '%LOJA%' OR X3_CAMPO LIKE '%_LOJ%')
ORDER BY X3_ARQUIVO, X3_CAMPO;

-- SX5 domains used by SA2 fields
SELECT 'SX5' k, X5_TABELA, X5_CHAVE, X5_DESCRI FROM SX5010
WHERE D_E_L_E_T_<>'*' AND X5_TABELA IN ('48','58','Y7','T3','83','GRU','74','B9','H4','MF')
ORDER BY X5_TABELA, X5_CHAVE;
